GoogleCloudPlatform/gcsfuse

internal/fs/inode/dir.go
internal/fs/inode/hns_dir_test.go

- Call Getfolder in case of LookUpConflicting function.
NA
1. Manual - NA

Callback getFolder in LookUpInode 

---

internal/fs/inode/dir.go
internal/fs/inode/hns_dir_test.go
internal/gcsx/prefix_bucket.go
internal/gcsx/prefix_bucket_test.go
internal/storage/gcs/folder.go
internal/storage/gcs/folder_test.go

- Fixed prefix_bucket implementation for the GetFolder API. This addresses a previous issue where the prefix was not being removed from the response, resulting in absolute paths instead of relative paths when mounting directories.
- Refactored the ConvertFolderToMinObject function to remove unnecessary arguments, streamlining its implementation.
NA
1. Manual - NA

Fix prefix bucket implementation for get folder

---

tools/integration_tests/concurrent_operations/concurrent_listing_test.go

For `--kernel-list-cache-ttl = 0` readir() operation takes more time, because of that we started seeing timeout failure in our e2e test.
Generally `MultipleConcurrentReadDir` takes around 400s to complete on std-48 vm, increasing more to make sure running on smaller VM.
NA
1. Manual - tested

Fixing e2e test because of timeout in concurrent_list test

---

internal/fs/handle/dir_handle.go
internal/fs/handle/dir_handle_test.go
internal/fs/inode/base_dir.go
internal/fs/inode/dir.go
internal/fs/inode/dir_test.go
internal/fs/kernel_list_cache_test.go
tools/integration_tests/concurrent_operations/concurrent_listing_test.go
tools/integration_tests/local_file/read_dir_test.go

When there is local file synced to GCS but not deleted from localFileInodes, listing fails with input/output error. This is because it detects duplicate entries with the same name.
Fix: Remove the duplicate entry when GCS entry matches with local file inode.
Issue link: https://github.com/GoogleCloudPlatform/gcsfuse/issues/2220
2. Unit tests - Added as required
3. Integration tests - Existing tests are sufficient

Fixing error in listing for duplicate files

---

docs/semantics.md

Matching the semantic docs with public doc: https://cloud.google.com/storage/docs/gcsfuse-cache#persistence
NA
1. Manual - NA

Semantic doc update: correcting persistence section of file-cache

---

internal/fs/inode/dir.go
internal/fs/inode/hns_dir_test.go
internal/gcsx/prefix_bucket.go
internal/gcsx/prefix_bucket_test.go
internal/storage/bucket_handle.go
internal/storage/bucket_handle_test.go
internal/storage/testify_mock_bucket.go

- CreateFolder fs level changes.
- Call createFolder API incase of HNS bucket
- Call createObject API incase of NonHNS bucket.
NA

Create folder fs level integration

---

tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go
tools/integration_tests/util/mounting/only_dir_mounting/only_dir_mounting.go
tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
tools/integration_tests/util/mounting/static_mounting/static_mounting.go

Previously, if tests passed on one flag suite but failed on another, the overall test run was not considered a failure.  This issue needs to be addressed by immediately returning a non-zero exit code whenever any tests fail.
NA
1. Manual - NA

Fix exit code in e2e tests

---

cfg/config.go
cfg/decode_hook.go
cfg/decode_hook_test.go
cfg/rationalize.go
cfg/rationalize_test.go
cfg/validate.go
cfg/validate_test.go
cmd/legacy_param_mapper.go
cmd/legacy_param_mapper_test.go
internal/storage/storage_handle.go
internal/storage/storage_handle_test.go
internal/storage/storageutil/client.go
internal/storage/storageutil/test_util.go
tools/config-gen/flag_template_data_gen.go
tools/config-gen/params.yaml
tools/config-gen/parser.go
tools/config-gen/templates/config.tpl
tools/config-gen/type_template_data_gen.go

This PR includes the following changes:
- removes url type from supported new config types. This was being used by custom end point parameter.
- Refactors StorageClientConfig's CustomEndPoint to string type (from url.Url earlier) for simplification.
NA
1. Manual - NA

[CLI config parity] migrate url type to string type

---

cmd/flags_test.go

Flag tests were not running as part of test suite because they did not have the "Test" prefix. Added the prefix and handled failures. 
NA
1. Manual - Manually verified that the tests are running now.

fix flag tests

---

tools/integration_tests/operations/operations_test.go

We see intermittent failure in operations package, storageClient timeout is set less than time taken by tests in operations package.
Increasing the storage client timeout from 40 minutes to 50 minutes.
NA
1. Manual - NA

Increasing timeout of operations package

---

cmd/flags.go
cmd/flags_test.go
cmd/legacy_param_mapper.go
cmd/legacy_param_mapper_test.go
cmd/mount.go
cmd/mount_test.go
cmd/root_test.go

Migrate mount options flag to use new config. This PR also includes some refactoring to move the parsing logic of mount options before usage.
NA
1. Manual - NA
2. Unit tests - Updated/added.

[CLI Config Parity] migrate mount options

---

internal/cache/metadata/stat_cache.go
internal/cache/metadata/stat_cache_test.go
internal/fs/inode/hns_dir_test.go
internal/storage/fake/bucket.go
internal/storage/gcs/folder.go
internal/storage/gcs/folder_test.go

Remove the meteGeneration field from the folder struct since its value remains constant throughout all operations
NA
1. Manual - NA

Remove metageneration argument from folder struct

---

tools/integration_tests/concurrent_operations/concurrent_listing_test.go

Increasing the timeout of OpenAndLookUp concurrent listing test, as it fails some time on smaller vm.
NA
1. Manual - NA

Fixing flaky OpenDirAndLookUp test

---

cfg/config.go
cfg/config_util.go
cfg/config_util_test.go
cmd/config_validation_test.go
cmd/legacy_param_mapper_test.go
cmd/root_test.go
cmd/testdata/valid_config.yaml
internal/config/config_util.go
internal/config/config_util_test.go
internal/config/mount_config.go
internal/fs/local_file_test.go
tools/config-gen/params.yaml
tools/config-gen/templates/config.tpl
tools/integration_tests/operations/operations_test.go

This PR is part of migration to cobra/viper configs and migrates legacy config write config to new config. Some refactoring is done to remove circular dependency.
NA
1. Manual - Manually verified that write config is working.
2. Unit tests - Updated/Added.

[CLI Config Parity] Migrate write config to new config

---

tools/integration_tests/interrupt/interrupt_test.go
tools/integration_tests/log_rotation/log_rotation_test.go
tools/integration_tests/managed_folders/list_empty_managed_folders_test.go
tools/integration_tests/operations/operations_test.go
tools/integration_tests/read_cache/job_chunk_test.go
tools/integration_tests/read_cache/setup_test.go
tools/integration_tests/read_large_files/read_large_files_test.go
tools/integration_tests/readonly/readonly_test.go
tools/integration_tests/util/setup/setup.go
tools/integration_tests/util/setup/yaml-config.go

Currently GCSFuse integration tests rely on internal mount config object in order to create the yaml file for testing. This is not a good practice as this doesn't allow catching failures in case of any breaking change to internal config. Updated the integration tests to manually create the yaml structure using `map[string]interface{}`
NA
1. Manual - NA
3. Integration tests - Updated and ran via KOKORO

[CLI Config Parity] Remove config object from integration tests

---

docs/semantics.md

Adding kernel-list-cache details in the semantic doc.
NA
1. Manual - NA

Adding Kernel List Cache Details in Semantic Doc

---

tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go

Fixed flaky TestListDirectoryWithTwelveThousandFiles by adjusting expected speedup according to number of logical CPUs usable by the current process.
NA

Fix for flaky list large dir

---

.github/CODEOWNERS

kislayk@ is part of CODEOWNERS so, no custom configuration is necessary.
NA
1. Manual - NA

Remove custom CODEOWNERS for kislayk@

---

perfmetrics/scripts/testing_on_gke/examples/dlio/data-loader/.helmignore
perfmetrics/scripts/testing_on_gke/examples/dlio/data-loader/Chart.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/data-loader/templates/dlio-data-loader.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/data-loader/values.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/.helmignore
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/Chart.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/data-loader/.helmignore
perfmetrics/scripts/testing_on_gke/examples/fio/data-loader/Chart.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/data-loader/templates/fio-data-loader.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/data-loader/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/.helmignore
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/Chart.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/utils/utils.py

This adds relevant files from fio/, dio/ and utils/ directories from https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/tree/main/examples for planned fio/dlio testing in gcsfuse on gke.
These contain resources needed to create GKE pods for fio/dlio testing for gcsfuse mounts.
This is a first in a series of PRs. The later PRs will focus on the following
1. Adding an end-2-end script to use the above resources and scripts to run the fio/dlio tests, and according changes in these scripts themselves.
2. Adding parameters in the e2e script to control various configurable properties such as cluster/node configurations, gcsfuse mount options, workload configurations, monitoring/debugging controls etc.
This is followed up in https://github.com/GoogleCloudPlatform/gcsfuse/pull/2284 . 
NA …

[testing-on-gke part 0.1] Add original fio/dlio load-testing code from gcs-fuse-csi-driver

---

cfg/constants.go
cfg/types.go
cfg/validate.go
cfg/validate_test.go
cmd/flags.go
cmd/flags_test.go
cmd/legacy_main.go
cmd/legacy_param_mapper_test.go
cmd/root_test.go
internal/config/mount_config.go
internal/config/yaml_parser.go

Migrate experimental-metadata-prefetch-on-mount to new config. Validation on the flag will be added in a follow-up PR.
NA
1. Manual - Tested manually that passing the flag works as intended.

Migrate experimental-metadata-prefetch-on-mount to new config.

---

perfmetrics/scripts/ls_metrics/listing_benchmark.py

To fix the check_dependencies function call in the listing benchmark script.
NA
1. Manual - Ran the script manually .

fixing check dependency from listing benchmark script

---

tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go

Fixed the flaky list large dir test by setting increase in directory listing performance to 2 times regardless of the number of CPUs.
NA

Fix for flaky list large dir tests

---

.github/workflows/codecov.yml

Without coverpkg being set, the coverage computed for a given test is limited to its own package alone and doesn't include the code from other packages that were involved. Setting coverpkg to ./... includes that coverage as well.
This is useful in cases like the cfg/ package where the `bindFlags` method is invoked by the tests in cmd/root_test.go package.
NA
1. Manual - NA

Specify coverpkg to include every package

---

go.mod
go.sum

Bump golang.org/x/time from 0.5.0 to 0.6.0
Bumps golang.org/x/sys from 0.22.0 to 0.23.0.
Bumps golang.org/x/oauth2 from 0.21.0 to 0.22.0.
Bumps golang.org/x/sync from 0.7.0 to 0.8.0.
NA
1. Manual - NA

Dependabot merge

---

internal/cache/data/object_range.go
internal/cache/file/downloader/jm_parallel_downloads_test.go
internal/cache/file/downloader/job.go
internal/cache/file/downloader/parallel_downloads_job.go
internal/cache/file/downloader/parallel_downloads_job_test.go
tools/integration_tests/read_cache/job_chunk_test.go

Incase of parallel downloads, we trigger n number of goroutines each downloading xMB and then we wait for x*nMB to be downloaded and then make the goroutines fetch another x*nMB.
Instead of that, we are making each goroutine continuously download xMB and then next xMB instead of worrying about other goroutines. Which offset to fetch will be passed via channel,.
NA
2. Unit tests - Existing tests are sufficient
3. Integration tests - Fixed as required.

Made the parallel downloads go routines running without synchronization

---

cfg/constants.go
cfg/validate.go
cfg/validate_test.go
cmd/config_validation_test.go
cmd/flags.go
cmd/flags_test.go
cmd/legacy_main.go
cmd/legacy_param_mapper_test.go
cmd/mount.go
cmd/root_test.go
cmd/testdata/valid_config.yaml

migrate sequential read size mb flag and test GCS Connection configs.
NA
1. Manual - NA

[CLI Config Parity] migrate sequential read size mb flag and test GCS Connection configs

---

cmd/config_validation_test.go
cmd/flags.go
cmd/legacy_main.go
cmd/root_test.go
cmd/testdata/file_system_config/invalid_ignore_interrupts.yaml
cmd/testdata/file_system_config/unset_file_system_config.yaml
cmd/testdata/valid_config.yaml
internal/config/config_util.go
internal/config/config_util_test.go
internal/fs/fs.go

This PR migrate Ignore Interrupts config and flag. Also added tests for file system config.
I will make kernel list cache and Enable Parallel Dirops migration changes in a follow up PR.
NA
1. Manual - NA

[CLI Config Parity] Migrate Ignore Interrupts config and flag. 

---

.github/header-checker-lint.yml

Currently, header-checks on PR fails for JSON files due to absence of license but comments are  unsupported in JSON,thus ignoring all json files from header-check.
NA
1. Manual - NA

Ignoring  JSON files from header checks

---

internal/fs/fs.go
internal/fs/local_file_test.go
tools/integration_tests/local_file/read_dir_test.go

I found an issue with the behavior of local files where recreating a local file with the same name causes a problem. The situation is as follows.
**Behavior:**
1. Directory creation: Successful.
2. Local file creation within the directory: Successful.
3. Stat operation on the local file: Successful.
4. Delete local file: Successful
5. Recreation of the local file within the directory with the same name: Successful.
6. Stat operation on the recreated local file: Failed (due to the reuse of the same inode).
e.g.
```
create dir
create local file dir/file.txt
stat dir/file.txt
rm dir/file.txt
create local file dir/file.txt
stat dir/file.txt -- Fail
```
**Fix:**
The issue was resolved by ensuring the creation of a new inode whenever a file with the same name created which unlinked.
NA
1. …

Local file bug fix - Recreation of local file had issue in stating

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
perfmetrics/scripts/run_load_test_and_fetch_metrics.sh

Includes fixes to the build scripts from continuous tests , which ensures that the perf tests are executed for both hns and flat buckets and the results are uploaded to respective gsheet whenever the perf experiments are triggered. 
NA
1. Manual - Manually tested perf tests script which runs load test for fio benchmarking and performs listing benchmark.Successful run and upload to gsheet.

Handle empty gsheet credentials when running load tests

---

perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py

This adds on top of https://github.com/GoogleCloudPlatform/gcsfuse/pull/2247, https://github.com/GoogleCloudPlatform/gcsfuse/pull/2284 and https://github.com/GoogleCloudPlatform/gcsfuse/pull/2264 .
This is followed up in #2270 .
NA
1. Manual - NA

[testing-on-gke part 1.2] Support generic workloads in gke load test-run scripts

---

perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml

This adds on top of https://github.com/GoogleCloudPlatform/gcsfuse/pull/2247, #2284 https://github.com/GoogleCloudPlatform/gcsfuse/pull/2264 and https://github.com/GoogleCloudPlatform/gcsfuse/pull/2268 .
This is followed up in #2271 .
NA
1. Manual - NA

[testing-on-gke part 1.3] Allow any generic machine-type, and passing GCSFuse configuration, workload configuration in the pod configuration

---

.github/header-checker-lint.yml
.github/workflows/ci.yml
.github/workflows/codecov.yml
Dockerfile
go.mod
perfmetrics/scripts/ml_tests/pytorch/run_model.sh
perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
perfmetrics/scripts/read_cache/setup.sh
tools/cd_scripts/e2e_test.sh
tools/containerize_gcsfuse_docker/Dockerfile
tools/integration_tests/run_e2e_tests.sh
tools/package_gcsfuse_docker/Dockerfile

Upgrade to golang 1.23.0
NA
1. Manual - NA
3. Integration tests - Ran via KOKORO (passed)
4. Perf test -

Upgrade to golang 1.23.0

---

perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/utils/utils.py

This adds on top of https://github.com/GoogleCloudPlatform/gcsfuse/pull/2247, #2284, https://github.com/GoogleCloudPlatform/gcsfuse/pull/2264, https://github.com/GoogleCloudPlatform/gcsfuse/pull/2268 and https://github.com/GoogleCloudPlatform/gcsfuse/pull/2270 .
This is followed up in #2272 .
NA
1. Manual - NA

[testing-on-gke part 1.4] Update parse_tests scripts based on workload config parsers

---

flaky_tests.lst

Disable TestParallelDiropsTestSuite/TestParallelReadDirs since it's flaky.
NA
1. Manual - NA

Disable flaky test

---

perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

This adds on top of This adds on top of https://github.com/GoogleCloudPlatform/gcsfuse/pull/2247, #2284, https://github.com/GoogleCloudPlatform/gcsfuse/pull/2264, https://github.com/GoogleCloudPlatform/gcsfuse/pull/2268, https://github.com/GoogleCloudPlatform/gcsfuse/pull/2270, and https://github.com/GoogleCloudPlatform/gcsfuse/pull/2271 .
This is followed up in https://github.com/GoogleCloudPlatform/gcsfuse/pull/2359.
NA
1. Manual - NA

[testing-on-gke part 2.1] Add top-level script to run tests

---

cfg/config.go
cfg/validate_test.go
cmd/config_validation_test.go
cmd/testdata/valid_config.yaml
internal/cache/file/downloader/jm_parallel_downloads_test.go
internal/cache/file/downloader/job.go
internal/cache/file/downloader/job_test.go
internal/cache/file/downloader/parallel_downloads_job.go
internal/config/mount_config.go
internal/config/testdata/valid_config.yaml
internal/config/yaml_parser_test.go
tools/config-gen/params.yaml

Allow a way to disable the use of O_DIRECT in parallel downloads
NA
1. Manual - Tried the flag during perf testing.
2. Unit tests - Added.
3. Integration tests - TBA in existing e2e tests in a separate PR

Allow a way to disable the use of O_DIRECT in parallel downloads

---

tools/integration_tests/concurrent_operations/setup_test.go
tools/integration_tests/implicit_dir/implicit_dir_test.go
tools/integration_tests/interrupt/interrupt_test.go
tools/integration_tests/kernel_list_cache/setup_test.go
tools/integration_tests/local_file/local_file_test.go
tools/integration_tests/log_rotation/log_rotation_test.go
tools/integration_tests/managed_folders/managed_folders_test.go
tools/integration_tests/operations/operations_test.go
tools/integration_tests/operations/write_test.go
tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
tools/integration_tests/read_cache/disabled_cache_ttl_test.go
tools/integration_tests/read_cache/job_chunk_test.go
tools/integration_tests/read_cache/local_modification_test.go
tools/integration_tests/read_cache/range_read_test.go
tools/integration_tests/read_cache/read_only_test.go
tools/integration_tests/read_cache/remount_test.go
tools/integration_tests/read_cache/setup_test.go
tools/integration_tests/read_cache/small_cache_ttl_test.go
tools/integration_tests/readonly_creds/readonly_creds_test.go
tools/integration_tests/util/client/storage_client.go

Removed Timeout limit in StorageClient from all packages in integration_tests as there was timeout limit exceeded error while running integration tests.
NA

Remove Timeout limit in StorageClient from all packages in integration_tests

---

internal/fs/wrappers/monitoring.go
internal/fs/wrappers/monitoring_test.go

Currently, the category names are phrases/sentences. Keeping it as codes makes them more succinct and easily searchable.
NA
1. Manual - NA

Change category name to look more like codes

---

perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

Enhancements to testing on GKE (reopen of accidentally closed #2319)
- Support instance_id
1. Support env variable instance_id in run-script and in the python scripts (this allows multiple users to run the same tests using the same input/output bucket(s) without overwriting each others's outputs).
- Support multiple combinations of blockSize,numThreads,filesPerThread combinations for a given fileSize for fio tests, in the same run without overwriting each other.
This follows right after https://github.com/GoogleCloudPlatform/gcsfuse/pull/2272 .
This is followed up in https://github.com/GoogleCloudPlatform/gcsfuse/pull/2322 and in https://github.com/GoogleCloudPlatform/gcsfuse/pull/2329 .
NA
1. Manual - NA

[testing-on-gke part 3] Support instance-id and more complex configuration combinations (reopen of PR#2319)

---

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
tools/integration_tests/read_cache/disabled_cache_ttl_test.go
tools/integration_tests/read_cache/job_chunk_test.go
tools/integration_tests/read_cache/local_modification_test.go
tools/integration_tests/read_cache/range_read_test.go
tools/integration_tests/read_cache/read_only_test.go
tools/integration_tests/read_cache/remount_test.go
tools/integration_tests/read_cache/setup_test.go
tools/integration_tests/read_cache/small_cache_ttl_test.go

Fix a bug in how read cache e2e tests are run for different configs - Without this fix, if same file name is put at the time of creation of config file and there are multiple places in the same test where we are creating config file, then only the last config is run (because the creation function overwrites the config file).
In this fix, we create config file just before running test for that config, so even if there are overwrites to config file, there is no problem.
NA
1. Manual - NA

Fix a bug in how read cache e2e tests are run for different configs.

---

internal/storage/storage_handle.go
internal/storage/storage_handle_test.go
internal/storage/storageutil/test_util.go

Do not create a gRPC client if a custom endpoint is provided, as custom endpoints may not support gRPC client functionality.(e.g. TPC)
NA
1. Manual - tested on TPC environment

Fix creation of gRPC client with enable-hns true on custom endpoint

---

.github/workflows/ci.yml
tools/scripts/skip_tests.go
tools/scripts/skip_tests/main.go

A convoluted shell pipeline was being used to generate the list of skipped tests in a format that `go test -skip` accepts. Use a script to simplify that.
NA
1. Manual - NA

Use a script to yield list of skipped tests

---

internal/fs/wrappers/error_mapping.go
internal/fs/wrappers/error_mapping_test.go

The Control client folder APIs are currently returning RPC error codes instead of Google API codes. This discrepancy is causing incorrect error conversion within the FUSE layer.
NA
1. Manual - Tested

Convert rpc error code in fuse error

---

cfg/config.go
cmd/config_validation_test.go
cmd/root_test.go
internal/config/mount_config.go
internal/config/testdata/valid_config.yaml
internal/config/yaml_parser_test.go
tools/config-gen/params.yaml
tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
tools/integration_tests/read_cache/disabled_cache_ttl_test.go
tools/integration_tests/read_cache/job_chunk_test.go
tools/integration_tests/read_cache/local_modification_test.go
tools/integration_tests/read_cache/range_read_test.go
tools/integration_tests/read_cache/remount_test.go
tools/integration_tests/read_cache/setup_test.go
tools/integration_tests/read_cache/small_cache_ttl_test.go
tools/integration_tests/run_tests_mounted_directory.sh

Disable O_DIRECT by default & add directio in e2e tests for read_cache
NA
1. Manual - NA

Disable O_DIRECT by default

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
perfmetrics/scripts/continuous_test/gcp_ubuntu/continuous.cfg

Adding log file to obtain gcsfuse debug logs for listing perf tests.
NA
1. Manual - NA

Added log file flag for list perf tests

---

perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh
perfmetrics/scripts/continuous_test/ml_tests/tf/resnet_hns/build.sh
perfmetrics/scripts/continuous_test/ml_tests/tf/resnet_hns/continuous.cfg
perfmetrics/scripts/ml_tests/tf/resnet/Dockerfile
perfmetrics/scripts/ml_tests/tf/resnet/setup_host_and_run_model.sh
perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh

- Add the necessary setup to run Tensorflow AI/ML tests with an HNS bucket, utilizing the newly integrated folder APIs.
- Created HNS bucket in us-central1 region and copied all ai-ml training data.
- Created reservation for a2-gpu machine in gcs-fuse-test project.
- Validated from the logs, folder APIs are getting called.
NA

Add script changes to run tensor flow model with control client APIs on HNS bucket

---

flaky_tests.lst

Skip the flaky test: RandomReaderTest.Test_ReadAt_CacheMissDueToInvalidJob
NA
1. Manual - NA

Skip flaky test

---

tools/integration_tests/run_e2e_tests.sh

The concurrent_operations package, which experiences intermittent failures on presubmit tests, primarily due to parallel execution on the FLAT bucket, has been executed. Added this package serially after all the tests gets completed to avoid intermittent failures.
NA
1. Manual - NA

Add concurrent op tests for HNS bucket

---

perfmetrics/scripts/ls_metrics/config-hns.json

Updated config-hns.json with folder containing 1 million files for periodic listing perf tests for HNS bucket.### Link to the issue in case of a bug fix.
NA
1. Manual - NA

Adding folder containing 1m files to ls perf tests config file for hns bucket

---

.github/workflows/flake-detector.yml

go tests have a timeout of 10 minutes by default. Since the tests are run several times in this workflow, we need to increase the timeout accordingly. Otherwise, the tests will time-out after 10 minutes.
NA
1. Manual - NA

Increase timeout of test runs

---

tools/integration_tests/operations/operations_test.go
tools/integration_tests/read_cache/setup_test.go
tools/integration_tests/read_large_files/read_large_files_test.go
tools/integration_tests/readonly/readonly_test.go
tools/integration_tests/rename_dir_limit/rename_dir_limit_test.go
tools/integration_tests/run_tests_mounted_directory.sh

During testing on the HNS bucket, I modified the cache-dir name with a random string at runtime. This change is incompatible with the GKE environment. I have now resolved this issue.
NA
1. Manual - Tested the script locally 

GKE e2e test fix

---

main.go
tools/integration_tests/mounting/gcsfuse_test.go

This switches the defaults to use the new Viper based configuration instead of urfave/cli.
NA
1. Manual - NA

Enable new config by default

---

internal/fs/fs.go
internal/fs/inode/base_dir.go
internal/fs/inode/dir.go
internal/fs/inode/dir_test.go
internal/fs/local_file_test.go
tools/integration_tests/concurrent_operations/concurrent_listing_test.go

Add new file to type cache
This avoids an additional list call in case of implicit-dirs.
NA
1. Manual - NA

Add new file to type cache

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go
cmd/root_test.go
cmd/testdata/valid_config.yaml
internal/config/mount_config.go
internal/config/yaml_parser_test.go
tools/integration_tests/mounting/gcsfuse_test.go

Make default enable-hns flag true
NA
1. Manual - NA

Make default enable-hns flag true

---

perfmetrics/scripts/ls_metrics/config.json
perfmetrics/scripts/ls_metrics/listing_benchmark.py

HNS bucket in use for the listing benchmarks script contains test folder with 1m files. Making that a one time manual run only since Kokoro periodic test job times out due to this case.
To run list perf test on folder with 1m files, comment out lines mentioned in the script header.
Part1: To prevent data deletion, did the necessary changes
Part2: Will add flag whether to run 1m files test or not.
NA
1. Manual - Ran to check if the script is working as intended and skips 1m files folder while performing tests.

Fixing kokoro timeout issue for perf test: Skipping testing folder with 1M files from HNS bucket from listing tests

---

tools/integration_tests/managed_folders/admin_permissions_test.go
tools/integration_tests/managed_folders/test_helper.go
tools/integration_tests/managed_folders/view_permissions_test.go

End-to-end tests were failing on some buckets due to the presence of that pre-existing data. This was fixed by cleaning up the directory before creating new data.
NA
1. Manual - NA

Fix for managed folders e2e test - intermittent

---

tools/integration_tests/run_e2e_tests.sh

Disable flaky concurrent ops tests for HNS. Enable it once we find the root cause and fix it.
NA
1. Manual - NA

Disable flaky concurrent ops tests for HNS

---

cfg/config_util.go
cfg/config_util_test.go
main.go
main_test.go

To maintain backward compatibility, we're adding a "-" prefix to all GCSFuse arguments, aligning with cobra/viper's use of POSIX-compliant flags (which require a "--" prefix). However, this led to a bug where negative numbers were also receiving the "-" prefix, as we hadn't explicitly accounted for this scenario. The fix involves implementing a check to bypass negative numbers when adding prefixes.
NA
1. Manual - Manually verified '--kernel-list-cache-ttl-secs -1` flag is working now.

[CLI Config Parity] fix error to handle negative numbers in gcsfuse arguments

---

internal/storage/caching/fast_stat_bucket.go
tools/integration_tests/run_e2e_tests.sh

While inserting and removing folder entries from the cache, we did not implement a lock. Consequently, during concurrent operations tests, it was failing with the error `Concurrent operation on map iterating and erasing`.
To resolve this issue, implement a lock before performing any operation on the cache.
NA
1. Manual - Tested by running concurrent_operation package many times locally.

Add lock for erasing/inserting entries for folder

---

perfmetrics/scripts/vm_metrics/vm_metrics.py

We recently started publishing latency in microseconds instead of milliseconds. This resulted in the latency shooting up by a factor of
1000. Divide it by 1000 to bring it back to the previous levels.
NA
1. Manual - NA

Divide the latency by 1000

---

cmd/config_validation_test.go
cmd/root.go
cmd/root_test.go
main.go
main_test.go

This makes the tests closer to the production case where the args are first modified to conform the Posix args format; one that pflag supports.
NA
1. Manual - NA

Convert args to Posix compatible args in tests

---

cmd/root.go

Currently, if the gcsfuse mounting fails on any error, the command's usage is printed. This is not always desirable since there is an overload of superfluous information and the actual error gets lost.
With this change, we now just show the actual error and suppress the usage. The usage continues to remain available if the user passes "-h" or "--help" as arguments.
NA
1. Manual - NA

Don't print usage when command execution errs out.

---

cfg/config.go
tools/config-gen/templates/config.tpl

The omitempty tag doesn't print the fields that are set to their zero values. For instance, if an int flag is set to 0, it's not printed in the logs. Fix that by removing the omitempty struct tags.
NA
1. Manual - NA

Remove omitempty tag to print the full config.

---

internal/auth/auth.go

- Made it more readable
- Fixed return  error
```
jwtConfig, err := google.JWTConfigFromJSON(contents, scope)
if err != nil {
err = fmt.Errorf("JWTConfigFromJSON: %w", err)
return nil, err
}
```
NA
1. Manual - Tested on TPC environment

Fix error return in tokenSrc 

---

internal/storage/storage_handle.go
tools/cd_scripts/package_gcsfuse.sh

Removing changes that attempt to run both ARM64 and AMD64 packages on the same AMD64 machine. This is because cross-platform builds can sometimes get stuck and fail to build ARM64 packages on an AMD64 machine.
NA
1. Manual - Tested on louhi

Disabling Cross-Platform Package Execution on AMD64

---

cfg/config.go
cfg/params.yaml
cmd/root_test.go

* Rename the file-cache-specific flags to have file-cache as prefix.
* Make file-cache-enable-crc hidden.
NA
1. Manual - NA

Rename file-cache specific flags

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh

Corrected mount flags for HNS perf test. Caching was turned off for HNS bucket initially, but now we use default values just like perf testing flat bucket for a correct comparison.
NA
1. Manual - NA

correcting mount config for hns perf test

---

cmd/legacy_main.go
cmd/root.go
main.go
main_test.go
tools/integration_tests/mounting/gcsfuse_test.go

Added a kill-switch flag "--disable-viper-config" to use legacy config/flags in case something goes wrong. This will be cleaned up after 2 releases.
NA
1. Manual - Manually verified that old configs are being used when kill switch flag is added.
3. Integration tests - Added

Add kill switch flag for cli config parity

---

.github/workflows/shadow.yml

ready_for_review triggers the GitHub action only when a PR is moved from draft PR to "Ready to Review" stage. So, shadow-reviewers don't get added when a PR is directly created without going through the draft stage. Use review_requested to add shadow reviewer when a review is requested.
NA
1. Manual - NA

Add shadow reviewer when PR's review is requested

---

cfg/config_util.go
cfg/config_util_test.go
cmd/legacy_main.go
cmd/legacy_main_test.go

Add enable-parallel-downloads flag in user agent so that we can track the adoption. Also did some refactoring in the existing unit tests.
NA
1. Manual - NA
3. Integration tests - [Run 1](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/9f6db78c-9df0-4605-860b-2b658d55340d)

Add enable-parallel-downloads flag in user agent

---

perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

1. This removes dependence on user having to pass absolute paths for arguments in the run-script.
2. Passes gcsfuse-mount-options, machine-type from run-script down to the python run script for better programmability rather than manipulating pod configs using SED.
3. Uses kubectl namespace properly in the run-script.
4. Makes output file/dir configurable.
5. Added overall timeout on pod runs.
This is on top of https://github.com/GoogleCloudPlatform/gcsfuse/pull/2359 (and #2319) .
This is followed up in https://github.com/GoogleCloudPlatform/gcsfuse/pull/2348 . 
NA
1. Manual - NA
6. Unit tests - NA
7. Integration tests - NA

[testing-on-gke part 4] Fixes and improvements in the test setup

---

perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload.py
perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload_test.py
perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload.py
perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload_test.py
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
perfmetrics/scripts/testing_on_gke/examples/utils/utils.py
perfmetrics/scripts/testing_on_gke/examples/workloads.json

This adds the following changes
1. Now, gcsfuse_mount_options is no longer taken on the run-gke-tests.sh script, and is instead taken per workload in the `${workload_config}` file. Sample at https://github.com/GoogleCloudPlatform/gcsfuse/blob/57da96f33bb3ec8d587df22ff651d3b5dc766b44/perfmetrics/scripts/testing_on_gke/examples/workloads.json#L18) .
2. helm chart names and pod names have been shortened by using a hash of the workload rather than the long names earlier used which encapsulated the workload parameters such as blockSize/numThreads/batchSize etc. It still keeps the name of the scenario and file-size in the pod/chart name for some information for easy spotting though.
3. Adds validation checks and unit tests for dlio_workload and fio_workload.
This is on top of #2329 . It is …

[testing-on-gke part 5] Support per-workload gcsfuse-mount-options and other improvements

---

internal/fs/wrappers/monitoring.go

OTel tracing leverages context to propagate information about the ongoing trace. While the invokeWrapped method creates a new context as part of creating a new trace, it doesn't propagate that context to the subsequent method calls; the old context gets propagated. This causes the subsequent spans to create a new trace instead of joining the ongoing one. Fix that by propagating the context containing span information.
Verified that there is no memory leak:
NA
1. Manual - Tested that the traces are getting correctly recorded.

Propagate the context augmented with trace info

---

perfmetrics/scripts/hns_rename_folders_metrics/run_rename_benchmark.sh
perfmetrics/scripts/upgrade_gcloud.sh

- Upgraded gcloud version for rename benchmark run. Previously kokoro periodic perf tests build fails due to 
```
ERROR: (gcloud) Invalid choice: 'storage'.
This command is available in one or more alternate release tracks.  Try:
gcloud alpha storage
```
This can be rectified by upgrading the gcloud version before the rename benchmark runs which makes use of gcloud commands.
NA
1. Manual - Ran on actual test data. Working as intended.

Upgrading gcloud version for rename perf tests

---

perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/utils/parse_logs_common.py

It extracts common code from fio/parse_logs.py and dlio/parse_logs.py and puts it in utils/parse_logs_common.py for sharing.
This is on top of #2507 (previously #2492 which got accidentally closed) and is followed up in #2493 .
NA
1. Manual - NA

[testing-on-gke part 6.1] extract common parser code

---

internal/contentcache/contentcache_test.go
internal/fs/all_buckets_test.go
internal/fs/caching_test.go
internal/fs/foreign_modifications_test.go
internal/fs/fs_test.go
internal/fs/local_modifications_test.go
internal/fs/read_only_test.go
internal/fs/stress_test.go
internal/gcsx/prefix_bucket_test.go
internal/gcsx/syncer_test.go
internal/gcsx/temp_file_test.go
tools/integration_tests/mounting/gcsfuse_test.go
tools/integration_tests/mounting/mount_helper_test.go
tools/prefetch_cache_gcsfuse/prefetch.go

ioutil is deprecated. Remove it with appropriate replacements in io and os packages.
NA
1. Manual - NA

Remove occurrences of ioutil from codebase

---

perfmetrics/scripts/testing_on_gke/examples/workloads.json

This adds test workload specific to serving workload in gke test setup tool.
NA
1. Manual - NA

[testing-on-gke future] Add tests for serving scenario

---

.github/workflows/ci.yml
go.mod
go.sum

This reverts commit 85cd104bfa13bc697f1d61e7c32c65e353591f3f. This is being done since currently running `go mod tidy` removes the goimports related dependencies. This causes the `goimports` command to fail in the format-test step of ci.yml. Revert the change until a proper fix is identified.
NA
1. Manual - NA

Revert "Use goimports to validate import declarations (#2462)"

---

.github/ISSUE_TEMPLATE/gcsfuse-bug-report.md

Changing the default priority of issue from p1 to p2.
NA
1. Manual - NA

Change default priority of bug report from p1 to p2

---

perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/utils/run_tests_common.py
perfmetrics/scripts/testing_on_gke/examples/utils/run_tests_common_test.py

It extracts common code from fio/run_tests.py and dlio/run_tests.py and puts it in utils/run_tests_common.py for sharing.
This is on top of #2489 and is followed in #2495 .
NA
1. Manual - NA

[testing-on-gke part 6.2] extract common runner code

---

cfg/config.go
cfg/constants.go
cmd/root.go
tools/config-gen/templates/config.tpl
tools/mount_gcsfuse/main.go
tools/mount_gcsfuse/main_test.go

* Get the list of flags from the code-generated list and use that to automatically convert the persistent mount flags to appropriate format.
https://b.corp.google.com/issues/368503898
1. Manual - NA
2. Unit tests - Tested with existing unit tests.

Do away with the requirement of adding every flag in mount_gcsfuse

---

benchmarks/internal/percentile/duration_test.go
internal/cache/file/downloader/downloader_test.go
internal/cache/file/downloader/job_test.go
internal/cache/file/downloader/parallel_downloads_job_test.go

Reverts GoogleCloudPlatform/gcsfuse#2523 since it seems to break race-detector tests

Revert "Migrate downloader and duration tests to stretchr/testify"

---

perfmetrics/scripts/testing_on_gke/examples/workloads.json

In gcsfuseMountOptions in workloads.json
* Make metadata-cache infinite in all workloads
* Make cache-size infinite in all workloads
* Enable cache-file-for-range-read by default in all workloads
NA
1. Manual - NA

[testing-on-gke independent] update default workload config

---

tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/testdata/create_objects.sh

Created a temp directory at runtime to avoid collisions while running tests parallely as implicit_dir_test and explicit_dir_test both use the same script.
NA

Create a temp directory to avoid collisions while running tests parallelly

---

cfg/config_util.go
cfg/config_util_test.go
internal/fs/server.go
internal/fs/wrappers/monitoring.go
internal/fs/wrappers/tracing.go
internal/fs/wrappers/tracing_test.go

While the calls to tracing APIs are cheap,
we can reduce the performance impact by
conditionally instrumenting code only if tracing is enabled.
b/369493319
1. Manual - Verified that the instrumentation is enabled only when the tracing mode is set and not otherwise.

Instrument fs ops only when tracing enabled.

---

internal/storage/storageutil/control_client.go

Separates retry for control client from data client | increses timeout for retry | adds more error code for retry in control client
NA
1. Manual - NA
2. Unit tests - done

Fixes retry for control client

---

perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

Handle dependencies for successful execution on a GCE VM.
- Install google-cloud-monitoring python package
- Wait 30 min after CSI driver installation, before deploying pods, to avoid failure
- Avoid putting `google` in the name of the package-bucket as `google` is not allowed in bucket names.
This is on top of #2495 and is followed up in #2496 .
NA
1. Manual - NA

[testing-on-gke part 6.4] Add support for GCE VM

---

perfmetrics/scripts/testing_on_gke/examples/run-automated.sh
perfmetrics/scripts/testing_on_gke/examples/workloads.json
perfmetrics/scripts/testing_on_gke/examples/workloads_test.json

This is on top of #2524.
NA
1. Manual - NA

[testing-on-gke part 6.10] Add script for automating runs

---

cfg/config_util.go
cfg/config_util_test.go

Remove unused function

---

perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
perfmetrics/scripts/testing_on_gke/examples/utils/parse_logs_common.py
perfmetrics/scripts/testing_on_gke/examples/utils/run_tests_common.py

This change moves the logic for adding read/write permission for data buckets for the tests for the kubernetes service account, from the shell script to the python backend library. This is for being accurate for the target buckets (which should be parsed from the JSON-based workload configuration) which is not trivial in a shell script, and also for better maintainability, testability etc.
Source request: https://github.com/GoogleCloudPlatform/gcsfuse/pull/2329#discussion_r1738201905 (#2359 )
This is on top of #2482 and is followed up in #2497  .
NA
1. Manual - NA

[testing-on-gke part 6.5] Move code to access bucket iam role to backend

---

perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/utils/utils.py
perfmetrics/scripts/testing_on_gke/examples/utils/utils_test.py

This is on top of #2496 and is followed up in #2498 .
NA
1. Manual - NA

[testing-on-gke part 6.6] Enforce one pod per node

---

tools/integration_tests/concurrent_operations/concurrent_listing_test.go

Reduced number of iterations as it takes longer to run this test while running concurrently with other tests.
NA

Reducing number of iterations as it takes longer to run this test while running concurrently with other tests.

---

tools/integration_tests/read_cache/helpers_test.go
tools/integration_tests/read_cache/job_chunk_test.go
tools/integration_tests/read_cache/setup_test.go

Reduced file size, adjusted chunk size accordingly and increased retries as it takes longer to cache while running this test concurrently with other tests.
NA

Reduce file size, adjust chunk size accordingly and increase retries.

---

tools/integration_tests/managed_folders/admin_permissions_test.go
tools/integration_tests/managed_folders/view_permissions_test.go
tools/integration_tests/operations/operations_test.go
tools/integration_tests/readonly/readonly_test.go
tools/integration_tests/readonly_creds/readonly_creds_test.go
tools/integration_tests/util/creds_tests/creds.go

Using storage client instead of executing gcloud command to apply/revoke permission for service account for integration tests.
Motivation: gcloud commands can't be run concurrently as part of parallelizing CD tests.Thus, needs to be replaced.
NA
1. Manual -  Ran the integration tests manually on GCE VM.

replacing gcloud command for updating/revoking permission to service account

---

go.mod
go.sum
tools/integration_tests/managed_folders/admin_permissions_test.go
tools/integration_tests/managed_folders/view_permissions_test.go
tools/integration_tests/operations/operations_test.go
tools/integration_tests/readonly/readonly_test.go
tools/integration_tests/readonly_creds/readonly_creds_test.go
tools/integration_tests/util/creds_tests/creds.go

Replacing gcloud command for accessing the credential secret for integration tests, currently using secret manager client to access it.
Motivation: gcloud commands can't be run concurrently as part of parallelizing CD tests.Thus, needs to be replaced.
NA
1. Manual - Ran the integration tests manually on GCE VM.

Replace gcloud command to access credential secret

---

internal/storage/storageutil/control_client.go
internal/storage/storageutil/user_agent_round_tripper.go

We've recently observed some failures in our end-to-end tests when calling the CreateFolder API. The error message reads:
```
"MkDir: input/output error, CreateChildDir: rpc error: code = Internal desc = We encountered an internal error. Please try again." 
````
In  [this](https://github.com/GoogleCloudPlatform/gcsfuse/pull/2539), we initially made this error non-retryable because the go-sdk wasn't retrying it. However, we're reverting that change because we're encountering this error frequently in GCSFuse, necessitating a retry mechanism on our end.
NA
1. Manual - Already_Exist error code returned when retrying to Create already created folder and Not_found for deleting folder which is already deleted, these error codes are not part of retry.
3. Integration tests - …

Make createFolder and deleteFolder retry able

---

tools/integration_tests/util/client/storage_client.go

Added a SetRetry feature in CreateStorageClient to handle transient errors. Since our end-to-end tests use separate buckets for different VMs and each test operates on distinct resources, we can safely bypass the idempotency check.
NA
1. Manual - Not tested as required effort was more than scope of project.

Add SetRetry in CreateStorageClient

---

docs/dev_guide.md

Adding flags to mount_gcsfuse/main.go is no longer required. So remove it.
NA
1. Manual - NA

Fix documentation

---

.github/CODEOWNERS

Added additional code-owners in ai/ml synthetic test tool directory i.e. `perfmetrics/scripts/testing_on_gke`, to enable quicker merges of fixes/improvements :
1. gargnitingoogle (original author)
2. kislaykishore (original reviewer)
3. tulsishah (inheriting from perfmetrics/scripts)
4. charith87 (original reviewer)
NA
1. Manual - NA

Add code-owners for perfmetrics/scripts/testing_on_gke

---

perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

Improvements in run-script:
* handle pod status 'error'
* unique AR image-name for each run
* implement only_parse
* remove unused code
* fix package-bucket name
* improve logs
* use existing cluster machine-type
* simplify gcloud auth login
* pass project-id in gcloud commands
* Remove need to pass absolute paths
* support setting gcsfuse_branch for cloning
* Throw error if exactly one out of project_id and project_number has been set.
* Improve error logs by adding `Error: ` as prefix.
This is on top of #2497 and is followed up in #2499, #2322, and #2528 .
NA
1. Manual - NA

[testing-on-gke part 6.7] Improvements in run script

---

tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go

Added a loop to read 5 times from kernel cache and take minimum listing time in order to ensure that listing from GCS takes twice or more time than listing from kernel cache .
NA

Add a loop to read 5 times from kernel cache and take minimum listing time

---

cfg/config.go
cfg/params.yaml

The create-empty-file flag helps in cases where local files are involved. So, we cannot deprecate it unless we have a viable alternative. Un-deprecate it.
b/373302630
1. Manual - Verified that the flag is now appearing in the help doc.

Un-deprecate create-empty-file flag

---

tools/mount_gcsfuse/main.go
tools/mount_gcsfuse/main_test.go

Kernel mount command converts device/bucket name to path if directory with same name as bucket exists in the working directory. This results into error and failure of GCSFuse persistent mounts.
In order to fix this issue, we will convert the device name path received from kernel to it's base file name which will be bucket name.
NA
1. Manual - Manually verified that after this fix, user is able to mount GCSFuse even if bucket name directory exists in current working directory. The fix is working for both 
- `mount -t` command and 
- `/etc/fstab` entry.

[Error fix] GCSFuse mount command results in error if directory with bucket name exists in the working directory

---

internal/cache/file/downloader/job.go
internal/cache/file/downloader/parallel_downloads_job.go

Fix to not use O_DIRECT by default.
Tests performed manually:
machine spec:
n2-standard-96
16LSSDs
fio
```
; -- use nrfiles and rw to CLI args to control readtype and number of files --
[global]
ioengine=libaio
direct=0
fadvise_hint=0
iodepth=64
invalidate=1
nrfiles=16
thread=1
openfiles=1
group_reporting=1
create_serialize=0
allrandrepeat=0
file_service_type=random
numjobs=1
filename_format=$jobname.$jobnum/$filenum
[Workload]
directory=${DIR}
bs=128K
filesize=10G
rw=read
```
pytorch data loader
```
Loaded Llama 70B model
```
With `enable-o-direct=true` 
Fio throughput: 733MiB/s (221s)
Llama 70B model load time: 275s
Without `enable-o-direct=false` (default with this fix)
Fio throughput: 812MiB/s (201s)
Llama 70B model load time: 267s
NA
1. Manual - NA
3. Integration …

Fix to not use O_DIRECT by default

---

perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py

To avoid confusion created regarding unclaimed buckets mentioned in the test script ,  renamed all bucket names mentioned in the script to unit-test-mock-bkt to indicate that these buckets do not exist irl.
NA
1. Manual - Manually ran the test script to confirm no failures.

Renaming  fake test buckets in HNS perf test

---

tools/integration_tests/rename_dir_limit/config_hns.yaml
tools/integration_tests/run_e2e_tests.sh

We are getting this error `exec: "python": executable file not found in $PATH` while running e2e tests in periodically due to newly added test which uses python library. Fixing it by installing python3.
NA
1. Manual - NA

Fix e2e test by python3 installation

---

tools/integration_tests/managed_folders/admin_permissions_test.go
tools/integration_tests/managed_folders/list_empty_managed_folders_test.go
tools/integration_tests/managed_folders/managed_folders_test.go
tools/integration_tests/managed_folders/test_helper.go
tools/integration_tests/managed_folders/view_permissions_test.go

Replacing operations.DeleteManagedFoldersInBucket with client.DeleteManagedFoldersInBucket (Making calls to the function which uses control client instead of gcloud commands)
NA
1. Manual - Ran integration tests on GCE VM

Using control client to delete managed folders instead of executing gcloud command

---

tools/integration_tests/managed_folders/admin_permissions_test.go
tools/integration_tests/managed_folders/list_empty_managed_folders_test.go
tools/integration_tests/managed_folders/managed_folders_test.go
tools/integration_tests/managed_folders/test_helper.go
tools/integration_tests/managed_folders/view_permissions_test.go
tools/integration_tests/util/client/control_client.go

Replaced gcloud command in helper function in  managed folders test package, using control client to :
1.  DeleteManagedFoldersinBucket
2. CreateManagedFoldersinBucket
Motivation:  gcloud commands can't be run concurrently as part of parallelizing CD tests.Thus, needs to be replaced.
NA
1. Manual - Ran integration tests on GCE VM

Replaced gcloud command with control client code in Create/DeleteManagedFoldersInBucket in managed_folders test package 

---

tools/integration_tests/rename_dir_limit/rename_dir_test.go
tools/integration_tests/run_e2e_tests.sh

We are getting this error exec: "python": executable file not found in $PATH while running e2e tests in periodically due to newly added test which uses python library. Fixing it by using python3 instead of python while running tests.
- Small fixes to stat directory after renaming not exist.
NA
1. Manual - NA

Fix e2e test

---

internal/block/block.go
internal/block/block_test.go

Added block interface and memory block implementation
NA
1. Manual - N/A since this is standlone class for now
3. Integration tests - N/A

Added block interface and memory block implementations.

---

internal/fs/hns_bucket_test.go

Test fail on local machine due to python not being present in $PATH. Changed to python3 instead as it is more likely to be present in the machine.
NA
1. Manual - NA

[HNS test fix] change python to python3

---

internal/storage/storage_handle_test.go

Remove nonsensical code.

---

internal/block/block.go
internal/block/block_pool.go
internal/block/block_pool_test.go
internal/block/block_test.go

Added blockpool struct which is responsible for creating and maintaining blocks as per the user configuration.
NA
1. Manual - NA

Added blockpool struct

---

cmd/legacy_main.go
internal/storage/storage_handle.go
internal/storage/storage_handle_test.go
internal/storage/storageutil/client.go
internal/storage/storageutil/test_util.go

- Integrating the go-sdk's read-stall-retry changes: https://pkg.go.dev/cloud.google.com/go/storage@v1.45.0/experimental#WithReadStallTimeout
- Disabled by default.
NA
1. Manual - NA

feat: support to retry for stalled read request

---

tools/integration_tests/managed_folders/test_helper.go

- Created a file in the temporary directory with a random suffix because tests were intermittently failing due to permission overrides during parallelization.
NA
1. Manual - NA

Fix flaky managed folder test

---

internal/gcsx/content_type_bucket.go
internal/gcsx/content_type_bucket_test.go
internal/gcsx/prefix_bucket.go
internal/gcsx/prefix_bucket_test.go
internal/storage/fake/bucket.go
internal/storage/fake/fake_object_writer.go

This PR implements the following methods for fake bucket, prefix bucket and and content type bucket:
- CreateObjectChunkWriter()
- FinalizeUpload()
This PR builds on top of PR #2597
NA
1. Manual - NA

[Buffered Writes] bucket interface changes for buffered writes part 2

---

Dockerfile

Dockerfile generates a warning while building saying that the casing is incorrect. Fix that.
NA
1. Manual - Ran the build manually.

Fix warning in docker build

---

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh

Adding label for automating package build tests as a part of CI.
1. It will execute [build_and_install_gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/perfmetrics/scripts/build_and_install_gcsfuse.sh) script.
2. [execute-package-build-tests](https://github.com/GoogleCloudPlatform/gcsfuse/labels/execute-package-build-tests) label need to attach to test.
**Motivation:**
- Reduce the toil while upgrading the gem dependency.
NA
1. Manual - NA
6. Package build - Success

Add label automated tests for package building

---

go.mod
go.sum

Upgrading go-sdk version from 1.45.0 to 1.46.0
Why? - Last go-sdk version 1.45.0 has a regression in gRPC because of that gRPC directpath stopped working in GCSFuse. Go-storage 1.46.0 contains the fix for that.
NA
1. Manual - NA

chore: upgrade go-stroage from 1.45.0 to 1.46.0

---

cfg/config.go
cfg/params.yaml
cmd/legacy_main.go

SIGTERM is a termination signal that's sent by system (like SIGINT is sent by user). For instance, `docker stop` command uses it to give the container a chance to gracefully terminate.
Handle it to gracefully unmount GCSFuse.
b/376174285
1. Manual - Tested with and without flag

Handle SIGTERM to gracefully unmount

---

cfg/config.go
cfg/params.yaml
cfg/rationalize.go
cfg/rationalize_test.go
cfg/validate.go
cfg/validate_test.go
cmd/config_rationalization_test.go
cmd/config_validation_test.go
cmd/legacy_main.go
cmd/root_test.go
cmd/testdata/invalid_metrics_config_both_set.yaml
cmd/testdata/metrics_config/metrics_export_interval_positive.yml
cmd/testdata/metrics_config/stackdriver_export_interval_positive.yml
cmd/testdata/valid_config.yaml

* This flag controls the export interval of metrics to GCP cloud monitoring.
* Deprecate stackdriver-export-interval flag in favor of cloud-metrics-export-interval-secs.
b/377176812
1. Manual - NA

Add cloud-metrics-export-interval-secs flag

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go

- Enabling read-stall retry with `read-stall-min-timeout = 1.5s` and `read-stall-initial-timeout = 20s`
- Currently, submitting it to take advantage of existing automation. We will revert this PR if we find any issue because of read-stall feature.
NA
1. Manual - Tested: working fine.

Enabling read-stall-retry by default with best default

---

cfg/config.go
cfg/params.yaml
cmd/root_test.go
cmd/testdata/metrics_config/empty.yml
cmd/testdata/metrics_config/enable_otel_false.yml
cmd/testdata/metrics_config/enable_otel_true.yml

This flag is used to toggle between OTel and OpenCensus exporters.
b/377226855
1. Manual - NA

Add enable-otel flag

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh
perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
tools/integration_tests/list_large_dir/list_large_dir_test.go

1. Enabling existing e2e tests for presubmit, periodic e2e test automation.
2. Not enabling the test for louhi pipeline, will do that separately.
NA
1. Manual - NA

chore: enabling existing e2e test for gRPC

---

tools/cd_scripts/e2e_test.sh

This PR removes the -short flag from integration tests to ensure complete gRPC testing 
NA
1. Manual - NA

Enable gRPC e2e test in louhi pipeline

---

perfmetrics/scripts/ml_tests/pytorch/run_model.sh
perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
tools/cd_scripts/e2e_test.sh

This PR configures non-HNS long haul tests to use gRPC for PyTorch V2 and TensorFlow (excluding PyTorch V1.12).
NA
1. Manual - NA

Override non-HNS long haul test for gRPC

---

tools/integration_tests/concurrent_operations/setup_test.go

Enabling grpc for concurrent operations test package guarded under short flag.
NA
1. Manual - NA

enabling grpc for concurrent operations test

---

internal/block/block_pool.go
internal/block/block_pool_test.go
internal/bufferedwrites/buffered_write_handler.go
internal/fs/fs.go
internal/fs/handle/dir_handle_test.go
internal/fs/inode/dir_test.go
internal/fs/inode/file.go
internal/fs/inode/file_test.go

Made changes to createFile, readFile and writeFile to support streaming writes. 
Composite tests (local_file_test.go) will be added after all operations are modified. goal is to run all tests in local_file_test.go with streamingWrites enabled. We can't run now since all operations are not fixed. Hence will be done after all operations are modified.
NA

Modified Fs operations to support streaming writes

---

CONTRIBUTING.md
docs/dev_guide.md

Added coding guidelines for external contributions.
NA
1. Manual - NA

Coding guidelines for external contributions

---

internal/storage/bucket_handle.go
internal/storage/debug_bucket.go

[Updated]
Since the logging information was incorrect in the previous implementation described below, now we only add a log (at info level) for actual getStorageLayout API call and report the time taken to serve the request.
[Previous implementation detail]
As part of HNS , storage layout API is called, logs for this does not come at TRACE severity unlike other GCS calls. Hence, added the logic for the same so that when log severity is set to TRACE, then storage layout api calls are also logged as gcs calls. 
Any error faced during fetching the bucket type is already logged at error level, and will show up in the logs separately . However, as for the GCS call log, the storage layout api returns with status OK even when error is faced and logged immediately afterwards due to the nature of …

adding gcs call log for storage layout api

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go

Disabling the read-tail-latency by default.
NA
1. Manual - NA

chores: disable the read-stall-retry by default

---

perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh

Long haul tests are trying to create a vm with specific os version which is no longer supported by google. Hence updated to the latest version.
NA
1. Manual - Ran the command manually to check if we are able to create the vm.

using the latest ubuntu version for long haul tests

---

internal/fs/inode/dir.go

Switch warning log to error log for unsupported prefixes encountered during listing.
NA
1. Manual - NA

Switch warning log to error log

---

cfg/validate.go
cfg/validate_test.go
cmd/legacy_main.go
go.mod
go.sum
internal/monitor/otelexporters.go
internal/monitor/traceexporter.go

Add support for OTel Prometheus exporter. We'll add OTel metrics support in a subsequent PR and as part of it add integration tests for the exporter.
b/378088556
1. Manual - Tested manually that the OC exporters continue to work. Verified that Prometheus exporter exposes the metrics at /metrics.
3. Integration tests - TBD once the metrics are migrated to OTel.

Implement OTel Prometheus metrics exporter

---

internal/monitor/otelexporters.go

Implement Google Cloud exporter to emit metrics to Cloud monitoring.
b/380002762
1. Manual - Added an OTel metric and verified that it appeared on metrics explorer
3. Integration tests - NA - will be added once metrics have been migrated to OTel.

Emit metrics to Cloud monitoring

---

tools/build_gcsfuse/main.go

The problem I faced is described in the title, I hope this fix can be useful to someone else too.
I have a custom Dockerfile based on [the original Dockerfile in this repo](https://github.com/GoogleCloudPlatform/gcsfuse/blob/v2.0.1/Dockerfile), and my build runs behind an HTTP proxy, the build was failing. I realized it was due the following code snippet in [tools/build_gcsfuse/main.go](https://github.com/GoogleCloudPlatform/gcsfuse/blob/v2.0.1/tools/build_gcsfuse/main.go):
```
cmd := exec.Command(
"go",
"build",
...
// Set up environment.
cmd.Env = []string{
"GO15VENDOREXPERIMENT=1",
"GO111MODULE=auto",
fmt.Sprintf("PATH=%s", pathEnv),
fmt.Sprintf("GOROOT=%s", runtime.GOROOT()),
fmt.Sprintf("GOPATH=%s", gopath),
fmt.Sprintf("GOCACHE=%s", gocache),
"CGO_ENABLED=0",
}			
```
This code …

pass environment variables to go build command of build_gcsfuse to support builds behind an HTTP proxy

---

internal/cache/file/cache_handle_test.go
internal/cache/file/cache_handler_test.go
internal/cache/file/downloader/downloader_test.go
internal/cache/file/downloader/jm_parallel_downloads_test.go
internal/gcsx/bucket_manager.go
internal/gcsx/bucket_manager_test.go
internal/storage/bucket_handle_test.go
internal/storage/storage_handle.go
internal/storage/storage_handle_test.go

Using  the [storage.CheckDirectConnectivitySupported](https://pkg.go.dev/cloud.google.com/go/storage@v1.47.0#CheckDirectConnectivitySupported) function to check for direct connectivity support, this PR
adds a warning log message if direct connectivity is unavailable, including the bucket name and the error message.
This logging is only for GRPC data client.
Sample log:
```
Direct path connectivity unavailable for <bucket-name>, reason: storage: direct connectivity not detected
```
Time observed for figuring out direct connectivity :
For vm located in us-west1-b: 10159 msec(issue actively tracked in internal bug)
For vm located in us-central1-f : 365 msec
NA
1. Manual - NA

Add warning log for direct path connectivity

---

tools/integration_tests/mounting/gcsfuse_test.go

The expected version differs depending upon whether the installed package is being used. So, condition the test accordingly.
b/381357743
1. Manual - NA

Fix Version test

---

internal/storage/fake/bucket.go
internal/storage/fake/testing/bucket_tests.go

Reverts GoogleCloudPlatform/gcsfuse#2707 as we should map storage.ErrObjectNotExist to gcs.NotFoundError in NewReader method of bucket_handle.go

Revert "Modify fake bucket implementation to throw accurate error."

---

tools/integration_tests/emulator_tests/proxy_server/request_mapper.go
tools/integration_tests/emulator_tests/proxy_server/request_mappper_test.go

- Introducing a proxy server  between GCSFuse and the storage testbench server. The proxy's sole purpose is to attach the retry ID to requests, enabling the server to recognize and respond according to the test instructions. This is require to add e2e tests on retries in GCSFuse.
- In this PR we are adding request mapper which can map http request to Json, XML request type and instruction.
NA
1. Manual - NA

[Emulator tests] Add proxy server - 1

---

.github/workflows/ci.yml
.github/workflows/flake-detector.yml

* Currently, tests get timed-out probably due to resource constraints on the machine. Reducing the parallelism to 1 so that the resource requirements reduces.
* Keeping the cache tests and 
b/380798155
1. Manual - NA

Reduce test-parallelism to 1

---

tools/cd_scripts/e2e_test.sh
tools/integration_tests/benchmarking/benchmark_delete_test.go
tools/integration_tests/benchmarking/benchmark_stat_test.go
tools/integration_tests/run_e2e_tests.sh

The benchmarking test package performs delete and stat benchmark, the test will fail if the time taken for the operation is beyond the threshold.Also, added this to e2e test scripts(both kokoro and louhi pipeline).
NA
1. Manual - on cloudtop and GCE VM

add benchmarking test package to e2e testing 

---

internal/storage/bucket_handle.go
internal/storage/bucket_handle_test.go

map storage.ErrObjectNotExist in NewReader method to gcs.NotFoundError since for all other methods in bucket_handle.go storage.ErrObjectNotExist is mapped to gcs.NotFoundError.
NA

map storage.ErrObjectNotExist in NewReader method to gcs.NotFoundError

---

common/oc_metrics.go

This fixes a bug due to which the file-cache metrics were not getting exported.
NA
1. Manual - Verified that the all the metrics are showing up now in the Prometheus export

Add file-cache metrics to the OC views

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/fs/inode/file_test.go

Throwing custom error when non-sequential writes are detected. The caller will finalize and fallback to current approach. Those changes will be done after the flush changes are submitted.
NA
1. Manual - NA

Throwing OutOfOrder error for out of order writes

---

internal/fs/fs_test.go
internal/fs/hns_bucket_test.go
internal/fs/local_file_test.go
internal/fs/type_cache_test.go

Removed global err variable from fs_test package.
NA

Remove global err variable from fs_test package.

---

internal/fs/fs.go
internal/fs/inode/file.go
internal/fs/inode/file_test.go

Updated SetInodeattributes and getAttributes for handling mtime for local files and empty GCS files.
invoking bufferedWrites flow for empty gcs files.
NA
1. Manual - NA

Made changes to support setting mtime and getting when buffered writes are enabled

---

perfmetrics/scripts/testing_on_gke/examples/dlio/data-loader/templates/dlio-data-loader.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/data-loader/templates/fio-data-loader.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

1. Print the shell commands being run in the fio/dlio workloads.
1. Error out the fio/dlio workloads if any of their commands fail, for fail-fast.
1. Don't print out `csi_src_dir` in `only_parse=true` command if it's not applicable.
1. Replace all gsutil commands with gcloud commands in fio/dlio load-test/data-loader workloads.
1. Create training data files in dlio unet3d-load workload if missing.
NA
1. Manual - I've tested these manually by running my sample workloads, meant for testing this setup, locally.
6. Integration tests - NA

fixes and improvements in gke test setup

---

perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml

* This is so that the performance doesn't get affected due to multiple pods running on the same node.
* Specify timeout so that a pod doesn't keep running indefinitely
b/379205752
1. Manual - NA

Ensure that test workloads get scheduled on different nodes.

---

tools/integration_tests/list_large_dir/testdata/delete_objects.sh

Internal issue b/380007938
`gcloud` command sometimes fails during cleanup. Printing debug logs in case of failure will help us debug this in future.
Note: these logs are printed only in case of failure in gcloud command so the noise it will create is ok.
NA
1. Manual - NA

add debug logs for failure in gcloud rm call

---

internal/fs/inode/file_test.go

Stretchr is needed to write new tests based on t.Run()
NA
1. Manual - NA

changing test framework of file_test from jacobsa/ogletest to stretchr

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go

Throw ErrUploadFailure error in case of failure during Write or Flush call.
NA
1. Manual - NA

Throw ErrUploadFailure error in buffered writes

---

tools/integration_tests/emulator_tests/proxy_server/main_test.go
tools/integration_tests/util/setup/setup.go

Previously, unit tests were failing when running alongside end-to-end (e2e) tests. The error message indicated an undefined flag: -integrationTest. This issue is resolved by adding the command that parse tests within the TestMain function and return if integrationTest flag passed.
**Note**: We can't use [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/integration_tests/util/setup/setup.go#L264) as it accepts *testing.T but in TestMain we have *testing.M. If we want to use this function then we have to add this in each and every unit test.
NA
1. Manual - NA

Prevent unit test failure due to flag parse

---

internal/fs/inode/file.go
internal/fs/inode/file_test.go

For an emptyGCS file after first writes, reads are not allowed since buffered writes come into picture. Handling it and fixing the bug in earlier PR/
NA
1. Manual - NA

Fixing read for bufferedwrites and handling it for empty GCS File

---

tools/integration_tests/mount_timeout/gcsfuse_mount_timeout_test.go
tools/integration_tests/mount_timeout/mount_timeout_test.go

- Relaxing region based timeout thresholds to 2.5x
- The time used to compare will be the minimum out of 10 iterations 
NA
1. Manual - NA

Increasing mount timeout threshold and taking minimum of 10 iterations

---

tools/integration_tests/mounting/gcsfuse_test.go

It's failing in CD pipeline. We'll reenable it after fixing the issues.
NA
1. Manual - NA

Remove Version test

---

tools/integration_tests/mount_timeout/gcsfuse_mount_timeout_test.go

Skipping the mount timeout e2e test for this release.
NA
1. Manual - NA

skip mount timeout test

---

tools/integration_tests/run_e2e_tests.sh

Improved CI reliability by suppressing unnecessary output from gcloud during bucket deletion. This prevents exceeding Kokoro's log limits and ensures critical logs are preserved.
NA
1. Manual - NA

Remove unnecessary noises while deleting bucket in CI Pipeline

---

tools/cd_scripts/e2e_test.sh

Increase timeout as some tests take longer to run when parallelized.
NA
1. Manual - NA

Increase timeout as some tests take longer to run.

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go

This PR includes changes to:
**BufferedWriteHandler:**
- The Sync call now waits for all in-progress blocks to be processed.
- The Flush call finalizes the object as possible in case of an upload failure. It will return an error along with the object if a failure occurs.
**UploadHandler:**
- The uploader goroutine now frees all blocks, even in the event of an upload failure.
- `AwaitBlocksUpload` has been added to wait for all blocks to be uploaded.
NA
1. Manual - NA

update buffered write sync and flush methods

---

tools/integration_tests/emulator_tests/emulator_tests.sh

Tests were failing on arm64 machine as we don't have arm64 docker image. Remove this fix when we have an ARM64 image for the storage test bench.
NA
1. Manual - NA

Fix emulator based kokoro tests

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go
internal/gcsx/prefix_bucket.go
internal/gcsx/prefix_bucket_test.go
internal/monitor/bucket.go
internal/ratelimit/throttled_bucket.go
internal/storage/bucket_handle.go
internal/storage/caching/fast_stat_bucket.go
internal/storage/caching/fast_stat_bucket_test.go
internal/storage/debug_bucket.go
internal/storage/fake/bucket.go
internal/storage/fake/fake_object_writer.go
internal/storage/gcs/bucket.go
internal/storage/mock/testify_mock_bucket.go
internal/storage/mock_bucket.go

Use MinObject instead of Object as we only need MinObject in GCSFuse.
NA
1. Manual - NA

Buffered Writes Optimisation: Use MinObject

---

tools/package_gcsfuse_docker/Dockerfile

builds using 'package_gcsfuse_docker/Dockerfile' fail without specifying 'bundler' version to match 'tools/gem_dependency/Gemfile.lock'
NA
1. Manual - NA

Lock bundler version

---

internal/fs/kernel_list_cache_inifinite_ttl_test.go
internal/fs/kernel_list_cache_test.go
internal/fs/kernel_list_cache_zero_ttl_test.go
tools/integration_tests/util/operations/operations.go

skip kernel list cache test for unsupported kernel version 6.9.x - Ref issue #2792
NA
1. Manual - NA

skip kernel list cache test for unsupported kernel version

---

internal/cache/file/downloader/job.go
internal/cache/file/downloader/job_test.go
internal/logger/logger.go
tools/integration_tests/managed_folders/test_helper.go
tools/integration_tests/util/operations/dir_operations.go
tools/integration_tests/util/operations/operations.go
tools/prefetch_cache_gcsfuse/prefetch.go

`go vet` command was failing with errors like: 
```
non-constant format string in call to github.com/googlecloudplatform/gcsfuse/v2/tools/integration_tests/util/operations.ExecuteGcloudCommandf
```
This PR fixes those errors.
NA
1. Manual - NA

fix make command

---

perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

This fixes a bug unintentionally introduced in #2818 . In that changeset, the bash function `uuid` was printing out some more information other than the uuid value itself because of the installation step. In bash, the printed log becomes the output of a function, hence the installation inside this function was changing the output of the `uuid` function breaking the caller. So, I have moved the installation out to wherever we're invoking this function.
NA
1. Manual - NA

fix bug in csi driver build

---

internal/fs/kernel_list_cache_inifinite_ttl_test.go

skip kernel list cache tests for kernel version 6.10+.
NA
1. Manual - NA

skip kernel list cache tests for kernel version 6.10+

---

internal/bufferedwrites/buffered_write_handler.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go

Fall back out of order writes to temporary file.
NA
1. Manual - NA

[Streaming writes] Fall back out of order writes to temporary file

---

internal/fs/fs.go
internal/fs/handle/file.go
internal/fs/inode/file.go
internal/fs/inode/file_test.go

Setting bwh to nil after all fileHandles are closed in case of error.
Follow up PR will be raised to clear the buffers
NA
1. Manual - NA

Setting bwh to nil after all fileHandles are closed

---

internal/storage/bucket_handle.go
tools/integration_tests/rename_dir_limit/rename_dir_limit_test.go

This change addresses an issue identified in [b/378625027](https://b.corp.google.com/issues/378625027) where gRPC precondition failures were not being handled correctly.
Previously, error handling only checked for HTTP status codes, but gRPC uses error code 9 for precondition failures. This update adds explicit handling for gRPC error code 9 to ensure proper detection and management of precondition failures in gRPC calls.
Additionally, gRPC tests are enabled for the rename_dir_limit test package to improve test coverage .
Note: Handling of rpc codes for the different flows will be taken seperately.
NA
1. Manual - NA

Fix: Handle gRPC precondition failures while creating object

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go
internal/fs/fs.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go
internal/fs/inode/inode.go
internal/fs/inode/symlink.go
internal/fs/streaming_writes_common_test.go
internal/fs/streaming_writes_empty_gcs_object_test.go
internal/fs/streaming_writes_empty_object_test.go
internal/fs/streaming_writes_local_file_test.go
tools/integration_tests/util/operations/validation_helper.go

Support Unlink operation when streaming writes are in progress.
Changes include:
- Cancelling ongoing upload's context and freeing up resources.
- File Inode Unlink will be called for both local and generation backed inodes.
NA
1. Manual - NA

Support Unlink operation when streaming writes in progress

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go
internal/fs/fs.go
internal/fs/handle/file.go
internal/fs/inode/file.go

Added destroy method which will clean up the memory buffers when bwh is unInitialized.
NA
1. Manual - NA

Added destroy method to free up the memory buffers

---

internal/fs/inode/base_dir.go
internal/fs/inode/dir.go
internal/fs/inode/hns_dir_test.go
internal/storage/mock/testify_mock_bucket.go

- RenameFile function in dir.go file
- Added unit tests for successful rename and source does not exist
NA
1. Manual - NA

[Move Object] Add rename file method in dir layer

---

internal/storage/bucket_handle.go
internal/storage/bucket_handle_test.go

- MoveObject bucket handle integration
- Unit tests are not covered as we're currently using a fake storage server for the rest of our storage client API unit tests. To add unit tests for the MoveObject function, we have two options:
1. Add a moveObject API to the [fake GCS server repository](https://github.com/fsouza/fake-gcs-server/blob/main/fakestorage/object.go,). This would involve extending the fake server's functionality to include support for the move operation. This seems like a more complex solution and time consuming.
2. Mock the MoveObject API. Mocking is not possible because the MoveObject function takes a [private](https://github.com/googleapis/google-cloud-go/blob/main/storage/http_client.go#L596) struct from storage library as an argument.  
NA
1. Manual - NA
2. Unit tests …

[Move Object] Bucket handle integration

---

internal/storage/caching/fast_stat_bucket.go
internal/storage/caching/fast_stat_bucket_test.go
tools/integration_tests/implicit_dir/local_file_test.go
tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
tools/integration_tests/util/operations/string_operations.go
tools/integration_tests/util/setup/setup.go

After deleting an object or folder populate negative cache immediately.
This will save call/s to a backend to verify existence of a said object/folder resulting in perf gains.
Added invalidate logic in case of error to better handle all scenarios in case delete[object/folder] fails.
NA
1. Manual - NA

Add negative cache entry after deleting object/folderCache entry update

---

tools/integration_tests/run_tests_mounted_directory.sh

As part of [this](https://github.com/GoogleCloudPlatform/gcsfuse/pull/2822/files) PR we have added extra flag in e2e tests, so adding the same mountedDirectory script. 
NA
1. Manual - Tested

Fix mounted directory script

---

tools/integration_tests/emulator_tests/emulator_test.go
tools/integration_tests/operations/parallel_dirops_test.go

**Potential Problems:**
1. Data Race: The update to statInfo and lookUpErr in the goroutine may not be visible to the main thread immediately.
This can lead to a situation where lookUpErr == nil, but statInfo still appears nil in the main thread and cause panic.
2. Improper Synchronization: Even though we're using sync.WaitGroup to wait for goroutines to finish, there is no explicit guarantee that statInfo and lookUpErr are synchronized across goroutines and the main thread.
**Applied Fixes:**
1. Use pointers to pass results (statInfo, lookUpErr, etc.) directly to avoid shared variable conflicts.
2. Avoid Shared Variables: Each goroutine updates its respective variables, ensuring no concurrent writes to shared memory.
3. Thread-Safe Updates: By passing pointers, the main thread accesses …

Fix flaky parallel dirOps e2e tests

---

tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_delete_dir_test.go
tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_deletion_test.go
tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
tools/integration_tests/run_tests_mounted_directory.sh

Tests began failing due to execution sequence issues stemming from the addition of a negative cache upon deletion. To address this, the affected tests were moved to a separate file and configured with a metadata cache TTL of 0.
NA
1. Manual - NA

Fix kernel cache ttl test failure for GKE

---

internal/fs/fs.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go

This PR includes code changes to:
-  separate out flush and sync flow.
- file inode test to test for both sync and flush.
- integrate flush file and sync file for streaming writes and associated refactoring.
b/385064030
1. Manual - NA

streaming writes flush and sync flow

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go
cmd/root_test.go

Use OTel for metrics by default. One can override the behavior to use OpenCensus instead by setting --enable-otel flag to false.
b/387898221
Perf impact:
| Master |  0.25MiB   | 452.23MiB/s  | 1.16MiB/s  |  63.39MiB/s  |  1.29MiB/s   |
|   PR   |  0.25MiB   | 465.06MiB/s  | 1.33MiB/s  |  65.42MiB/s  |  1.29MiB/s   |
| Master | 48.828MiB  | 3757.51MiB/s | 77.25MiB/s | 1176.68MiB/s |  79.37MiB/s  |
|   PR   | 48.828MiB  | 3832.38MiB/s | 80.22MiB/s | 1209.13MiB/s | …

Make OTel the default for metrics

---

internal/fs/fs.go

Panic in inode.NewFileName() leads to another panic in the defer function, because of fs.mu.Unlock()
call over the already unlocked mutex. This eventually results into the loss of actual panic message
inside inode.NewFileName().
Moving defer function after fs.mu.Lock() to avoid this nested panic and hence original
panic message loss.
After the change, started getting the panic message:
```
{"timestamp":{"seconds":1736229731,"nanos":75546141},"severity":"ERROR","message":"Panic: Inode '' cannot have child file ''"}
{"timestamp":{"seconds":1736229731,"nanos":75724827},"severity":"ERROR","message":"goroutine 178 [running]:\nruntime/debug.Stack()\n\t/home/princer_google_com/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/runtime/debug/stack.go:26 …
```

Avoiding nested panic while lookUpLocalFileInode

---

tools/integration_tests/util/operations/validation_helper.go

Updated the ValidateStaleNFSFileHandleError function to dynamically fetch the error message associated with syscall.ESTALE. This change ensures that the function correctly identifies stale file handle errors across different architectures, including ARM64 and AMD64, which may return different error messages for the same syscall error.
NA

Refactor: ValidateStaleNFSFileHandleError for ARM64 Compatibility

---

.github/workflows/flake-detector.yml

* Flake detector runs the same set of tests 20 times which times out since the tests are no longer running in parallel. Reduce the number of times to 5 to make it pass.
b/380798155
1. Manual - NA

Reduce number of iterations for flake-detector

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go
cmd/root_test.go

This reverts commit 94c5ebd31c3123513ee73dcea434c8d3b66695a9.
* This is causing some of the periodic tests  to fail. These tests fetch the metrics using certain attributes that are valid only in the opencensus world. At the moment, I don't have bandwidth to check this. So, reverting it.
b/387898221
1. Manual - NA

Revert "Enable OTel metrics by default (#2859)"

---

tools/integration_tests/benchmarking/benchmark_delete_test.go
tools/integration_tests/benchmarking/benchmark_rename_test.go
tools/integration_tests/benchmarking/benchmark_stat_test.go
tools/integration_tests/benchmarking/setup_test.go

- Adding rename tests in benchmarking e2e tests to validate execution time for rename operation.
[b/388391082](https://b.corp.google.com/issues/388391082)
1. Manual - NA

[Move Object] Rename benchmark e2e perf test

---

internal/fs/fs.go
internal/fs/handle/dir_handle_test.go
internal/fs/inode/dir_test.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go

global max blocks semaphore limits the total number of blocks used across the files when streaming writes are enabled. This config should be created only once at file system level and re-used across files.
b/388184725
1. Manual - NA

Create global max blocks semaphore only once at file system level.

---

internal/fs/fs.go

Removed lock unnecessary comment for rename
NA
1. Manual - NA

Remove lock unnecessary comment

---

tools/cd_scripts/e2e_test.sh
tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_delete_dir_test.go
tools/integration_tests/negative_stat_cache/disabled_negative_stat_cache_test.go
tools/integration_tests/negative_stat_cache/finite_int_negative_stat_cache_test.go
tools/integration_tests/negative_stat_cache/infinite_negative_stat_cache_test.go
tools/integration_tests/negative_stat_cache/setup_test.go
tools/integration_tests/run_e2e_tests.sh

This PR adds e2e integration tests for negative stat cache, scenarios include:
1. Happy path - TTL set to a finite positive integer.
2. Disabled Cache - TTL set to 0
3. Infinite Cache - TTL set to -1
b/387905752
1. Manual - NA

Negative cache integration tests

---

cfg/config.go
cfg/params.yaml
cmd/root_test.go

Turn on the flag for Move object
NA
1. Manual - NA

Turn on the flag for Move object

---

internal/fs/inode/file.go

This PR updates wrapped error while returning FileClobberedError after calling clobbered method as clobbered method return err as nil if file is clobbered.
[Bug Link](https://b.corp.google.com/issues/388693349)

Update wrapped error while returning FileClobberedError after calling clobbered method

---

go.mod
go.sum

Downgrading the go-sdk to v1.49.0 for GCSFuse v2.8.0.
NA
1. Manual - NA

Downgrade go-sdk from v1.50.0 to v1.49.0

---

docs/semantics.md

Updating the semantic docs with a new un-supported object for gcsfuse - object with suffix `\n`
NA
1. Manual - NA

Semantic doc for unsupported object with suffix `\n`

---

.github/workflows/stale.yml

Reduce stale period from 30 days to 14 days for external github issue.
b/389558445
1. Manual - NA

Close github issues if Cx doesn't response for 2 weeks

---

internal/fs/kernel_list_cache_inifinite_ttl_test.go

Based on https://github.com/GoogleCloudPlatform/gcsfuse/issues/2792#issuecomment-2591559168, the bug should be fixed for kernel version 6.13.0 and onwards.
Hence, skipping the KLC test till 6.12.x.
b/380427259
1. Manual - NA

Skipping KLC test for kernel version b/w v6.9.x and v6.12.x

---

common/util.go
common/util_test.go
internal/fs/kernel_list_cache_inifinite_ttl_test.go
tools/integration_tests/kernel_list_cache/finite_kernel_list_cache_test.go
tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_delete_dir_test.go
tools/integration_tests/util/operations/operations.go
tools/integration_tests/util/operations/validation_helper.go

1. Refactoring - moving the common utility b/w gcsfuse/internal and e2e tests in common package.
2. Added check to skip the e2e kernel list cache test for unsupported kernel version.
Ref: https://github.com/GoogleCloudPlatform/gcsfuse/issues/2792
1. Manual - Tested manually on unsupported kernel version.
4. Unit tests - Automation
5. Integration tests - Automation

Skipping Kernel List Cache E2E Test on the Unsupported Kernel Version

---

docs/semantics.md

This PR updates Semantics doc about the changes in GCSFuse behavior after Write Failure Improvements.
https://b.corp.google.com/issues/305012368
1. Manual - NA

Update Semantics doc about changes in GCSFuse behavior after Write Failure Improvements

---

tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go

2sec for the file to download is not getting sufficient for certain vm types in cd pipeline. Doubling it.
NA
1. Manual - NA

Increasing the wait time for cache population

---

tools/cd_scripts/e2e_test.sh

Monitoring tests fail with installed_package. So, skip them from cd. They are already covered by ci tests.
b/391097316
1. Manual - NA

Skip monitoring tests from cd

---

internal/storage/fake_storage_util.go
internal/storage/storage_handle.go
internal/storage/storage_handle_test.go

Enable dynamic creation of storage clients based on bucket type and specified protocol
Reason for not using mutex in getClient:
Multiple clients can be created in dynamic mounting case only. But in this case, the root dir will actually be a base_dir & we take a lock before calling LookUpChild for base_dir. So, this will ensure that call to BucketHandle (which means calls to getClient) will be serialized.
Reason for not adding a new config EnableBidiConfig in StorageClientConfig (& instead passing a separate parameter for bidi config while creating grpc client):
This config is created from the user provided config at the start (& should reflect that) and I would not like to keep a transient field to it (i.e. would not like to keep a field which has to be set every time before grpc client …

Enable dynamic creation of storage clients based on bucket type and specified protocol

---

docs/troubleshooting.md

Adding workaround to fix the crash because of object with suffix `\n`
b/389224118
1. Manual - NA

Update troubleshooting doc for crash `unlock of unlocked mutex`

---

tools/integration_tests/run_e2e_tests.sh

[b/391057586](https://buganizer.corp.google.com/issues/391057586) - Fix and put back TPC and emulator-tests
This partially reverts commit 9d33fa5340017208be465653ee7dc3f10442663c.
This re-enables TPC e2e tests from the code. Instead of this, we'll disable TPC e2e tests from kokoro config which is more efficient.
NA
1. Manual - NA

Partially Revert "Disable tpc and emulator tests in e2e"

---

tools/integration_tests/monitoring/prom_test.go

This is a temporary fix. We would like to get it working with installed package too but disabling it for now since metrics is currently not being worked upon.
b/391498868
1. Manual - NA

Skip test when testing with installed package

---

internal/gcsx/multi_range_downloader_wrapper.go
internal/gcsx/random_reader.go

1. Changes to ensure reader size does not stop growing in random reads scenario.
2. Logging error in MRD::Read
b/390543202, b/391753515

Fixing reader growth logic & logging errors in MRD::Read

---

tools/integration_tests/streaming_writes/default_mount_local_file_test.go
tools/integration_tests/streaming_writes/default_mount_test.go
tools/integration_tests/streaming_writes/truncate_file_test.go

Using existing tests to verify if bwh is returning file size correctly.
NA
1. Manual - NA

added stat calls in truncate tests for streaming writes

---

internal/fs/wrappers/error_mapping.go
internal/fs/wrappers/error_mapping_test.go
tools/integration_tests/negative_stat_cache/infinite_negative_stat_cache_test.go
tools/integration_tests/negative_stat_cache/setup_test.go
tools/integration_tests/util/client/control_client.go

On HNS bucket, when metadata cache is enabled and folder creation results into conflict (409), we are returning input/output error. The correct error code should be EEXIST.
This issue occurred on HNS buckets because the control client was returning a different error than the HTTP/gRPC client (a Precondition error), which prevented the conversion to the correct error code.
[b/391649826](https://buganizer.corp.google.com/issues/391649826)
1. Manual - NA

Fix "Already Exist" error code for folder creation

---

internal/gcsx/multi_range_downloader_wrapper.go
internal/gcsx/multi_range_downloader_wrapper_test.go

Making changes to stop using timer based cleanup function for MRD (Created b/391508479 to track restoring it).
Making this change against b/388177094

Stopping use of timer based cleanup logic for MRD

---

internal/fs/fs.go
tools/integration_tests/operations/stat_file_test.go

GCSFuse crashes when a stat call is made for a path where the file name is just "\n". Instead, return an ENOENT error.
b/391795883
1. Manual - NA
3. Integration tests - Added.

Fix crash when the file name being statted is just "\n"

---

tools/integration_tests/streaming_writes/default_mount_empty_gcs_file_test.go

Fixing the truncate test for empty GCS file in streaming writes flow

---

internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go

Handle write edge case when first write is out of order write followed by write at offset 0.
Issue: when we get out of order write, we flush buffered write handler (to finalize whatever we have) and also set bwh to nil
First out of order write creates a source object of size 0, so even after bwh is cleared, it is recreated during the write call. Later when a write at offset 0 happens, it will go to bwh. Partial writes to bwh and temp file can cause errors.
Solution: If temp file is in use, don't re-create buffered write handler.
b/391545203
1. Manual - NA

Handle write edge case when first write is out of order write

---

cfg/config.go
cfg/params.yaml
cfg/rationalize.go
cfg/rationalize_test.go
cfg/validate.go
cfg/validate_test.go
cmd/config_validation_test.go
cmd/testdata/write_config/invalid_write_config_due_to_invalid_global_max_blocks.yaml
cmd/testdata/write_config/invalid_write_config_due_to_zero_max_blocks_per_file.yaml
internal/fs/fs.go

Change global max blocks config to allow for 0 blocks.
Set a reasonable value for max blocks per file when it is set to -1.
b/392549199
1. Manual - NA

Streaming writes config validation changes

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go

We were finalizing only for upload failure and out of order writes but it makes sense to finalize the object in case of any failure.
b/392834488
1. Manual - NA

Finalize object for any error in buffered writes flow

---

internal/fs/fs.go

[Readability fix] Be explicit that nil child is being returned.

---

cfg/config_util.go
cmd/legacy_main.go
cmd/legacy_main_test.go

To track usage of streaming writes config, added bitset for streaming writes to user agent. This is a temporary change until we find a better way to track usage.
NA
1. Manual - NA

Add streaming writes config to useragent

---

internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go

This is a temporary change to set no chunk retry timeout for buffered writes writer.
b/393112604
1. Manual - NA

Remove chunk retry timeout for buffered writes writer

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/bufferedwrites/upload_handler.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go

- A panic was happening due to close of already closed channel in upload_handler.go Finalize() method.
We should not allow finalize after the upload has failed once.
- During write, we should flush partially written object for out of order writes only. For all other cases, we will wait for file handle to send flush call to finalize the object.
b/393120278
1. Manual - NA

fix re-flush for streaming writes

---

internal/fs/inode/file.go
internal/fs/inode/file_test.go
internal/gcsx/multi_range_downloader_wrapper.go
internal/gcsx/multi_range_downloader_wrapper_test.go
internal/gcsx/random_reader_stretchr_test.go

1. Ensure MRD's minObject is updated when inode's minObject is updated.
2. Ensure that we set MRD to nil if there were any errors while creating it. (We observed that NewMultiRangeDownloader returned a non nil value for MRD even in case of error)
b/391534052

Fixing MinObject related issues in MRDWrapper

---

internal/fs/wrappers/error_mapping.go

gRPC returns status messages on error (https://google.aip.dev/193#error_model). So, it should be used to handle gRPC errors.
apiError is a wrapper over status & googleApi.Error. So, ideally, we should just be using apiError.Error and then check whether the underlying error was http or gRPC and then proceed (i.e. try to convert error to apiError.Err and if it succeeds, then use appropriately). But the http error that we got returned success when converted to both status as well as googleApi.Error (although with unknown code in converted status). 
Hence, we have to check for both scenarios (http & grpc). So, there is no use of using apiError. Hence, started using status directly for gRPC.
b/392000371

Improving error conversion logic

---

internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go

we should close upload failure channel in case of error during finalize. This will ensure that all file handles will fail after error in flush.
NA
1. Manual - NA

Close upload failure channel in case of error during finalize

---

internal/fs/fs.go
tools/integration_tests/local_file/rename.go
tools/integration_tests/streaming_writes/move_file_test.go

Doing this only when streaming writes is enabled to be safe. Will do it later for non-streaming writes.
NA
1. Manual - NA

Doing flush for pending writes on rename file 

---

tools/integration_tests/run_tests_mounted_directory.sh
tools/integration_tests/streaming_writes/buffer_size_test.go
tools/integration_tests/streaming_writes/streaming_writes_test.go
tools/integration_tests/write_large_files/write_large_files_test.go

This PR adds streaming_writes integration tests to run_tests_mounted_directory.sh.
Both the commands have been manually tested.
b/394024245
1. Manual - done

Add streaming_writes integration tests to run_tests_mounted_directory.sh

---

Dockerfile
go.mod
perfmetrics/scripts/ml_tests/pytorch/run_model.sh
perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
perfmetrics/scripts/read_cache/setup.sh
tools/cd_scripts/e2e_test.sh
tools/containerize_gcsfuse_docker/Dockerfile
tools/integration_tests/run_e2e_tests.sh
tools/package_gcsfuse_docker/Dockerfile

Upgrade golang version to 1.23.5.
b/394002727
1. Manual - NA

upgrade to golang 1.23.5

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go
cmd/root_test.go
perfmetrics/scripts/vm_metrics/vm_metrics.py
perfmetrics/scripts/vm_metrics/vm_metrics_test.py

Use OTel for metrics by default. One can override the behavior to use OpenCensus instead by setting --enable-otel flag to false.
Perf:
| Master |  0.25MiB   | 480.23MiB/s  | 1.28MiB/s  |  67.36MiB/s  |  1.24MiB/s   |
|   PR   |  0.25MiB   | 489.49MiB/s  | 1.21MiB/s  |  68.74MiB/s  |  1.32MiB/s   |
| Master | 48.828MiB  | 3535.15MiB/s | 81.58MiB/s | 1250.43MiB/s |  82.85MiB/s  |
|   PR   | 48.828MiB  | 3428.55MiB/s | 81.17MiB/s | 1231.22MiB/s |  81.53MiB/s  |
| …

Enable OTel by default

---

tools/integration_tests/managed_folders/admin_permissions_test.go
tools/integration_tests/managed_folders/view_permissions_test.go
tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
tools/integration_tests/read_cache/disabled_cache_ttl_test.go
tools/integration_tests/read_cache/job_chunk_test.go
tools/integration_tests/read_cache/local_modification_test.go
tools/integration_tests/read_cache/range_read_test.go
tools/integration_tests/read_cache/read_only_test.go
tools/integration_tests/read_cache/remount_test.go
tools/integration_tests/read_cache/small_cache_ttl_test.go
tools/integration_tests/util/setup/setup.go

Read Cache logs are cleared in teardown for log parsing of next test. We should persist these logs in case of failure for debugging.
b/394211437
1. Manual - NA

Persist logs in read_cache test

---

tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/util/setup/setup.go

[b/393050917](http://b/393050917) - Create and pass test flag for zonal bucket
This creates a passable new flag '-zonal' to the e2e script i.e. tools/integration_tests/run_e2e_tests.sh and enables it to define a utility IsZonalBucketRun in e2e tests' setup. This only defines and passes the flag, but doesn't implement its usage in the e2e tests themselves. That change will be made in future PRs.
NA
1. Manual - NA

b/393050917 - Create zonal-bucket flag for e2e tests

---

internal/gcsx/random_reader.go
internal/gcsx/random_reader_stretchr_test.go

We collect readType as part of our read metrics and hence need to ensure that proper readType value is being maintained and shared for metrics collection.
b/394500505

Maintain readType for random reader

---

tools/integration_tests/run_e2e_tests.sh

test_dir_p was always the last package in the list. We need to maintain a mapping between package name and pid to print the correct package name in case of failure.
b/395002082
1. Manual - NA

keep mapping between pid and package name in e2e test script

---

tools/integration_tests/benchmarking/benchmark_delete_test.go
tools/integration_tests/benchmarking/benchmark_rename_test.go
tools/integration_tests/benchmarking/benchmark_stat_test.go
tools/integration_tests/util/setup/setup.go

* Tests in the benchmarking test package will be skipped in case the presubmit flag is turned on.
* Clean up for the cd scripts.
* In a follow-up PR, I will adjust the thresholds value based on periodic test region which is now us-west4.
NA
1. Manual - NA

making sure that benchmarking tests are run for periodic tests only

---

tools/integration_tests/readonly/readonly_test.go
tools/integration_tests/util/client/storage_client.go

* Always use client-type grpc for zonal bucket in e2e tests
* Always set append flag in the storage writer objects for zonal bucket in e2e tests
[b/393050972](http://b/393050972) - Create and pass test flag for zonal bucket
1. Manual - NA
3. Integration tests - Enabled through presubmit

Use grpc client always for zonal buckets in e2e tests

---

internal/monitor/bucket.go
internal/monitor/full_read_closer.go
internal/monitor/full_read_closer_test.go

* Wait for the entire buffer to be filled up before updating the metrics. This helps reduce the number of updates to the gcs/read_bytes_count metric by a factor of 1000 there by improving performance and reducing CPU and memory usage.
b/386226641
1. Manual - Verified reader behavior by checking that the md5 checksum of a file doesn't change when copied into a GCSFuse bucket.

Reducing the number of metric updates

---

internal/fs/inode/file.go
internal/fs/inode/file_mock_bucket_test.go

During Flush, we make a stat call to fetch all the attributes of an object which are required by create object call. For local files, this call can be avoided.
b/394759110
1. Manual - NA

do not do force stat for local files during flush

---

internal/storage/bucket_handle.go
internal/storage/bucket_handle_test.go
internal/storage/gcs/errors.go
internal/storage/gcs/errors_test.go

- Created a single method which wraps the error returned by go-sdk under gcs.NotFound or gcs.PreconditionFailed. This takes care of error coming from http, grpc and control client.
- Updated all the methods of bucket_handle.go to use the new method for conversion.
- I'll enable the streaming write test for GRPC protocol as a separate PR (with more test-packages).
b/395511337
1. Manual - Tested the streaming write test manually by enabling that for gRPC. `GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/streaming_writes/... -p 1 --integrationTest -v --testbucket=<bucket_name> -run=TestDefaultMountLocalFileTest/TestCreateNewFileWhenSameFileExistsOnGCS`

[Refactoring] Common method to wrap error as Precondition or NotFound

---

tools/integration_tests/emulator_tests/emulator_tests.sh
tools/integration_tests/emulator_tests/proxy_server/configs/second_chunk_upload_returns412.yaml
tools/integration_tests/emulator_tests/streaming_writes_failure/local_file_failure_test.go
tools/integration_tests/emulator_tests/streaming_writes_failure/streaming_writes_failure_test.go
tools/integration_tests/emulator_tests/util/test_helper.go
tools/integration_tests/emulator_tests/write_stall/write_stall_test.go
tools/integration_tests/emulator_tests/write_stall/writes_stall_on_sync_test.go
tools/integration_tests/util/client/storage_client.go
tools/integration_tests/util/operations/file_operations.go
tools/integration_tests/util/setup/setup.go

Reverts GoogleCloudPlatform/gcsfuse#3007
The previous revert attempt aimed to simplify the commit history on the master branch. However, instead of removing the unwanted commits, it introduced a new "revert" commit that undid the changes of those commits, effectively adding to the history rather than cleaning it up.

Revert "Revert "Add Streaming Writes failure scenario tests for local files.""

---

go.mod
go.sum

Bringing [jacobsa/fuse changes](https://github.com/jacobsa/fuse/commit/8a36813dc07424e363c77ef2a4b7a766f819ad56) to improve fuse debug logging.
Currently, it's hard to map request to response for similar operations, we get the operation-id of request and then search to know the matching response.
**Log Before**  
```
time="25/06/2024 03:05:52.093580" severity=TRACE message="fuse_debug: Op 0x00000160        connection.go:420] <- LookUpInode (parent 1, name \"b.txt\", PID 870932)"
time="25/06/2024 03:05:52.093777" severity=TRACE message="fuse_debug: Op 0x00000160        connection.go:513] -> OK (inode 2)"
```
**Log After**
```
time="25/06/2024 03:03:45.288441" severity=TRACE message="fuse_debug: Op 0x0000015c        connection.go:420] <- LookUpInode (parent 1, name \"b.txt\", PID 869418)" …
```

Upgrading fuse for better fuse logging

---

tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser.go
tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser_test.go

Cache tests started running into failures after changes in the logs recently (PR #3009).
Made a quick fix to only parse ReadFile request logs.
b/397835673
1. Manual - NA

fix log parsing in cache tests

---

cfg/config.go
cfg/params.yaml

Improves how default values are printed in `gcsfuse --help` .
This PR still doesn't address the following issues:
1. For flags of type string, the default value isn't printed if it's "", similarly the default values of ints, bools aren't printed if they are 0, and false respectively.
2. For flags of type bool, the type isn't printed.
3. `--temp-dir should give the actual default (you're a program! you know what the system default is!) not a description of what it might be`
[b/397660108](http://b/397660108)
1. Manual - <img width="1549" alt="20250220-150207-gcsfuse-help-defaults" src="https://github.com/user-attachments/assets/62cbf140-91a8-4441-ba03-befc818ef361" />

Improve logging of default values in --help

---

tools/cd_scripts/e2e_test.sh
tools/integration_tests/monitoring/prom_test.go

* The monitoring tests are currently skipped in installed_package mode of test runs. This will be changed and monitoring tests will be run in the installed package mode as well.
* Don't clear the test directory post test run. This is to ensure that logs remain available and can be collected post run.
b/391754854
1. Manual - NA

Run monitoring tests in installed_package mode

---

tools/integration_tests/log_content/file_upload_log_test.go
tools/integration_tests/util/operations/file_operations.go
tools/integration_tests/write_large_files/concurrent_write_files_test.go
tools/integration_tests/write_large_files/concurrent_write_to_same_file_test.go
tools/integration_tests/write_large_files/random_write_large_file_test.go
tools/integration_tests/write_large_files/seq_write_large_file_test.go
tools/integration_tests/write_large_files/write_large_files_test.go

The large file write tests were flawed: they were comparing the content read through GCSFuse after write operations with the original content residing in the bucket, rather than verifying the consistency of the data written and read through GCSFuse. 
This PR modifies the test logic to ensure that the content written via GCSFuse is identical to the content read back from GCSFuse, providing accurate validation of write operations.
b/392292871
1. Manual - NA

fix write large file tests

---

internal/gcsx/multi_range_downloader_wrapper_test.go

Fix flaky UT TestMRDWrapperTestSuite/Test_Read by increasing the read-timeout from 1ms to 10ms in it.
The UT in question reads some data from a fake MRD (multi-range-downloader) with a timeout of 1 ms, which seems to be too low given that within this timeout, there is a buffer created in MRD wrapper, call to fake MRD, data copied to this buffer in fake MRD, and callback made from fake MRD to the MRD wrapper, which is causing this test to fail randomly. Increasing this timeout to 10ms makes it test pass consistently.
[b/391770606](http://b/391770606)
- Before change 
```sh
gcsfuse/internal/gcsx$ go test . -test.run ^TestMRDWrapperTestSuite/Test_Read.*$ -test.timeout 10s -test.count=1000
{"timestamp":{"seconds":1740045441,"nanos":603344792},"severity":"ERROR","message":"Mult …
```

Fix flaky UT TestMRDWrapperTestSuite/Test_Read

---

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
tools/integration_tests/read_cache/helpers_test.go
tools/integration_tests/util/operations/file_operations.go

This PR addresses flaky `TestConcurrentReads_ReadIsTreatedNonSequentialAfterFileIsRemovedFromCache` test, which verifies GCSFuse's cache eviction behavior under concurrent read scenarios. Previously, concurrent reads triggered unpredictable situations like:
1. premature file removal from the cache, even before the initial read operation completed. 
2. logs order inconsistency.
This made the test flaky and unreliable.
To resolve this, the PR modifies the test to perform sequential partial reads one by one. By eliminating concurrent operations, we ensure a deterministic execution flow, allowing the cache to operate as expected. 
b/390309943
1. Manual - NA

Fix flaky TestConcurrentReads_ReadIsTreatedNonSequentialAfterFileIsRemovedFromCache

---

cfg/config.go
cfg/params.yaml

Make metadata-cache:negative-ttl-secs as public
b/398799346

Marks negative stat cache flag public

---

tools/integration_tests/emulator_tests/emulator_tests.sh
tools/integration_tests/emulator_tests/proxy_server/main.go
tools/integration_tests/emulator_tests/read_stall/read_stall_test.go
tools/integration_tests/emulator_tests/read_stall/setup_test.go
tools/integration_tests/emulator_tests/streaming_writes_failure/common_failure_test.go
tools/integration_tests/emulator_tests/streaming_writes_failure/streaming_writes_failure_test.go
tools/integration_tests/emulator_tests/util/test_helper.go
tools/integration_tests/emulator_tests/write_stall/write_stall_test.go
tools/integration_tests/emulator_tests/write_stall/writes_stall_on_sync_test.go
tools/integration_tests/util/client/storage_client.go
tools/integration_tests/util/setup/setup.go

* Start using random Proxy Server Ports for emulator tests.
* Use logFilePath for logging proxy server logs. We log Port and ProxyProcessId in a pre-defined format which can be read back in tests with the same format. This removes using hard-coded port and also removes uses of `lsof` which seems to hang if any of the NFS mounts become unresponsive (Crash GCSFuse mounts).
* Running all emulator tests packages in parallel by removing `-p 1` flag. 
* Removed `--TestOnCustomEndpoint` as we have a more elegant way to create storage client for [emulators](https://cloud.google.com/go/docs/reference/cloud.google.com/go/storage/latest#hdr-Creating_a_Client)
[b/398808494](http://b/398808494)

Start using random port for proxy server and run test packages in parallel.

---

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go

On arm64 architecture, we see that kernel sends read request for a few extra chunks which is resulting in test failure. 
Fix: check for last chunk instead of immediate next chunk.
b/399540438
1. Manual - NA

fix TestReadIsTreatedNonSequentialAfterFileIsRemovedFromCache on arm64 architecture

---

.github/workflows/ci.yml
.github/workflows/flake-detector.yml
Dockerfile
go.mod
perfmetrics/scripts/ml_tests/pytorch/run_model.sh
perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
perfmetrics/scripts/read_cache/setup.sh
tools/cd_scripts/e2e_test.sh
tools/containerize_gcsfuse_docker/Dockerfile
tools/integration_tests/run_e2e_tests.sh
tools/package_gcsfuse_docker/Dockerfile

[b/397172415](http://b/397172415)
1. Manual - NA
4. Perf test -

Upgrade to golang 1.24.0

---

perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload.py
perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload_test.py
perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload.py
perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload_test.py
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/workloads.json
perfmetrics/scripts/testing_on_gke/examples/workloads_test.json

This is for gke-testing scripts available in perfmetrics/scripts/testing_on_gke/examples/ . With this change, you can add a "numEpochs" attribute in each workload element in the workload configuration JSON file.
[b/367949393](http://b/367949393)
1. Manual - NA

Add support for setting numEpoch for each workload

---

internal/fs/handle/file.go
internal/gcsx/multi_range_downloader_wrapper.go
internal/gcsx/multi_range_downloader_wrapper_test.go
internal/gcsx/random_reader_stretchr_test.go
internal/storage/fake/fake_multi_range_downloader.go

1. Adding UTs for negative cases
2. Updated handling of EOF in file_handle
3. Updated FakeMRD code to return bytes read as the 2nd parameter in the callback. Next release of go-sdk will have the changes from their side in MRD as well

Adding UTs for negative cases in MRD

---

cfg/config.go
cfg/params.yaml

We plan to publish and document this flag. So, unhide it.
b/400830067
1. Manual - NA

Unhide prometheus-port flag

---

perfmetrics/scripts/ml_tests/checkpoint/Jax/run_checkpoints.sh

GCSFuse should be pre-cloned for KOKORO runs so just cd into correct path
b/400851101
1. Manual - NA

Fix periodic jax tests

---

internal/storage/storage_handle.go

Added info log for successful gRPC connection over directpath.This will be used for e2e tests for validation for gRPC activation (e2e tests will be included in a follow-up PR).
Example logs for success case:
```
{"timestamp":{"seconds":1741243229,"nanos":31380851},"severity":"INFO","message":"GetStorageLayout <- (anushkadhn-grpc-validation)"}
{"timestamp":{"seconds":1741243229,"nanos":79429877},"severity":"INFO","message":"GetStorageLayout -> (anushkadhn-grpc-validation) 48 msec"}
{"timestamp":{"seconds":1741243229,"nanos":439687090},"severity":"INFO","message":"Successfully connected over gRPC DirectPath for anushkadhn-grpc-validation"}
```
Motivation:  Currently we only show a warning log if directpath connection is not possible. To validate for success cases, this was required.
NA
1. …

Adding INFO log for successful gRPC connection

---

perfmetrics/scripts/ml_tests/checkpoint/Jax/run_checkpoints.sh

append bucket name with architecture in checkpoint tests to avoid failures due to concurent checkpoints on the same bucket.
b/401124062 b/401124902
1. Manual - NA

append bucket name with architecture in checkpoint tests

---

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh

Implement new github presubmit label execute-integration-tests-on-zb similar to the pre-existing label execute-integration-tests . This new label should pass `true` for the e2e presubmit run for zonal bucket.
This PR is dependent on #3054 . This PR is dependency for #3064.
[b/400360552](http://b/400360552)
1. Manual - Tested manually by testing with all possible combinations (ON/OFF) of labels `execute-integration-tests` and `execute-integration-tests-on-zb` to see that the non-zonal, zonal bucket test runs ran accordingly.
3. Integration tests - [passed](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/ff270d07-176e-4bbe-8a69-c8f85deb6961/details), [another …

Implement github presubmit label execute-integration-tests-on-zb

---

tools/integration_tests/run_e2e_tests.sh

Enable more test packages for e2e test runs on ZB.
This is dependent on #3059 . This PR is dependency for #3065.
[b/400360552](http://b/400360552)
1. Manual - NA
3. Integration tests - [passed through presubmit](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/5f314bf1-3373-4f17-a98c-95427615a64b/summary)

Enable more e2e test packages for rapid bucket

---

internal/gcsx/bucket_manager_test.go

Bucket manager tests are asserting the error string to be equal. Changed to check for substring instead as the test is failing on go sdk upgrade.
**b/402340996**
1. Manual - NA

fix bucket manager unit tests

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/zonal/e2e-tests-master.cfg

Add new build config for e2e daily run on ZB . This new build is consumed by the new kokoro job being created in [cl/735704462](http://cl/735704462) .
This is dependent on #3064 .
[b/400360552](http://b/400360552)
1. Manual - NA

Add new build config for e2e daily run on ZB

---

perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
perfmetrics/scripts/testing_on_gke/examples/utils/run_tests_common.py

[testing-on-gke] Introduce and implement new env-var-based option custom_csi_driver
`custom_csi_driver` is a new env-var based option for fio/dlio GKE test tool, which allows user to pass a pre-built custom csi driver, rather than having to build a new one each time. 
It works in conjunction with use_custom_csi_driver. Its behavior is as follows:
- If a non-empty `custom_csi_driver` is passed, then the value of `use_custom_csi_driver` is ignored and the passed driver is used for running the workloads (new behavior added)
- If `custom_csi_driver` is not passed or passed as `""`, and if `use_custom_csi_driver` is passed as true, then a new custom csi driver is built and used. This also prints out the full path of the csi-driver built, which can be used with custom_csi_driver in the future …

[testing-on-gke] Add support to reuse preexisting custom csi driver

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh
perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/tpc_build.sh

The e2e tests bottom script and kokoro
configs use the env var RUN_TESTS_WITH_ZONAL_BUCKET, while the top level e2e test script uses RUN_TESTS_FOR_ZONAL_BUCKET instead. Changing all instances of RUN_TESTS_FOR_ZONAL_BUCKET to RUN_TESTS_WITH_ZONAL_BUCKET in this change for consistency.
This is to fix the mismatch that caused [e2e zonal bucket run](https://fusion2.corp.google.com/ci;prev=s/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fperiodic%2Fe2e_tests%2Fsubjobs%2Fe2e-tests-amd64-master-zb/activity/fe1c06b1-ca3f-478c-aedf-0d1e60d69519/log?q=gcsfuse&s=p) to run on non-zonal bucket.
[b/400360552](http://b/400360552)
1. Manual - NA

Fix typo RUN_TESTS_FOR_ZONAL_BUCKET -> RUN_TESTS_WITH_ZONAL_BUCKET

---

internal/bufferedwrites/upload_handler.go
tools/cd_scripts/e2e_test.sh
tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/stale_handle_streaming_writes/setup_test.go
tools/integration_tests/stale_handle_streaming_writes/stale_file_handle_streaming_writes_common_test.go
tools/integration_tests/stale_handle_streaming_writes/stale_file_handle_streaming_writes_empty_gcs_file_test.go
tools/integration_tests/stale_handle_streaming_writes/stale_file_handle_streaming_writes_local_file_test.go

Added streaming writes test for stale file handle scenarios and also fixed the error conversion in streaming writes uploader go routine when the unlink operation cancels the context.
b/395053734, b/399256056

Fix context canceled error conversion and add stale file handle tests for streaming writes.

---

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh

In order to ensure that metrics enablement doesn't cause performance degradation, let's enable metrics as part of performance tests.
Perf:
| Master |  0.25MiB   | 565.81MiB/s  | 1.09MiB/s  |  80.33MiB/s  |  1.21MiB/s   |
|   PR   |  0.25MiB   | 576.78MiB/s  | 1.32MiB/s  |  78.64MiB/s  |  1.19MiB/s   |
| Master | 48.828MiB  | 3866.66MiB/s | 87.37MiB/s | 1559.47MiB/s |  86.65MiB/s  |
|   PR   | 48.828MiB  | 3855.06MiB/s | 87.2MiB/s  | 1521.87MiB/s |  83.73MiB/s  |
| …

Enable metrics while running perf tests

---

cfg/constants.go
cfg/rationalize.go
cfg/rationalize_test.go
tools/integration_tests/monitoring/prom_test.go

This PR adds the logic rationalize.go to enable parallel downloads whenever cache dir is set.
This is first PR is making parallel downloads default ON for file cache customers.
Fixed the error string in prom test, was not printing metrics variables correctly - [error](https://screenshot.googleplex.com/9DX8uTJN3r4LGwn)
[Perf test results](https://screenshot.googleplex.com/4Q3j4dq6hfJXVDS)
b/404435879

Enable parallel downloads config

---

perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload.py
perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload.py
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/utils/parse_logs_common.py

Add new columns in output table for e2e-latency. The values added are as following:
- max of e2e-latency
- P50 of e2e-latency
- P90 of e2e-latency
- P99 of e2e-latency
- P99.9 of e2e-latency
This also removes the obsolete gcsfuse scenarios `gcsfuse-file-cache` and `gcsfuse-no-file-cache` .
[b/400360265](http://b/400360265)
1. Manual - Tested manually with the output generated as follows:

[testing-on-gke] Add e2e-latency output metrics

---

internal/cache/file/downloader/job_test.go

Re-enabling a unit-test that was disabled during rapid-bucket development because it was failing at the time. I have re-enabled it here because it is now passing. More details in the issue ticket below.
[b/390578338](http://b/390578338)
1. Manual - NA

re-enable disabled UT

---

tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go
tools/integration_tests/util/mounting/only_dir_mounting/only_dir_mounting.go
tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
tools/integration_tests/util/mounting/static_mounting/static_mounting.go

This is to avoid unnecessary error logs in e2e runs.
[b/405912004](http://b/405912004)
1. Manual - NA
3. Integration tests - tested through presubmit

Replace `--debug_*` with `--log-severity=trace` in e2e tests

---

internal/fs/handle/file.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go

Implicitly Call Zonal Bucket writer.Flush() before read operation to ensure writes using streaming_writes are available for read from zonal buckets.
http://b/406160016
1. Manual - NA

Use new writer flush before reads for zonal buckets with streaming writes.

---

perfmetrics/scripts/testing_on_gke/examples/utils/utils.py

Don't fail output parsing if no cpu/memory output data found in cloud-metrics. This default the min/max cpu/memory metrics to -1,-1 if no data is found for them.
[b/388667681](http://b/388667681)
1. Manual - NA

[testing-on-gke] handle no memory/cpu errors in output parsing

---

cfg/config.go
cfg/params.yaml
cmd/root_test.go

1. Implement a hidden flag to enable the new implementation.
2. The default value is currently false.
3. This flag will be turned on by default in the future.
[b/408912993](https://b.corp.google.com/issues/408912993)
4. Unit tests - Updated
5. Integration tests - Automated

[Random Reader Refactoring] Create hidden flag to enable new implementation

---

docs/benchmarks.md

Updating doc with benchmarks run on c4-standard-96 and n2-standard-96 machines, using latest GCSFuse version(v2.11.1)
1. Manual - NA

Update GCSFuse External Benchmarks with version 2.11.1

---

.gitignore

Changing `.vscode/` to `.vscode` to ignore both the `.vscode/` folder and `.vscode` symlink. Currently, If the `.vscode/` folder is backed by symlink then gitignore doesn't ignore it.
1. Manual - NA

Ignore both .vscode/ folder and .vscode symlink.

---

tools/cd_scripts/e2e_test.sh

Added `RUN_ON_ZB_ONLY` flag to run integration tests only for ZB via this script.
Follow up CL:
* Changes in louhi pipeline to setup stages for the zb-only tests
ZB integration tests cannot be run in parallel with flat or HNS buckets. Hence, in our release pipeline , we are going to run these tests on a seperate VM altogether. To ensure this targeted test execution, we pass this field as a VM metadata argument , which is consumed the same VM's starter script (e2e_test.sh)
[b/405035152](http://b/405035152)
1. Manual - Checked script in cloned louhi pipeline. WAI.

cd script changes to run zb tests only based on flag passed

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go
cmd/root_test.go
cmd/testdata/metrics_config/enable_otel_false.yml
cmd/testdata/metrics_config/enable_otel_true.yml
tools/integration_tests/monitoring/prom_test.go

Remove enable-otel flag.
b/408033151
1. Manual - NA
enable-otel has always been a hidden flag. So, it's safe to remove.

Remove enable-otel flag

---

.github/.codecov.yml

config.go is auto-generated. Excluding it from code-coverage computation.
1. Manual - NA

Exclude config.go from code coverage computation

---

tools/mount_gcsfuse/main.go
tools/mount_gcsfuse/main_test.go

When GCSFuse mount entries are added to `/etc/fstab`, the kernel implicitly passes the `-o rw` command-line flag to GCSFuse. This behavior overrides any mount options explicitly defined in the configuration file.
Ignoring this rw flag is acceptable because GCSFuse mounts are created in read-write mode by default.
Ref: https://github.com/GoogleCloudPlatform/gcsfuse/discussions/3135
internal bug: b/407781622
1. Manual - NA
4. Manual testing - done to validate that config file settings apply.
config file used in `/etc/fstab` entry:
```
file-system:
fuse-options: allow_other,rw
```
Before the change, mount options printed in GCSFuse log:
`"FuseOptions":["rw"]`
After the change, mount option printed in GCSFuse log: …

[Bug fix] ignore rw option passed as CLI flag during persistent mounting

---

tools/integration_tests/grpc_validation/setup_test.go
tools/integration_tests/run_e2e_tests.sh

The `grpc_validation` test package will only be run in periodic tests. Follow up of https://github.com/GoogleCloudPlatform/gcsfuse/pull/3098
**Note** 
These tests have not been added to GKE test script for the time being due to the nature of tests. Will follow-up after discussion.
[b/376372141](https://b.corp.google.com/issues/376372141)
1. Manual - Manually testing on local machine.

Adding grpc validation test package to periodic test runs

---

tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go
tools/integration_tests/list_large_dir/list_large_dir_test.go
tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/util/client/storage_client.go

* Create the 12k files and 100 implicit directories and 100 explicit directories for testing in ZB using storage-client instead of using gcloud (as `gcloud storage cp` doesn't work for ZB)
- No change in use of gcloud for non-ZB. This is for speed as creating/copying files in bulk using gcloud (which is highly parallelized) is faster than using storage-client, so leaving part that as it is. We can switch easily for non-ZB later if it makes sense.
* Disable GRPC-specific test for zonal-bucket case, as it's a duplicate, as ZB by default work over GRPC.
* Enable list_large_dir e2e test package for ZB.
[b/407894658](http://b/407894658)
1. Manual - NA
3. Integration tests - through presubmit - [Passed ZB run](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu …

Fix and enable package list_large_dir in ZB e2e tests

---

.github/workflows/shadow.yml

Changing the trigger action from `review_requested` to `opened` as currently, the action triggers when a review is requested, but it also requests a review itself—creating a potentially endless loop.
1. Manual - NA

Trigger shadow reviewer workflow only when PR is opened

---

internal/cache/file/cache_handle.go
internal/cache/file/cache_handle_test.go
internal/cache/file/cache_handler.go
internal/cache/file/cache_handler_test.go
internal/cache/file/downloader/job.go
internal/cache/file/downloader/job_test.go
internal/cache/lru/lru.go
internal/cache/lru/lru_test.go
internal/cache/util/util.go
internal/cache/util/util_test.go
internal/gcsx/random_reader.go
internal/gcsx/random_reader_test.go

Comparing error strings is fragile because error messages can change. `errors.Is` checks if an error wraps a specific target error, providing a robust and type-safe way to verify error identity regardless of the exact message.   
As part of the random reader refactoring project, this thing is being updated to align with best practices. Note that these changes are specific to the reader scenario and are not being applied to the entire codebase.
[b/409482191](https://b.corp.google.com/issues/409482191)
1. Manual - NA

[Random Reader Refactoring] Convert error message consts in error variable

---

tools/integration_tests/implicit_dir/delete_test.go
tools/integration_tests/implicit_dir/list_test.go
tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go

* Uses storage-client instead of gcloud for input object creations in `implicit_dir` test package for test specific to ZB. 
- It leaves non-ZB untouched to avoid causing need for validating non-ZB buckets again, and also the reduce the surface area of impact if there is something wrong in the change.
* Enables package `implicit_dir` in run_e2e_tests.sh
* It is followed up in PR #3144 .
A dependent change on this is the fix for explicit_dir package, which is in #3144 .
[b/407894792](http://b/407894792)
1. Manual - NA
3. Integration tests - Run as part of presubmit - [log](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/94e7d815-93df-4b98-b9cd-973a6a27768c/log).

Fix and enable package implicit_dir in e2e tests for rapid buckets

---

tools/integration_tests/run_e2e_tests.sh

Enable e2e package concurrent_operations for ZB
[b/407895631](http://b/407895631)
1. Manual - NA
3. Integration tests - Run as part of presubmit - [log](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/1d340073-5e4f-468c-bcc8-1e1978920e56/summary)

Enable e2e package concurrent_operations for ZB

---

tools/integration_tests/grpc_validation/setup_test.go
tools/integration_tests/util/operations/file_operations.go

Validated that it is indeed getting skipped
1. Manual - NA

Fix: grpc_validation test suite should be skipped in presubmits

---

tools/integration_tests/util/operations/file_operations.go

Read large file tests should use O_DIRECT when reading the file via GCSFuse, otherwise reads get served from page cache.
internal bug: b/408343842
1. Manual - NA
NA

fix read large file tests

---

tools/integration_tests/explicit_dir/explicit_dir_test.go
tools/integration_tests/explicit_dir/list_test.go
tools/integration_tests/implicit_dir/delete_test.go
tools/integration_tests/implicit_dir/list_test.go
tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go
tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/util/operations/string_operations.go
tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go

* Uses storage-client instead of gcloud for input object creations in explicit_dir test package.
- leaves non-ZB tests untouched.
* Enables package `explicit_dir` in run_e2e_tests.sh
This is on top of PR #3143  .
[b/407896339](http://b/407896339), [b/407894792](http://b/407894792)
1. Manual - NA
3. Integration tests - Run as part of presubmit: [log](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/94e7d815-93df-4b98-b9cd-973a6a27768c/log), [log](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/daa39f5f-e0ed-4a9b-8cf5-daa1a60ffe86/summary)

Fix and enable package explicit_dir in zb e2e tests

---

tools/integration_tests/operations/write_test.go
tools/integration_tests/run_e2e_tests.sh

* Fix enable e2e test package "operations" for ZB
- ZB object metadata doesn't get media link, so relaxing the check on that, but putting behind a log for remembrance.
- ZB object metadata shows storageClass as "STANDARD" in some cases, so relaxing the check on that, but putting behind a log for remembrance.
* Enable e2e test package "operations" for ZB
For cleanup, and undoing this relaxation on the StorageClass, a task for myself is captured in [b/409734728](http://b/409734728) . That will be taken up once [b/409734378](http://b/409734378) is resolved.
[b/407894662](http://b/407894662)
1. Manual - NA
3. Integration tests - [kokoro presubmit run](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/d26aab7d-b …

Fix and enable e2e test package "operations" for ZB

---

internal/fs/stale_file_handle_common_test.go
tools/integration_tests/emulator_tests/streaming_writes_failure/common_failure_test.go
tools/integration_tests/kernel_list_cache/disabled_kernel_list_cache_test.go
tools/integration_tests/kernel_list_cache/finite_kernel_list_cache_test.go
tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_delete_dir_test.go
tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
tools/integration_tests/local_file/remove_dir.go
tools/integration_tests/local_file/sym_link.go
tools/integration_tests/local_file/unlinked_file.go
tools/integration_tests/managed_folders/list_empty_managed_folders_test.go
tools/integration_tests/managed_folders/test_helper.go
tools/integration_tests/operations/copy_dir_test.go
tools/integration_tests/operations/delete_file_test.go
tools/integration_tests/operations/move_file_test.go
tools/integration_tests/operations/read_test.go
tools/integration_tests/operations/write_test.go
tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
tools/integration_tests/read_gcs_algo/concurrent_read_same_file_test.go
tools/integration_tests/rename_dir_limit/move_dir_test.go
tools/integration_tests/stale_handle/stale_file_handle_common_test.go
tools/integration_tests/stale_handle_streaming_writes/stale_file_handle_streaming_writes_common_test.go
tools/integration_tests/stale_handle_streaming_writes/stale_file_handle_streaming_writes_empty_gcs_file_test.go
tools/integration_tests/streaming_writes/symlink_file_test.go
tools/integration_tests/util/client/gcs_helper.go
tools/integration_tests/util/client/storage_client.go
tools/integration_tests/util/operations/dir_operations.go
tools/integration_tests/util/operations/file_operations.go
tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go

CloseFile test helper logs a fatal error in case of failure which exits the tests. Due to this, sometimes GCSFuse failure logs are also not retained. Changing to use assert library instead so that logs are retained.
b/406133834
1. Manual - NA
NA

CloseFile should not exit the tests

---

internal/fs/stale_file_handle_common_test.go
internal/fs/stale_file_handle_streaming_writes_common_test.go
internal/fs/stale_file_handle_streaming_writes_local_file_test.go
internal/fs/stale_file_handle_streaming_writes_synced_file_test.go
internal/fs/stale_file_handle_synced_file_test.go
tools/integration_tests/local_file/create_file.go
tools/integration_tests/local_file/read_dir.go
tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/stale_handle/stale_file_handle_common_test.go
tools/integration_tests/stale_handle/stale_file_handle_synced_file_test.go
tools/integration_tests/stale_handle_streaming_writes/stale_file_handle_streaming_writes_common_test.go
tools/integration_tests/stale_handle_streaming_writes/stale_file_handle_streaming_writes_empty_gcs_file_test.go
tools/integration_tests/streaming_writes/rename_file_test.go
tools/integration_tests/unfinalized_object/setup_test.go
tools/integration_tests/unfinalized_object/unfinalized_object_operations_test.go
tools/integration_tests/util/client/gcs_helper.go
tools/integration_tests/util/client/storage_client.go
tools/integration_tests/util/operations/validation_helper.go

Add e2e tests for operations on unfinalized object.
This PR is copy of PR #3139
b/407959986
1. Manual - NA
3. Integration tests - added
No

add unfinalized object operations tests 

---

internal/fs/inode/file.go
tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/streaming_writes/default_mount_empty_gcs_file_test.go
tools/integration_tests/streaming_writes/default_mount_local_file_test.go
tools/integration_tests/streaming_writes/default_mount_test.go
tools/integration_tests/streaming_writes/read_file_test.go
tools/integration_tests/streaming_writes/rename_file_test.go
tools/integration_tests/streaming_writes/symlink_file_test.go
tools/integration_tests/util/operations/file_operations.go

Start running streaming writes package for ZB. Currently read tests are skipped as reads are not working on unfinalized Objects. Added a TODO bug to remove skip conditions.
Note: `execute-integration-tests` and `execute-integration-tests-on-zb` passed on commit #5fb608a removing labels to ensure no re-runs during review comments.
b/407894714

Start running streaming_writes package for ZB.

---

internal/fs/inode/file.go
internal/fs/inode/file_test.go

Holding a direct reference to an inode's MinObject within MRDWrapper could lead to unsynchronized access and potential data races on inode's minObject mutex-protected fields. To prevent this, MRDWrapper will now store a reference to a separate copy of the MinObject.
b/410751316
1. Manual - NA

Make MRDWrapper store copy of MinObject from inode to prevent data race.

---

internal/gcsx/file_cache_reader.go
internal/gcsx/file_cache_reader_test.go
internal/gcsx/random_reader.go
internal/gcsx/random_reader_stretchr_test.go
internal/gcsx/random_reader_test.go

1. Implemented the ReadAt method for the file cache reader, utilizing the helper function tryReadingFromCache.
2. Unit tests cover the following scenarios:  
i. Nil file cache handler 
ii. Cache hit and data population from cache on subsequent reads 
iii. Cache hit and data population from cache on subsequent reads (next offset from the first read) 
iv. Sequential range read 
v. When cacheRangeRead is false, an ErrFallbackToGCS error is returned, triggering a fallback to another reader. 
vi. When the cacheRangeRead flag is true, the file is downloaded into the cache. 
vii. Receiving ErrFallbackToGCS error. 
viii. Receiving ErrInvalidFileDownloadJob error.
ix. Sequential to Random SubsequentRead Offset less than previous
x. Sequential to Random SubsequentRead Offset More than ReadChunkSize …

[Random reader refactoring] File cache reader implementation - 1

---

tools/integration_tests/run_e2e_tests.sh

Temporary fix for failing periodic tests. 
The tests pass on a GCE VM or in presubmit tests but fail in the periodic test pipeline due to ADC revoked in one of the tests being run in parallel. When this credential is revoked, the directpath authentication fails, hence the tests fail.
Will enable once investigated and fixed. 
1. Manual - NA

Disabling grpc_validation test suite 

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go
cmd/root_test.go
cmd/testdata/valid_config.yaml

This PR enables read stall retry by default.
https://b.corp.google.com/issues/406926331

Enable Read Stall Retry by default

---

tools/integration_tests/mount_timeout/gcsfuse_mount_timeout_test.go
tools/integration_tests/mount_timeout/mount_timeout_test.go

- Splits the existing MountTimeoutTest class to NonZBMountTimeoutTest and ZBMountTimeoutTest. 
- Creates and adds new ZBs for mount_timeout tests and mounts them in the test
- Disables the tests for mounting of non-ZB out of the E2E ZB runs
- Adds new tests for mounting the ZBs during the E2E ZB runs .
[b/411578929](http://b/411578929) , [b/410500613](http://b/410500613)
1. Manual - NA
3. Integration tests - as part of presubmit - [logs](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/a369417f-6667-4e9b-b529-e200bc260385/summary)

Changes in mount_timeout package for ZB E2E

---

tools/integration_tests/streaming_writes/buffer_size_test.go
tools/integration_tests/streaming_writes/default_mount_test.go
tools/integration_tests/util/setup/setup.go

Save gcsfuse logs for failed integration tests to ensure logs are available for debug.
Also made a small fix to not save LogFile in case of mountedDirectory is not nil.
b/412190425
1. Manual - Tested log file saving code: http://gpaste/5768501689843712
3. Integration tests - Ran as part of presubmit tests.

Save gcsfuse logs for streaming writes package for easier debugging.

---

cfg/config.go
cfg/params.yaml

We've removed `Should only be used for testing` from the custom endpoint description. This was added previously as the feature was developed for the test-bench server.
Currently, the custom endpoint is being used in the TPC environment, which is not a test server. Therefore, we are updating its description.
I'll also update cloud documentation as well after this.
[b/412284502](https://b.corp.google.com/issues/412284502)
1. Manual - NA

Update documentation for  custom-endpoint flag

---

docs/troubleshooting.md

Updating troubleshooting doc for avoiding `o=sync,o=dirsync` options in the mount configuration when trying to clone a repo inside the mounted GCS bucket.
[Ref](https://github.com/GoogleCloudPlatform/gcsfuse/issues/3189)
1. Manual - NA

Update troubleshooting doc for git clone issue

---

tools/integration_tests/operations/parallel_dirops_test.go

It randomizes the file/directory names in tests defined in `tools/integration_tests/operations/parallel_dirops_test.go` to avoid failures related to a file being deleted and one test and the same file being recreated in the next test, which is causing random failures in ZB e2e tests.
This is complementary to the changes in PR #3227 .
[b/411076451](http://b/411076451)
1. Manual - NA
3. Integration tests - passed as part of [presubmit](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/b3e94036-f08f-451d-8147-5911d4d30106/summary)

Randomize file/dir names in tools/integration_tests/operations/parallel_dirops_test

---

internal/storage/storage_handle.go
tools/integration_tests/run_e2e_tests.sh

Previously, TPC did not support the control client at the time GCSFuse implementation for TPC was developed. However, control client support for TPC has been available since December 2024, necessitating modifications to enable GCSFuse to support TPC with HNS buckets.
Also added automated tests for HNS buckets on TPC.
[b/379063794](https://b.corp.google.com/issues/379063794)
1. Manual - Tested on TPC environment

TPC support with HNS buckets

---

perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh

Intermittent failures occur when establishing SSH connections to long haul test VMs, arising from a timing conflict between the removal of OS Login-managed SSH keys and subsequent SSH connection attempts. Specifically, `gcloud compute ssh ` may attempt to connect using a newly generated key before the OS Login key removal has fully propagated.This leads to the VM rejecting the authentication attempt , as a result, kokoro jobs which probe for the test status fail.
The ssh keys removal is necessary due to the size limit on os login profiles: [ref](https://github.com/kyma-project/test-infra/issues/93)
Solution -
Implemented a retry mechanism with exponential backoff for the SSH connection attempt. This allows sufficient time for the OS Login key removal to propagate, significantly reducing …

Fix: Handle Intermittent SSH Connection Errors for long haul test VMs

---

perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
perfmetrics/scripts/testing_on_gke/examples/utils/parse_logs_common.py

1. This is a fix in synthetic AI/ML test tool to support rapid (aka zonal) bucket scenarios, especially for output parsing. The tool needs to read fio outputs from bucket(s) specified for the workload(s). For this, the tool traditionally used `gcloud`, but reading/writing objects in rapid buckets using `gcloud` isn't supported as of today. As an alternative, the tool will mount the bucket(s) using gcsfuse and read the output files using the mounted directory. This is required to unblock testing on rapid buckets.
2. Additionally, this changes the underlying cluster's properties to use ipv6 access-type to bidirectional, which is required to connect to direct-path for rapid buckets, as of today.
**Note**:  These are both workarounds, and will be removed later when no longer needed. …

[testing-on-gke] Support for rapid buckets

---

tools/integration_tests/util/setup/setup.go

fix: use local rand.NewSource() in each invocation as NewSource() is not safe for concurrent use.

---

internal/monitor/full_read_closer.go
internal/monitor/full_read_closer_test.go

If an EOF is encountered before reading the full length of the buffer, ReadFull returns an ErrUnexpectedEOF error. This needs to be convered to EOF in order to have a consistent behavior (error) with and without gcsFullReadCloser.
b/413109300
1. Manual - NA
3. Integration tests - Executed after enabling metrics

Fix error handing with gcsFullReadCloser

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/gcsx/prefix_bucket.go
internal/monitor/bucket.go
internal/ratelimit/throttled_bucket.go
internal/storage/bucket_handle.go
internal/storage/caching/fast_stat_bucket.go
internal/storage/caching/fast_stat_bucket_test.go
internal/storage/debug_bucket.go
internal/storage/fake/bucket.go
internal/storage/gcs/bucket.go
internal/storage/mock/testify_mock_bucket.go
internal/storage/mock_bucket.go
internal/storage/testify_mock_bucket.go
tools/integration_tests/streaming_writes/rename_file_test.go

Create object from attributes returned by the writer's `flush` operation, specifically for zonal buckets. The full GCS object metadata (including name, generation, metageneration, etc.) is now returned after a successful flush of a zero-byte file.
Also use the returned object to populate metadata cache.
b/412583244
1. Manual - NA
NA

fix: Return complete object on flush writer 

---

internal/fs/handle/file.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go
tools/integration_tests/streaming_writes/rename_file_test.go

Promote zonal bucket objects to generation backed inodes as soon as the Sync() is called for local inodes which does a implicit flush on zonal buckets and upload pending buffers for non-zonal buckets. In case of non-zonal buckets they are only updated to generation backed inodes once the Close() has been called on them which finalizes the object.
Note: Start running tests which were skipped as part of b/413296959
**Note: A follow up PR will be send to promote Zonal Object to generation backed Inode as soon as BWH is initialized.**
b/413296959
b/413587897
1. Manual - Tested skipped tests from b/413296959
2. Unit tests - Updated unit tests and tested.
3. Integration tests - Run as part of presubmit tests.

fix: promote zonal object to generation backed inode on sync

---

cfg/optimize.go
cfg/optimize_test.go
cmd/root_test.go

Remove setting streaming writes by default for high end machines as it would be set as true in the future.
Also, spruce up a test case to handle the auto config flag properly and make behavior of the test more predictable.
b/402273935
1. Manual - NA
NA

Remove setting streaming writes by default for high end machines

---

internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go
tools/integration_tests/unfinalized_object/unfinalized_read_test.go

Return unsupported error for reads on unfinalized objects.
b/414336188
1. Manual - NA
3. Integration tests - added
NA

un-support read operations on unfinalized objects

---

cfg/config.go
cfg/params.yaml
cmd/config_validation_test.go
cmd/root_test.go
cmd/testdata/valid_config.yaml

Description :
Revert the PR to enable Read Stall Retries by default as we started seeing regression in tail latencies and job duration on running LG Air workload with 1MiB I/O.
Bug Link : [b/414516573](https://b.corp.google.com/issues/414516573)

Revert "Enable Read Stall Retry by default"

---

internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go
internal/fs/fs.go
internal/fs/inode/file.go
internal/fs/inode/file_mock_bucket_test.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go
tools/integration_tests/streaming_writes/buffer_size_test.go
tools/integration_tests/streaming_writes/default_mount_local_file_test.go
tools/integration_tests/unfinalized_object/unfinalized_object_operations_test.go

Ensure implicit sync file inode at the time bwh is initialized. This ensures as soon as bwh is created we have the correct generation from the server. With this change Local File Tests from local_file package which were running started failing for ZB with streaming writes as those tests validate local file but in this case file is not local and it is promoted to generation backed inode as soon as created. Removed local_file package tests from running as part of streaming writes test as those require a large refactoring and error checking for multiple scenarios.
Note: Manually verified that ZB tests are passing.
[b/414501988](http://b/414501988)
3. Integration tests - Tested stale handle skipped tests in this …

Sync file Inode at the time of BWH initialization

---

internal/clock/simulated_clock.go
internal/clock/simulated_clock_test.go

- Adding a simulated clock for time.After() method.
- Current fake_clock implementation doesn't provide the SetTime() and AdvanceTime() support with time.After implementation.
b/414538309
1. Manual - NA

Adding simulated clock implementation for time.After method

---

tools/integration_tests/read_cache/remount_test.go
tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go

Current method can't create multiple random buckets for dynamic mounting if required for parallel execution of tests within same package test. Currently running two tests in a test package in sequential is also not possible if they create dynamic bucket and one of them fails to delete it. Thus other test will see that bucket already exists on GCS. This is part of larger effort in which I am trying to reduce test package run time.
- Use random bucket name in each CreateTestBucketForDynamicMounting call instead of using random fixed name.
- Use `metadata.ProjectIDWithContext(ctx)` instead of `deprecated metadata.ProjectID()`
- Improved error handling.
b/413231761
1. Manual - NA
3. Integration tests - run as part of Presubmit run

fix: Use random bucket name in each CreateTestBucketForDynamicMounting call instead of using  fixed random name.

---

internal/storage/debug_bucket.go

Log both source and destination folder in RenameFolder debug log . This to make debugging easier using gcsfuse debug logs.
[b/414503184](http://b/414503184)
1. Manual - Tested.
- Before
```sh
{"timestamp":{"seconds":1746202763,"nanos":779817438},"severity":"TRACE","message":"fuse_debug: Op 0x00000018        connection.go:426] <- Rename (PID 84541, old_parent 1, old_name \"a\", new_parent 1, new_name \"b\")"}
{"timestamp":{"seconds":1746202763,"nanos":779917854},"severity":"TRACE","message":"gcs: Req              0x6: <- RenameFolder(\"a/\")"}
{"timestamp":{"seconds":1746202763,"nanos":850611929},"severity":"TRACE","message":"gcs: Req              0x6: -> RenameFolder(\"a/\") (70.678157ms): OK"}
{"timestamp":{"seconds":1746202763,"nanos":850663526},"severity":"TRACE","message":"fuse_debug: …
```

Log both source and destination folder in gcs debug log for RenameFolder

---

tools/integration_tests/concurrent_operations/concurrent_listing_test.go

- Switching failure in folder renames from soft-failures to fatal-asserts as they should be.
- Extended it to all failures in concurrent_operations where proceeding after failure is pointless.
This is to reduce unnecessary repeated failures after a fatal failure.
[b/414503184](http://b/414503184)
1. Manual - NA
3. Integration tests - Tested with [presubmit](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/1f5807ab-c2bc-4598-b778-2fc9b8198b1c/summary) .

Early termination in Test_ListWithMoveDir on failure in renameFolder

---

internal/gcsx/inactive_timeout_reader.go
internal/gcsx/inactive_timeout_reader_test.go

This PR introduces a new reader wrapper, inactiveTimeoutReader, to automatically close open GCS read streams after a timeout. Useful for gRPC client-protocol where total number of max-streams is limited and surpassing the limit leads to stuck/hang.
More concurrent tests will be implemented in the follow up PR.
b/412465587
1. Manual - Functional testing using a python script which starts reads, idle for more than timeout and then read again.
2. Unit tests - added.

feat: inactive timeout support for range reader

---

cmd/legacy_main.go
cmd/legacy_main_test.go

Forward env variables `GCE_METADATA_HOST`, `GCE_METADATA_ROOT`, `GCE_METADATA_IP` to gcsfuse daemon process in case of background run. `GCE_METADATA_HOST` is used [here](https://github.com/googleapis/google-cloud-go/blob/a6c85f6387ee6aa291e786c882637fb03f3302f4/compute/metadata/metadata.go#L461) to determine where to send the metadata requests.
[b/414377352](http://b/414377352)
1. Manual - Tested manually that after this change, the env vars GCE_METADATA_HOST, GCE_METADATA_ROOT and GCE_METADATA_IP are being passed down the gcsfuse daemon process.

Forward env variables `GCE_METADATA_*` to gcsfuse daemon process in case of background run

---

perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py

Dump new fields `bucket_name`, `machine_type` in the output csv file from the pods. These will be useful for dashboard for filtering out data based on more dimensions.
This PR is dependent on PR #3127 .
[b/412912760](http://b/412912760)
1. Manual - Tested locally. It generated the following csv file content
```
File Size,Read Type,Scenario,Epoch,Duration (s),Throughput (MB/s),IOPS,Throughput over Local SSD (%),GCSFuse Lowest Memory (MB),GCSFuse Highest Memory (MB),GCSFuse Lowest CPU (core),GCSFuse Highest CPU (core),Pod,Start,End,GcsfuseMoutOptions,BlockSize,FilesPerThread,NumThreads,InstanceID,e2e_latency_ns_max,e2e_latency_ns_p50,e2e_latency_ns_p90,e2e_latency_ns_p99,e2e_latency_ns_p99.9,bucket_name,machine_type
1M,randread,gcsfuse-generic,1,1,75,603,NA,108.0,108.0,0.00285,0.00285,fio-te …
```

[testing-on-gke] Dump bucket_name, machine_type in FIO output file

---

.github/workflows/ci.yml
internal/gcsx/inactive_timeout_reader.go
internal/gcsx/inactive_timeout_reader_test.go

1. Adding race detector test for inactive timeout reader.
2. Enabling race detector test for the gcsx.
3. Fixing ctx crash when Close() resets the context to nil and simultaneous monitor routine access in the for-select loop.
b/415783752
1. Manual - Test fails, when I remove lock from the handle-timeout implementation.

Adding race detector test for inactive timeout reader

---

cfg/config.go
cfg/params.yaml
cfg/rationalize.go
cfg/rationalize_test.go
cmd/root_test.go
cmd/testdata/read_config/override.yaml
cmd/testdata/read_config/override_with_grpc.yaml
cmd/testdata/valid_config.yaml

- Adding a new hidden flag `--read-inactive-stream-timeout`
- Default value - 0s (that means disabled)
- Currently only applicable for `--client-protocol=grpc`
412465859
1. Manual - NA

Flag to support inactive timeout reader

---

tools/integration_tests/benchmarking/benchmark_delete_test.go
tools/integration_tests/benchmarking/benchmark_rename_test.go
tools/integration_tests/benchmarking/benchmark_stat_test.go
tools/integration_tests/benchmarking/setup_test.go
tools/integration_tests/run_e2e_tests.sh

This PR includes the following changes: 
* Increasing the number of iterations for which benchmark is run to 100 ( please note the overall runtime is about a minute)
* Increasing the thresholds for expected operation latency to 4 times the observed latency so that any failure is a clear indication of anomaly and not network variance. 
[b/383948519](b/383948519)
1. Manual - Ran on GCE VM. Tests pass.

Fix flaky benchmark tests

---

perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload.py
perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/fio/bq_utils.py
perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
perfmetrics/scripts/testing_on_gke/examples/utils/parse_logs_common.py
perfmetrics/scripts/testing_on_gke/examples/utils/utils.py
perfmetrics/scripts/testing_on_gke/examples/utils/utils_test.py

This builds on top of #3281 and adds the remaining proposed elements from the LLD at [go/fio-perf-dashboard-design](http://goto.google.com/fio-perf-dashboard-design) .
- implements export to bigquery table in python script (by creating a new FioBqExporter and invoking append_rows on it from the fio output metrics)
- adds arguments for bigquery project-id, dataset-id and table-id in fio output parser
- Passes the BQ arguments from the top-level CLI .
- add utility for converting file/block size like `64K` etc. to `65536` etc for calculating metrics like file_size_in_bytes etc.
- add utility for creating a fio_workload_id from the output metrics.
This is on top of #3281 .
[b/412924212](http://b/412924212)
1. Manual - Tested manually.

[testing-on-gke] [BQ-integration-part-3] Implement export to bigquery table in python script

---

perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh

This fixes the bug in downloading the fio outputs generated by gke ai/ml test tool for runs on ZB buckets (i.e. with `zonal=true`). This failure is specifically in a case where a single input bucket is used for runs of different file-size values in different fio workloads. This fix downloads only the fio outputs relevant to specific file-sizes while parsing outputs for that file-size.
1. Manual - NA

[testing-on-gke] Fix bug in zb output download

---

internal/fs/fs.go
internal/fs/handle/file.go
internal/gcsx/random_reader.go
internal/gcsx/random_reader_stretchr_test.go
internal/gcsx/random_reader_test.go

Includes:
- Changes to integrate the inactiveTimeoutReader in random reader, activated for positive inactive-stream-timeout.
- Unit test to validate no behavior change of random-reader and integration with inactiveTimeoutReader.
---
Currently, timeout is only enabled when user passes client-protocol as gRPC. In case of zonal bucket, when user doesn't pass the grpc as client protocol - this feature will be disabled. So, requires an internal discussion to support for zonal bucket,  we might need to create another kill-switch flag instead of using the same timeout.
> Discussed offline, we would need to enable it for http also, then we would not need any consideration about the zonal bucket. I'll create a separate PR to enable this flag for http client protocol.
b/416129654
1. Manual - NA
4. …

Integrate inactiveTimeoutReader in random-reader

---

common/noop_metrics.go
common/otel_metrics.go
common/telemetry.go
internal/fs/wrappers/monitoring.go
internal/gcsx/file_cache_reader.go
internal/monitor/bucket.go

Metrics units should be a concern of metrics related files as opposed to the code that generates those metrics.
Perf:
|--------|----------|--------------|-----------|----------------|----------------|
| Master |  0.25MiB   | 553.65MiB/s  | 1.09MiB/s  |  81.91MiB/s  |  1.14MiB/s   |
|   PR   |  0.25MiB   | 573.52MiB/s  | 1.18MiB/s  |  81.43MiB/s  |  1.22MiB/s   |
| Master | 48.828MiB  | 3923.0MiB/s  | 84.98MiB/s | 1518.44MiB/s |  85.93MiB/s  |
|   PR   | 48.828MiB  | 3930.72MiB/s | 82.77MiB/s | 1557.12MiB/s |  84.43MiB/s  |
|        |            | …

Refactor metrics to move unit conversion logic to otel_metrics

---

internal/gcsx/bucket_manager.go
internal/storage/bucket_handle.go

Currently, enabling metrics will conditionally enable a decorator that activates the code flows to record metrics. However, this leads to test-gaps since we currently don't enable metrics in our tests and that decorator doesn't come into picture while running tests. So, we unify the flow with/without metrics enabled so that the monitoring decorator will always be set even in cases when no metrics are to be computed.
Perf:
| Master |  0.25MiB   | 542.32MiB/s  | 1.14MiB/s  |  77.38MiB/s  |  1.21MiB/s   |
|   PR   |  0.25MiB   | 535.05MiB/s  | 1.23MiB/s  |  78.74MiB/s  |   1.3MiB/s   |
|        |            |              | …

 Use the same code-flow regardless of metrics being enabled

---

tools/integration_tests/negative_stat_cache/disabled_negative_stat_cache_test.go
tools/integration_tests/negative_stat_cache/finite_int_negative_stat_cache_test.go
tools/integration_tests/negative_stat_cache/infinite_negative_stat_cache_test.go
tools/integration_tests/negative_stat_cache/setup_test.go

E2E tests make extensive use of global variables which hampers readability and can give rise to inadvertent logical errors due to name clashes.
This change demonstrates how to encapsulate them into a structure and its usage.
b/417329502
1. Manual - NA
NA

Encapsulate test environment variables

---

perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
perfmetrics/scripts/testing_on_gke/examples/utils/run_tests_common.py

If user passes an instance_id, then suffix it with user-name/date-time/uuid to make it unique. If user also passed 'only_parse', then use the passed `instance_id` as it is.
1. Manual - NA

[testing-on-gke] Make user-passed instance_id unique

---

perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py

- The tool should calculate throughput in both MiB/s (for backward compatibility) and MB/s (for future)
- Clean-up code a bit
- Print out correct units (MiBs) for low/high memory usage
- Print out records during parsing only when they fail, reduces log size
1. Manual - NA

[testing-on-gke] Add support to output throughput in MB/s

---

internal/gcsx/prefix_bucket_test.go

Due to a partial migration of tests to Stretchr Testify, the flush and finalize writer tests within prefix buckets were missed. This was caused by conflicting changes between the pre-launch and GCSFuse main repositories. This pull request addresses the oversight by adding a `Test` prefix, ensuring these tests are now executed.
minor change
1. Manual - NA
NA

run flush and finalize writer tests in prefix bucket

---

perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload.py
perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
perfmetrics/scripts/testing_on_gke/examples/run-automated.sh
perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
perfmetrics/scripts/testing_on_gke/examples/utils/parse_logs_common.py
perfmetrics/scripts/testing_on_gke/examples/utils/run_tests_common.py

1. Rename instance-id to experiment-id for consistency everywhere. During design review for BQ integration, one of the strong suggestions was to use the name experiment-id instead of instance-id, so I had used experiment-id in the BQ table. This is a follow-up to it to make it consistent throughout.
2. If user passes instance-id, put an error log and use its value as experiment-id
3. If user passes both instance-id and experiment-id, throw an error.
1. Manual - NA

[testing-on-gke] Switch from instance_id to experiment_id everywhere for consistency.

---

perfmetrics/scripts/micro_benchmarks/read_single_thread.py
perfmetrics/scripts/micro_benchmarks/write_single_thread.py
perfmetrics/scripts/micro_benchmarks/write_single_thread_test.py

1. Create function to create file of given size with single thread.
2. Calculate latency, bandwidth and log in big query table.
3. File size, Num of files can be passed through flags.
[b/415708057](https://b.corp.google.com/issues/415708057)
1. Manual - Manually tested script
4. Unit tests - Added

Script to find micro benchmarks for writing file with single thread 

---

perfmetrics/scripts/testing_on_gke/examples/fio/bq_utils.py
perfmetrics/scripts/testing_on_gke/examples/fio/bq_utils_test.py

- Robustness improvement for BQ integration for GKE AI/ML tool. 
- Adds utility to return the number of rows in the BQ table.
- If some bad rows out are sent for insert_rows in BQ table, then BQ client stops even the good rows from being inserted. This change retries inserting all rows one by one on failure. This also adds the unit tests for the same.
This has a follow-up in https://github.com/GoogleCloudPlatform/gcsfuse/pull/3304 .
1. Manual - Manually tested using the tests added in bq_utils_test.py . In the test, there are two good rows and two bad rows added. The test passed as insert_rows retried without the failed rows as fallback. The test also printed out the following error message:
```sh
Some rows failed to insert using insert_rows.
Result: …
```

[testing-on-gke] [BQ-integration-improvement] Add retry for failed insert_rows 

---

internal/gcsx/content_type_bucket.go
internal/gcsx/prefix_bucket.go
internal/monitor/bucket.go
internal/ratelimit/throttled_bucket.go
internal/storage/bucket_handle.go
internal/storage/caching/fast_stat_bucket.go
internal/storage/debug_bucket.go
internal/storage/fake/bucket.go
internal/storage/gcs/bucket.go
internal/storage/gcs/request.go
internal/storage/mock/testify_mock_bucket.go
internal/storage/mock_bucket.go
internal/storage/testify_mock_bucket.go

Adding CreateAppendableObjectWriter method to all bucket interfaces , to implement the takeover support for appendable unfinalized objects in ZB. Ref: [link](https://github.com/tritone/google-cloud-go/blob/24b051557ee14dbe3fdaf66e0d422bd88c1331c6/storage/storage.go#L1267)
Implementation and tests will be included in a follow-up PR.
[b/415727697](b/415727697)
1. Manual - Manually testing of different flows - No breakage.

integrating takeover API in all bucket layers

---

perfmetrics/scripts/testing_on_gke/examples/fio/bq_utils.py
perfmetrics/scripts/testing_on_gke/examples/fio/bq_utils_test.py
perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py

This detects if the data for the given experiment_id is already present in the BQ table, and skips inserting rows for it if so.
This is dependent on https://github.com/GoogleCloudPlatform/gcsfuse/pull/3282 for unit test code.
1. Manual - NA

[testing-on-gke] Don't re-insert entries for already inserted experiment_id to the BQ table

---

internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go

This PR adds chunk transfer timeout of streaming writes chunk uploads. The value for chunk transfer timeout for 32MiB is proposed to be same as previous 16MiB chunk transfer.
b/381479965
go/gcsfuse-chunk-timeout-streaming-writes-http
go/gcsfuse-chunk-transfer-timeout
1. Manual - NA

add chunk transfer timeout for streaming writes uploads.

---

internal/block/block_pool.go
internal/block/block_pool_test.go
internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/fs/inode/file.go
internal/fs/stale_file_handle_streaming_writes_common_test.go

This PR ensures streaming writes respect the `--write-global-max-blocks` limit. Previously, streaming writes could create at least 1 block per file, ignoring this global cap. This one block was not counted towards the global limit. Now this block will be reserved at the time of block pool creation.
Now, if a file needs a new block but global-max-blocks is reached, GCSFuse will not create buffered write handler and use disk staged writes.
This change significantly improves resource management and stability by preventing uncontrolled block creation.
Limits and flag changes will be done in subsequent PR.
b/417094016
1. Manual - NA
3. Integration tests - existing tests WAI
NA

 Limit blocks for streaming writes; fallback to staged writes

---

tools/integration_tests/inactive_stream_timeout/setup_test.go
tools/integration_tests/inactive_stream_timeout/with_timeout_test.go
tools/integration_tests/inactive_stream_timeout/without_timeout_test.go
tools/integration_tests/run_tests_mounted_directory.sh
tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser.go
tools/integration_tests/util/log_parser/json_parser/read_logs/structure.go

1. WithTimeout test to validate - reader is closed and further reader works as expected.
2. WithoutTimeout test to validate - no such read closer after the timeout.
b/416943998
1. Manual - NA

E2E test for inactiveStreamTimeout Support

---

tools/integration_tests/streaming_writes/common_streaming_writes_suite_test.go
tools/integration_tests/streaming_writes/empty_gcs_file_test.go
tools/integration_tests/streaming_writes/local_file_test.go
tools/integration_tests/streaming_writes/read_file_test.go
tools/integration_tests/streaming_writes/rename_file_test.go
tools/integration_tests/streaming_writes/setup_test.go
tools/integration_tests/streaming_writes/symlink_file_test.go
tools/integration_tests/streaming_writes/truncate_file_test.go
tools/integration_tests/util/client/storage_client.go

This PR refactors existing streaming write tests and introduces a new flagset to execute these tests with zero global blocks. 0 global blocks are used here to ensure predictable behavior.
b/417094016
1. Manual - NA
3. Integration tests - added
NA

add tests for fall back to disk case when streaming writes are limited by global blocks

---

tools/integration_tests/inactive_stream_timeout/with_timeout_test.go
tools/integration_tests/inactive_stream_timeout/without_timeout_test.go
tools/integration_tests/run_e2e_tests.sh

- Adapt e2e test for PR to extend the timeout feature for http client-protocol
- Integrate the test package as part of  GCSFuse CI/CD.
b/418891989
1. Manual - NA

Run inactive_stream_timeout test as part of CI/CD

---

cfg/config.go
cfg/params.yaml
cmd/legacy_main.go
cmd/root_test.go
go.mod
go.sum
internal/profiler/cloud_profiler.go
internal/profiler/cloud_profiler_test.go

- Adding support to profile cpu, heap, mutex, go-routines and upload to cloud for analysis.
- Controlled by a hidden flag `--enable-cloud-profiling`, by default disabled.
- Only for dev purpose.
b/418896993
1. Manual - Working as expected.
3. Unit tests - Added.
4. Integration tests - in the next PR.

feat: cloud profiler support for cpu/heap/goroutines/mutex profiling

---

tools/integration_tests/explicit_dir/explicit_dir_test.go
tools/integration_tests/explicit_dir/list_test.go
tools/integration_tests/implicit_dir/delete_test.go
tools/integration_tests/implicit_dir/implicit_dir_test.go
tools/integration_tests/implicit_dir/list_test.go
tools/integration_tests/implicit_dir/local_file_test.go

Encapsulate global vars in a struct for following tests
* implicit_dir
* explicit_dir
b/419266928
NA

Encapsulate global vars in a struct for a few e2e tests

---

cfg/config.go
cfg/params.yaml

Follow up this [PR](https://github.com/GoogleCloudPlatform/gcsfuse/pull/3325). Missed updating the help doc. Now, the timeout applies for all `client-protocol` value.
NA
1. Manual - NA

Help doc update for inactive stream timeout

---

internal/cache/file/downloader/parallel_downloads_job_testify_test.go

Refactors Test_ParallelDownloadObjectToFile_NewReaderWithReadHandle
with aggregate counting for ReadHandle usage, making it robust
to goroutine scheduling races and ensuring consistent results.
b/418921265

Fixed flaky parallel download test [Test_ParallelDownloadObjectToFile_NewReaderWithReadHandle]

---

tools/integration_tests/cloud_profiler/cloud_profiler_test.go
tools/integration_tests/cloud_profiler/with_gcp_profiler_service_test.go

- Adding e2e test to validate gcsfuse uploads the profiles to the gcp profiler service.
- Performs read for 3 minutes, and check the profile for the given profiling-label.
- Test returns success if any of the profile (for unique label) present on the  profiling server. [ListingProfile](https://cloud.google.com/profiler/docs/reference/v2/rest/v2/projects.profiles/list) api doesn't provide any filtering based on the label or timing, because of which test fetches only first 5000 entries and check if required profile present or not. 
- Successful integration test run logs:
```
{"timestamp":{"seconds":1748286118,"nanos":380113950},"severity":"INFO","message":"Using GCSFuse installed on the target machine"}
{"timestamp":{"seconds":1748286118,"nanos":380199430},"severity":"INFO","message":"Enabli …
```

E2E test for cloud profiler support

---

internal/gcsx/client_readers/gcs_reader.go
internal/gcsx/client_readers/gcs_reader_test.go
internal/gcsx/client_readers/range_reader.go
internal/gcsx/client_readers/range_reader_test.go
internal/gcsx/inactive_timeout_reader.go
internal/gcsx/inactive_timeout_reader_test.go
internal/gcsx/random_reader_stretchr_test.go
internal/gcsx/read_manager/read_manager.go

- Adding inactive reader support - https://github.com/GoogleCloudPlatform/gcsfuse/pull/3284
- Made InactiveTimeoutReader public
- Created GCSReaderConfig to store all the fields related to GCSReaders.
[b/420579744](https://b.corp.google.com/issues/420579744)
1. Manual - NA

[Random Reader Refactoring] Adding inactive reader support

---

perfmetrics/scripts/install_bash.sh

Adding bash installation script which will be used by new run e2e script for integration tests. Script is added in chmod +x mode.
b/416254121

Add bash installation script

---

internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/buffered_write_handler_test.go
internal/fs/fs.go
internal/fs/handle/file.go
internal/fs/handle/file_test.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go
internal/fs/streaming_writes_common_test.go
internal/fs/streaming_writes_empty_gcs_object_test.go
tools/integration_tests/local_file/stat_file.go
tools/integration_tests/streaming_writes/truncate_file_test.go
tools/integration_tests/streaming_writes/write_file_test.go

Add support for truncate to lower size than current file size during streaming writes. We are going to finalise the file and fallback to stage disk. This PR also fixes the promotion to generation backed Inodes for both out of order write flow and truncate to lower size scenario.
b/421367385
2. Unit tests - Updated.
3. Integration tests - Ran as part of presubmit.

Add support for truncate to lower for streaming writes and fix promotion to generation backed Inode in Write and Truncate Flow.

---

internal/storage/caching/fast_stat_bucket.go

Previously, when a StatObject() call resulted in a cache miss or forceFetchFromGCS was true, the StatObjectFromGCS() method would fetch a minObj and extended attributes. This minObj was first converted to a gcs.Object while invoking the method to insert object into cache and the method itself would convert this gcs.Object back into minObj since that is what is being stored in the cache anyways. 
This PR eliminates that unnecessary inter-conversion by directly inserting the initially received minObj into the cache.
Note: Observed improvement in random read BW
[b/422080005](https://b.corp.google.com/issues/422080005)
1. Manual - NA

insert gcs.minObj directly into stat cache in StatObjectFromGCS()

---

tools/cd_scripts/install_test.sh

Installation tests were failing when running against patch releases. This was because the test script assumed the version being released was the most recent.
This PR updates the test script to no longer rely on the release version being the absolute latest, making it compatible with patch releases.
internal bug : b/409958930
1. Manual - manually ran on CD pipeline
NA

fix install test for patch release

---

internal/storage/bucket_handle.go
internal/storage/gcs/request.go

The object handle for creating the takeover writer must be set before method invocation.
[b/422892135](b/422892135)
1. Manual - Tested as part of POC, that the writer is successfully getting created. 

setting generation for object handle before creating takeover writer

---

internal/cache/file/downloader/job.go
internal/cache/file/downloader/job_test.go

There are two issues being fixed in this PR
* Make sure that tests wait for cleanup to finish before checking status of remove callback
* doneCh is closed at the end of the cleanup function. This will make sure that all callbacks are executed and contexts are made null before channel is closed.
https://b.corp.google.com/issues/420327719

Fix flaky Download_WhenAsyncFails test

---

cfg/config.go
cfg/params.yaml
cmd/root_test.go

This PR enables the inactive reader feature with 10s timeout.
b/424668838
1. Manual - Done.
2. Unit tests - Automated.
3. Integration tests - Automated.

Enable Inactive Timeout Reader by Default with 10s Timeout

---

cmd/mount.go
internal/cache/file/cache_handle_test.go
internal/cache/file/cache_handler_test.go
internal/cache/file/downloader/downloader_test.go
internal/cache/file/downloader/jm_parallel_downloads_test.go
internal/gcsx/bucket_manager.go
internal/gcsx/bucket_manager_test.go
internal/storage/bucket_handle.go
internal/storage/bucket_handle_test.go
internal/storage/storage_handle.go
internal/storage/storage_handle_test.go

Currently, stat calls incorrectly report the size of unfinalized objects as zero. This poses a significant blocker for unfinalized object support, as our read/write operations depend on accurate size information. As a temporary workaround, we're implementing a zero-byte reader. This is because the reader's attributes correctly reflect the unfinalized object's size.
Caveat: Listing is slightly slow.
[b/422944268](b/422944268)
1. Manual - Manual ls, stat show correct object size.
2. Unit tests - Skipping as this is a temporary fix.
3. Integration tests - [Automated](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/e4580def-3dfa-405a-9d62-7bb8d5caaea2/summary)

zero byte read to fetch size for unfinalized obj

---

cfg/config.go
cfg/params.yaml

This PR makes the --enable-read-stall-retry flag public for v3.1.0
https://b.corp.google.com/issues/425506968

Make the --enable-read-stall-retry flag public

---

tools/cd_scripts/e2e_test.sh
tools/integration_tests/improved_run_e2e_tests.sh
tools/integration_tests/release_version/release_version_test.go
tools/integration_tests/release_version/setup_test.go
tools/integration_tests/run_e2e_tests.sh
tools/util/build_gcsfuse.go

- Add e2e tests for `gcsfuse --version`
[b/425285473](https://b.corp.google.com/issues/425285473)
1. Manual - NA

Adding e2e tests for release version 

---

internal/gcsx/client_readers/gcs_reader.go
internal/gcsx/client_readers/gcs_reader_test.go

- Inc totalBytes in case reading from existing reader as well.
[b/426166667](https://b.corp.google.com/issues/426166667)
1. Manual - NA
4. Perf tests
Performance tests were conducted by averaging results from multiple runs.
i. Scenario 1: 200 MiB file, 1 thread, 1 MiB block size
- Without this fix: 180 MiB/s
- With this fix: 250 MiB/s (same as master)
ii. Scenario 2: 200 MiB file, 1 thread, 4 KiB block size
- Without this fix: 20 MiB/s
- With this fix: 50 MiB/s (same as master)

[Random Reader Refactoring] Increase totalBytes for existing reader

---

cfg/config.go
cfg/params.yaml
cmd/root_test.go

Created a hidden flag for the kill-switch. This is for backward compatibility if any issue occurs with the new authentication method.
[b/426095550](https://b.corp.google.com/issues/426095550)
1. Manual - NA

[Migrate auth] Add new hidden flag for kill switch

---

tools/integration_tests/run_tests_mounted_directory.sh

Disable streaming writes for local file packages as tests compatible with streaming writes in local file packages are already run from streaming_writes package.
```
$ ./gcsfuse --implicit-dirs=true --rename-dir-limit=3 --enable-streaming-writes=false mohitkyadav-hns $HOME/bucket
{"timestamp":{"seconds":1750410750,"nanos":78703430},"severity":"INFO","message":"Start gcsfuse/unknown (Go version go1.24.0) for app \"\" using mount point: /home/mohitkyadav_google_com/bucket\n"}
{"timestamp":{"seconds":1750410750,"nanos":78744642},"severity":"INFO","message":"GCSFuse config","config":{"AppName":"","CacheDir":"","Debug":{"ExitOnInvariantViolation":false,"Fuse":false,"Gcs":false,"LogMutex":false},"DisableAutoconfig":false,"EnableAtomicRenameObject":true,"EnableHns":true,"EnableNewReader":false,"Fi …
```

Disable Streaming writes for local file packages.

---

.github/workflows/ci.yml

Codecov uploads fail for external contributors because they lack access to the secret stored on GitHub required to upload the Codecov report. We are making this step optional to prevent it from failing the CI pipeline and blocking external contributors' PRs.
b/427367094
1. Manual - NA
NA

Make codecov upload optional

---

samples/gcsfuse_config/README.md

GCSFuse mount requires read_ahead_kb to be set in a specific way which is different than non-fuse mounts.
This PR fixes the example.
1. Manual - NA

Fix example of setting `read_ahead_kb` for GCSFuse mount

---

internal/cache/file/downloader/job.go
internal/cache/file/downloader/parallel_downloads_job.go
internal/gcsx/client_readers/gcs_reader.go
internal/gcsx/client_readers/gcs_reader_test.go
internal/gcsx/client_readers/range_reader.go
internal/gcsx/file_cache_reader.go
internal/gcsx/random_reader.go
internal/gcsx/random_reader_stretchr_test.go
internal/util/util.go

Use read-type constants from "common" package instead of "internal/util"

---

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
tools/integration_tests/improved_run_e2e_tests.sh

Adding `getopt` option in e2e test run script which offers enhanced arg handling and clean way of executing script.
Ref: https://www.man7.org/linux/man-pages/man3/getopt.3.html
Fixed optional resource usage collection in e2e script as per the comment in : https://github.com/GoogleCloudPlatform/gcsfuse/pull/3414#discussion_r2154229482
```
$ ./tools/integration_tests/improved_run_e2e_tests.sh --bucket-location us-central1
$ ./tools/integration_tests/improved_run_e2e_tests.sh --bucket-location us-central1 --presubmit
$ ./tools/integration_tests/improved_run_e2e_tests.sh --bucket-location us-central1 --presubmit --zonal
```
```
$ ./tools/integration_tests/improved_run_e2e_tests.sh 
[INFO] 2025-06-25 11:12:10: Bash version: 5.2
[ERROR] 2025-06-25 11:12:10: Invalid or empty value [] for option …
```

Add getopt in e2e script for enhanced command line arg handling.

---

tools/integration_tests/improved_run_e2e_tests.sh

Typo fixes for e2e script and an if condition which was not evaluating as intended after this PR: #3433
Now it's working as intended:
b/426462003
3. Integration tests - Run as part of presubmit.

Fix typo in e2e test script and a condition check.

---

internal/cache/file/cache_handle.go
internal/cache/file/cache_handler.go
internal/gcsx/file_cache_reader_test.go
internal/gcsx/random_reader_test.go
internal/gcsx/read_manager/read_manager_test.go
internal/storage/caching/fast_stat_bucket.go
internal/storage/gcs/object.go
internal/storage/gcs/object_test.go

The change is based on [design doc](https://docs.google.com/document/d/1eKAsVbvmiBYtPs8h3jbapN8jP_Pmegb4_AW8WlTdNts/edit?usp=sharing&resourcekey=0-z2SvePxO8kTVnL64-qHq5w)
Changes in behavior for unfinalized objects:
- Don't invalidate file-cache entry if size of completed download entry >= intended downloaded size
- Don't fall back to GCS from file-cache read if size of completed download entry >= intended upper limit of offset to be read.
- Fallback to GCS while reading from cache_handle if requested read isn't available from the cached file-info data size. If partial read is possible from the cache, then go ahead and start the download job.
Additional changes
- Added a simple utility for easily checking if an object is unfinalized.
- Enable zonal bucket unit tests for …

[read-unfinalized-object] [part1] Relax file-cache checks for unfinalized objects

---

cmd/mount.go
go.mod
go.sum
internal/fs/fs.go
internal/fs/wrappers/error_mapping.go
internal/fs/wrappers/monitoring.go
internal/fs/wrappers/tracing.go
internal/fs/wrappers/tracing_test.go

Update the github.com/jacobsa/fuse version in go.mod
Add ReadDirPlus method in tracing.go, monitoring.go, error_mapping.go
Add ReadDirPlus method in fs.go to return not implemented error.
1. Manual - NA

Update Jacobsa FUSE version and add initial support for ReadDirPlus 

---

internal/block/block_pool.go
internal/bufferedwrites/buffered_write_handler.go
internal/bufferedwrites/upload_handler.go
internal/bufferedwrites/upload_handler_test.go

- Replacing blockPool.FreeBlockChannel() with blockPool.Release(block)
b/429960425
1. Manual - Locally tested, working fine as expected.

Block Pool: Release Block Flow Improvement for Buffered Write

---

internal/block/block.go
internal/block/block_test.go

- Adding ReadAt method in block interface.
- Implementing ReadAt method for memory block.
PR: b/430153116
1. Manual - NA

Block: Adding ReadAt method in block interface and memoryBlock

---

internal/fs/fs.go
internal/fs/handle/file.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go
tools/integration_tests/streaming_writes/common_streaming_writes_suite_test.go
tools/integration_tests/unfinalized_object/unfinalized_read_test.go

**What this change does**:
- ~This builds on top of #3401 . So, it shouldn't be merged before that one.~
- This pull request enables reading from GCS objects while they are being written to via streaming.
- This change is particularly relevant for zonal buckets. 
- The changes primarily involves modifying the conditions under which a read is permitted and ensuring data is flushed to GCS before a read occurs.
- The associated unit and integration tests have been updated to validate this new behavior.
- Undoes changes from #3250 
**What it does not do**:
- It doesn't add new e2e tests for testing reads of unfinalized objects. That task is separately tracked in [b/421361399](http://421361399) .
[b/425828097](http://b/425828097)
[b/410698332](http://b/410698332) …

[read-unfinalized-object] [part2] Enable read of unfinalized objects while being written via streaming

---

internal/block/block.go
internal/block/block_test.go

- Adding Getter for AbsStartOffset in the block interface and corresponding implementation in the memory block.
- Adding Setter for AbsStartOffset in the block interface and corresponding implementation in the memory block.
b/430157809
1. Manual - NA

Block: Adding Getter/Setter for the AbsStartOffset in the block

---

internal/fs/fs.go
internal/fs/inode/base_dir.go
internal/fs/inode/base_dir_test.go
internal/fs/inode/dir.go
internal/fs/inode/dir_test.go
internal/fs/inode/file.go
internal/fs/inode/file_streaming_writes_test.go
internal/fs/inode/file_test.go
internal/fs/inode/inode.go
internal/fs/inode/symlink.go
internal/fs/inode/symlink_test.go

Modify the Attributes method in the Inode interface by adding a clobberedCheck boolean parameter. This change allows callers to control whether a remote check is performed to verify if the backing GCS object has been modified or "clobbered".
Disabling this check offers a more performant alternative for retrieving inode attributes in scenarios where this verification is not strictly necessary.
https://b.corp.google.com/issues/423824746
1. Manual - NA
2. Unit tests - Updated unit tests to verify the functionality of the Attributes method with the new clobberedCheck parameter for FileInode, Dir, BaseDir, and Symlink.

Add boolean clobberedCheck parameter to Attributes method of Inode interface

---

internal/block/block.go
internal/block/block_test.go

- Adding cap() method to get block-capacity.
- This will be handy to know the block-size from the block.
NA
1. Manual - NA

Block: adding Cap() method

---

internal/fs/inode/base_dir.go
internal/fs/inode/base_dir_test.go
internal/fs/inode/dir.go
internal/fs/inode/dir_test.go

Add the ReadEntryCores method to the DirInode interface and its implementations. This method allows for reading a batch of directory entries and returning them as a map of inode.Core objects.
This change is a foundational step for the future implementation of the ReadDirPlus FUSE operation.
1. Manual - NA
2. Unit tests - Added unit tests in base_dir_test.go and dir_test.go

Add ReadEntryCores method to DirInode interface

---

.github/pull_request_template.md
.github/workflows/pr-title-check.yml

A standardized format for PR titles to streamline the process of generating release notes.
To achieve this, the following changes have been implemented:
1. Updated PR Template: The pull request template has been updated to include instructions for the new title format, guiding contributors to use a title structure.
2. New CI Check: A new GitHub Actions workflow, pr-title-check.yml, has been added to automatically enforce this standard. This uses [standard templated](https://github.com/marketplace/actions/semantic-pull-request).
[b/430442495](https://b.corp.google.com/issues/430442495)
1. Manual - NA
No

[Process Improvement] Standardize PR titles

---

docs/troubleshooting.md

```
Error occurred during command execution on gcsfuse/3.1.0 (Go version go1.24.0): daemonize.Run: readFromProcess: sub-process: Error while mounting gcsfuse: mountWithArgs: mountWithStorageHandle: mount: mount: running /usr/bin/fusermount3: exit status 1"}
```
This can happen if you're trying to mount the bucket on a directory that has read-only permissions.
[b/430801686](https://b.corp.google.com/issues/430801686)
1. Manual - NA

docs: update troubleshooting doc for exit 1 error

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/build.sh
perfmetrics/scripts/upgrade_python3.sh

Micro benchmark build is failing because kokoro has some older python version but it requires latest one.
[b/431566452](https://b.corp.google.com/issues/431566452)
1. Manual - NA

ci: Upgrade to python311 in micro benchmark script

---

internal/fs/handle/dir_handle.go
internal/fs/handle/dir_handle_test.go
internal/fs/inode/dir.go

This PR supports ReadDirPlus implementation by adding the logic to fetch directory entry cores and populate the FUSE response buffer. To support this new functionality efficiently and avoid code duplication, the underlying directory entry processing logic has been refactored.
Key Changes:
A new FetchEntryCores function has been added to retrieve the core inode data for all entries within a directory from GCS.
The ReadDirPlus method uses this data to populate the response buffer with both the entry names and their attributes.
Refactoring to Avoid Duplication:
A generic DirEntry interface has been introduced to abstract common operations over the different directory entry types (fuseutil.Dirent and fuseutil.DirentPlus).
A generic helper function, resolveAndSortEntries, now centralizes the …

Dir Handle changes to support Readdirplus operation

---

.github/workflows/auto-pr-reminder.yml

Remove dependabot from review reminders.
b/427343327
1. Manual - NA

fix(review reminder): exclude dependabot from review reminders.

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/build.sh
perfmetrics/scripts/micro_benchmarks/requirements.txt

Some of the dependency are missing on kokoro machine, causing failure in execution.  Also fix exit code logic in case both (Read and write) tests will fail.
1. Manual - Tested on kokoro machine

ci: Add missing dependency for micro benchmarks failing on kokoro machine

---

docs/troubleshooting.md

This adds a more clear identifier error log, diagnosis and mitigation for unsupported GCS objects in a
gcsfuse mounted bucket.
[b/431536850](http://b/431536850)
1. Manual - NA

docs(troubleshooting): Update troubleshooting doc for unsupported objects

---

cmd/legacy_main.go
cmd/legacy_main_test.go

- Forward environment variables GRPC_GO_LOG_VERBOSITY_LEVEL and GRPC_GO_LOG_SEVERITY_LEVEL to gcsfuse daemon for background run. This is needed for debugging errors coming from grpc.
- This doesn't set these variables by default, only forwards them to the daemon, if they have been passed by the user to the gcsfuse command.
[b/412688930](http://b/412688930#comment51)
1. Manual - NA
3. Integration tests - Ran as [presubmit](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/9ffe5e01-e9f6-44e1-9c1c-bdafccf5379b/summary) .

chore: Pass grpc log env variables to gcsfuse daemon

---

Makefile

goimports currently is leading to a lot of churn in the GCSFuse codebase. Disabling it until we know the root-cause.
1. Manual - NA

refactor(formatting): Disable goimports in Makefile

---

cmd/mount.go
cmd/mount_test.go

This PR integrates the --experimental-enable-readdirplus flag to activate the ReaddirPlus functionality.
1. Manual - Mounted a GCS bucket using the --experimental-enable-readdirplus flag to verify that ReadDirPlus is being called.

feat(Readdirplus): Integrate readdirplus with flag

---

internal/fs/fs.go
internal/fs/read_dir_plus_test.go

This PR implements the `ReadDirPlus` operation. 
The implementation includes:
The implementation includes:
- The `ReadDirPlus` method in `internal/fs/fs.go`.
- Three new helper functions:
- `coreToDirentPlus`: Creates a `fuseutil.DirentPlus` entry from an inode core.
- `localFileEntriesPlus`: Lists local files that are not yet present on GCS.
- `lookupAndFetchAttributesForLocalFileEntriesPlus`: Performs a lookup and fetches attributes for each local file entry.
This feature is controlled by a new `EnableReaddirplus` mount option and is disabled by default.
https://b.corp.google.com/issues/423824641
1. Manual - NA
2. Unit tests -  Added fs test `internal/fs/read_dir_plus_test.go` to cover various scenarios:
- Reading an empty directory (`TestEmptyDirectory`).
- Reading a directory with …

feat(Readdirplus): Implement ReadDirPlus operation

---

internal/fs/fs.go
internal/fs/read_dir_plus_test.go

This change enables dentry (directory entry) caching by setting the entry expiration timeout when the experimental-enable-dentry-cache flag is set.
This change allows the kernel to cache the mapping of file paths to inodes.
The expiration time is set on entries returned by LookUpInode and ReadDirPlus operations.
b/423824806
1. Manual - NA

feat(entry-timeout): Set EntryExpiration for dentry caching

---

cmd/legacy_main.go
go.mod
go.sum

- Adding info unmount logs when unmount failed for externally managed mount point.
- Corresponding jacobsa/fuse change - https://github.com/jacobsa/fuse/pull/179
**Tested in GKE Environment**:
```text
I0717 16:45:04.019697       1 main.go:124] received SIGTERM signal, waiting for all the gcsfuse processes exit...
I0717 16:45:04.019728       1 main.go:127] the sidecar mounter is calling ctx.cancel
I0717 16:45:04.019768       1 sidecar_mounter.go:112] context marked as done, sleep for 5 seconds, to evaluate gcsfuse process 22 exit state
I0717 16:45:04.019778       1 sidecar_mounter.go:102] sending SIGTERM to gcsfuse process: /gcsfuse --app-name gke-gcs-fuse-csi --foreground --gid 0 --config-file /gcsfuse-tmp/.volumes/gcs-fuse-warp-test-volume/config.yaml --enable-cloud-profiling …
```

fix: improve logging while unmount external mount

---

tools/integration_tests/mount_timeout/gcsfuse_mount_timeout_test.go

This change enhances the mount_timeout integration test by saving GCSFuse logs as an artifact when a mount or unmount operation fails. This provides crucial debugging information for test failures and improves error message formatting for better clarity.
[b/412688930](http://b/412688930)
1. Manual - NA
5. Integration tests - Ran as [presubmit](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/3c87da41-d19c-42ca-a8f8-8f9a2f455b8f) .

ci(debugging): Save gcsfuse logs for failed mount_timeout package

---

internal/storage/caching/fast_stat_bucket.go
internal/storage/caching/fast_stat_bucket_test.go

This change addresses an issue where the fastStatBucket cache entry was not being invalidated when a read operation failed because the underlying GCS object was not found.
When a ReadFile operation encountered a gcs.NotFoundError, it would correctly return a "stale NFS file handle" error. However, the stale metadata remained in the cache. This caused subsequent lookups for the same file to succeed, leading to a loop of failed read attempts.
This PR fixes the behavior by explicitly checking for gcs.NotFoundError after a read attempt and invalidating the cache entry if the error is present.
https://b.corp.google.com/issues/433184217
1. Manual - NA

fix(caching): Invalidate fast stat cache on NotFoundError

---

.github/workflows/ci.yml

- Only run go tests when pr contains related changes.
- Used https://github.com/dorny/paths-filter to implement this. Can't use standard [paths or paths ignore](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) in workflow actions as it leads to stuck. This is because linux-test is required, and using path or paths-ignore at workflow level skip the execution of linux-test and PR will get stuck waiting for the status of required `linux-test`.
b/431911068
1. Manual - Tested.

chore(ci): Don't run go specific test if PR doesn't contain any related file

---

.github/workflows/ci.yml

- Follow up on this: https://github.com/GoogleCloudPlatform/gcsfuse/pull/3534
- Skipping job leads to stuck because of required status check. Hence, moving the check on the steps level, this will ensure status success every time and only skip the real linux test part.
NA
1. Manual - NA

ci: moving path filters check at job.steps level

---

.github/workflows/ci.yml

Currently, we have a host of lint issues on master which we don't plan to fix anytime soon. Until then, the post-submit ci run always fails due to lint issues. Let's stop the linter run in postsubmits until all the lint issues are fixed so that the post-submit run starts succeeding.
b/433235596
1. Manual - NA

chore(ci.yml): Don't run linter on post-submit runs

---

cmd/mount.go
common/util.go
common/util_test.go
internal/fs/fs.go
internal/fs/inode/name.go
internal/fs/inode/name_test.go
internal/fs/notifier_test.go
internal/fs/server.go

This change integrates `fuse.Notifier` to handle stale file entries when the experimental dentry cache is enabled.
When `experimental-enable-dentry-cache` is active, if a file is modified directly in GCS (clobbered), the kernel's dentry cache becomes stale. Subsequent read or write operations on that file would fail, typically with a "stale file handle" error.
This PR introduces logic to detect this specific failure (`FileClobberedError`) and uses the notifier to send an `InvalidateEntry` message to the kernel. This forces the kernel to evict the stale cache entry. As a result, the next operation on the same file will succeed, as gcsfuse will re-fetch the file's latest attributes.
This functionality is only enabled when the `experimental-enable-dentry-cache` flag is set to true. …

feat(Notifier): Use notifier to invalidate stale dentry cache on clobber

---

go.mod
internal/auth/token_source.go
internal/storage/storageutil/auth_client_option.go
internal/storage/storageutil/auth_client_option_test.go
internal/storage/storageutil/testdata/key.json

- Created a function to fetch credentials/tokenSource/UniverseDomain and return them as client options.
- The function also returns the token source, as it will be necessary for the HTTP client to append it in the Transport layer.
[b/432654490](https://b.corp.google.com/issues/432654490)
1. Manual - NA

feat(Migrate Auth TPC): Function for creating credentials/tokenSource/UniverseDomain and add option for client

---

internal/cache/file/downloader/job.go
internal/cache/file/downloader/parallel_downloads_job.go
internal/gcsx/client_readers/gcs_reader.go
internal/gcsx/client_readers/gcs_reader_test.go
internal/gcsx/client_readers/range_reader.go
internal/gcsx/client_readers/range_reader_test.go
internal/gcsx/file_cache_reader.go
internal/gcsx/random_reader.go
internal/gcsx/random_reader_stretchr_test.go
internal/gcsx/random_reader_test.go
metrics/constants.go

This pull request introduces significant changes to how shared state variables are managed within the GCS read path, specifically for GCSReader and randomReader components. By migrating these variables to use Go's sync/atomic package, the PR lays the groundwork for future performance optimizations by enabling the removal of traditional locks for random reads, benefiting parallel random read operations from same file handle on Zonal Buckets. The changes ensure thread-safe access to critical counters and flags, improving the robustness and scalability of the read operations.
Highlights
Concurrency Improvement: Replaced standard variable types (string, int64, uint64) with their sync/atomic counterparts (atomic.Int64, atomic.Uint64) for shared state variables like readType, expectedOffset, …

refactor(parallel random reads): Changes to start using atomic variables for shared state in read path

---

internal/block/block.go
internal/block/block_pool_test.go
internal/block/block_test.go
internal/block/prefetch_block_test.go
internal/bufferedwrites/upload_handler.go

- Making the block interface also a reader.
- Passing directly block instead while uploading the content to gcs instead of reader.
b/429969295
1. Manual - Tested locally, working as expected.

Block: Making block interface a reader

---

internal/fs/wrappers/error_mapping.go
tools/cd_scripts/e2e_test.sh
tools/integration_tests/dentry_cache/notifier_test.go
tools/integration_tests/dentry_cache/setup_test.go
tools/integration_tests/dentry_cache/stat_test.go
tools/integration_tests/improved_run_e2e_tests.sh
tools/integration_tests/run_e2e_tests.sh
tools/integration_tests/run_tests_mounted_directory.sh

This change introduces a new e2e integration test package for the dentry cache feature, enabled by the `--experimental-enable-dentry-cache` flag.
These tests validate the correctness of the dentry cache implementation under different scenarios:
*   **Stat Cache Behavior**: A new test verifies that `os.Stat` returns cached file attributes and that these are correctly refreshed after the metadata cache TTL expires. This is covered in `stat_test.go`.
*   **Notifier Invalidation**: New tests ensure that when a cached file is modified externally on GCS, subsequent `read` and `write` operations fail initially, triggering a cache invalidation that allows the next attempt to succeed. This is covered in `notifier_test.go`.
The test execution scripts have also been updated to run these new tests. …

feat(dentry cache): Add integration tests for dentry cache

---

tools/integration_tests/rapid_appends/appends_test.go

The functional test introduced in this PR asserts that the appends made to finalized object will not be real time i.e. not immediately available for reads. This is so because real time appends is a feature of unfinalized object only. 
Write behavior for finalized object will be similar to objects in regional bucket.
[b/432141061](b/432141061)
1. Manual - Yes.
`--- PASS: TestRapidAppendsSuite/TestAppendsToFinalizedObjectNotVisibleUntilClose (1.36s)`

test(rapid appends): Appends to finalized object is not visible on GCS till Close()

---

tools/integration_tests/rapid_appends/appends_test.go
tools/integration_tests/rapid_appends/setup_test.go

The functional test in this PR tests the scenario when multiple concurrent file handles are opened against the same unfinalized object from the same mount( i.e. the same file inode). 
The test includes :
- File handle opened in append mode and *write* issued in order to trigger the BW flow.
- Another file handle from the same mount, opened in read plus mode , which will use the same bwh initialized in the previous step, ensuring even writes using this file handle will be real-time.
[b/432420125](b/432420125)
`  --- PASS: TestRapidAppendsSuite/TestAppendsVisibleInRealTimeWithConcurrentRPlusHandle (1.46s)`

test(rapid appends): appends with concurrent file handles must be real time

---

internal/bufferedread/buffered_reader.go
internal/bufferedread/buffered_reader_test.go

This PR implements `prefetch` and `freshStart` methods that will be used by Buffered Reader to prefetch the data in prefetch blocks.
https://b.corp.google.com/issues/432168690
1. Manual - NA

feat(bufferedread): Add freshStart and prefetch methods to Buffered Reader

---

internal/block/prefetch_block.go
internal/block/prefetch_block_test.go
internal/bufferedread/buffered_reader_test.go
internal/bufferedread/download_task.go
internal/bufferedread/download_task_test.go

- Using BlockFailed state for BlockCancelled too, canceled state will be decided based on the error.
NA
1. Manual - NA

refactor: removing cancelled block state

---

cfg/config.go
cfg/params.yaml
cfg/validate.go
cfg/validate_test.go
cmd/config_validation_test.go
cmd/root_test.go
cmd/testdata/valid_config.yaml

- Currently all the buffered-red configuration flags are hidden, will make few flags visible after complete implementation.
b/434674228
1. Manual - NA

feat(bufferedread): adding mount config to control buffered-read feature

---

tools/integration_tests/util/operations/dir_operations.go

In this utility, don't proceed with file creation, if the parent directory failed to create. And
similarly, don't try to close file handle if file
creation itself failed first.
These are needed to avoid
- confusing and misleading error logs
- run time wasted in dependent operations for failed operations
I discovered this while debugging b/434203417 with @ChrisThePattyEater .
[b/434203417](http://b/434203417)
1. Manual - NA

ci: fail fast in utility CreateDirectoryWithNFiles

---

tools/integration_tests/util/setup/setup.go

While debugging [b/434203417](http://b/434203417), I found that we don't fail fast if the user passes `--testBucket` as `a/b` which is obviously not supported, and the test fails somewhere in some test much later making it hard to root cause. This change will make it fail at argument parsing time itself.
[b/434203417](http://b/434203417)
1. Manual - NA

fix: fail gcsfuse e2e tests if testBucket argument is improper

---

tools/integration_tests/rapid_appends/appends_test.go

This PR covers the functional test for rapid appends , majorly concerned with the size which is visible to kernel as appends to an unfinalized object is done. Scenarios include: 
- When a file is appended and the stat cache is valid, the kernel must see the correct updated file size
- When a file is appended and the stat cache is expired (new inode for the file), the kernel must see the correct file size.
[b/433375953](b/433375953)
[b/433375791](b/433375791)
1. Manual - Yes.
3. Integration tests - Part of the PR.

test(rapid appends): test size visible to kernel on appends

---

internal/block/prefetch_block.go
internal/bufferedread/buffered_reader.go
internal/bufferedread/buffered_reader_test.go
internal/bufferedread/download_task.go

This PR implements the `ReadAt` method on BufferedReader to support reads from GCS objects, satisfying the `gcsx.Reader` interface.
The method leverages the existing prefetching mechanism to read from in-memory blocks. Key features of the implementation include:
- Random Read Detection: Identifies random read patterns and falls back to a simpler GCS reader if the configured threshold for random seeks is exceeded.
- Efficient Seek Handling: Discards stale blocks from the queue on seeks to ensure the reader starts from the correct offset.
- Continuous Prefetching: Triggers new prefetch operations as data is consumed to keep the read pipeline full and minimize latency.
https://b.corp.google.com/issues/432169239

feat(bufferedread): Implement ReadAt method of Buffered Reader

---

tools/integration_tests/implicit_dir/implicit_dir_test.go
tools/integration_tests/util/client/storage_client.go
tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go
tools/integration_tests/util/setup/setup.go

- Fix for [b/434203417](http://b/434203417) (more details in [b/issues/434203417#comment23](http://b/issues/434203417#comment23))
- Re-allow `/` in `--testBucket` argument as it's needed for gke testing for allowing `only-dir` testing.
- Don't run duplicate tests for ZB-run (`enable-hns` and `grpc`)
- Enhance error logs with object names
This pull request primarily addresses a CI issue related to `only-dir` testing in GKE environments by enabling the use of forward slashes in the `--testBucket` argument. This change necessitated a refactoring of the test setup for implicit and explicit directories to correctly handle these new path structures. Minor improvements to error logging and test configuration for different bucket types were also included.
* **Test Bucket Path Flexibility**: I've …

ci: fix only-dir testing in implicit_dir test package

---

.github/workflows/ci.yml

- Adding ci linux timeout to 25 minutes.
NA
1. Manual - NA
2. Unit tests - Automated.

chores: Increase CI linux timeout to 25 minutes

---

internal/block/block_pool.go
internal/block/block_pool_test.go

- Adding a new method TryGet in the block-pool, which doesn't block the call in case block-pool limit is reached. Instead returns an error.
- Existing `Get` method is blocks the execution in case block-pool limit is reached.
b/435631891
1. Manual - NA

feat(block-pool): adding tryGet similar to Get() but doesn't block execution when block-pool is full

---

internal/bufferedread/buffered_reader.go
internal/bufferedread/buffered_reader_test.go
internal/fs/fs.go
internal/fs/handle/file.go
internal/fs/handle/file_test.go
internal/gcsx/read_manager/read_manager.go
internal/gcsx/read_manager/read_manager_test.go
internal/workerpool/static_worker_pool.go
internal/workerpool/static_worker_pool_test.go

This PR integrates the `BufferedReader` with the filesystem components to improve read performance.
The ReadManager is updated to use the BufferedReader when enabled via the `read.enable_buffered_read flag`. 
b/435417084

feat(bufferedread): Integrate Buffered Reader with the filesystem

---

internal/storage/debug_bucket.go

Removing unnecessary back-slash from gcs-read logs.
**Before:**
```text
time="02/08/2025 01:04:56.190970" severity=TRACE message="gcs: Req             0x5d: <- \"ReadWithReadHandle\"(\"10G_file\", [1526726656, 1543503872))"
```
**After:**
```text
time="02/08/2025 01:18:29.321032" severity=TRACE message="gcs: Req             0x5e: <- ReadWithReadHandle(\"10G_file\", [1543503872, 1560281088))"
```
NA
1. Manual - NA

style(debug_bkt): removing unnecessary back-slash from gcs-read log

---

internal/fs/flat_bucket_test.go
internal/fs/fs.go
internal/fs/fs_test.go
internal/fs/hns_bucket_test.go
internal/fs/rename_dir_test.go
internal/fs/rename_file_test.go

- Enable move object flat bucket
- Enable composite tests
- Created common test suite for RenameFile and RenameDirectory tests. Added those for hns, flat and zonal buckets.
[b/432388929](https://b.corp.google.com/issues/432388929)
4. The tessellation checkpointing run was executed successfully, with no rename failures detected.

feat(MoveObject): Enable move object for flat bucket

---

internal/fs/fs.go

Add flag check in accessing moveObject API for flat bucket in renaming directory.
1. Manual - NA

fix: Add flag check in accessing moveObject API for flat bucket

---

internal/bufferedread/buffered_reader.go

- Using TryGet (unblocking) instead of Get (blocking) to avoid deadlock when blockPool is fully utilized.
b/433678041
1. Manual - NA

feat(buffered-read): use blockPool's tryGet (unblocking) instead Get to 

---

tools/cd_scripts/e2e_test.sh

Install latest gcloud version and alpha component in CD script tests because managed folder tests were failing with the following error in the CD pipeline:
```
Test_helper.go:102: Error in removing permission to managed folder: failed command '/bin/bash -c gcloud alpha storage managed-folders remove-iam-policy-binding  gs://<bucket_name>/TestDirForManagedFolderTest/managedFolder1 --member=<service account name> --role=roles/storage.objectAdmin': exit status 1, You do not currently have this command group installed.  Using it         requires the installation of components: [alpha]                ERROR: (gcloud) You cannot perform this action because you do not have permission to modify the Google Cloud SDK installation directory [/usr/local/google-cloud-sdk].
```
b/436794846
1. Manual - …

fix: install latest gcloud version in CD script tests

---

tools/integration_tests/improved_run_e2e_tests.sh

Add logs if bucket creation fails in e2e runs instead of failing the script silently.
1. Manual - NA

fix(e2e script): add logs if bucket creation fails in e2e script

---

tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser.go
tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser_test.go
tools/integration_tests/util/log_parser/json_parser/read_logs/helpers.go
tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser_test.go
tools/integration_tests/util/log_parser/json_parser/read_logs/structure.go

- Implementing parser for buffered read logs. This will be required to write e2e test for buffered-read feature.
b/436123285
1. Manual - NA

test(buffered-read): adding log parser utility required for buffered-read e2e test

---

tools/integration_tests/benchmarking/benchmark_delete_test.go
tools/integration_tests/benchmarking/benchmark_rename_test.go
tools/integration_tests/benchmarking/benchmark_stat_test.go
tools/integration_tests/benchmarking/setup_test.go

This pull request focuses on enhancing the debuggability of our end-to-end benchmarking tests. My goal is to provide more actionable insights when tests fail by logging specific file paths involved in errors and ensuring gcsfuse debug logs are preserved for detailed analysis, ultimately streamlining the debugging process for CI failures.
* **Enhanced Debugging Output**: I've improved the error messages for failed `delete`, `rename`, and `stat` operations within the benchmarking tests. These messages now explicitly include the file path(s) involved, which should significantly aid in quickly identifying the root cause of failures.
* **Automated Log Preservation**: I've added functionality to automatically save the gcsfuse debug logs if any benchmarking test fails. This ensures that critical …

ci: save failure gcsfuse logs and add more useful debug logs for e2e benchmarking package

---

optimizedmetrics/otel_metrics.go
tools/metrics-gen/main.go
tools/metrics-gen/otel_metrics.tpl

This PR introduces sampled logging for undeclared metric attributes to help identify and debug unexpected attribute values.
[b/435205304](b/435205304)
1. Manual -Yes (with optimized metrics implementation, expected log generated in case of undeclared attribute)

chore(metrics): sampled logging for undeclared metric attributes

---

internal/monitor/otelexporters.go

This change disables exemplars in OTel metrics by configuring the meter provider with `exemplar.AlwaysOffFilter`.
1. Manual - NA

chore(metrics): disable exemplar filter for metrics

---

internal/gcsx/client_readers/multi_range_reader.go
internal/gcsx/client_readers/multi_range_reader_test.go
internal/gcsx/multi_range_downloader_wrapper.go
internal/gcsx/multi_range_downloader_wrapper_test.go
internal/gcsx/random_reader.go
internal/gcsx/random_reader_stretchr_test.go

timeout is currently unused in MRD flow. Cleanup timeout value from the code while we decide how to implement it properly.
b/435356759
1. Manual - NA
NA

chore: clean up timeout from MRD

---

perfmetrics/scripts/build_and_install_gcsfuse.sh

The Kokoro script is failing because of a recent change that skips Docker reinstallation when the software is already present. The existing, older version of Docker on the Kokoro machines is missing the necessary features.
[b/437464330](https://buganizer.corp.google.com/issues/437464330)

fix: Kokoro tests failure

---

metrics/otel_metrics.go
tools/metrics-gen/main.go

This change fixes a `panic: runtime error: invalid memory address or nil pointer dereference` that occurs when GCSfuse is run with metrics enabled and encounters an operation with an unrecognized attribute for a histogram-based metric .
When an attribute for one of these metrics is not recognized, the code proceeds with a nil histogramRecord . This nil record is then passed to a background goroutine for processing, causing a nil pointer dereference.
The fix is to add a return statement immediately after logging the unrecognized attribute.
Follow-up in seperate [PR](https://github.com/GoogleCloudPlatform/gcsfuse/pull/3667) : Run all integration test packages with metrics enabled .
1. Manual - Since the issue raised was related to readdirplus experimental flag, i have tested manually by …

fix(metrics): Prevent panic from unrecognized histogram attributes

---

metrics/metrics.yaml
metrics/otel_metrics.go
metrics/otel_metrics_test.go

This PR adds missing attribute values to existing metrics. These are what I have manually caught, will check with the automated tests to validate that nothing is remaining.
1. Manual - NA
3. Integration tests - Automated as part of PR #3667

chore(metrics): add missing metric attribute values

---

tools/integration_tests/explicit_dir/explicit_dir_test.go
tools/integration_tests/test_config.yaml
tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
tools/integration_tests/util/mounting/static_mounting/static_mounting.go
tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go
tools/integration_tests/util/setup/setup.go
tools/integration_tests/util/test_suite/config.go

This PR includes changes to migrate explicit_dir package to use common config file. This common config will be used by both GCSFuse binary and GCSFuse csi driver tests.
**Changes include:**
1. config file flag addition.
2. refactoring to use config file by test methods.
3. changes are made in a backward compatible way so tests can run with both config file and flags. This will be cleaned up in future PRs after the migration is complete.
4. Migration of explicit dir package so it can use config file.
b/430184649
1. Manual - Manually tested with config file for both cases when mounted directory is set and not set. Also validated that the tests work without config file.
6. Integration tests - via KOKORO
NA

refactor: explicit_dir test package migration [GKE-GCSFuse Test migration]

---

cfg/config.go
cfg/params.yaml
cmd/root_test.go
tools/integration_tests/util/mounting/static_mounting/static_mounting.go

Make default value of flag(enable-google-lib-auth) true with valid testing.
1. Manual 
i. GCS - GCE - Done(both http/gRPC)
ii. GCS - GKE - Done(both http/gRPC)
iii. TPC - GCE
iv. TPC - GKE
3. Unit tests - Automated
4. Integration tests - Automated
5. Checkpoint tests - [b/437030559](https://b.corp.google.com/issues/437030559)
6. Benchmark perf tests - [Sheet link](https://docs.google.com/spreadsheets/d/1eZjSDxaX-vpzkFI3bPphDanrYtYA7koc_mCQP34Dh7Q/edit)
7. Perf tests

feat(Migrate auth TPC): Make default value of flag true

---

internal/bufferedread/buffered_reader.go
internal/bufferedread/buffered_reader_test.go
internal/bufferedread/download_task.go
internal/fs/handle/file_test.go

Following the recent removal of file-handle-level locks, the buffered read path is no longer thread-safe. Consequently, running multiple goroutines on the same file handle can lead to issues due to shared resources. Adding locks in buffered Read readAt method to make it thread safe. Also adding unit test to validate the same.
[b/438091542](https://b.corp.google.com/issues/438091542)
1. Manual - NA

fix(Buffered read): Make buffered read path thread safe

---

perfmetrics/scripts/install_bash.sh
perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh

Bash version 5.1 had an issue with installation from source with parallel 
build (ref: https://bugs.gentoo.org/921535). Updated the bash version to more latest 5.3 version and modified the script to improve failure logging and use `set -euo pipefail` within the install block and report failure if any of the commands fail.
[b/438135166](http://b/438135166)
3. Integration tests - as part of presubmit runs
NA

fix(bash installation): use latest bash 5.3 and improve logging in case of error.

---

internal/bufferedread/buffered_reader_test.go
tools/integration_tests/buffered_read/fallback_test.go
tools/integration_tests/buffered_read/helpers_test.go
tools/integration_tests/buffered_read/setup_test.go
tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser.go

This PR adds integration tests for the buffered reader's fallback logic. It ensures the reader correctly falls back when there isn't enough memory to create it or when the random read limit is surpassed.
b/438682062

feat(bufferedread): Add integration tests for fallback mechanism in buffered reader

---

internal/storage/bucket_handle.go
tools/integration_tests/emulator_tests/write_stall/writes_stall_on_sync_test.go

Enabling write stall in streaming writes path which was disabled in https://github.com/GoogleCloudPlatform/gcsfuse/pull/3404. As bug in dependency has been fixed and upgraded in GCSFuse.
b/424091803
1. Manual - NA
3. Integration tests - Ran as part of presubmit tests on zb and regional

revert(enable-write-stall): enable write stall in streaming writes

---

.github/workflows/auto-pr-reminder.yml

Fix permission issue with auto review reminder when PR is raised from forked gcsfuse.
Error seen in this PR https://github.com/GoogleCloudPlatform/gcsfuse/pull/3709
Error:
1. Manual - NA

fix(review reminder): fix auto reminder issue when PR is raised from fork gcsfuse.

---

internal/storage/bucket_handle.go
internal/storage/debug_bucket.go

fix: re-use read handle from previous read.
b/432639555
1. Manual - Manually verified that the code is working
3. Integration tests - via KOKORO (all tests passed except TestMountTimeout/TestMountMultiRegionUSBucketWithTimeout which is a known flaky test)
4. Perf improvement - negligible for sequential reads (2%)
NA

fix: re-use read handle from previous read.

---

tools/integration_tests/run_tests_mounted_directory.sh

This PR adds `buffered_read` test package to `run_tests_mounted_directory.sh` so that this test package can be picked up to run in GKE.
b/436738278

test: Add buffered read integration tests in mounted directory script

---

cfg/config.go
cfg/params.yaml

This flag is no longer advised for end user to use.
[b/438387832](http://b/438387832)
1. Manual - NA
3. Integration tests - Ran as part of presubmit.
- [run1](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/3f8b12ef-e973-49f5-98fa-379fc79ad732/log) - e2e non-zb - Failed with an unrelated random failure ([b/441423036](http://b/441423036))
- [run2](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/2eb66691-2076-4842-9516-568a9611b75d) - e2e non-zb - running
5.

fix: Hide flag create-empty-file on gcsfuse --help

---

tools/integration_tests/explicit_dir/explicit_dir_test.go
tools/integration_tests/gzip/gzip_test.go
tools/integration_tests/implicit_dir/implicit_dir_test.go
tools/integration_tests/list_large_dir/list_large_dir_test.go
tools/integration_tests/readonly/readonly_test.go
tools/integration_tests/test_config.yaml
tools/integration_tests/util/creds_tests/creds.go
tools/integration_tests/util/setup/setup.go
tools/integration_tests/write_large_files/write_large_files_test.go

This PR includes changes to migrate readonly package to use common config file. This common config will be used by both GCSFuse binary and GCSFuse csi driver tests.
b/439724838
1. Manual - manually verified both with and without config file tests work.
NA

refactor: readonly test package migration [GKE-GCSFuse Test migration] 

---

tools/integration_tests/concurrent_operations/setup_test.go

This is needed for debugging in case of e2e test failure. Without this, there is almost no debugging information available.
[b/441631278](http://b/441631278)
1. Manual - NA
3. Integration tests - Ran as presubmit - [run](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/32f4ebe3-9753-436c-a65f-d68f92890276)

ci: Preserve gcsfuse log file for e2e package concurrent_operations on failure

---

tools/integration_tests/mount_timeout/gcsfuse_mount_timeout_test.go

Enable debug log in e2e test package mount-timeout to debug failures.
[b/442353614](http://b/442353614)
1. Manual - NA
3. Integration tests - Ran as presubmit.

ci(debug e2e failure): Enable trace logs in e2e package mount-timeout

---

cmd/root_test.go
tools/integration_tests/util/mounting/static_mounting/static_mounting.go

- This reverts the remaining changes of #3610 which were not reverted in #3777
- This helps fix an error in e2e TPC test suite.
[b/442950851](http://b/442950851)
1. Manual - NA
3. Integration tests - Ran as [presubmit](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/654198db-5fb1-410d-9f7b-d51195db0e9f)

revert: Revert "feat(Migrate auth TPC): Make default value of flag true (#3610)"

---

tools/integration_tests/interrupt/git_clone_test.go

Retry on failed to resolve host 'github.com' in e2e test `interrupt`.
[b/443696923](http://b/443696923)
1. Manual - tested manually. Sample log below.
```sh
{"timestamp":{"seconds":1757403839,"nanos":634340643},"severity":"INFO","message":"File system has been successfully mounted."}
+ set +x
+ GODEBUG=asyncpreemptoff=1
+ go test . -test.timeout 5400s -test.parallel 1 --integrationTest -test.v --testbucket=gargnitin-test-hns-asiase1 -test.run '.*/TestGitClone' --gcsfuse_prebuilt_dir /usr/local/google/home/gargnitin/work/cloud/storage/client/gcsfuse/tasks/adhoc/20250906-git-clone-test/src/gcsfuse github.com/googlecloudplatform/gcsfuse/v3/tools/integration_tests/interrupt --mountedDirectory=/usr/local/google/home/gargnitin/work/test_buckets/gargnitin-test-hns-asiase1-mount …
```

fix(e2e random error): Retry on failed to resolve host github.com

---

internal/bufferedread/buffered_reader_test.go
internal/gcsx/read_manager/read_manager_test.go
internal/workerpool/static_worker_pool.go
internal/workerpool/static_worker_pool_test.go

This PR reduces the channel size in workerpool to 2 times Global Max Read Blocks as at a given time at most readGlobalMaxBlocks can be scheduled. This would also help reduce around 2-3 MiBs of memory used by buffered read as seen in this [bug](https://b.corp.google.com/issues/443636263).
https://b.corp.google.com/issues/443915926

feat(bufferedread): Reduce the channel size in workerpool to 2 times Global Max Read Blocks

---

perfmetrics/scripts/continuous_test/gcp_ubuntu/continuous.cfg
perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/checkpoint-tests.cfg
perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-master-zb.cfg
perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-master.cfg
perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-release.cfg
perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-tpc.cfg

In order for Test fusion to ingest logs and XML files, Kokoro generated sponge.log and sponge.xml files needs to be copied to the artifacts directory. For GCSFuse, this directory is the [gcsfuse-kokoro-logs bucket](https://pantheon.corp.google.com/storage/browser/gcsfuse-kokoro-logs)
[444189036](https://b.corp.google.com/issues/444189036)
1. Manual - NA
3. Integration tests - Integrations tests run on submit.
None
The upcoming CI integration tests will be impacted since none of the previous run jobs will generate these files.

ci(kokoro): copy sponge logs to artifacts to gcsfuse kokoro bucket

---

tools/integration_tests/util/setup/setup.go

This change resolves an issue where the only-dir argument was not being properly handled in GCSFuse tests following a refactoring of the config-file logic. Bucket names passed by GKE, which can be in the format <bucket_name>/<only_dir_mounted>, were not being parsed correctly. This has now been addressed.
b/445614904
1. Manual - tests have been validated in GKE environment during the last release

fix: bucket name while identifying Bucket Type for only-dir mount tests

---

tools/integration_tests/concurrent_operations/concurrent_listing_test.go

Adding sleep after writing to a file to ensure that append works properly.

test: Fixing errors in concurrent listing package

---

tools/integration_tests/buffered_read/setup_test.go
tools/integration_tests/concurrent_operations/setup_test.go
tools/integration_tests/explicit_dir/explicit_dir_test.go
tools/integration_tests/grpc_validation/setup_test.go
tools/integration_tests/gzip/gzip_test.go
tools/integration_tests/implicit_dir/implicit_dir_test.go
tools/integration_tests/list_large_dir/list_large_dir_test.go
tools/integration_tests/monitoring/prom_test.go
tools/integration_tests/read_large_files/read_large_files_test.go
tools/integration_tests/readonly/readonly_test.go
tools/integration_tests/rename_dir_limit/rename_dir_limit_test.go
tools/integration_tests/util/creds_tests/creds.go
tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go
tools/integration_tests/util/mounting/only_dir_mounting/only_dir_mounting.go
tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
tools/integration_tests/util/mounting/static_mounting/static_mounting.go
tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go
tools/integration_tests/util/setup/setup.go
tools/integration_tests/util/test_suite/config.go
tools/integration_tests/write_large_files/write_large_files_test.go

This pull request refactors the integration test framework to use a centralized configuration for mounting gcsfuse. Previously, mounting functions used global flags, making tests harder to maintain.
This is also part of GCSFuse GKE test migration to a common config.
The key changes in this PR are:
- The mounting functions have been updated to accept a TestConfig struct.
- The MountedDirectory field in TestConfig has been renamed to GKEMountedDirectory for clarity. A new GCSFuseMountedDirectory field has been added for the gcsfuse mount point.
- Also changed config file to accept relative path.
b/445873072
1. Manual - NA

refactor: Migrate mount function to configs

---

cfg/config.go
cfg/params.yaml

Make the flag `--profile` visible in `gcsfuse --help` .
[b/446805375](http://b/446805375)
1. Manual - Tested manually. The flag now shows up on `gcsfuse --help` as 
```sh
gcsfuse$ go run . --help | grep -i profile
--profile string                               The name of the profile to apply. e.g. aiml-training, aiml-serving, aiml-checkpointing
```
4. Integration tests - Ran as presubmit
- [run](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/8316d438-f3dd-4cdd-83d4-ec17b007fdf5) - e2e non-zb

feat(optimize profile): make the flag --profile visible in gcsfuse --help

---

cfg/config.go
cfg/params.yaml
cfg/validate.go
cfg/validate_test.go
cmd/root_test.go

Rename the erstwhile http-dns-cache-ttl-secs flag to enable-http-dns-cache which is a boolean flag. The DNS caching infrastructure will take care of handling the TTL.
b/446170703
1. Manual - NA
No

feat(dns_cache): Guard HTTP/1 DNS cache enablement with a boolean flag

---

cfg/config.go
cfg/params.yaml

The help documentation for the GCS Fuse `--custom-endpoint` flag is causing user confusion and leading to mount failures because it does not specify the correct endpoint format.
Ref issue - https://github.com/GoogleCloudPlatform/gcsfuse/issues/3705
I recently found(b/429928623) that, standard URL formats results in errors. The only format that has been found to work reliably is `storage.<UNIVERSE_DOMAIN>:443`. Update the documentation with this URL format.
[b/440981458](https://b.corp.google.com/issues/440981458)
1. Manual - NA

fix: Fix custom-endpoint format in help doc

---

docs/troubleshooting.md

This PR updates troubleshooting doc about a known issue that we face in `v3.3.0` and `v3.4.0` while setting `--read-global-max-blocks` to `-1`.
https://b.corp.google.com/issues/448271034
1. Manual - NA

docs: Update troubleshooting doc regarding error while setting readGlobalMaxBlocks to -1

---

internal/workerpool/static_worker_pool.go
internal/workerpool/static_worker_pool_test.go

This PR limits the channel size in static worker pool by the number of workers available as at a time the max tasks that be executed equals the number of workers and also when `--read-global-max-blocks` is set to `-1` it tries to create a very large channel which takes upto `52s` during mount and is not needed.
b/448570386

feat(bufferedread): Limit channel size in buffered reader by number of workers.

---

Makefile
cfg/config_test.go
cfg/optimize_test.go
tools/config-gen/main.go
tools/config-gen/templates/config_test.tpl

- ~Dependent on #3799~
- This adds code to auto-generate unit test file `cfg/config_test.go` from the given (new) template file `toos/config-gen/template/config_test.tpl`, similar to how `cfg/config_test.go` is generated from  `toos/config-gen/template/config_test.tpl` using `go generate`.
- This generated file `cfg/config_test.go` unit tests the newly added `ApplyOptimizations` function implemented in the generated file `cfg/config_test.go` for all the flags optimized/overriden in various situations e.g. user-config set or not set, machine-type set or not set, `--profile` set or not set, optimization defined or not defined etc.
- There is no change to any actual gcsfuse library code. The only change is to how the code-gen tool works, and the added generation of the unit test file …

test(optimize-profile): Add code for generating unit tests for optimize profile (generated function ApplyOptimizations)

---

tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go
tools/integration_tests/util/client/storage_client.go

- Increase goroutines handling deletion of objects to reduce wait time between cleanups
- Remove 2s delay per file while creating files to reduce wait time for setup
1. Manual - NA

fix(rapid): fixes for list_large_dir test timeouts in GKE test grid
