GoogleCloudPlatform/gcsfuse

- README.md
- docs/installing.md
Update to README.md and installing.md to highlight supported platforms and installation prerequisites.
> Minor reformatting to installation instructions

- docs/mounting.md
- tools/mount_gcsfuse/main.go
This adds the feature requested in #219.
> Add support for uid, gid in /etc/fstab

- docs/mounting.md
- tools/mount_gcsfuse/main.go
> Add stat-cache-ttl and type-cache-ttl as fstab options

- tools/build_gcsfuse/main.go
e.g. `build_gcsfuse ${GOPATH}/src/github.com/googlecloudplatform/gcsfuse /tmp ${gcsfuse_version} "-ldflags=-s -ldflags=-w"`
@bjornleffler Hello there! If this looks alright to you, can we merge sometime tomorrow? I have need of this for a project 😄
> Allow extra build args

- docs/installing.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> It's possible to install gcsfuse on Debian Stretch

- docs/installing.md
Hey I just hacked a small Arch package together - might be worth mentioning ;-)
> add link to arch linux aur package

- internal/fs/inode/file.go
- internal/fs/inode/file_test.go
Hi folks!
I'd recently migrated a ton of data from bare disks to Google Cloud Storage, using `gsutil rsync` for initial the bulk copy, and then mounting via gcsfuse to maintain a filesystem interface to those files.
Once running on gcsfuse, the mtimes recorded against the files was the time of the bulk copy of data, rather than the original files' mtimes.
Turns out that gsutil does [preserves the original `mtime`](https://github.com/GoogleCloudPlatform/gsutil/blob/0d9d0175b2b10430471c7b744646e56210f991d3/gslib/commands/rsync.py#L1448-L1450) when copying or syncing files, under the metadata key [`goog-reserved-file-mtime`](https://github.com/GoogleCloudPlatform/gsutil/blob/0d9d0175b2b10430471c7b744646e56210f991d3/gslib/utils/posix_util.py#L50).
Gcsfuse resolves mtimes by consuming a …
> Consume mtimes set by gsutil cp / rsync

- internal/fs/local_modifications_test.go
- internal/gcsx/content_type_bucket_test.go
- internal/gcsx/random_reader_test.go
- mount.go
This PR is dedicated to fix the test failures in current gcsfuse. Right now, there are still a couple more tests failing.
> Fix existing test failures

- tools/util/flaky_transport.go
The file changed is only used for debugging.
> Improve debug util with better error message

- internal/fs/monitoring_fs.go
LookUpInode was the most common operation. It could easily become the bottleneck. So, monitoring its latency is necessary.
> Measure the latency of LookUpInode

- docs/installing.md
Update installation documentation.
> Tested on ubuntu 20.04 LTS

- internal/fs/all_buckets_test.go
- internal/fs/fs_test.go
Some file system unit tests were broken. This PR fixes them. 
Test result
```
$ go test ./internal/...
?   	github.com/googlecloudplatform/gcsfuse/internal/canned	[no test files]
ok  	github.com/googlecloudplatform/gcsfuse/internal/fs	11.794s
?   	github.com/googlecloudplatform/gcsfuse/internal/fs/handle	[no test files]
ok  	github.com/googlecloudplatform/gcsfuse/internal/fs/inode	(cached)
ok  	github.com/googlecloudplatform/gcsfuse/internal/gcsx	(cached)
?   	github.com/googlecloudplatform/gcsfuse/internal/logfile	[no test files]
?   	github.com/googlecloudplatform/gcsfuse/internal/mount	[no test files]
?   	github.com/googlecloudplatform/gcsfuse/internal/perms	[no test files]
```
> Fix file system unit tests

- flags.go
> Fix message for flag --max-retry-sleep

- docs/installing.md
> Fix installing.md for typo in GCE image names

- .travis.yml
- internal/gcsx/temp_file.go
- tools/integration_tests/main_test.go
Add a few bits about `max-retry-sleep`, inspired by https://github.com/GoogleCloudPlatform/gcsfuse/issues/467
> Add documentaion about max-retry-sleep flag

- vendor/github.com/jacobsa/gcloud/gcs/retry.go
Updated via: govendor sync
Fixes #505.  Fixes #467.  Fixes #363.
> Upgrade module github.com/jacobsa/gcloud

- flags.go
- internal/fs/fs.go
- internal/fs/inode/file.go
- internal/fs/inode/file_test.go
- mount.go
- tools/mount_gcsfuse/main.go
This flag is no longer useful.
> Remove limited-mtime-mutation option

- internal/fs/fs.go
- internal/fs/local_modifications_test.go
It's the level 1 support for a directory renaming from #518
> Allow rename empty directories

- flags.go
- internal/fs/fs.go
- internal/fs/fs_test.go
- internal/fs/inode/base_dir.go
- internal/fs/inode/dir.go
- internal/fs/local_modifications_test.go
- mount.go
> Rename directory with files under a limit

- go.mod
- go.sum
- vendor/github.com/jacobsa/fuse/internal/buffer/in_message.go
- vendor/github.com/jacobsa/fuse/mount_darwin.go
- vendor/modules.txt
This addresses incompatibilities with ARM-based Macs and MacFuse >=
4.0.  Fixes #548.  References #514.
> Upgrade jacobsa/fuse

- internal/fs/caching_test.go
- internal/fs/fs_test.go
- internal/fs/inode/dir.go
- internal/fs/inode/record.go
- internal/fs/inode/record_test.go
- internal/fs/inode/type_cache.go
- vendor/github.com/jacobsa/ogletest/register_test_suite.go
> Rewrite type-cache to simplify directory lookup

- internal/fs/local_modifications_test.go
- tools/integration_tests/mounting/gcsfuse_test.go
Fix failing integration tests and add read/write test for files containing unicode and rune characters.
> Fix integration tests and create fuzzy read/write test

- internal/contentcache/contentcache.go
- internal/fs/fs.go
Create populate cache function and mark TODO.
Run go test ./... and no unit tests should fail.
TODO: add testing once the function implementation is complete.
> Create pre-populate cache plumbing

- internal/contentcache/contentcache.go
- internal/gcsx/temp_file.go
Implement addReplace, remove and get methods to interact with the cache.
Run go test ./...
There should be no failures.
TODO: implement some basic unit tests later to verify correctness of the cache datastructure.
> gcsfuse cache method implementation

- .github/workflows/ci.yml
This PR is to run all tests as #567 was fixed.
> Run all tests

- internal/contentcache/contentcache.go
- internal/gcsx/temp_file.go
Recover the cache from disk on gcsfuse startup.
Depends on #608.
> gcsfuse Recover Cache

- internal/contentcache/contentcache.go
- internal/gcsx/temp_file.go
Move the cache file IO into contentcache package.
gcsfuse behaviour should remain unchanged.
> Move cache file IO into contentcache package

- internal/contentcache/contentcache_test.go
Adds another validate generation unit test.
Depends on #631
> Gcsfuse test validate generation negative case

- internal/contentcache/contentcache.go
- internal/fs/inode/file.go
Change comments to link to github issues.
There should be no code behaviour changes.
> Add todos to github issues

- go.mod
- go.sum
- vendor/github.com/jacobsa/gcloud/gcs/compose_objects.go
- vendor/github.com/jacobsa/gcloud/gcs/conversions.go
- vendor/github.com/jacobsa/gcloud/gcs/gcscaching/fast_stat_bucket.go
- vendor/github.com/jacobsa/gcloud/gcs/object.go
- vendor/github.com/jacobsa/gcloud/gcs/requests.go
- vendor/modules.txt
https://github.com/GoogleCloudPlatform/gcsfuse/issues/648
> Updating gcloud version

- .github/ISSUE_TEMPLATE/gcsfuse-bug-report.md
Adding a template to report issues which explicitly calls out the flags to pass for debug logs.
> Update issue templates

- README.md
Added info about Go Storage Client.
> Updated README.md for Go Storage Client

- .gitignore
>> Just to reduce the effort of developer working on IntelliJ IDEA
> Adding IntelliJ Project Folder to Git Ignore

- tools/integration_tests/implicitdir/write_test.go
Integration test for testing gcsfuse if write made at the start of file is handled correctly
> Test for write at start of the file

- tools/integration_tests/implicitdir/write_test.go
Integration test for checking if writes at random place in a file are saved properly using gcsfuse
> Write at random place in a file

- go.mod
- go.sum
- vendor/github.com/jacobsa/gcloud/gcs/conn.go
- vendor/github.com/jacobsa/gcloud/gcs/reqtrace_bucket.go
- vendor/modules.txt
Updating version of jacobsa gcloud
> Updating version of Jacobsa gcloud

- tools/integration_tests/implicitdir/file_operations_test.go
Integration tests for copy file
> Integration tests for copy file

- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
- perfmetrics/scripts/ml_tests/run_image_recognition_models.py
Experimental flag is now made production ready. Updating its references
> updating references of experimental flag usage

- perfmetrics/scripts/README.md
- perfmetrics/scripts/ls_metrics/README.md
- perfmetrics/scripts/vm_metrics/vm_metrics_test.py
1) Fix testdata dir path in vm_metrics/vm_metrics_test.py 
2) Update metrics' google sheet link. New link points to google sheet
which has same format as sheet used in gsheet/gsheet.py
> Minor fixes to performance/scripts.

- perfmetrics/scripts/job_files/seq_rand_read_write.fio
Changed the block size for 256kb fio load test file
> Changed the block size for 256kb fio load test file to 256kb

- go.mod
- go.sum
- vendor/github.com/jacobsa/fuse/conversions.go
- vendor/github.com/jacobsa/fuse/fuseops/ops.go
- vendor/github.com/jacobsa/fuse/mounted_file_system.go
- vendor/modules.txt
Latest changes in fuse
> 1. Support on sticky bit on directories
> 2. API added to fetch some state data related to any operation - gid, pid etc.
> 3. Changes in sample client file system
All seems to be safe change for gcsfuse.
Did sanity over the basic functionality - everything was working fine. (Read, Write, Edit, List)
> Updated the gcsfuse with latest jacobsa/fuse

- internal/storage/bucket_handle.go
Adding condition for generation and metageneration, if both are non zero or nil.
> Fixing create object method

- docs/installing.md
- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
>> Did the sanity over the regular file-system operations.
>> Updated the doc with the latest version of gcsfuse.
> Updating the GCSFuse Release Version to 0.41.11

- main_test.go
gcsfuse version string was mismatching
> Fixing Main Test File 

- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
-m comes before cp in gsutil command.
> Fixing usage of gsutil with -m option. 

- internal/storage/storageutil/custom_retry.go
- internal/storage/storageutil/custom_retry_test.go
- internal/storage/storageutil/object_attrs.go
- internal/storage/storageutil/object_attrs_test.go
- internal/storage/user_agent_round_tripper.go
>> Minor Test Comments: Changed the order of argument we passed expected vs the actual.
> Added copyright in storage/storageutil and fixed minor test comments

- README.md
- docs/playbook.md
>> Adding the reference of playbook in the main README doc.
>> Updating the playbook with application-credential issue.
> Updating the playbook with application-credential issue

- flags.go
- flags_test.go
Update --max-conns-per-host default to 100
> Update --max-conns-per-host default to 100

- perfmetrics/scripts/load_tests/python/load_generator/__init__.py
- perfmetrics/scripts/load_tests/python/load_generator/constants.py
- perfmetrics/scripts/load_tests/python/load_generator/load_generator.py
- perfmetrics/scripts/load_tests/python/load_generator/task.py
Load testing tool to generate load with custom piece of code in python.
> Python load testing tool

- perfmetrics/scripts/load_tests/python/tasks/__init__.py
- perfmetrics/scripts/load_tests/python/tasks/python_os.py
- perfmetrics/scripts/load_tests/python/tasks/tf_data.py
- perfmetrics/scripts/load_tests/python/tasks/tf_gfile.py
Predefined tasks include:
1. Python OS read to read using python's native open api/
2. TF GFile read to read using tensorflow's tf.io.gfile.GFile api.
3. TF data read to read using tensorflow's tf.data api.
> Adding predefined tasks for python load test

- perfmetrics/scripts/load_tests/python/README.md
- perfmetrics/scripts/load_tests/python/__init__.py
- perfmetrics/scripts/load_tests/python/load_test.py
- perfmetrics/scripts/load_tests/python/requirements.txt
- perfmetrics/scripts/load_tests/python/sample_tasks.yaml
Script for running python load testing tool and predefined tasks for reading files through python's open, tf.io.gfile and tf.data apis.
> Adding scripts and tasks for python load testing tool

- internal/logger/logger.go
- main.go
Going forward:
(a) when we don't pass any log-file, this will write the logs to syslog files.
(b) when we pass the log-file, it will start writing the logs to the specified file path.
> GCSFuse code change to write the logs to syslog files

- flags.go
- flags_test.go
- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
- perfmetrics/scripts/ls_metrics/listing_benchmark.py
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- tools/integration_tests/implicitdir/implicitdir_test.go
Did sanity check (Basic file operations are working fine)
> Making enable-storage-client-library flag production ready

- flags.go
- flags_test.go
- tools/mount_gcsfuse/main.go
Fixed remaining changes in one file.
> Make enable-storage-client-library flag production ready 

- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
Revert changes in script
Manual - git checkout on yesterday's commit id ( tested script on VM)
Unit test - N/A
Integration test - N/A
> Revert changes in script

- docs/installing.md
Changing the gcsfuse installation command to install the latest gcsfuse version.
1. Manual - NA
2. Integration Test - NA
3. Unit Test - NA
> Updating the installation doc with latest released version

- perfmetrics/scripts/load_tests/python/requirements.txt
Fixing the version of tensorflow module used in load-test script
(1) Manual - load_test is working fine.
(2) Integration Test - NA
(3) Performance Test - NA
> Fixing the version of tensorflow used in load_test script

- docs/benchmarks.md
- perfmetrics/scripts/README.md
We will merge these changes after release(v0.42.1) as it will change the documentation.
> Update readme docs for removing disable-http2 flag

- docs/installing.md
Description: Update release version in installation doc.
Testing: N/A.
> Update GCSFuse release version(0.42.2) in installation doc

- tools/integration_tests/implicitdir/implicitdir_test.go
Testing
Manual:
1. Ran the integration tests using: GODEBUG=asyncpreemptoff=1 go test -v --mountedDirectory=gcs. This runs the tests only once using the mounted directory (gcs).
2. Ran the integration tests using: GODEBUG=asyncpreemptoff=1 go test -v --testbucket=temp-0011001100-bucket. This runs the tests for all flags by building and mounting gcsfuse from code.
Unit tests: NA.
Integration tests: NA.
> Allow running integration tests using mounted directory

- docs/installing.md
Update release version in installation doc.
N/A.
> Update GCSFuse release version(0.42.3) in installation doc

- flags.go
Adding -o ro in gcsfuse help
https://b.corp.google.com/issues/265181889
N/A
> Adding -o ro in gcsfuse help

- tools/package_gcsfuse/package.go
Change maintainer from jacobsa to gcs-fuse-dev in package_gcsfuse
Internal
1. Manual
2. Unit tests
3. Integration tests
> Change maintainer from jacobsa to gcs-fuse-dev

- tools/integration_tests/readonly/copy_object_test.go
- tools/integration_tests/readonly/rename_object_test.go
- tools/integration_tests/util/operations/dir_operations.go
This will be pull request template
Adding helper functions for Rename and Copy.
Manual - Manually tested all the tests with both the flags(testBucket and mountedDir)
Unit tests - N/A
Integration tests - All the tests together are working fine.
> Creating helper functions for directory

- tools/integration_tests/operations/copy_dir_test.go
- tools/integration_tests/operations/operations_test.go
Adding copy directory tests.
NA
1. Manual - All the integration tests are working fine for both the flags testBucket and mountedDirectoy.
2. Unit tests - N/A
3. Integration tests- All the integration tests are working fine together
> Copy directory integration tests

- docs/installing.md
Error in printing "-" in installation doc
NA
1. Manual - command is working fine now
> Error in printing "-" in installation doc

- benchmarks/read_full_file/main.go
- benchmarks/write_locally/main.go
- benchmarks/write_to_gcs/main.go
- internal/logger/logger.go
- internal/mount/flag.go
- internal/perf/cpu.go
- internal/perf/memory.go
- tools/build_gcsfuse/main.go
- tools/package_gcsfuse/build.go
- tools/package_gcsfuse/main.go
This CL fixes some of the lint failures we see today on the master branch.
NA
1. Manual - NA
> Fix lint failures

- docs/mounting.md
Add command to unmount fs mounted by mount command in docs
NA
1. Manual - NA
> Add command to unmount fs mounted by mount command

- Dockerfile
- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
- perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh
- perfmetrics/scripts/ml_tests/setup.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
- tools/containerize_gcsfuse_docker/Dockerfile
- tools/package_gcsfuse_docker/Dockerfile
NA
1. Manual - Perf test results:
Branch  | File Size       |   Read BW       |  Write BW  | RandRead BW  | RandWrite BW |
+--------+------------+--------------+------------+--------------+--------------+
| Master |  0.25MiB     | 422.44MiB/s  | 2.69MiB/s  |  29.9MiB/s        |   3.3MiB/s   |
|   PR      |  0.25MiB     | 425.33MiB/s  | 2.91MiB/s   |  30.12MiB/s      |  3.75MiB/s   |
| Master | 48.828MiB  | 3999.93MiB/s | 78.9MiB/s  | 1051.53MiB/s |  83.36MiB/s  |
|   PR      | 48.828MiB  | 4099.36MiB/s | 81.25MiB/s | 1043.18MiB/s |  83.94MiB/s  | …
>  upgrading go version to 1.20.5

- Dockerfile
- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
- perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh
- perfmetrics/scripts/ml_tests/setup.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
- tools/containerize_gcsfuse_docker/Dockerfile
- tools/package_gcsfuse_docker/Dockerfile
Reverts GoogleCloudPlatform/gcsfuse#1196
> [execute-perf-test] Revert " upgrading go version to 1.20.5"

- README.md
> Updating README.md to include GA status

- tools/integration_tests/operations/copy_dir_test.go
- tools/integration_tests/operations/operations_test.go
Copy Empty directory integration tests
1. TestCopyEmptyDirectoryInNonEmptyDirectory
2. TestCopyEmptyDirectoryInEmptyDirectory
3. TestCopyEmptyDirectoryInNonExistingDirectory
NA
11. Unit tests - NA
12. Integration tests - Run all the tests for testbucket and mountedDirectory flags.(status:SUCCESS)
> Copy empty dir integration tests

- perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh
- perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/resnet_runner.py
Changing the machine from 1 GPU to 2 GPUs and increasing the epochs for tf-resnet and pytorch-dino models accordingly. 
Minor change:  copying the status.txt to its respective commit artifact directory before the status is changed to START from COMPLETE.
NA
1. Manual - NA
> Changing the machine spec from 1 GPU to 2 GPUs

- perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh
> Correction in GPU creation command

- perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/build.sh
Giving 'y' value input to 'jq' install.
NA
1. Manual - Tested code changes with the existing codebase and verified that the expected behavior is maintained
> Made changes to fix some problems related to KOKORO build failing.

- perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Modified the name, branch and flags of an existing experiment configuration to run experiments on sept_release branch.
NA
1. Manual - Ran the build script from the "periodic_experiments" folder using command "./build.sh" after setting EXPERIMENT_NUMBER to "2". Ran all list tests and 1 load test.  Ensured that the tests were running as expected on newly added configuration.
> Added experiment config for sept_release branch

- docs/semantics.md
> Update semantics.md -- fix typos

- go.mod
- go.sum
fusetesting: fix compilation on arm64 where syscall.Stat_t is a uint32
https://github.com/jacobsa/fuse/pull/149
1. Manual - Tested on arm64 machine
> Updating fuse library version

- DEBIAN/control
- tools/package_gcsfuse_docker/Dockerfile
Changed architecture in DEBIAN/control file to all so that it builds for both arm64 and amd64 architectures.
Changed package name in dockerfile based on the passed build argument. (By default amd64)
NA
1. Manual - Manual mount, file creation, deletion, update succeeds on the created arm64 and amd64 package.
3. Integration tests - @Tulsishah verified and fixed the integration tests.
> updated deb package architecture to all

- tools/integration_tests/util/operations/file_operations.go
Fix kokoro job failure for gzip integration tests
Kokoro VM is based on a specialized linux image created by the Kokoro team for
running jobs on it. This has an old version of gcloud on it, and
thus the gcsfuse integration test jobs use `gcloud alpha` on it as
opposed to `gcloud` command.
To make matters worse, on the kokoro VM, `gcloud alpha` doesn't support
the `-Z` option as well as the options for updating object metadata.
Both these features are required for integration tests for GCS objects
with content-encoding gzip in GCSFuse. Hence, for both these features,
switching from `gcloud alpha` to equivalent `gsutil` commands.
NA
1. Manual - Tested by running gzip integration tests on local VM.
3. Integration tests - Tested by the passing of integration tests on kokoro …
> Fix kokoro job failure for gzip integration tests

- perfmetrics/scripts/requirements.txt
[this ](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1267/files) PR removed installation exceptiongroup and tomli.
NA
1. Manual - Tested script locally on VM.
> kokoro fix: fixing requirements

- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
- perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
Removing extra logs in kokoro continous test
NA
1. Manual - Tested on kokoro machine for pr perf test.
> Removing extra logs in kokoro continous test

- .github/CODEOWNERS
- Added Swetha & Ayush as mandatory reviewer for gcsfuse codebase. One approval is enough to merge the codebase.
Note: code owners must have write permissions for the repository.
NA
1. Manual - NA
> Added mandatory codeowners file for gcsfuse

- internal/fs/fs.go
- internal/fs/local_file_test.go
NA
1. Manual - 
without sync local file changes:
* renaming local file
```
~/mnt$ touch a.txt
~/mnt$ mv a.txt b.txt
mv: cannot move 'a.txt' to 'b.txt': Operation not supported
```
logs
```
D0823 09:07:11.286248 fuse_debug: Op 0x00000108        connection.go:416] <- Rename (PID 512428, old_parent 1, old_name "a.txt", new_parent 1, new_name "b.txt")
E0823 09:07:11.286332 Rename: operation not supported, rename opened file "a.txt": operation not supported
D0823 09:07:11.286389 fuse_debug: Op 0x00000108        connection.go:500] -> Error: "operation not supported"
E0823 09:07:11.286392 fuse: *fuseops.RenameOp error: operation not supported
```
* renaming directory containing local file
```
~/mnt$ mkdir testDir
~/mnt$ touch testDir/local.txt
~/mnt$ mv testDir/ newTestDir/
mv: cannot move …
```
> Rename operation on local files should not be supported

- flags.go
Changing the description as per our public doc.
NA
1. Manual - NA
> Changing the help description for custom-endpoint

- internal/fs/local_file_test.go
Reading local file will be supported. It will not be supported when minimal file buffering is added
NA
2. Unit tests - Added unit tests
3. Integration tests - Integration tests will be added in seperate PR
> Adding unit tests for reading local file

- internal/fs/local_file_test.go
Added unit tests for symlink flow
Creating a symlink to local file and reading it
Creating symlink to local file, deleting it and reading the symlink
NA
1. Manual - Only unit tests are added
> Added unittests for symlink flow

- internal/fs/fs.go
> Fix comment for local file sync  call

- tools/cd_scripts/package_gcsfuse.sh
Creates gcsfuse binaries for both amd64 and arm64 machine.
NA
1. Manual - Tested locally on louhi pipeline.
> Create gcsfuse packages for louhi pipeline

- .github/CODEOWNERS
Adding @raj-prince as code-owner
NA
1. Manual - NA
> Adding @raj-prince as code-owner

- internal/contentcache/contentcache.go
As we are enabling log-levels, removed debug logger from contentcache.go and used appropriate default logger methods instead.
NA
1. Manual - NA
> use default logger instead of separate logger in contentcache.go [slog PR-2]

- docs/semantics.md
Updated the semantics doc with the new write file behaviour for remove 0 byte file changes.
NA
1. Manual - NA
> update semantics.md for remove 0 byte file changes

- internal/config/yaml_parser.go
- internal/config/yaml_parser_test.go
Elaborate error messages returned while parsing the config file.
This PR addresses the review comments added on PR https://github.com/GoogleCloudPlatform/gcsfuse/pull/1396 which were added after the PR was merged.
NA
1. Manual - NA
2. Unit tests - updated
> Fix config file error mssg

- Dockerfile
- perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh
- perfmetrics/scripts/ml_tests/setup.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
- perfmetrics/scripts/run_e2e_tests.sh
- tools/cd_scripts/e2e_test.sh
- tools/containerize_gcsfuse_docker/Dockerfile
- tools/package_gcsfuse_docker/Dockerfile
NA
1. Manual - Tested manually with following operations: list, stat, delete, copy, create, append, prepend, read and they all worked etc.
2. Unit tests - All tests ran and passed locally.
3. Integration tests - Ran as part of presubmit.
> Upgrade golang from 1.21.1 to 1.21.2

- go.mod
- tools/integration_tests/util/setup/yaml-config.go
Update yaml package version from v2 to v3 in integration tests
NA
1. Manual - NA
> Update yaml package version from v2 to v3 in integration tests

- internal/cache/data/file_info.go
- internal/cache/data/file_info_test.go
Adding data class which will be used as an entry for LRU cache
NA
1. Manual - Basic sanity
> Adding FileInfo data class

- internal/cache/data/file_info.go
- internal/cache/file/downloader/job.go
- internal/cache/file/downloader/job_test.go
Add structure for File Download Job struct. Currently, I haven't added unimplemented methods for job.Start() and job.Retry as I am figuring out their final function signatures after today's call.
NA
1. Manual - Ran unit tests.
> Read cache job 1

- Dockerfile
- perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh
- perfmetrics/scripts/ml_tests/setup.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
- perfmetrics/scripts/run_e2e_tests.sh
- tools/cd_scripts/e2e_test.sh
- tools/containerize_gcsfuse_docker/Dockerfile
- tools/package_gcsfuse_docker/Dockerfile
Upgrading go version from 1.21.2 to 1.21.3
NA
1. Manual - NA
3. Integration tests - Successfully passed.
> Upgrade go version to 1.21.3

- internal/cache/file/downloader/job.go
- internal/cache/file/downloader/job_test.go
Adding Download and Cancel function along with tests.
NA
1. Manual - NA
2. Unit tests - added for new functions.
> Read cache job 5 - Download and Cancel function.

- internal/cache/file/downloader/job.go
- internal/cache/file/downloader/job_test.go
Add invalidate and getstatus function download job.
NA
1. Manual - NA
2. Unit tests - Added unit tests for new functions
> Adding invalidate and getstatus function

- internal/cache/file/downloader/downloader.go
- internal/cache/file/downloader/downloader_test.go
- internal/cache/file/downloader/job_test.go
- internal/cache/util/util.go
- internal/cache/util/util_test.go
Adding file download job manager.
NA
1. Manual - NA
2. Unit tests - added unit tests for new functions
> Adding download job manager 

- internal/cache/file/cache_handle_test.go
- internal/cache/file/cache_handler.go
- internal/cache/file/cache_handler_test.go
- internal/cache/file/downloader/downloader.go
- internal/cache/file/downloader/downloader_test.go
- internal/cache/util/util.go
- internal/cache/util/util_test.go
1. Added GetCacheHandle() and InvalidateCache() method.
2. Added unit tests for the implementation.
NA
1. Manual - NA
3. Unit tests -Added unit test.
> Adding Cache Handler Class

- internal/cache/file/cache_handler.go
Updating doc for CacheHandler class.
NA
1. Manual - NA
> Minor doc update for CacheHandler class

- internal/cache/metadata/stat_cache.go
- internal/cache/metadata/stat_cache_test.go
- internal/fs/caching_test.go
- internal/gcsx/bucket_manager.go
- internal/storage/caching/fast_stat_bucket.go
- internal/storage/caching/integration_test.go
- internal/storage/caching/mock_gcscaching/mock_stat_cache.go
NA
1. Manual - Did sanity testing locally, mounting, listing, file and directory reads etc.
2. Unit tests - All rand and passed locally. No new tests passed.
3. Integration tests - Tested through presubmit.
> Move statCache struct to internal/cache/metadata

- perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Run periodic tests for read cache branch with cache enabled. I am raising this PR to master because these changes only affect test setup.
NA
1. Manual - NA
> Run periodic tests for read cache branch with cache enabled

- perfmetrics/scripts/ml_tests/pytorch/v1_12/dino/Dockerfile
Missed inverted commas in pytorch setup.
NA
1. Manual - NA
> Fix inverted commas in pytorch setup

- internal/cache/file/cache_handle.go
- internal/cache/file/cache_handler.go
- internal/cache/file/cache_handler_test.go
- internal/cache/util/util.go
- internal/fs/read_cache_test.go
- internal/gcsx/random_reader.go
Fix file creation in case of random read when downloadFileForRandomRead is true
NA
1. Manual - NA
2. Unit tests - Added unit tests where applicable.
> Fix file creation in case of random read when downloadFileForRandomRead is False

- internal/cache/file/cache_handler.go
- internal/cache/file/cache_handler_test.go
- internal/cache/file/downloader/downloader.go
- internal/cache/file/downloader/downloader_test.go
- internal/cache/util/util.go
- internal/fs/fs.go
- internal/fs/read_cache_test.go
Add destroy method to delete cache post unmounting
NA
1. Manual - NA
2. Unit tests - Added wherever applicable
> Add destroy method to delete cache during unmounting

- perfmetrics/scripts/ml_tests/pytorch/run_model.sh
- perfmetrics/scripts/ml_tests/pytorch/v2/dino/Dockerfile
- Took patch of this Fix "https://github.com/pytorch/pytorch/pull/100071"
- Run the model with compile mode
NA
> Pytorch 2.0 support compile mode

- perfmetrics/scripts/read_cache/setup.sh
Correcting the read-cache script (setup.sh) branch.
NA
1. Manual - NA
> Correcting the read-cache script (setup.sh) branch

- perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Fetching config file change from master - https://github.com/GoogleCloudPlatform/gcsfuse/pull/1598
NA
1. Manual - NA
> Changing config json file as master

- internal/cache/file/cache_handle.go
- internal/cache/file/cache_handler.go
- internal/cache/file/downloader/job.go
- internal/cache/file/downloader/job_test.go
- internal/cache/util/util_test.go
- internal/config/yaml_parser.go
- internal/fs/fs.go
- internal/gcsx/random_reader.go
- internal/monitor/reader.go
Format error with %w instead of %v.
Ref: https://stackoverflow.com/questions/61283248/format-errors-in-go-s-v-or-w
NA
1. Manual - NA
3. Integration tests - [Run](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/9ab1b42a-7fb7-4fdd-a9aa-90e6b7a2f734/log)
> Format error with %w instead of %v

- .github/CODEOWNERS
Add Ashmeen to integration test code owners
NA
1. Manual - NA
> Add Ashmeen to integration test code owners

- tools/integration_tests/read_cache/helpers_test.go
- tools/integration_tests/read_cache/read_only_test.go
- tools/integration_tests/read_cache/setup_test.go
- tools/integration_tests/util/client/gcs_helper.go
- tools/integration_tests/util/client/storage_client.go
- tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser.go
- tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser_test.go
- tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go
- tools/integration_tests/util/mounting/only_dir_mounting/only_dir_mounting.go
- tools/integration_tests/util/mounting/static_mounting/static_mounting.go
- tools/integration_tests/util/operations/file_operations.go
> Read cache functional test case 1

- internal/fs/fs.go
- internal/fs/read_cache_test.go
> adds bug fix for cache location in case temp dir is defined by user

- internal/cache/util/util.go
- internal/cache/util/util_test.go
- internal/fs/fs.go
[buganizer](https://b.corp.google.com/issues/315991900)
1. Manual - WIP
> Cache dir perm check

- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
I noticed that the region of bucket and VM is not same. Changing bucket to west1 region to keep VM and bucket in same region.
NA
1. Manual - NA
> Changing tf model bucket

- docs/semantics.md
Update semantics about disk-leak on write-failure
NA
1. Manual - NA
> Update semantics about disk-leak on write-failure

- internal/config/mount_config.go
Remove unused variable AverageTypeCacheEntrySize
NA
1. Manual - NA
> Remove unused const variable

- tools/integration_tests/operations/write_test.go
- tools/integration_tests/util/client/storage_client.go
This PR includes e2e tests that validate that object attributes are properly written by GCSFuse.
NA
1. Manual - NA
> E2e test for min object

- README.md
- docs/metrics.md
- docs/semantics.md
> [Merge After V2 release only!] Upgrade github documentation to v2.0.0 on master branch

- go.mod
- go.sum
- internal/mount/flag.go
- internal/storage/storage_handle.go
- internal/storage/storage_handle_test.go
- internal/storage/storageutil/client.go
- internal/storage/storageutil/client_test.go
Added support in the storage package, to create gRPC storage based on Client-protocol value.
- User agent support.
- Custom endpoint support.
NA
1. Manual - NA
3. Integration tests - Automation (gRPC related integration test will run after complete integration).
> GRPC: PR2: Added grpc support in the storage package

- internal/storage/storage_handle.go
- internal/storage/storage_handle_test.go
This [PR](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1802) was merged due to last integration test success. Ideally, this should be refreshed after [gcsfuse/v2](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1798) change.
NA
1. Manual - NA
> Fixing build failure change and incorporating minor comment

- tools/integration_tests/explicit_dir/explicit_dir_test.go
- tools/integration_tests/explicit_dir/list_test.go
- tools/integration_tests/implicit_dir/delete_test.go
- tools/integration_tests/implicit_dir/implicit_dir_test.go
- tools/integration_tests/implicit_dir/list_test.go
- tools/integration_tests/run_e2e_tests.sh
- tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go
Made implicit-explicit dir package independent, to make it parallel run with other packages.
NA
1. Manual - NA
> Making implicit-explicit dir test package parallel

- tools/integration_tests/operations/copy_dir_test.go
- tools/integration_tests/operations/copy_file_test.go
- tools/integration_tests/operations/create_three_level_dir_test.go
- tools/integration_tests/operations/delete_dir_test.go
- tools/integration_tests/operations/delete_file_test.go
- tools/integration_tests/operations/file_and_dir_attributes_test.go
- tools/integration_tests/operations/list_dir_test.go
- tools/integration_tests/operations/move_file_test.go
- tools/integration_tests/operations/operations_test.go
- tools/integration_tests/operations/read_test.go
- tools/integration_tests/operations/rename_file_test.go
- tools/integration_tests/operations/write_test.go
- tools/integration_tests/run_e2e_tests.sh
- tools/integration_tests/util/setup/setup.go
Made operations package independent, to make it parallel run with other packages.
NA
1. Manual - NA
> Making operations test package parallell 

- tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go
- tools/integration_tests/util/mounting/only_dir_mounting/only_dir_mounting.go
- tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
- tools/integration_tests/util/mounting/static_mounting/static_mounting.go
Printing flags in test logs.
NA
1. Manual - NA
> Printing flags in test logs

- perfmetrics/scripts/bigquery/requirements.txt
- perfmetrics/scripts/load_tests/python/requirements.txt
> Bump python dependabot dependencies

- internal/logger/logger_test.go
- internal/mount/flag_test.go
- internal/perms/perms_test.go
Moving logger, flag & perms package tests to stretchr testify
NA
1. Manual - NA
> Moving logger, flag & perms package tests to stretchr testify

- README.md
Add codecoverage badge in README.
NA
1. Manual - NA
> Include code-coverage badge in README

- internal/ratelimit/limiter_capacity_test.go
- internal/ratelimit/throttle_reader_test.go
- internal/ratelimit/throttle_test.go
- internal/util/sizeof_test.go
Move to stretchr testify in ratelimit & util packages
NA
1. Manual - NA
> Move to stretchr testify in ratelimit & util packages

- .github/workflows/codecov.yml
> Add timeout to the coverage workflow

- .github/.codecov.yml
> Exclude tools/ and benchmarks/ from code-coverage computation

- Dockerfile
- go.mod
- go.sum
- perfmetrics/scripts/bigquery/requirements.txt
- tools/gem_dependency/Gemfile.lock
Bump dependabot PRs
https://github.com/GoogleCloudPlatform/gcsfuse/pull/1953
https://github.com/GoogleCloudPlatform/gcsfuse/pull/1950
https://github.com/GoogleCloudPlatform/gcsfuse/pull/1942
https://github.com/GoogleCloudPlatform/gcsfuse/pull/1932
https://github.com/GoogleCloudPlatform/gcsfuse/pull/1931
https://github.com/GoogleCloudPlatform/gcsfuse/pull/1926
NA
1. Manual - NA
> Bump dependabot PRs

- internal/cache/file/downloader/job_test.go
> Delete flaky test

- .github/CODEOWNERS
remove @ashmeenkaur as co-owner of integration tests
NA
1. Manual - NA
> remove @ashmeenkaur as co-owner of integration tests

- .github/workflows/scorecard.yml
The scorecard workflow has been failing for some time now. Fixing it.
b/344701958
1. Manual - NA
> Fix scorecard workflow

- cmd/legacy_main_test.go
- internal/cache/file/cache_handle_test.go
- internal/cache/file/cache_handler_test.go
- internal/cache/file/downloader/downloader.go
- internal/cache/file/downloader/downloader_test.go
- internal/cache/file/downloader/job.go
- internal/cache/file/downloader/job_test.go
- internal/config/mount_config.go
- internal/config/testdata/valid_config.yaml
- internal/config/yaml_parser_test.go
- internal/fs/fs.go
- internal/gcsx/random_reader_test.go
Just the flag is added. not used any where. The flag is true by default.
NA
> Added flag to enable crc check 

- internal/cache/file/cache_handle_test.go
- internal/cache/file/downloader/downloader.go
- internal/cache/file/downloader/job.go
- internal/cache/file/downloader/job_test.go
> passes cache config to job

- internal/cache/metadata/stat_cache_test.go
- internal/util/sizeof.go
- internal/util/sizeof_test.go
> updating memory computation because a new field is added in minObject.go

- cfg/config.go
- tools/config-gen/params.yaml
temp-dir should be of type resolved path.
NA
1. Manual - NA
> temp-dir should be of type resolved path

- cmd/root.go
> Improve comment

- cfg/config_util.go
- cmd/flags.go
- cmd/flags_test.go
- cmd/legacy_main.go
- cmd/legacy_main_test.go
- cmd/legacy_param_mapper_test.go
- cmd/mount.go
Migrate most flags to use the new config
NA
1. Manual - NA
> Migrate most flags to the new config

- internal/gcsx/prefix_bucket.go
- internal/monitor/bucket.go
- internal/ratelimit/throttled_bucket.go
- internal/storage/bucket_handle.go
- internal/storage/caching/fast_stat_bucket.go
- internal/storage/control_client_wrapper.go
- internal/storage/debug_bucket.go
- internal/storage/fake/bucket.go
- internal/storage/fake_storage_util.go
- internal/storage/gcs/bucket.go
- internal/storage/mock_bucket.go
- internal/storage/mock_control_client.go
This PR introduces the rename folder API for the GCS bucket interface, along with implementations in relevant structures. 
implementations will be addressed in a subsequent PR.
- Bucket handle
- Fast stat bucket
-  fake bucket 
NA
1. Manual - NA
> Implement rename folder 1

- internal/config/mount_config.go
- internal/storage/storageutil/client.go
In the new config, bools will not have a separate type but just be bools. Change the type to bring it in line with the new config.
NA
1. Manual - NA
> Replace EnableHNS type with bool

- internal/cache/metadata/stat_cache.go
- internal/cache/metadata/stat_cache_test.go
- internal/gcsx/prefix_bucket.go
- internal/gcsx/prefix_bucket_test.go
- internal/monitor/bucket.go
- internal/ratelimit/throttled_bucket.go
- internal/storage/bucket_handle.go
- internal/storage/bucket_handle_test.go
- internal/storage/caching/fast_stat_bucket.go
- internal/storage/caching/mock_gcscaching/mock_stat_cache.go
- internal/storage/debug_bucket.go
- internal/storage/fake/bucket.go
- internal/storage/gcs/bucket.go
- internal/storage/gcs/folder.go
- internal/storage/mock_bucket.go
- Adds new struct folder
- Updates stat cache to use new struct folder
- Updates Get folder to use new struct folder
currently these methods are not being used in any flow
NA
1. Manual - NA
> Fast stat bucket changes

- cmd/legacy_main.go
> Move enableHNS to new config

- cmd/legacy_param_mapper.go
- cmd/legacy_param_mapper_test.go
- internal/config/config_util.go
- internal/config/config_util_test.go
Fixed overriding in max retry attempts flag.
NA
1. Manual - NA
> Fix overriding in max retry attempts flag

- tools/integration_tests/run_e2e_tests.sh
> Add an example of valid location value in integration tests

- tools/integration_tests/concurrent_operations/concurrent_listing_test.go
- tools/integration_tests/concurrent_operations/setup_test.go
add setup for concurrent operations test
NA
1. Manual - NA
> add setup for concurrent operations test

- .github/workflows/shadow.yml
Adds shadow-reviewers to PRs
NA
> Add shadow-reviewers to PRs

- tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
1. addition of new dir.
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from GCSFuse filesystem
2. deletion of new dir.
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from GCSFuse filesystem
3. dir rename.
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from GCSFuse filesystem
NA
1. Manual - NA
6. Integration tests - Automated
> Functional test infinite kernel cache ttl - 3

- internal/fs/inode/dir.go
Adds Code changes to fix e2e hns tests pre submit failure.
NA
1. Manual - NA
> Hns pre submit test fix

- tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
Add tests for list and remove directory scenarios.
NA
1. Manual - NA
> [Kernel List Cache e2e tests] Add tests for list and remove directory scenarios.

- internal/gcsx/prefix_bucket.go
- internal/monitor/bucket.go
- internal/ratelimit/throttled_bucket.go
- internal/storage/bucket_handle.go
- internal/storage/caching/fast_stat_bucket.go
- internal/storage/control_client_wrapper.go
- internal/storage/debug_bucket.go
- internal/storage/fake/bucket.go
- internal/storage/gcs/bucket.go
- internal/storage/mock_bucket.go
- internal/storage/mock_control_client.go
This PR introduces the rename folder API for the GCS bucket interface, along with implementations in relevant structures.
implementations will be addressed in a subsequent PR.
Method is not being called from anywhere in the code.
- Bucket handle
- Fast stat bucket
- fake bucket
NA
1. Manual - NA
> Create folder integration - 1

- internal/cache/file/cache_handle_test.go
Add one more pd tests to cache_handle_test.go
NA
1. Manual - NA
> Add one more pd tests to cache_handle_test.go

- internal/cache/file/cache_handler_test.go
Move to stretchr testify for cache_handler_test.go
NA
1. Manual - NA
> Move to stretchr testify for cache_handler_test.go

- internal/cache/file/cache_handler_test.go
Move from suite.suite to testing.T as per best practices of writing tests.
NA
1. Manual - NA
> Move from suite.suite to testing.T

- internal/cache/file/cache_handler_test.go
Add parallel downloads tests in cache_handler.go
NA
1. Manual - NA
> Add parallel downloads tests in cache_handler.go

- tools/integration_tests/read_cache/helpers_test.go
- tools/integration_tests/read_cache/job_chunk_test.go
- tools/integration_tests/util/log_parser/json_parser/read_logs/helpers.go
- tools/integration_tests/util/log_parser/json_parser/read_logs/json_job_log_parser.go
- tools/integration_tests/util/log_parser/json_parser/read_logs/json_job_log_parser_test.go
- tools/integration_tests/util/log_parser/json_parser/read_logs/structure.go
Add tests to validate async job chunk size.
NA
1. Manual - NA
> [Read Cache parallel downloads test] Add tests to validate async job chunk size

- internal/fs/inode/dir.go
- internal/storage/caching/fast_stat_bucket.go
- internal/storage/caching/fast_stat_bucket_test.go
- tools/integration_tests/util/operations/file_operations.go
adds and uses new method to insert objects and prefixes into stat cache.
NA
1. Manual - NA
> adds and uses new method to insert objects and prefixes into stat cache

- perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files.py
- perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py
Helper function to upload files in the gcs bucket at specified location
NA
1. Manual - NA
2. Unit tests - [link](https://github.com/GoogleCloudPlatform/gcsfuse/blob/1aa474c936244fb8683f4f861e55fc2d457ba145/perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py#L260)
> Upload files for hns rename folder test in gcs bucket 

- coverage.out
- internal/fs/fs.go
Create common functions to reuse it in further renameFolder method.
NA
1. Manual - NA
> Rename fs level integration - 1

- docs/semantics.md
> Fix grammar

- CONTRIBUTING.md
- internal/gcsx/append_object_creator.go
- internal/gcsx/bucket_manager_test.go
- perfmetrics/scripts/compare_fuse_types_using_fio.py
- perfmetrics/scripts/continuous_test/ml_tests/tf/resnet/build.sh
- perfmetrics/scripts/fio/constants.py
- perfmetrics/scripts/fio/fio_metrics_test.py
- perfmetrics/scripts/generate_files.py
- perfmetrics/scripts/gsheet/gsheet.py
- perfmetrics/scripts/gsheet/gsheet_test.py
- perfmetrics/scripts/ls_metrics/directory.proto
- perfmetrics/scripts/ls_metrics/run_ls_benchmark.sh
- perfmetrics/scripts/ml_tests/setup_host.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_host_and_run_model.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/populate_metrics.sh
- perfmetrics/scripts/populate_vm_metrics.py
- perfmetrics/scripts/utils/metrics_util.py
- perfmetrics/scripts/utils/metrics_util_test.py
- tools/integration_tests/util/setup/setup.go
- tools/integration_tests/util/setup/yaml-config.go
- tools/log_rotate/install_script.sh
> chore: add license header and CONTRIBUTING.md

- perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
- perfmetrics/scripts/testing_on_gke/examples/dlio/run_tests.py
- perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
- perfmetrics/scripts/testing_on_gke/examples/fio/run_tests.py
- perfmetrics/scripts/testing_on_gke/examples/utils/utils.py
This adds on top of https://github.com/GoogleCloudPlatform/gcsfuse/pull/2247 . This has no functional changes, and only formats the files underneath.
This is followed up in https://github.com/GoogleCloudPlatform/gcsfuse/pull/2264 .
NA
1. Manual - NA
> [testing-on-gke part 0.2] Format original fio/dlio load-testing code

- cfg/config.go
- tools/config-gen/templates/config.tpl
This helps keeping the generated code slightly more concise.
NA
1. Manual - NA
> Use short-if in generated code.

- .github/header-checker-lint.yml
> test: configure header-checker-lint bot

- tools/config-gen/params.yaml
- tools/config-gen/parser.go
There are no changes to the params.yaml. Just that the order of the params have changed since they have now been sorted. The fact that the generated files haven't changed is a proof of that.
NA
1. Manual - NA
> Impose a sort-order in params.yaml

- perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
- perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/build.sh
- perfmetrics/scripts/ls_metrics/config-hns.json
- perfmetrics/scripts/ls_metrics/run_ls_benchmark.sh
- perfmetrics/scripts/run_load_test_and_fetch_metrics.sh
Modified existing script to run performance tests on HNS as well as flat bucket and upload metrics to [gsheet](https://docs.google.com/spreadsheets/d/1wXRGYyAWvasU8U4KaP7NGPHEvgiOSgMd1sCLxsQUwf0/edit?usp=sharing&resourcekey=0-Kv_559oGD9Z9474dPN6dxA).
NA
1. Manual - Ran the scripts manually for a smaller workload.
> Performance tests (read/write/list) for HNS bucket

- tools/integration_tests/run_tests_mounted_directory.sh
Add Parallel Download tests to mounted directory script for GKE team
NA
1. Manual - Manually ran the tests of GCE VM.
> Add Parallel Download tests to mounted directory script.

- cmd/legacy_main.go
- cmd/legacy_main_test.go
This PR migrates grpc conn pool size config which was missed earlier. Tests to test new config were added as part of the previous PR: https://github.com/GoogleCloudPlatform/gcsfuse/pull/2336
NA
1. Manual - NA
> [CLI Config Parity] Migrate GRPC connection pool size

- benchmarks/stat_files/main.go
- internal/fs/inode/dir.go
- internal/fs/stress_test.go
- internal/gcsx/garbage_collect.go
- internal/storage/fake/testing/bucket_tests.go
- internal/storage/storageutil/create_objects.go
- internal/storage/storageutil/delete_all_objects.go
Replacing syncUtil.Bundle with errGroup
> Replacing syncUtil.Bundle with errGroup

- tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
- tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
- tools/integration_tests/read_cache/disabled_cache_ttl_test.go
- tools/integration_tests/read_cache/job_chunk_test.go
- tools/integration_tests/read_cache/local_modification_test.go
- tools/integration_tests/read_cache/range_read_test.go
- tools/integration_tests/read_cache/read_only_test.go
- tools/integration_tests/read_cache/remount_test.go
- tools/integration_tests/read_cache/setup_test.go
- tools/integration_tests/read_cache/small_cache_ttl_test.go
add test with cache pointing to ram based dir
NA
1. Manual - NA
> add test with cache pointing to ram based dir

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- flaky_tests.lst
> Add support to ignore flaky tests.

- cfg/config.go
- cmd/config_validation_test.go
- cmd/root_test.go
- cmd/testdata/valid_config.yaml
- internal/config/mount_config.go
- internal/config/yaml_parser_test.go
- tools/config-gen/params.yaml
Reverts to enable-hns default false
NA
> makes enable-hns default false

- .github/workflows/flake-detector.yml
> Increase the number of test runs to 20 to capture rarer flakes

- flaky_tests.lst
> Skip flaky tests.

- cfg/config.go
- cfg/params.yaml
- cfg/validate_test.go
- cmd/config_validation_test.go
- cmd/root_test.go
- cmd/testdata/valid_config.yaml
- internal/cache/file/downloader/jm_parallel_downloads_test.go
- internal/cache/file/downloader/job.go
- internal/cache/file/downloader/job_test.go
- internal/cache/file/downloader/parallel_downloads_job.go
- internal/config/mount_config.go
- internal/config/testdata/valid_config.yaml
- internal/config/yaml_parser_test.go
- tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
- tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
- tools/integration_tests/read_cache/disabled_cache_ttl_test.go
- tools/integration_tests/read_cache/job_chunk_test.go
- tools/integration_tests/read_cache/local_modification_test.go
- tools/integration_tests/read_cache/range_read_test.go
- tools/integration_tests/read_cache/remount_test.go
- tools/integration_tests/read_cache/setup_test.go
- tools/integration_tests/read_cache/small_cache_ttl_test.go
- tools/integration_tests/run_tests_mounted_directory.sh
NA
1. Manual - NA
3. Integration tests - [Run](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/6a25354a-84ba-4858-9b49-279b5d92edf2)
> rename disable o direct to enable-o-direct

- internal/fs/wrappers/monitoring.go
- internal/fs/wrappers/monitoring_test.go
> Disable tracing temporarily

- tools/cd_scripts/package_gcsfuse.sh
add git checkout to package_gcsfuse.sh script
NA
1. Manual - NA
> add git checkout to package_gcsfuse.sh script

- perfmetrics/scripts/ls_metrics/listing_benchmark.py
- perfmetrics/scripts/ls_metrics/listing_benchmark_test.py
HNS and flat bucket in use for the listing benchmarks script contains test folder with 1m files. Making that a one time manual run only since Kokoro periodic test job times out due to this case.
To run list perf test on folder with 1m files, run the listing benchmark script with run_1m_test flag.
NA
1. Manual - Ran the script with/without the added flag , working as intended.
2. Unit tests - Added unit tests to check both scenarios when run_1m_test is set to true and false.
> Adding flag to ls perf script to make 1m files listing optional

- .github/workflows/ci.yml
- go.mod
- go.sum
- tools/integration_tests/mounting/gcsfuse_test.go
* Install goimports
* Use `make fmt` to generate auto-generated code, run `goimports` and `go fmt`.
NA
1. Manual - NA
> Use goimports to validate import declarations

- internal/monitor/traceexporter.go
This will help annotate the GCSFuse traces with GCSFuse version.
NA
1. Manual - NA
> Add GCSFuse version in resource definition.

- docs/troubleshooting.md
Added troubleshooting steps for transport endpoint not connected.
NA
1. Manual - NA
> Add troubleshooting steps for transport endpoint not connected.

- docs/dev_guide.md
> Add documentation on how to add flags.

- benchmarks/read_full_file/main.go
Fixing static check failure in benchmark/read_full_file.
- Install static check
` go install honnef.co/go/tools/cmd/staticcheck@latest`
- Run static check
`staticcheck ./benchmarks/read_full_file/...`
Goal is to fix all the static-check failures and then enable static check in CI/CD.
NA
1. Manual - NA
> Fixing static check issues in benchmarks/read_full_file

- perfmetrics/scripts/bigquery/requirements.txt
- perfmetrics/scripts/hns_rename_folders_metrics/requirements.txt
- perfmetrics/scripts/requirements.txt
- tools/gem_dependency/Gemfile.lock
https://github.com/GoogleCloudPlatform/gcsfuse/pull/2311
https://github.com/GoogleCloudPlatform/gcsfuse/pull/2387
NA
1. Manual - Tested by building gcsfuse docker image as gemlock file is being used there. requirements changes we can't tests as it will update production bigquery table.
> Bump dependabot PR

- internal/gcsx/random_reader_test.go
Sample executions: 
* https://github.com/GoogleCloudPlatform/gcsfuse/actions/runs/10877682426/job/30179423787
NA
1. Manual - NA
> Comment out flaky test

- perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
This is a reopen of #2492 .
This is on top of #2348 and is followed up in #2489 .
NA
1. Manual - NA
> [testing-on-gke part 6] fix dependency installations

- internal/storage/bucket_handle.go
- tools/cd_scripts/e2e_test.sh
- tools/integration_tests/run_e2e_tests.sh
- Small fix in script to send HNS logs in the same bucket directory
- Remove unnecessary exit code.
NA
1. Manual - NA
> Fix in script

- tools/mount_gcsfuse/main.go
- tools/mount_gcsfuse/main_test.go
> Persistent mounting kill switch

- perfmetrics/scripts/testing_on_gke/examples/fio/data-loader/templates/fio-data-loader.yaml
- perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
> [testing-on-gke part independent] Clean up references to read-cache branch

- tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser_test.go
> Move to stretchr/testify

- docs/semantics.md
- This PR adds a section describing the support and advantages of HNS in gcsfuse
NA
1. Manual - NA
> Adds a section for HNS to semantics doc

- cfg/config.go
- cfg/params.yaml
> Hide unpublished flags.

- cmd/mount.go
- internal/gcsx/bucket_manager.go
- internal/gcsx/bucket_manager_test.go
> Remove unused field

- flaky_tests.lst
- internal/gcsx/random_reader_test.go
Fix one flaky test in random_reader_test.go
b/362686470
1. Manual - NA
> Fix one flaky test in random_reader_test.go

- internal/cache/file/downloader/downloader.go
- internal/logger/logger.go
- internal/storage/fake_storage_util.go
- internal/util/sizeof.go
- tools/integration_tests/util/operations/dir_operations.go
- tools/integration_tests/util/operations/file_operations.go
- tools/integration_tests/util/setup/setup.go
> Remove unused functions.

- tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go
- tools/integration_tests/list_large_dir/testdata/create_implicit_dir.sh
- tools/integration_tests/list_large_dir/testdata/delete_objects.sh
- tools/integration_tests/list_large_dir/testdata/upload_files_to_bucket.sh
Improved error handling and error message in list_large_dir
NA
> Improve error handling in list_large_dir

- Dockerfile
- go.mod
- perfmetrics/scripts/ml_tests/pytorch/run_model.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
- perfmetrics/scripts/read_cache/setup.sh
- tools/cd_scripts/e2e_test.sh
- tools/containerize_gcsfuse_docker/Dockerfile
- tools/integration_tests/run_e2e_tests.sh
- tools/package_gcsfuse_docker/Dockerfile
upgrade to golang v1.23.2
NA
1. Manual - NA
> upgrade to golang v1.23.2

- tools/cd_scripts/e2e_test.sh
Updated e2e_test.sh to run test packages concurrently in the CD pipeline
NA
1. Manual - Used louhi pipeline for testing this script on 16 VMs.
3. Integration tests - Used this script to run integration tests on 16 VMs in louhi pipeline.
> Update e2e_test script to run test packages concurrently in CD pipeline

- perfmetrics/scripts/load_tests/python/README.md
> Fix typos in documentation

- internal/storage/bucket_handle.go
IDE suggested fix: change all receivers to bh in bucket_handle.go
NA
1. Manual - NA
> [Refactoring] change all receivers to bh in bucket_handle.go

- .github/ISSUE_TEMPLATE/gcsfuse-bug-report.md
- docs/troubleshooting.md
- perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/README.md
- perfmetrics/scripts/ml_tests/tf/resnet/README.md
> Remove deprecated flags from documentation

- internal/block/block_pool.go
- internal/block/block_pool_test.go
- internal/bufferedwrites/buffered_write_handler.go
- internal/bufferedwrites/buffered_write_handler_test.go
Added all required method defintion to bufferedWriteHandler struct. Implementation of sync/flush will be added after uploadHandler changes are done.
NA
1. Manual - NA
> Added bufferedwriteHandler for handling buffered writes flow

- docs/dev_guide.md
> Revise the guidance on adding tests for new flags

- tools/integration_tests/benchmarking/benchmark_delete_test.go
- tools/integration_tests/benchmarking/benchmark_stat_test.go
Adding benchmark tests for delete file .  
NA
1. Manual - NA
> benchmark tests for delete file

- internal/fs/inode/dir.go
Prints out error logs when ListObjects return objects which are unsupported i.e. objects with names starting with / or containing // .
Perf test results: [full logs](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/ae786e77-5c05-41d4-b76d-663a1125eb9e)
```
+--------+------------+--------------+------------+--------------+--------------+
+--------+------------+--------------+------------+--------------+--------------+
| Master |  0.25MiB   | 409.24MiB/s  | 1.38MiB/s  |  56.97MiB/s  |  1.32MiB/s   |
|   PR   |  0.25MiB   | 410.66MiB/s  | 1.17MiB/s  |  56.94MiB/s  |  1.29MiB/s   | …
```
> Add warning logs for unsupported objects

- Dockerfile
- go.mod
- perfmetrics/scripts/ml_tests/pytorch/run_model.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
- perfmetrics/scripts/read_cache/setup.sh
- tools/cd_scripts/e2e_test.sh
- tools/containerize_gcsfuse_docker/Dockerfile
- tools/integration_tests/run_e2e_tests.sh
- tools/package_gcsfuse_docker/Dockerfile
> chore: upgrading go-lang from 1.23.2 to 1.23.3

- perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
> Fix a dlio output parsing bug

- docs/troubleshooting.md
Append information to solve permission issues by specifying appropriate VM scope.
b/380799288
1. Manual - NA
> Update troubleshooting guide

- cmd/config_validation_test.go
- cmd/datatypes_parsing_test.go
- cmd/root.go
- cmd/root_test.go
Make NewRootCmd package-private.
NA
1. Manual - NA
> Restrict visibility

- tools/integration_tests/run_tests_mounted_directory.sh
Follow up PR for [add benchmarking test package to e2e testing](https://github.com/GoogleCloudPlatform/gcsfuse/pull/2725)
NA
1. Manual - NA
> adding benchmarking test to mounted directory tests script

- tools/integration_tests/mounting/gcsfuse_test.go
* Remove Version test
It's failing in CD pipeline. We'll reenable it after fixing the issues.
NA
1. Manual - NA
> Remove Version test (#2785)

- go.mod
- perfmetrics/scripts/ml_tests/pytorch/run_model.sh
- perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
- perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
- perfmetrics/scripts/read_cache/setup.sh
- tools/cd_scripts/e2e_test.sh
- tools/containerize_gcsfuse_docker/Dockerfile
- tools/integration_tests/run_e2e_tests.sh
- tools/package_gcsfuse_docker/Dockerfile
Upgrade to golang v1.23.4
NA
1. Manual - NA
4. Perf tests - ![image](https://github.com/user-attachments/assets/a62b28a6-511e-4bbf-b528-1d072fc16f6f)
> Upgrade to golang v1.23.4

- perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
This addresses internal bug id 383980261 .
NA
1. Manual - NA
> Enable-gVNIC in gke scripts

- internal/bufferedwrites/buffered_write_handler.go
- internal/bufferedwrites/buffered_write_handler_test.go
- internal/fs/inode/file.go
- internal/fs/inode/file_test.go
Added logic to handle truncate in case of buffered writes.
NA
1. Manual - NA
> Handling truncate in buffered writes flow

- go.mod
- go.sum
Dependency Upgrade Crypto for CVE.
b/384085379
Integration and Perf Test - Yes
> Dependency upgrade Crypto for CVE

- perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
This is to handle google internal bug id 384494459 . This creates a new image hash for each new custom csi driver build to force gke cluster nodes to use it on re-run.
NA
1. Manual - Tested manually.
> Create a new custom-csi-driver hash on each build

- tools/cd_scripts/e2e_test.sh
- tools/integration_tests/emulator_tests/emulator_tests.sh
Integrate emulator-based tests into the CD pipeline. 
Include the missing monitoring package in the CD pipeline. (Missed in @kislaykishore's PR)
NA
1. Manual - Manually tested on louhi
> [Write stall] CD pipeline integration

- internal/gcsx/prefix_bucket.go
- internal/monitor/bucket.go
- internal/ratelimit/throttled_bucket.go
- internal/storage/bucket_handle.go
- internal/storage/caching/fast_stat_bucket.go
- internal/storage/debug_bucket.go
- internal/storage/fake/bucket.go
- internal/storage/gcs/bucket.go
- internal/storage/gcs/request.go
- internal/storage/mock/testify_mock_bucket.go
- internal/storage/mock_bucket.go
Integrating MoveObject in all the bucket layers.
- Bucket handle
- Prefix bucket
- Throttle bucket
- debug bucket
- testify bucket
- fake bucket
- mock bucket
- Fast Stat bucket
NA
1. Manual - NA
> [Move Object] Integrating MoveObject in all the bucket layers

- internal/gcsx/prefix_bucket.go
- internal/gcsx/prefix_bucket_test.go
- internal/storage/fake/bucket.go
- internal/storage/gcs/request.go
- Fake and Prefix bucket implementation
NA
1. Manual - NA
> [Move Object] Fake and Prefix bucket implementation

- internal/storage/caching/fast_stat_bucket.go
- internal/storage/caching/fast_stat_bucket_test.go
- Fast stat bucket implementation
NA
1. Manual - NA
> [Move object] Fast stat bucket implementation

- internal/fs/streaming_writes_local_file_test.go
rename test function so common tests are also run
NA
1. Manual - NA
> rename test function so common tests are also run

- docs/troubleshooting.md
Add troubleshooting guide about implicit dir flag.
NA
1. Manual - NA
> Add troubleshooting guide about implicit dir

- internal/block/block_pool_test.go
review comment from PR: https://github.com/GoogleCloudPlatform/gcsfuse/pull/2860 to rename test function.
NA
1. Manual - NA
> review comment from PR: https://github.com/GoogleCloudPlatform/gcsfuse/pull/2860

- tools/cd_scripts/e2e_test.sh
- tools/integration_tests/local_file/create_file_test.go
- tools/integration_tests/local_file/unlinked_file_test.go
- tools/integration_tests/local_file/write_file_test.go
- tools/integration_tests/run_e2e_tests.sh
- tools/integration_tests/streaming_writes/buffer_size_test.go
- tools/integration_tests/streaming_writes/default_mount_local_file_test.go
- tools/integration_tests/streaming_writes/default_mount_test.go
- tools/integration_tests/streaming_writes/streaming_writes_test.go
- tools/integration_tests/streaming_writes/truncate_file_test.go
Added out of order write testcases
Creating files with same name after delete
NA
1. Manual - NA
> Added new integration test cases for streaming writes flow

- cfg/config.go
- cfg/params.yaml
- cmd/root_test.go
Reverts GoogleCloudPlatform/gcsfuse#2889
> Revert "Turn on the flag for Move object"

- internal/fs/fs.go
- internal/fs/hns_bucket_common_test.go
- internal/fs/hns_bucket_test.go
- internal/fs/zonal_bucket_test.go
Added support of ZB moveObject operation.
NA
1. Manual - Tested
> [Move Object] Support on ZB

- internal/gcsx/multi_range_downloader_wrapper.go
Since we have not added synchronization in the MRD creation logic, to ensure that there are no edge cases, we are updating MRD in MRDWrapper only when it is a valid MRD. 
This takes care of the edge case scenario where a nil MRD could have been used.
b/394728598
> Ensuring MRD in MRDWrapper is always valid

- internal/gcsx/random_reader.go
- internal/monitor/bucket.go
> Testing with recording just readFull

- common/otel_metrics.go
Rename a data member to make it explicit that it's atomic i.e. concurrent-safe.
NA
1. Manual - NA
> Rename data member

- cfg/config.go
- cfg/params.yaml
Turn on the flag for Move object
NA
1. Manual - NA
> Turn on the flag for Move object

- internal/storage/bucket_handle.go
Fixing the missing error handling in RenameFolder
b/397368077
1. Manual - NA
> Fixing the missing error handling in RenameFolder

- docs/troubleshooting.md
As part of onduty bug b/395736039 , adding this troubleshooting steps to help.
> Add Troubleshooting guide for No space left on Device

- tools/integration_tests/monitoring/prom_test.go
* Ports don't quickly become available after use. So, this can lead to
bind errors when one tries to use the same port for multiple tests. Fix
that by using different ports for different tests.
* Use non-HNS bucket when tests are being run in non-HNS mode.
b/391754854
1. Manual - NA
> Use different ports for Prometheus metrics tests

- tools/integration_tests/emulator_tests/proxy_server/main.go
Adding request, response and time elapsed information in proxy server logs. This helps in writing new tests as we can see the requests and response with the retry operation and time it took to complete the request.
NA
1. Manual - NA
> Add request, respone and elapsed time logging in proxy server

- tools/integration_tests/emulator_tests/streaming_writes_failure/common_failure_test.go
Adding pending test from the [review comment](https://github.com/GoogleCloudPlatform/gcsfuse/pull/2988#discussion_r1953951804). 
[b/388720840](http://b/388720840)
> Add streaming writes failure test when file handle is open in readonly mode.

- go.mod
- go.sum
Upgrade fuse module to fetch changes for adding operation ID in error log - https://github.com/jacobsa/fuse/commit/009e36f010a3e5d49d5a7e9cc57f83d82972050d
NA
1. Manual - NA
> Upgrade fuse module 

- tools/integration_tests/stale_handle/setup_test.go
- tools/integration_tests/streaming_writes/default_mount_test.go
- tools/integration_tests/streaming_writes/streaming_writes_test.go
Run all tests for the stale handle and streaming writes package with GRPC and without GRPC flag.
[b/396038740](http://b/396038740)
> Run stale handle and streaming writes package tests with and without GRPC flag.

- go.mod
- go.sum
Fetch latest fuse module with this commit - https://github.com/jacobsa/fuse/commit/219b4762b40e9ef2ebfbe21e96690f6949514315
NA
1. Manual - NA
> Upgrade fuse module - Remove duplicate error logs 

- docs/metrics.md
> Change OpenCensus references to OTel in documentation

- internal/cache/file/downloader/job.go
- internal/fs/inode/file.go
- internal/gcsx/integration_test.go
- internal/gcsx/prefix_bucket.go
- internal/gcsx/prefix_bucket_test.go
- internal/gcsx/random_reader_test.go
- internal/monitor/bucket.go
- internal/ratelimit/throttled_bucket.go
- internal/storage/bucket_handle.go
- internal/storage/bucket_handle_test.go
- internal/storage/caching/fast_stat_bucket.go
- internal/storage/debug_bucket.go
- internal/storage/fake/bucket.go
- internal/storage/fake/testing/bucket_tests.go
- internal/storage/gcs/bucket.go
- internal/storage/mock/testify_mock_bucket.go
- internal/storage/mock_bucket.go
- internal/storage/storageutil/read_object.go
- internal/storage/testify_mock_bucket.go
Since we have replaced newReader method with newReaderWithReadHandle method, removed unused code as a part of this PR.
NA
1. Manual - NA
> cleanup task: removing newReader method (replaced by newReaderWithReadHandle)

- perfmetrics/scripts/testing_on_gke/examples/run-gke-tests.sh
- perfmetrics/scripts/testing_on_gke/examples/workloads_test.json
A minor bug fix that came out of some failures that @ankitaluthra1 was facing (unnecessarily reference to `output gsheet` when that feature hasbn't been merged yet). Other than, this also fixes and error in the log generated in the `=debug` mode in the test tool.
This has a follow-up in #3068 .
NA
1. Manual - NA
> [testing-on-gke] Fixing minor bugs in script

- internal/bufferedwrites/buffered_write_handler.go
- internal/bufferedwrites/buffered_write_handler_test.go
- internal/bufferedwrites/upload_handler.go
- internal/bufferedwrites/upload_handler_test.go
- internal/fs/fs.go
- internal/fs/inode/file.go
- internal/fs/stale_file_handle_common_test.go
- internal/fs/stale_file_handle_local_file_test.go
- internal/fs/stale_file_handle_streaming_writes_common_test.go
- internal/fs/stale_file_handle_streaming_writes_local_file_test.go
- internal/fs/stale_file_handle_streaming_writes_synced_file_test.go
- internal/fs/stale_file_handle_synced_file_test.go
- internal/storage/fake/fake_object_writer.go
* Fix error conversion for streaming writes flow in case of pre-condition errors.
* Add unit tests.
* Refactor existing files.
[b/399256056](http://b/399256056)
> Fix streaming upload error conversion and add unit tests.

- internal/fs/fs.go
- internal/fs/local_file_test.go
- internal/fs/streaming_writes_common_test.go
- internal/fs/streaming_writes_empty_gcs_object_test.go
- internal/fs/streaming_writes_local_file_test.go
- tools/integration_tests/local_file/rename.go
- tools/integration_tests/streaming_writes/rename_file_test.go
We are doing implicit flush for local files with streaming writes configuration to support rename operation.
[b/396029467](http://b/396029467)
> Flush local files with streaming writes for rename operation.

- docs/semantics.md
Adding streaming writes details to semantics doc.
b/396037658
1. Manual - NA
> Update semantics doc for streaming writes

- go.mod
- go.sum
Command used to upgrade: go get $(go list -f '{{if not (or .Main .Indirect)}}{{.Path}}{{end}}' -m all)
b/404140577
Perf:
| Master |  0.25MiB   |  588.0MiB/s  | 1.03MiB/s  |  81.77MiB/s  |  1.29MiB/s   |
|   PR   |  0.25MiB   | 582.94MiB/s  | 1.31MiB/s  |  78.05MiB/s  |  1.23MiB/s   |
| Master | 48.828MiB  | 4230.1MiB/s  | 85.0MiB/s  | 1580.27MiB/s |  86.15MiB/s  |
|   PR   | 48.828MiB  | 4245.92MiB/s | 85.13MiB/s | 1584.92MiB/s |  87.19MiB/s  |
|        | …
> Update direct deps

- perfmetrics/scripts/testing_on_gke/examples/dlio/dlio_workload.py
- perfmetrics/scripts/testing_on_gke/examples/dlio/parse_logs.py
- perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
- perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/values.yaml
- perfmetrics/scripts/testing_on_gke/examples/fio/fio_workload.py
- perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
- perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/values.yaml
- perfmetrics/scripts/testing_on_gke/examples/fio/parse_logs.py
- perfmetrics/scripts/testing_on_gke/examples/utils/parse_logs_common.py
This is an internal code cleanup.
NA
1. Manual - NA
> [testing-on-gke] remove obsolete unused gcsfuse scenarios

- perfmetrics/scripts/testing_on_gke/examples/dlio/unet3d-loading-test/templates/dlio-tester.yaml
- perfmetrics/scripts/testing_on_gke/examples/fio/loading-test/templates/fio-tester.yaml
[b/404100039](http://b/404100039)
1. Manual - NA
> Increase fio/dlio pod timeout to 15k seconds

- internal/bufferedwrites/upload_handler.go
- internal/bufferedwrites/upload_handler_test.go
Integrate flush writer with upload handler
b/404999845
1. Manual - NA
> Integrate flush writer with upload handler

- internal/bufferedwrites/buffered_write_handler.go
- internal/bufferedwrites/buffered_write_handler_test.go
Integrate buffered write handler with writer.flush
b/405337871
1. Manual - NA
> Integrate buffered write handler with writer.flush

- tools/mount_gcsfuse/main.go
- tools/mount_gcsfuse/main_test.go
> Clean up the remnants of config-cli-parity

- tools/integration_tests/run_e2e_tests.sh
[b/407892771](http://b/407892771)
1. Manual - NA
> fix package pass/fail log in run_e2e_tests.sh

- docs/troubleshooting.md
This PR adds troubleshooting steps for permission denied while accessing GCSFuse mounted file system.
https://b.corp.google.com/issues/408353709
1. Manual - NA
> Add troubleshooting steps for Permission Denied while accessing files or directories

- internal/cache/util/util.go
- internal/gcsx/file_cache_reader.go
- internal/gcsx/file_cache_reader_test.go
- internal/gcsx/random_reader_test.go
- internal/gcsx/reader.go
- Initialize file cache reader
[b/409440931](http://b/409440931)
1. Manual - NA
> [Random Reader Refactoring] Initialize file cache reader

- cfg/config.go
- cfg/params.yaml
- cmd/root_test.go
Delay enabling this feature and release in conjunction with other features.
b/402273935
> Make default value of disable-autoconfig false

- perfmetrics/scripts/ml_tests/checkpoint/Jax/run_checkpoints.sh
add zonal buckets to periodic/presubmit checkpoint tests
b/411002074
1. Manual - NA
NA
> add zonal buckets to periodic/presubmit checkpoint tests

- docs/troubleshooting.md
b/416747045
Doc Change. No Test Changes.
> Add Parallel Downloads Default ON CPU troubleshooting guidance.

- internal/fs/local_file_test.go
Refactored the local file test package to leverage stretchr/testify. This enables individual execution of failed fs_tests, significantly streamlining the debugging process by reducing the need to sift through extensive GCSFuse logs.
b/417398022
1. Manual - NA
NA
> refactor local file test package to use stretchr testify

- perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_bench/build.sh
- perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmark/build.sh
- perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmark/continous.cfg
- Create build script to execute micro benchmark tests.
- Added cfg file to automatically trigger test through kokoro.
[b/418106708](https://b.corp.google.com/issues/418106708)
1. Manual - NA
> Create build script for micro benchmark

- internal/storage/bucket_handle.go
Integration of takeover API by implementing `createAppendableObjectWriter` in bucket_handle.go . Implementation for other buckets in upcoming PRs.
[b/417083182](b/417083182)
1. Manual - NA
2. Unit tests - Not feasible as requires either extending fake server's functionality to support grpc client , and mocking not possible due to nested and conditional invocation.
> implementing createAppendableObjectWriter method in bucket_handle.go

- internal/gcsx/client_readers/gcs_reader_test.go
- Added more unit tests
1. Test ReadAt InvalidOffset
2. Test ReadAt PropagatesCancellation
3. Test ReadInfo WithInvalidInput
4. Test ReadInfo Sequential
5. Test ReadInfo Random
- Code coverage (97.1%)
[b/418691408](https://b.corp.google.com/issues/418691408)
1. Manual - NA
6. Unit tests - NA
7. Integration tests - NA
> [Random Reader Refactoring] GCS Reader implementation - 2

- .github/workflows/shadow.yml
> Update shadow reviewer workflow to skip on draft

- internal/gcsx/file_cache_reader.go
- internal/gcsx/mock_reader.go
- internal/gcsx/read_manager/read_manager_test.go
- Adding more unit tests
- Implementing checkInvariant method for file cache reader.
- 96% code coverage.
- Adding mock reader.
[b/420337383](https://b.corp.google.com/issues/420337383)
1. Manual - NA
> [Random Reader Refactoring] Read manager implementation - 2

- common/noop_metrics.go
- common/otel_metrics.go
- common/telemetry.go
- common/telemetry_test.go
- internal/fs/wrappers/monitoring.go
- internal/gcsx/file_cache_reader.go
- internal/monitor/bucket.go
- internal/util/util.go
- tools/integration_tests/monitoring/prom_test.go
Reduce metric CPU usage from ~10% for single threaded reads to ~4% and memory allocation from 10% to ~1%.
The `metric.WithAttributes` method is inefficient and is not recommended for performance-sensitive scenarios. This PR moves it to use `metric.WithAttributeSet` method that takes an attribute-set as input and doesn't have those performance concerns. To optimize it further, we use a cache that takes attribute-keys as input, and returns a corresponding attribute.Set object. This reduces memory-allocations by creating an attribute.Set object just once.
There are more improvements that could be performed and will be taken up in the subsequent PRs.
Before fix: http://shortn/_zNJRaWzRB4
After fix: http://shortn/_nPnS1bb5Vy
b/424403628
Perf:
| Branch | File Size  |   Read BW    |  Write BW  | …
> Reduce CPU and memory usage incurred by metrics

- internal/gcsx/client_readers/gcs_reader.go
Update seek after existing reader read fail as we did in [random reader](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/gcsx/random_reader.go#L366)
1. Manual - NA
> [RRR] update seek after existing reader read fail

- README.md
- docs/semantics.md
- docs/troubleshooting.md
Streaming writes default documentation changes.
b/415727461
1. Manual - NA
NA
> v3 documentation changes - Streaming writes

- cmd/mount.go
- go.mod
- go.sum
Update jacobsa fuse version in go.mod
1. Manual - NA
> Update jacobsa fuse version in go.mod

- perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/build.sh
Fix kokoro failure in micro benchmark script. 
1. Manual - NA
> ci: Fix kokoro failure in micro benchmark script

- go.mod
- go.sum
This PR updates the github.com/jacobsa/fuse dependency to [commit](https://github.com/jacobsa/fuse/commit/8f8de1982c060137a62236637b72c903af46c3e6) 
1. Manual - NA
> chore(deps): Update jacobsa fuse version

- .github/pull_request_template.md
Show the available PR types to serve as a guide while creating PRs.
1. Manual - NA
> chore(PR Template): Update pull_request_template.md

- internal/bufferedread/buffered_reader.go
- internal/bufferedread/buffered_reader_test.go
This PR introduces the foundational structs (BufferedReadConfig, BufferedReader) for creating a new buffered reader.
Future logic and tests will be added in subsequent PRs.
https://b.corp.google.com/issues/430755847
https://b.corp.google.com/issues/432169852
1. Manual - NA
> feat(bufferedread): Add initial structs for buffered reader

- docs/semantics.md
Add a note about how GCSFuse supports symlinks that point to paths external to the mount-point.
b/432697752
1. Manual - NA
No
> docs(semantics): Supporting symlinks to external paths

- cmd/legacy_main.go
- internal/fs/foreign_modifications_test.go
- internal/fs/fs.go
- internal/fs/fs_test.go
- internal/fs/handle/dir_handle_test.go
- internal/fs/local_modifications_test.go
- internal/fs/read_cache_test.go
- internal/storage/bucket_handle.go
- internal/storage/bucket_handle_test.go
- internal/storage/fake/testing/bucket_tests.go
- internal/storage/storageutil/client_test.go
- internal/util/sizeof.go
- tools/integration_tests/gzip/gzip_test.go
- tools/integration_tests/gzip/read_gzip_test.go
- tools/integration_tests/kernel_list_cache/disabled_kernel_list_cache_test.go
- tools/integration_tests/kernel_list_cache/finite_kernel_list_cache_test.go
- tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_delete_dir_test.go
- tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
- tools/integration_tests/kernel_list_cache/setup_test.go
- tools/integration_tests/read_cache/helpers_test.go
- tools/integration_tests/read_cache/remount_test.go
- tools/integration_tests/readdirplus/readdirplus_with_dentry_cache_test.go
- tools/integration_tests/readdirplus/readdirplus_without_dentry_cache_test.go
- tools/integration_tests/readdirplus/setup_test.go
- tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
Removing unused code as suggested by golangci-lint.
1. Manual - Manually verified mounting and few operations
2. Unit tests - github actions will take care of this
3. Integration tests -  github actions will take care of this
> style: removing unused code part -1

- perfmetrics/scripts/micro_benchmarks/helper.py
- perfmetrics/scripts/micro_benchmarks/read_single_thread.py
- perfmetrics/scripts/micro_benchmarks/write_single_thread.py
- Correction from Mbps to MB/s
[b/433625837](https://b.corp.google.com/issues/433625837)
1. Manual - NA
> ci: Correction from Mbps to MB/s

- internal/fs/handle/dir_handle_test.go
- internal/fs/handle/file_test.go
- internal/fs/inode/dir_test.go
- internal/fs/inode/file_streaming_writes_test.go
- internal/fs/stale_file_handle_common_test.go
- internal/fs/stale_file_handle_streaming_writes_common_test.go
- internal/fs/stale_file_handle_streaming_writes_local_file_test.go
- internal/fs/stale_file_handle_streaming_writes_synced_file_test.go
- internal/fs/stale_file_handle_synced_file_test.go
- internal/gcsx/file_cache_reader_test.go
- internal/gcsx/inactive_timeout_reader_test.go
- internal/storage/caching/integration_test.go
- tools/integration_tests/read_cache/cache_file_for_exclude_regex_test.go
- tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
- tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
- tools/integration_tests/read_cache/disabled_cache_ttl_test.go
- tools/integration_tests/read_cache/helpers_test.go
- tools/integration_tests/read_cache/job_chunk_test.go
- tools/integration_tests/read_cache/local_modification_test.go
- tools/integration_tests/read_cache/range_read_test.go
- tools/integration_tests/read_cache/read_only_test.go
- tools/integration_tests/read_cache/remount_test.go
- tools/integration_tests/read_cache/setup_test.go
- tools/integration_tests/read_cache/small_cache_ttl_test.go
- tools/package_gcsfuse/build.go
- tools/package_gcsfuse/main.go
- tools/package_gcsfuse/package.go
Removing unused code as suggested by golangci-lint.
1. Manual - Manually verified mounting and few operations
2. Unit tests - github actions will take care of this
3. Integration tests - github actions will take care of this
> style: removing unused code - part2

- .github/workflows/ci.yml
- cfg/optimize.go
- cfg/optimize_test.go
- cmd/root.go
- internal/fs/inode/dir_test.go
removing the unused code as suggested by lint. Also added the lint check as part of github actions
2. Unit tests - Will run as part of  PR checks
3. Integration tests -Will run as part of  PR checks
> style: remove unused code - part3 and adding lint check

- optimizedmetrics/otel_metrics.go
- optimizedmetrics/otel_metrics_test.go
- tools/metrics-gen/main.go
- tools/metrics-gen/otel_metrics.tpl
- tools/metrics-gen/otel_metrics_test.tpl
Code-generate tests for metrics.
b/435358875
1. Manual - NA
No
> perf(metrics): Code-generate tests for metrics.

- internal/block/prefetch_block.go
- internal/bufferedread/buffered_reader.go
- internal/bufferedread/buffered_reader_test.go
- internal/bufferedread/download_task.go
- Optimizing trace logs to not print redundant of un-important messages.
- Adding more contexts wherever required.
b/435866378
1. Manual - Tested.
> style(buffered-reader): Improving log and error message

- docs/troubleshooting.md
This PR adds information regarding ESTALE error in troubleshooting guide.
https://b.corp.google.com/issues/437132043
1. Manual - NA
> docs: Add information regarding ESTALE error in troubleshooting guide

- internal/storage/storage_handle.go
- internal/storage/storageutil/control_client.go
- internal/storage/storageutil/control_client_test.go
Remove unused method parameter
N/A
1. Manual - NA
No
> style(control client): Remove unused method parameter

- internal/gcsx/inactive_timeout_reader.go
Downgrade info log to trace.
b/441129643
1. Manual - NA
3. Integration tests - Covered by existing tests.
No
> fix(log level): Downgrade info log to trace.

- go.mod
- go.sum
Bringing jacobsa/fuse changes to fix `false unmount success` issue. Ref: https://github.com/jacobsa/fuse/pull/182
| Master |  0.25MiB   | 560.49MiB/s  | 1.21MiB/s  |  76.93MiB/s  |  1.26MiB/s   |
|   PR   |  0.25MiB   | 549.93MiB/s  | 1.21MiB/s  |  75.9MiB/s   |  1.09MiB/s   |
| Master | 48.828MiB  | 2576.42MiB/s | 80.87MiB/s | 1441.35MiB/s |  80.36MiB/s  |
|   PR   | 48.828MiB  | 2893.17MiB/s | 80.91MiB/s | 1348.24MiB/s |  81.6MiB/s   |
|        |            | …
> fix(unmount): Fixing false unmount success bug

- go.mod
- go.sum
Upgrade direct dependencies.
Command: `go get $(go list -f '{{if not (or .Main .Indirect)}}{{.Path}}{{end}}' -m all)`
Perf:
| Master |  0.25MiB   |  552.3MiB/s  | 1.29MiB/s  |  78.3MiB/s   |  1.25MiB/s   |
|   PR   |  0.25MiB   | 574.75MiB/s  | 1.23MiB/s  |  78.88MiB/s  |  1.25MiB/s   |
| Master | 48.828MiB  | 3987.8MiB/s  | 81.72MiB/s | 1532.67MiB/s |  83.47MiB/s  |
|   PR   | 48.828MiB  | 3846.19MiB/s | 86.27MiB/s | 1561.08MiB/s |  86.28MiB/s  |
| Master | …
> chore(dep upgrade): Dependency upgrades

- metrics/otel_metrics.go
- tools/metrics-gen/otel_metrics.tpl
Cosmetic changes: Remove unnecessary whitespaces in generated code.
b/446663088
2. Unit tests - No - covered by existing tests.
No
> style(metrics): Remove unnecessary whitespaces

- cmd/legacy_main.go
- go.mod
- go.sum
- internal/storage/storageutil/client.go
- internal/storage/storageutil/client_test.go
Implement DNS caching in GCSFuse
b/446170703
> feat(dnscaching): Implement DNS caching

- tools/cd_scripts/e2e_test.sh
Fixes for 
- b/443039033 targeting rhel/rocky-linux-8
- b/447064201 targeting rhel/centos/rocky-linux-9s
- b/447059258 targeting rhel/centos/rocky-linux-10s
1. Manual - yes
> refactor(cd): fixes in cd script for robustness

- docs/troubleshooting.md
Update streaming writes troubleshooting documentation.
Follow up of PR #3832 
b/438404050
1. Manual - NA
> docs: Update streaming writes troubleshooting documentation.
