flags.go, main.go
New output:
```
(master)jjg@jjg1:~/projects/gcsfuse$ go build . && ./gcsfuse --help
NAME:
gcsfuse - Mount a GCS bucket locally
USAGE:
gcsfuse [global options] bucket mountpoint
VERSION:
0.1.0
GLOBAL OPTIONS:
--dir-mode, -d               Permissions bits for directories. (default: 0755)
--file-mode, -f              Permission bits for files (default: 0644)
--gcs-chunk-size             Max chunk size for loading GCS objects. (default: 16777216)
--gid                        GID owner of all inodes.
--implicit-dirs              Implicitly define directories based on content. Seedocs/semantics.md
--limit-bytes-per-sec        Bandwidth limit for reading data, measured over a 30-second window. (use -1 for no limit) (default: -1)
--limit-ops-per-sec          Operations per second limit, measured …
```
=> Fixes #89 - Make help text prettier

docs/mounting.md, tools/mount_gcsfuse/main.go
This adds basic support for `key_file` fstab option, which can be used for mounting with specific credentials (like for cross-project buckets and VMs).
It's quite useful, because `mount.gcsfuse` doesn't respect `GOOGLE_APPLICATION_CREDENTIALS` env var, but only `gcsfuse` does. But even if it did, it would be quite hacky to make it work under systems like Puppet, for example.
The option simplifies this by a lot:
```
my-bucket /mount/point gcsfuse rw,noauto,user,key_file=/path/to/key.json
```
it re-uses already existing `--key-file` argument for `gcsfuse`.
=> Support for key_file fstab option

docs/mounting.md, tools/mount_gcsfuse/main.go
Allows functionality to pass temp_dir as a mount option in fstab
=> Update main.go to support passing in temp_dir

docs/installing.md
The step "yum update" was missing.
Without it the system won't be able to find the package gcsfuse, because it has yet to initialize the repo.
=> Added another CentOS setup instruction

README.md
Add JSON API to Prerequisites section. If the API is not enabled, gcsfuse displays an error about bad credentials.
setUpBucket: OpenBucket: Bad credentials for bucket "xxxxxxx".  
Check the bucket name and your credentials.
Whereas gsutil displays more meaningful error:
Access Not Configured. Please go to the Google Cloud Platform Console (https://cloud.google.com/console#/project) for your project, select APIs and Auth and enable the Google Cloud Storage JSON API.
=> Add JSON API prerequisite

main.go, mount.go
Include timestamp in the debug logs
The need for this was brought up in issue #262
Tested:
no
=> Include timestamp in the debug logs.

bucket.go, flags.go
These changes add support for requester pays buckets. Some of the changes are in a dependency (vendor/github.com/jacobsa/gcloud/gcs), and I'm not sure whether those changes should be first merged into the vendor repo.
=> Adds support for requester pays buckets.

docs/semantics.md
For at-least the past two years, GCS bucket listing has been strongly consistent [1, 2]. Thus update the semantics in-light of this fact.
[1] https://cloud.google.com/blog/products/gcp/how-google-cloud-storage-offers-strongly-consistent-object-listing-thanks-to-spanner
[2] https://cloud.google.com/storage/docs/consistency
=> Update semantics.md now that GCS bucket listing is strongly consistent

internal/fs/dir_handle.go, internal/fs/handle/file.go, internal/fs/inode/dir.go, internal/fs/inode/file.go, internal/fs/inode/inode.go, internal/fs/inode/symlink.go, internal/perms/perms.go
Every exported function in a program should have a doc comment. The first sentence should be a summary that starts with the name being declared.
From [effective go](https://golang.org/doc/effective_go.html#commentary).
I generated this with [CodeLingo](https://codelingo.io) and I'm keen to get some feedback, _but this is automated so feel free to close it and just say "**opt out**" to opt out of future CodeLingo outreach PRs._
=> Fix function comments based on best practices from Effective Go

main.go
On isolated hosts without Internet or direct GCS access, it's possible to access the GCP endpoints through a HTTP proxy server; Go's HTTP libraries respect the http_proxy environment variable.
(Using a proxy server configured as per https://cloud.google.com/vpc/docs/special-configurations#proxyvm)
> [root@localhost mfielding]# export http_proxy=http://10.1.1.1:3128
> [root@localhost mfielding]# gcsfuse --foreground --key-file $PWD/gcs.json gcs-bucket /mnt/gcs &
> [1] 17589
> [root@localhost mfielding]# Using mount point: /mnt/gcs
> Opening GCS connection...
> 
> WARNING: gcsfuse invoked as root. This will cause all files to be owned by
> root. If this is not what you intended, invoke gcsfuse as the user that will
> be interacting with the file system.
> 
> Opening bucket...
> Mounting …
=> Preserve http_proxy environment variable when daemonizing

README.md, bucket.go, docs/semantics.md, flags.go, flags_test.go
PR to go alongside #350. To quote that original issue:
> Hi folks,
> 
> We've been having some issues with a media manager which browses our gcsfuse-backed folders. The media manager was working absolutely fine until recently, and then at some point it got super slow.
> 
> This turned out to be due to the stat cache's capacity being 4096
> 
> https://github.com/GoogleCloudPlatform/gcsfuse/blob/6ab0a79f97b7481b23c3724cd0c4b323f0627d69/bucket.go#L127-L135
> 
> And with our project, one of our folder's has ballooned from ~3500 files to ~4100 files (using the folder as a dumping ground is a separate problem that we'll be addressing internally). This means that a `ls` operation on that folder takes forever because it blows the stat cache:
> 
> * The `ListObjects` GCS call (unless I am …
=> Make stat cache capacity configurable

tools/mount_gcsfuse/main.go
Allow passing debugging options like `--debug_gcs` through `mount_gcsfuse` as mount options (e.g., `mount -t gcsfuse -o debug_gcs ...`).
This may be useful when debugging `gcsfuse` mounts from non-interactive sessions like systemd, autofs, or simply `/etc/fstab`.
=> Allow passing debugging options through `mount_gcsfuse`

docs/mounting.md, tools/mount_gcsfuse/main.go
This PR allows requester pays buckets to be mounted with an /etc/fstab entry.
=> Adds billing_project to supported fstab options.

docs/mounting.md
On a GCE centos VM, auto-mounting failed as it tries to mount before the network is ready. Adding systemd.requires=network-online.target solves this issue.
=> Add options for successful auto-mounting

main.go, tools/mount_gcsfuse/main.go
Added http_proxy to the mount.gcsfuse helper as it was done previously for the cli part (v.0.29.0), Closes #388
=> http_proxy support for mount_gcsfuse

vendor/github.com/jacobsa/gcloud/gcs/debug_bucket.go
The prefix of the ListObjectRequest is printed to help debug.
=> Print critical request info in GCS ListObject calls

internal/fs/inode/dir.go, internal/fs/inode/type_cache.go
Implicit dirs are the gcs directories that don't have an object to back up.
The dir inodes used to memoize the subdirs, but not distinguishing the implicit subdirs. When it looked up subdir children, it had to issue an gcs ListObject api call to tell if the child was implicit or not, which was very expensive. This PR allows the dir inodes to cache the dirs as implicit dirs, to avoid such expensive api calls.
As a result, the latency of `ls a/b/c/d/` of 1024 files could be reduced from 10 min to 1.5 seconds, due to 4096 api calls avoided.
=> Cache implicit dirs to reduce ls latency

flags.go, main.go, tools/util/flaky_transport.go
Transient backend errors (e.g. HTTP 503) can interrupt a large scale
file I/O, causing the user script to fail: #407 #408 #410 
Retry is enabled to avoid that.
TEST
Add flaky_transport.go as test util. 
Manually swap `http.DefaultTransport` with `NewFlakyTransport(0.5)`,
and see the flakiness does not lead to any file I/O failure from the
user's perspective.
=> Retry for transient backend errors

flags.go, internal/fs/fs.go, main.go
Since the wildcard `*` is confusing and easily misued with local shell,
it's removed from the CLI. If a bucket name is not specified, the
gcsfuse will mount all accessible buckets as subdirectories.
Before:
```
gcsfuse '*' ~/mnt/gcs
```
After:
```
gcsfuse ~/mnt/gcs
```
=> Update the CLI for mount-all-buckets

flags.go, internal/fs/fs.go, internal/fs/inode/file.go, internal/fs/inode/file_test.go, mount.go
Gcsfuse used have local temp files cached and synced for writes.
However, as the local SSD speeds improve, we may get better performance
reading from local cached files than from GCS backend.
Thus, this commit adds an option `--local-file-cache` that enables
reading from temp files cached at the directory specified by
`--temp-dir`.
Currently, the performance still needs to be optimized. The files are
downloaded in a blocking way to the cache when their inodes are created,
which can be very slow.
=> New option to cache files locally for reads

internal/gcsx/temp_file.go
Previously, when the temp file is created, it has to be loaded with the
source data in full extent. When `--local-file-cache` is specified, this
can be excessively slow and expensive, as all the files that are
detected will be downloaded, and operations will be blocked by the those
expensive downloads.
This commit eliminates the unnecessary downloads. The temp file will
only be filled with source data when it's being used.
TEST
- Run the unit tests in temp_file_tests.go.
- Run end to end tests with real gcs data.
=> Load temp files on demand

internal/fs/fs_test.go, internal/fs/inode/base_dir.go, internal/fs/inode/base_dir_test.go, internal/gcsx/bucket_manager.go
When the GCS bucket name is omitted, the root directory contains
subdirectories that represent buckets. Currently, reading the root
directory will end up in an error. This commit changes the behavior by
providing a list of bucket names for such operation.
The implementation uses the [official GCS client library](
https://godoc.org/cloud.google.com/go/storage). So, for it to be built, 
you may need to call `go get` to install the dependencies at GOPATH.
For this API to work, 
- It must know the project id, which can be passed  in as 
`--billing-project=...`.
- The user or the service account must have the permission 
`storage.buckets.list`.
TEST
The test is done by listing the all buckets on a GCE instance.
=> Make root directory containing buckets readable

flags.go, main.go
The default protocol used by Go's http transport is HTTP/2. However,
I found HTTP/1.1 with multiple TCP connections can perform better
compared to HTTP/2 with TCP multiplexing.
This commit adds new flags `--disable-http2` and `--max-conns-per-host`.
It disables HTTP/2 and sets MaxConnsPerHost option for HTTP/1.1, which
can potentially improve read throughput by 2x.
=> Tune TCP connections for HTTP/1.1

internal/fs/inode/file.go, internal/gcsx/syncer_test.go, internal/gcsx/temp_file.go, internal/gcsx/temp_file_test.go
There were several issues with the previous temp file implementation.
1. The temp file did not close the http connection. 
2. The temp file did not handle errors from loading the source file.
3. The temp file reads the entire file before handling any read request from fuse. 
They're all fixed in this PR.
1. The temp file now closes the http connection once the source file is completely fetched.
2. The temp file fails the fuse request upon errors from loading the source file.
3. The temp file reads a reasonable chunk of the source file in order to serve the read request from fuse.
=> Fix bugs in temp file

flags.go, internal/gcsx/bucket_manager.go, internal/gcsx/monitoring_bucket.go, main.go
This PR adds 4 prometheus metrics:
- number of GCS requests by type,
- number of bytes read,
- number of readers created,
- number of readers closed.
They can be helpful for debugging performance issues as well as tracking the progress of some client application relying on gcsfuse.
TEST
Acquire the stats from localhost:8086 while running gcsfuse:
```
gcsfuse_bytes_read{bucket="tf-ent-dev",object="datasets/imagenet/combined/train-00001-of-01024"} 1.33300224e+08
gcsfuse_gcs_requests{bucket="tf-ent-dev",method="ListObjects"} 10
gcsfuse_gcs_requests{bucket="tf-ent-dev",method="NewReader"} 1
gcsfuse_gcs_requests{bucket="tf-ent-dev",method="StatObject"} 15
gcsfuse_object_readers_closed 1
gcsfuse_object_readers_created 1
```
=> Add prometheus metrics for monitoring

benchmarks/concurrent_read/main.go, benchmarks/concurrent_read/readers.go, benchmarks/concurrent_read/transport.go
This benchmark can test the read throughput of different reader implementation as well as the underlying protocol config. A few examples on GCE n1-highmem-8:
1. HTTP/1.1 100 Conns Per Host +  verdor implementation: 1456.8 MB/s
2. HTTP/2 + vendor implementation: 294.0 MB/s
3. HTTP/1.1 100 Conns Per Host + official implementation: 309.9 MB/s
4. HTTP/2 + official implementation:  273.0 MB/s
Here, "vendor implementation" refers to github.com/jacobsa/gcloud/gcs/read.go, whereas "official implementation" refers to cloud.google/com/go/storage/reader.go.
=> Benchmarking different reader implementations

internal/fs/fs.go, internal/fs/monitoring_fs.go, internal/gcsx/monitoring_bucket.go
Internally, gcsfuse has a "FileSystem" struct to handle fuse requests. This PR modifies each method of the FileSystem with these monitoring metrics:
- the number of each requests,
- the number of errors,
- the latency of ReadFile and OpenFile requests.
These metrics will be very helpful for debugging performance issues.
=> Monitor the fuse requests

internal/fs/fs.go, mount.go
Mention the bucket name or "all accessible buckets" when printing the
message for setting up buckets.
=> Improve logging message for mounted bucket name

flags.go, internal/logfile/logfile.go, main.go
In some applications, the log messages should be printed to a log file with a json format that can be parsed by the fluentd-based Stackdriver agent.
Currently, it's very hard to make all log messages that way. So, this PR starts with the most important messages, ie. the "status" messages printed at mounting time. 
This PR adds an option "--log-file" to specify a log file containing all the status messages in the fluentd json format.
It's tested in both foreground and background running mode. The log file now has these logs:
```
{"name":"root","levelname":"INFO","severity":"INFO","message":"Opening GCS connection...\n","timestampSeconds":1599780949,"timestampNanos":826263000}
{"name":"root","levelname":"INFO","severity":"INFO","message":"Mounting file …
```
=> Print status log messages to a log file with json format

tools/build_gcsfuse/main.go, tools/integration_tests/main_test.go
The integration tests can't be built due to the upgrade of Go.
```
> go test ./tools/integration_tests/
2020/08/28 14:34:14 Building build_gcsfuse at /tmp/gcsfuse_integration_tests718659205/build_gcsfuse
2020/08/28 14:34:14 buildGcsfuse: buildBuildGcsfuse: go build build_gcsfuse: exit status 1
Output:
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
FAIL	github.com/googlecloudplatform/gcsfuse/tools/integration_tests	0.091s
FAIL
```
This is fixed by adding necessary environment variables:
- PATH,
- GOROOT,
- GOCACHE.
Now, the tests can be run.
=> Fix the build of integration tests

README.md
Change the URL from https://console.developers.google.com
to https://console.cloud.google.com.
=> [Documentation] Replace URL for Google Developers Console

tools/integration_tests/gcsfuse_test.go
This fixes all the tests.
```
> go test ./...                                                                                                                                                                                                                                                                                     
ok  	github.com/googlecloudplatform/gcsfuse	(cached)
?   	github.com/googlecloudplatform/gcsfuse/benchmarks/concurrent_read	[no test files]
?   	github.com/googlecloudplatform/gcsfuse/benchmarks/internal/format	[no test files]
ok  	github.com/googlecloudplatform/gcsfuse/benchmarks/internal/percentile	(cached)
?   	github.com/googlecloudplatform/gcsfuse/benchmarks/read_full_file	[no test files]
?   	github.com/googlecloudplatform/gcsfuse/benchmarks/read_within_file	[no …
```
=> Fix a broken test caused by API change

.travis.yml
The golang version should updated from `1.9` from 2017 to `1.15.2` the latest.
=> Update golang version in travis.yml for CI

internal/fs/fs.go
Currently, there are two ways to mount gcsfuse:
```
gcsfuse foo /gcs 
gcsfuse /gcs 
```
However, the 2nd way can't used by the [kubernetes CSI driver](https://github.com/ofek/csi-gcs), which calls linux `mount` to mount gcsfuse:
```
mount -t gcsfuse foo /gcs
mount -t gcsfuse /gcs
```
So, this PR adds a placeholder bucket name for "all buckets" -- "_". When the bucket name is "_", it means "all buckets". Then, we can mount all buckets with gcsfuse this way in kubernetes:
```
mount -t gcsfuse _ /gcs
```
=> Use _ to represent all buckets in CLI

tools/mount_gcsfuse/main.go
The tool `mount.gcsfuse` is provided to be used with `mount(8)`. Its options are different from gcsfuse. 
This PR syncs the options between the 2 executables.
=> Fix mount.gcsfuse options

internal/auth/auth.go, main.go
Currently, there are 2 ways of creating TokenSource in auth.go. They specify the context individually, which is duplicate code.
This PR consolidates that by specifying the context at the GetTokenSource function.
=> Refactor authentication code to specify context in TokenSource

internal/gcsx/bucket_manager.go, internal/gcsx/connection.go, main.go, mount.go
Fix #471 where the `storage.NewClient` did not get the `TokenSource` backed by the key-file.
=> Fix authentication failure with key-file specified but not used

docs/installing.md
Updated prerequisites of Golang version to 1.13.
From these changes as below, Duration.Milliseconds method came into use. This method was added from go 1.13.
https://github.com/GoogleCloudPlatform/gcsfuse/commit/0bb4b043e144dcd02479fbb1488afed207478c9f#diff-d3ee08e42116032bd6394fd75495bfaa265bef1c6855762d568a7cff0342b1a3R84
https://github.com/GoogleCloudPlatform/gcsfuse/commit/3e07ccb961ef882bc11a885c61ed17af7df6c965#diff-2487b52744eeda784a0d378437ccf3830d88ddfeac76f1ef8fd5d1c419507396R104
https://github.com/golang/go/issues/28564
https://golang.org/pkg/time/#Duration.Milliseconds
So gcsfuse cannot be started less than go 1.13.
Docker Image: `golang:1.12.13-alpine3.10` 
```
src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/monitoring_bucket.go:108:38: time.Since(start).Milliseconds …
```
=> Fix installing.md for updating Golang version.

flags.go, internal/auth/auth.go, internal/auth/proxy.go, main.go, tools/mount_gcsfuse/main.go
Currently, there are 2 ways of authentication. 
1. Specify a `key-file`, and gcsfuse uses the key file to authenticate. 
2. Specify nothing, and gcsfuse uses the default method to authenticate. 
Now, we add the 3rd way: `--token-url`. With this option, gcsfuse will read the access token from this url. This basically delegates the authentication process to an external endpoint. 
In a typical case, the external endpoint will be a sidecar container in a Kubernetes pod, and gcsfuse will run in the main container.
=> Fetch access tokens from a token url specified in flag

docs/mounting.md
Change 'systemd.requires' to 'x-systemd.requires' as per the https://www.freedesktop.org/software/systemd/man/systemd.mount.html manpage
=> Fix a typo in the /etc/fstab line

docs/installing.md
Homebrew Cask installation has changed. Instead of `brew cask install` it's now `brew install --cask`. I've updated the documentation to reflect this change.
=> Updated homebrew installation documentation

internal/perf/cpu.go, internal/perf/memory.go, main.go
1. Use timestamp in pprof files to avoid overwriting the same file.
2. Print the heap allocation right before memory profiling.
3. Move the code from main.go to its own package.
=> Profiling improvements

.travis.yml, internal/gcsx/temp_file.go, tools/integration_tests/main_test.go
- Fix minor issues in the failed test
-  Use only modern (supported) go versions in TravisCI
=> Make CI green and update TravisCI go versions with supported only

docs/mounting.md
I had to execute `gcloud auth application-default login` per https://github.com/GoogleCloudPlatform/gcsfuse/issues/320#issuecomment-698284734 to use the right credentials. Otherwise, I receive the following error after executing gcloud auth login:
`daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: fs.NewServer: SetUpBucket: OpenBucket: Bad credentials for bucket "bucket******_hil". Check the bucket name and your credentials.
`
=> replace with gcloud auth application-default login

internal/fs/inode/symlink.go
This mimics the file logic and avoids nonsense values.  Found via
pjdfstests.
=> Set symlink atime and ctime to mtime

tools/mount_gcsfuse/find.go
Tried gcsfuse with nixos and since the paths in nixos are very different it failed to find the executables. I just added the appropriate paths for nixos to findFuserMount and findGcsfuse.
=> Add nixos paths to findFusermount and findGcsfuse

flags.go, go.mod, go.sum, internal/gcsx/connection.go, main.go, vendor/github.com/jacobsa/gcloud/gcs/bucket.go, vendor/github.com/jacobsa/gcloud/gcs/compose_objects.go, vendor/github.com/jacobsa/gcloud/gcs/conn.go, vendor/github.com/jacobsa/gcloud/gcs/copy_object.go, vendor/github.com/jacobsa/gcloud/gcs/create_object.go, vendor/github.com/jacobsa/gcloud/gcs/read.go, vendor/github.com/jacobsa/gcloud/gcs/update_object.go, vendor/modules.txt
This allows use of other implementations like fake-gcs-server.  Setting a
non-Google endpoint disables OAuth.
=> Allow configuring non-Google endpoint

main.go
One character clarification. Just because when you read it, it doesn't make sense, so you re-read it, and realize it's a typo, and then go follow the code...
=> clarify https_proxy precedence in commentary

README.md
Thanks for an amazing tool! 
During some performance testing at NYT, I noticed that the README mentions a default 5 req/s GCS rate limit, but the [flags.go](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/flags.go#L166) looks like it sets `-1` by default.
This PR updates the README to indicate that both rate-limit and bandwidth are unlimited by default.
=> Update rate-limit docs to match default flag values

mount.go
This allows identifying mounts as "fuse.gcsfuse" instead of only
"fuse" on Linux.  This is useful for pjdfstest so it can exclude tests
that are not supported.  References #590.
=> Set subtype to gcsfuse

internal/fs/fs.go
This allows pjdfstest rename/20.t to pass.  References
GoogleCloudPlatform/gcsfuse#590.
=> Do not allow renaming into a non-empty directory

internal/fs/fs.go
=> Return ENOTSUP when creating named pipes or sockets

internal/contentcache/contentcache.go, internal/gcsx/temp_file.go
We add metadata and file support in memory for the cache.  We add the in memory map in contentcache.go and create supporting structs and modifications to support metadata in gcsx.TempFile.
This change should not impact or break any unit tests: run go test ./... in the gcsfuse directory and all tests should continue to pass.
=> Add cache and metadata support for on disk cache

internal/fs/fs.go, internal/fs/local_modifications_test.go
Redo #597. Required for #590. 
Making directory renaming behavior compliant with POSIX https://pubs.opengroup.org/onlinepubs/000095399/functions/rename.html
> If *new* names an existing directory, it shall be required to be an empty directory.
> [EEXIST] or [ENOTEMPTY]: The link named by *new* is a directory that is not an empty directory.
=> Handle name conflicts in directory renaming

.github/workflows/ci.yml, tools/integration_tests/mounting/gcsfuse_test.go
Tests previously ran in Travis but were accidentally removed in
2dee82339ae07fc8f2d8b2a7b592c560ab2ce2b4.  This would have prevented a
regression introduced in #597.  References #590.
=> Run tests during CI

internal/contentcache/contentcache.go, internal/gcsx/temp_file.go
Add way to persist temp cache files and metadata files on disk.
One concern I have is whether we want to store a pointer to the file on disk or if storing the struct in memory is enough.  The metadata on disk is only used to allow gcsfuse to hotload the cache on startup and isn't used any other time.
Testing:
Run go test ./....  and unit tests should pass. There should be no impacting changes on unit tests.
=> Allow creation of temp cache files and metadata files

internal/fs/inode/file.go, internal/gcsx/syncer.go
Each file inode keeps a temp file containing written data. The temp file
should be destroyed when the content is synced (uploaded), and other
conditions of the file inodes are met (such as local file cache
configs).
Before this change, the temp file destruction is triggered by the syncer
in the client library gcsx, regardless of the file inode conditions.
This change, however, moves the destruction out of the syncer to the file
inode, making it simplier to couple the destruction with the rest of the
inode instead.
Test:
```
go test ./...
```
=> Move the temp file destruction from syncer to inode

benchmarks/concurrent_read/readers/vendor.go, flags.go, main.go
According to the [official storage endpoints documentation](https://cloud.google.com/storage/docs/request-endpoints):
| The www.googleapis.com endpoint is also supported for the JSON API, but storage.googleapis.com is the preferred endpoint for better performance and availability.
This change helps allowing/denying specific services based off host name in more restrictive environments.
=> Use `storage.googleapis.com/storage/v1` by default for GCS requests

tools/prefetch_cache_gcsfuse/main.go, tools/prefetch_cache_gcsfuse/prefetch.go
Creates a catch prefetch tool to download files into local disk cache from specified bucket.  We use a typical single-producer multi-consumer concurrency pattern.
Usage:
`prefetch_cache_gcsfuse cache_dir bucket_name [prefix]`
To test, run the binary with the specified command line arguments.
Verify cache_dir is populated with files and metadata files.
Next try running gcsfuse specifying --local-file-cache flag with the value of the same cache_dir.  This will allow gcsfuse to use the cached files on disk.
The constant NUM_WORKERS specifies how many consumer workers to download files are created.
A higher NUM_WORKERS value creates more goroutines which can speed up downloads (up to a limit).
In the future, NUM_WORKERS can be a configurable command line flag exposed to the user.
=> Create prefetch tool to cache gcs objects on disk

tools/integration_tests/mounting/gcsfuse_test.go
Removes unnecessary TODO from broken integration test in CI.
=> Remove unnecessary TODO

internal/contentcache/contentcache.go, internal/contentcache/contentcache_test.go, internal/fs/fs.go, internal/fs/inode/file.go, internal/gcsx/temp_file.go, tools/prefetch_cache_gcsfuse/prefetch.go
Refactor content cache to support dynamic cache feature implementation.
To test, verify the read-only cache still works and that there is no change in behaviour.
=> Refactor content cache to use wrapper structs

internal/contentcache/contentcache.go, internal/gcsx/temp_file.go
Properly recover files from disk after prefetching, evict/cleanup stale cache files and handle both read/write to our cache. 
Dynamic cache support for the writethrough content cache should now be working.
**Known Issue:**
Currently, if files are generated in the virtual filesystem (for example swap files), these will be left in the cache as garbage files with no cleanup.  Work needs to be done to investigate how best to clean these up.
Depends on #624
=> Gcsfuse dynamic writethrough cache support

.github/workflows/ci.yml
If tests in CI are hanging, timeout will trigger earlier.
=> Update CI timeout to 10 minutes

internal/contentcache/contentcache.go, internal/contentcache/contentcache_test.go, internal/fs/inode/file.go
Validate on metageneration (in addition to generation numbers) to verify consistency and update the unit tests to reflect this change.
=> Add metageneration validation for cache files

internal/contentcache/contentcache.go, internal/contentcache/contentcache_test.go, internal/fs/handle/file.go, internal/fs/inode/file.go
The changes move ensureContent from inode creation to the file read path so files are only cached during reads and not during file inode creation (which happens during directory listings etc.) to improve performance.
In order to support these changes, the content cache now needs to be thread safe as there are no synchronization primitives protecting against concurrent cache access.  (previously we had filesystem and inode locks as cache access occurred at the inode creation step, but such locks do not guard against concurrent cache access during reads)
=> gcsfuse content cache thread safety

internal/contentcache/contentcache.go, tools/prefetch_cache_gcsfuse/prefetch.go
Add additional comments and change constant names to conform to Go standards.
No behaviour changes introduced.
=> Update contentcache comments and constants to conform to standards

internal/contentcache/contentcache.go, internal/fs/inode/file.go, internal/gcsx/temp_file.go
Address #645 as quickfix for error handling.
Long term we would like to open files in our cache with os.Open only when necessary (on demand).
=> Fix contentcache error handling

go.mod, go.sum, internal/fs/inode/dir.go, vendor/github.com/jacobsa/gcloud/gcs/bucket.go, vendor/github.com/jacobsa/gcloud/gcs/requests.go, vendor/modules.txt
Right now we don't set the maxResults param in listObjects api. By default 1000 results are returned. ListObjects api supports fetching upto 5000 results. Hence utilising the maxResults param to fetch larger data set which will improve the directory listing.
https://github.com/GoogleCloudPlatform/gcsfuse/issues/652
=> Setting MaxResults to 5000 and projection to noAcl in ListObjects call to fetch larger data set

internal/fs/inode/file.go
Object metadata is fetched in different flows like lookupInode, ListObject etc. Based on the flow either complete metadata or subset is fetched from gcs and stored in cache.  So cache will not have all the object metadata. Hence before syncing the file which recreates the file in gcs - we need to fetch the all the object properties and set those properties to the new file.
=> Changes to fetch statObject from gcs before syncing the file

vendor/github.com/jacobsa/gcloud/gcs/bucket.go, vendor/github.com/jacobsa/gcloud/gcs/conn.go, vendor/github.com/jacobsa/gcloud/gcs/read.go, vendor/github.com/jacobsa/gcloud/gcs/read_test.go
Moved Go Storage Client declaration from NewReaderSCL method in read.go to newBucket method in bucket.go.
The earlier declaration in NewReaderSCL method was not thread protected i.e. multiple clients can be formed from different threads whereas we want a single client for all threads.
Moved to newBucket method because it is only called once after starting gcsfuse irrespective of different threads. Also if passed as a argument to bucket, the same client can be used by read, write, get methods without creating different clients for different methods.
=> Set up Go Storage Client as a parameter of bucket struct in jacobsa library.

README.md, docs/installing.md
Hello, this PR is just some format fixes and name corrections in `README.md` and `installing.md`.
=> docs: fix Markdown format and rename "OS X" to "macOS"

tools/integration_tests/mounting/gcsfuse_test.go
**Issue:** By default when we pass wrong key-file it retries several time and returns the response after ~200 secs. We have two test-cases in that particular test (KeyFile), so it returns the response after ~400 secs, which feels like the hang in the integration test.
**Fix:**    By setting the --max-retry-sleep to 0, we only try to connect to the server once which also removes the concept of wait time and we are able to complete the test in 4-5 secs.
=> Fixing Hang Issue in KeyFile Integration Test

flags.go, flags_test.go, mount.go
PR adds the --log-fuse-errors as a default true flag which can be optionally set to false in case a user wants to ignore the error logs from fuse.  Attached a screenshot which confirms that the fuse: messages disappear only when the flag is explicitly set to false.
=> Flag changes to have ErrorLogger as optional

tools/integration_tests/readwrite/readwrite_test.go
1. Using fusermount instead of umount since umount requires sudo permissions.
2. Clearing kernel page cache after write to ensure reads are made from gcsfuse
3. Deleting files from mount directory to ensure gcsbucket is not overloaded.
=> ReadWrite integration tests fixes

internal/gcsx/random_reader.go, internal/monitor/bucket.go, internal/monitor/tags/tags.go
1. Added two new metrics - gcs/read_count to capture number of read calls along with type, gcs/downloaded_bytes_count to capture amount of data downloading from gcs.
2. gcsfuse_read_bytes is same as gcs/read_bytes_count. Hence removed gcsfuse_read_bytes
=> Made changes to export metrics for gcs read calls along with type

tools/integration_tests/implicitdir/implicitdir_test.go, tools/integration_tests/implicitdir/read_test.go
No code changes, just refactoring done.
we will use this directory structure for creating integration tests
```
/integration_tests
/implicit_dir - Tests when implicit dir is set
implicit_dir_test.go - main class for test setup
read_test.go - all read tests
write_test.go - all write tests
/file_cache - Tests when file caching is enabled
```
In case we want to run the same set of tests with a different flag, for eg: run implicit_dir tests with go_storage_library flag=true/false, then we will do that setup in implicit_dir_test.go to run tests twice by enabling & disabling the flag.
=> refactoring integration tests

flags.go, flags_test.go, main.go, tools/integration_tests/mounting/gcsfuse_test.go
>> log-file flagKey path tested.
>> key-file flagKey path not tested. Maybe we can disable it for now, by seeing the scope of the bug.
=> Fixing the Log-file Relative Path Bug using Environment Variable

flags.go, flags_test.go, internal/auth/auth.go, internal/auth/proxy.go, main.go
This is essentially adding a flag against the https://github.com/GoogleCloudPlatform/gcsfuse/commit/cf6bfbb27cc1365201f47d1fb8a4fafc92fbd485 change where a user should have an option to call for a new token for each request which will be done by the ProxyTokenSource
=> Add flag to have ability to not cache Token from token-url

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
If ls tests doesn't find the required data, it will delete the data from the entire bucket and tries to recreate it. Offline population is conflicting with the ls tests triggered by kokoro and entire data is getting wiped off.
=> Disabling ls tests till the data is populated correctly

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
Generated the required data in gcsbucket. Enabling the ls_metrics
=> Enabling the ls_metrics tests

tools/integration_tests/mounting/gcsfuse_test.go
>> Issue: whenever we run the test related to relative log/key file path. One new test.txt file gets created in the working directory.
>> Fix: We were passing different working directory while creating the absolute path for given relative path. Now, I made changes to get the current working directory from os.Getwd()
Question: Why the behavior is different for desktop machine and GCP machine?
>> For desktop, finally mounting happens with **fusermount3** package binary and for GCP vm, it is done using **fusermount**.   Both are different package binary, if we want the same behavior, we need to install **fusermount3** on the GCP_vm. So, fusermount3 looks updated version and it mounts the non-empty directory too, which is not the case for fusermout.
=> Fixing Integration Test Related to Relative Log/Key File Path

internal/auth/auth.go, internal/auth/proxy.go
In order to address the security concern where using a http endpoint for gcsfuse to retrieve token is not safe enough. If the token/auth server and the gcsfuse run on the same machine, using a unix socket for the communication is safer.
The code change is inspired by [[unixhttpc.go](https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74)](https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74)
The old way using http protocol and the new proposed unix protocol are all tested.
=> add unix socket support for token url

perfmetrics/scripts/vm_metrics/vm_metrics.py
seconds attribute is no longer available in
google.cloud.monitoring_v3.TimeInterval.start_time (google.protobuf.timestamp_pb2.Timestamp) in the latest version of protobuf (4.21.6). Using .timestamp() method to get time in seconds.
=> Fix seconds not available error

tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
Changes include:
(a) Addition of Dockerfile for building ubuntu/debian images with gcsfuse package from github release installed. To be used for publishing image to public registry.
(b) Changes in Dockerfile used for building gcsfuse packages to include support for building ubuntu/debian images with those gcsfuse packages installed. This is for building image for testing as part of CI/CD
=> Dockerfile(s) for images with gcsfuse installed

perfmetrics/scripts/vm_metrics/vm_metrics_test.py
Earlier timeseries json data was converted into dictionary and api calls were mocked using it. It worked since everywhere in the code data is accessed using dot operator. 
With the recent change timestamp data is using timestamp() method instead of .seconds(): https://github.com/GoogleCloudPlatform/gcsfuse/pull/825/files
hence the tests started breaking.
To fix it, it is required to convert json data into timeseries object instead of dictionary. But since pb2 file is not present for timeseries object, creating object and setting the fields manually.
=> fixing vm_metrics tests

docs/installing.md
Using insecure HTTP for software updates unnecessarily opens a user up to interception / MitM attacks.
=> Use HTTPS to access packages.cloud.google.com

docs/installing.md, perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
>> Updating the installation docs for 0.41.9 release.
>> Updating the kokoro build script.
Tried on one of the machines, I was able to install the latest version (0.41.9).
=> Gcsfuse Release 0.41.9 | Updating the Installation Docs and Build Script

internal/fs/fs.go
We need to follow this order for fetching locks -> inode and then filesystem level lock. Incase of implicitDir flow, we are fetching taking fs lock and then inode lock which is conflicting with other flow in the code that follows locking order. This conflict is creating deadlocks.
This PR fixes the deadlock by following the lock order in case of implicit dir flow.
=> Handling the order of lock for implicit dir node in lookupinode flow

internal/storage/bucket_handle.go
Issue:
Because of NopCloser conversion  for converting Reader object to ReadCloser, we got less bandwidth and more latencies for random reads.
For 50mb File size
Bandwidth - 224 MiB/s
Latency - 12084.52 ms
Fixes:
After rechecking http_client [NewRangeReader](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/vendor/cloud.google.com/go/storage/http_client.go#L771) method we got  to know that the object is ReadCloser type only so we don't need extra conversion of NopCloser.
For 50mb File size
Bandwidth - 1184MiB/s
Latency - 2199.80ms
Reason:
This could be because of we are copying heavy object many times during conversion.
=> Fixing the Performance Drop in Random Reads - Implemented using Go Storage Client

tools/containerize_gcsfuse_docker/Dockerfile
Removing labels from Dockerfile as suggested by @songjiaxun.  These labels are for opencontainers and are not required for our Dockerfiles. E.g. https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/0a39720fc2878584cdb43d9fea8d506da34dddf2
=> Removing opencontainers labels.

go.mod, go.sum, vendor/github.com/jacobsa/gcloud/gcs/retry.go, vendor/modules.txt
>> This contains the fix for seek issue while retrying through gcloud library.
>> The similar change is not required for go-storage library. [verified]
=> Refreshing the gCloud go module in gcsfuse

internal/storage/storageutil/object_attrs.go, internal/storage/storageutil/object_attrs_test.go
Crc returned from go-client library is copied by reference because of which entire attrs object returned by go-client library is not getting garbage collected. Fixing it to copy by value instead of reference
=> copying crc by value instead of by-reference from attrs object

internal/fs/inode/file.go, internal/gcsx/random_reader.go, internal/gcsx/random_reader_test.go, internal/storage/object.go
Right now we store entire object metadata in fileinode. But GCSFuse use few object properties. To avoid unnecessary memory usage by fileInode, made changes to store only min set of properties which are used by GCSFuse.
=> Created MinObject to store subset of object metadata and using that in fileInode

tools/mount_gcsfuse/main.go
This change was identified in https://github.com/GoogleCloudPlatform/gcsfuse/issues/891#issuecomment-1397905072
=> Support experimental_enable_storage_client_library flag in mount command

docs/installing.md, perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
Did the regular file-system operations.
Updated the doc with the latest version of gcsfuse.
https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.41.12
=> Updating the GCSFuse Release Version to 0.41.12

internal/storage/storage_handle.go, internal/storage/storageutil/custom_retry.go, internal/storage/storageutil/custom_retry_test.go
>> Added support for custom error retry in go-client workflow.
>> Adding 401 as a retryable error - specially this 401 retryable error will be reverted after the resolution of the issue: https://github.com/golang/oauth2/issues/623
=> Adding custom retry mechanism in Go Storage Client

perfmetrics/scripts/continuous_test/ml_tests/tf/setup_scripts/setup_container.sh, perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh
>>  Adding the --foreground flag while mounting the gcsfuse in the pytorch/tf script. Since, we don't get the crash logs when we run the command with nohup and gcsfuse in background.
=> Adding the --foreground flag while mount gcsfuse using nohup in kokoro-automation

docs/playbook.md, internal/perms/perms.go
>> Removing the panic, since it doesn't propagate to parent process.
>> Updated play book to fix the error - **current requires cgo or $USER set in environment** - while mounting gcsfuse with source code and without **--foreground** flag.
=> Panic while fetching current user in child-process

perfmetrics/scripts/job_files/seq_rand_read_write.fio
Reducing the startdelay should reduce the overall duration of test by ~50 minutes.
=> Adding fsync=1 and reducing startdelay to 2m

perfmetrics/scripts/fetch_metrics.py
Intermittently we are seeing that custom metrics are not available after 240 secs, hence waiting for more time for metrics to be ready.
=> Adding wait for 360secs for custom metrics to be ready

internal/fs/all_buckets_test.go, internal/fs/caching_test.go, internal/fs/foreign_modifications_test.go, internal/fs/implicit_dirs_test.go, internal/fs/local_modifications_test.go, internal/fs/read_only_test.go, internal/fs/stress_test.go
Unit tests are getting stuck intermittently.
The issue is kernel stops sending messages even though there are no errors returned for previous messages from kernel.
Right now, mounting and unmounting is done for every test case. Instead of that, we will move to mounting/umounting at struct level (class level in java terms). This seems to work.
Changes to convert initialisation to struct level are huge, hence will be done iteratively.
=> Not executing  fs tests in CI

internal/fs/all_buckets_test.go, internal/fs/caching_test.go, internal/fs/fs_test.go, internal/fs/implicit_dirs_test.go
Cleanup of unused variables in fs_test.go will be done after all tests are fixed.
=> Making allbuckets and caching tests use struct level init and tear down

internal/storage/storage_handle.go
Currently, the default WithPolicy is [RetryIdempotent](https://github.com/googleapis/google-cloud-go/blob/storage/v1.29.0/storage/storage.go#L1945) which only causes idempotent request to be retried in case of errors. Because of this, we recently observed failure in CopyObject operation(which is not idempotent) due to intermittent backend err(503) from GCS as retry was not performed.
With this change, we are shifting to RetryAlways policy which will try to retry for all requests regardless of idempotency considerations.
=> Use RetryAlways policy in conjunction with custom ShouldRetry

internal/fs/all_buckets_test.go, internal/fs/caching_test.go, internal/fs/foreign_modifications_test.go, internal/fs/fs_test.go
These variables are required by every test method but are not persisted in fstest struct since new instance of fsTest will be passed for every test method. https://pkg.go.dev/github.com/jacobsa/ogletest#SetUpTestSuiteInterface
Hence making them global.
=> Making required variables as global.

perfmetrics/scripts/job_files/seq_rand_read_write.fio
Currently the delay between first two jobs is 0 and for others it is 2mins. fio_metrics.py uses global start delay(2m) to compute the start and end time of each job.  https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/perfmetrics/scripts/fio/fio_metrics.py#L240
Because of this the start and end times of first job are computed wrong and goes to the time where the test hasn't even started. 
end_time_of_first_job = start_time_of_2nd_job - delay.
Delay used in above formula is 2mins (global_delay) whereas actual delay is 0secs.
Hence vm_metrics returns no metrics found for given interval.
=> Fixing the delay between first two jobs

tools/integration_tests/mounting/gcsfuse_test.go
Fixing the regression in integration test - came with syslog changes.
Reason:
In this particular test, it tries to read the log from stderr. As a part of syslog changes, we start writing the logs to syslog by default if --log-file key is no specified. Since, after the syslog changes, we don't write to stderr and test try to get from stderr and wait for long time and eventually cancelled due to time-out.
=> Fixing Integration Test Regression - Produced due to Syslog Changes

tools/mount_gcsfuse/main.go
'foreground' option is not added for mount command. I tried using foreground with mount command and it is working. Command used: `mount -t gcsfuse ayushsethi-working-dirs ./gg -o "key_file=key.json,client_protocol=http1,debug_gcs,debug_http,foreground"`
=> Adding foreground flag to work with mount command

flags.go, flags_test.go, internal/mount/flag.go, internal/storage/storage_handle.go, internal/storage/storage_handle_test.go, main.go, main_test.go, perfmetrics/scripts/compare_fuse_types_using_fio.py, perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/ls_metrics/listing_benchmark.py, perfmetrics/scripts/ls_metrics/listing_benchmark_test.py, perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh, perfmetrics/scripts/ml_tests/run_image_recognition_models.py, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, tools/mount_gcsfuse/main.go
This PR includes code changes. I will raise another PR for documentation changes.
Testing details:
1. Manual: 
- Check client-protocol flag's description and default value using `gcsfuse --help` command.
- Tried mounting and reading and writing a file with combinations - (http1, jacobsa/gcloud), (http2, jacobsa/gcloud), (http1, Go storage library),  (http2, Go storage library).
- Build gcsfuse using tools/build_gcsfuse.
- Mount gcsfuse with http1, http2 protocol using mount command: `mount -t gcsfuse ayushsethi-working-dirs ./gg -o "key_file=key.json,client_protocol=http1,debug_gcs,debug_http,log_file=gg.l"`
- Tried passing invalid `client-protocol` (http4) and got the expected error.
3. Unit tests:
- Added unit test case in flags_test.go to test that the input string value for …
=> Removing --disable-http2 flag and adding --client-protocol flag

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/fetch_metrics.py, perfmetrics/scripts/fio/fio_metrics.py, perfmetrics/scripts/run_load_test_and_fetch_metrics.sh
Logging time when fio test starts.
Logging start time and end time  for each job in fio. 
Blocked checkout through commit ID
Uses master branch script only
=> Print starttime and endtime for kokoro failure

flags.go
Changing the description of log-file flag, for default we started writing the logs to /var/log/gcsfuse.log.
1. Manual - NA
2. Integration Test - NA
3. Unit Test - NA
=> Changing the description of log-file flag

main.go
>> We are changing the logging behavior, earlier we used to print the logging info to the stdout when mounting is done through gcsfuse with --foreground flag and without --log-file flag.
Adding the info just to convey the new behavior to the user. 
1. Manual - manually tested print message and verified for foreground as well as background.
2. Unit Test - NA
3. Integration Test - NA
=> Adding the logging info, since we are changing the default behavior

docs/installing.md
Updating Installing doc for new release 0.42.0
Manual -  Installed newer version on VM, Did sanity check(Basic file operations are working)
Unit test - N/A
Integration test - N/A
=> Updating Installing doc for new release

main.go
Reverts GoogleCloudPlatform/gcsfuse#973
We need to properly think about the support on docker container. Reverting it right now due to the below mentioned issues.
Issue link - https://github.com/GoogleCloudPlatform/gcsfuse/issues/976
=> Revert "Adding the logging info, since we are changing the default behavior"

flags.go
Reverts GoogleCloudPlatform/gcsfuse#971
We need to properly think about the support on docker container. Reverting it right now due to the below mentioned issues.
Issue link - https://github.com/GoogleCloudPlatform/gcsfuse/issues/976
=> Revert "Changing the description of log-file flag"

internal/logger/logger.go, main.go
Reverts GoogleCloudPlatform/gcsfuse#949
We need to properly think about the support on docker container. Reverting it right now due to the below mentioned issues.
Issue link - https://github.com/GoogleCloudPlatform/gcsfuse/issues/976
=> Revert "GCSFuse code change to write the logs to syslog files"

internal/logger/logger.go, main.go
1. Reverts GoogleCloudPlatform/gcsfuse#977
2. Modified log behavior - If user passes --log-file in case all the logs will be written to given log file. Otherwise in background mode gcsfuse will write the log to syslog and in foreground mode logs will be printed to console as stdout/err.
1. Manual - Checked all the four behaviors manually.
2. Integration Test - NA
3. Unit Test - NA
=> GCSFuse code change to write the logs to syslog files

internal/gcsx/bucket_manager.go, internal/gcsx/bucket_manager_test.go, internal/storage/bucket_handle_test.go, internal/storage/storage_handle.go, internal/storage/storage_handle_test.go
Before [Bucket Handle](https://github.com/GoogleCloudPlatform/gcsfuse/blob/ComponentCount_Not_Set/internal/storage/storage_handle.go#L109) method was making [bucket.Attrs](https://pkg.go.dev/cloud.google.com/go/storage#BucketHandle.Attrs) call which needs storage.object.get permission to check if the bucket does exist or not. I skip this call as we are already checking if the bucket exists [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/4859983c583c9f09f3edd26651c8de7f4e490439/internal/gcsx/bucket_manager.go#L248). Before this line only threw an error; I made it throw an error and closed mounting.
Manual 
- Did sanity check(list, create, copy, delete operations)
-  What permissions does SA has - Storage Object Viewer
- no storage.buckets.get permission
- has storage.objects.get …
=> Permission issue mounting a bucket in go client library

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
Since we have renamed the flag from --experimental-enable-storage-client-library=true to "enable-storage-client-library" and by default it's true. Hence, removing this flag while mounting gcsfuse in the script.
(1) Manual - NA
(2) Integration Test - NA
(3) Performance Test - NA
=> Correcting the flag used in PR_PERF_TEST script

perfmetrics/scripts/job_files/presubmit_perf_test.fio
Run the perf_test script manually on the system. I have observed much fluctuation in perf_number of master branch vs current branch. Not sure, why exactly. 
Adding the fsync = 1 in the perf_fio_job so that we start comparing more realistic numbers.
Manual - NA
Integration - NA
Performance - NA
=> Adding fsync=1 in performance test fio-job

internal/fs/fs.go, internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go
1. Rightnow CreateObject is not idempotent because when generation is zero in the request, generation is not set in the call to GCS. To make it idempotent, we need to set storage.conditions.DoesNotExist = true when generation is zero.
Generation is zero means create the object only when object doesn't exist.
2. In the rename flow, when the destination directory already exists, precondition error is ignored. But rightn ow it also checks if the error has string **object exists** which is not returned by gcs. Hence removing it.
Testing:
Unit Tests: Added
Integration Tests: N/A
Manual Testing: Done for all scenarios where CreateObject is called using linux commands. Retry is simulated by calling CreateObject twice. Also added some custom log statements to log what is happening - whether the …
=> Making createObject idempotent

internal/storage/storageutil/object_attrs.go, internal/storage/storageutil/object_attrs_test.go
Throwing nil pointer exception when the project team was nil. 
- Manual
- Did sanity check(list, create, copy, delete operations)
- Project team is nil(in User), it will set Project Team nil in Object (see Unit test)
- If Access = Uniform: No object-level ACLs enabled - ACL=nil 
- If Access = Fine-grained: Object-level ACLs enabled - It has 4 ACLs (3 Project Related and 1 User) - for the first three project team will not equal to nil so that It will set, and for the fourth(User) ProjectTeam will be nil so It will set nil.
- Unit-test -
- Created unit test when the project team was nil
- Integration-test - N/A
=> Adding condition when project team is nil in ObjectAttr conversion

internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go
Description: Make ComposeObject method (when storage client library is enabled) idempotent when destination object doesn't exist. Currently, ComposeObject is called at the time of appending to file where dstObj = original object & srcObjects = [original object, temp object]. Hence, ComposeObject is always called with some GenerationPrecondition set. With these changes, ComposeObject will make idempotent requests even when dstObject doesn't exist and caller of ComposeObject sets 0 as GenerationPrecondition.
Testing:
Manual: 
1. Tried appending to a file of size 2mb and checked the debug_gcs logs. ComposeObject requests were successful.
2. Tried simulating retry of requests in 1# case by duplicating [this statement](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/vendor/cloud.goog …
=> Compose object idempotency when dst object doesn't exist.

internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go
**Issue:** Before deleting the stale objects, garbage collector first list all the objects with configured prefix (.gcsfuse_temp/) and it is [not passing](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/vendor/github.com/jacobsa/gcloud/gcs/gcsutil/list_prefix.go#L32) 'MaxResults' in [ListObjectsRequest](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/gcsx/garbage_collect.go#L41). And the ListObject method of Go storage client library [lists](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/storage/bucket_handle.go#L225) number of objects <= MaxResults which is 0 by default. So, no objects are listed.
**Fix** Modify the condition to list all objects when MaxResults is not passed (or when 0 is passed). This behaviour is similar to that in …
=> Fix list in garbage collection

tools/mount_gcsfuse/main.go
This change should have been done as part of this change https://github.com/GoogleCloudPlatform/gcsfuse/pull/962 but was skipped mistakenly.
Testing:
Manual: NA
Unit Test: 
Ran all unit tests in gcsfuse.
Integration test: NA
=> Remove disable_http2 flag from mount command.

main.go
Changing the log-level from NewNotice to NewInfo while mounting the gcsfuse.
NewNotice is used to write the mount status using daemonize.StatusWriter - useful in case we run the gcsfuse in background mode. 
But StatusWriter isinitialized with os.stderr hence all the information from the daemon process is written as stderr. 
Ideally, we should print the error only in case of error while mounting the gcsfuse.
```text
2023/03/14 12:58:20.430060 Value of [log-file] resolved from [gcsfuse.log] to [/usr/local/google/home/princer/Documents/code/gcsfuse_release/gcsfuse/gcsfuse.log]
2023/03/14 12:58:20.430140 Start gcsfuse/unknown (Go version go1.20-20221229-RC00 cl/498461153 +db36eca33c) for app "" using mount point: /usr/local/google/home/princer/Downloads/mnt
2023/03/14 12:58:20.454958 Value of …
```
=> Changing log-level notice to info while mounting

perfmetrics/scripts/continuous_test/ml_tests/pytorch/dino/build.sh, perfmetrics/scripts/continuous_test/ml_tests/pytorch/dino/continuous.cfg, perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh, perfmetrics/scripts/ml_tests/setup_log_rotation.sh
1. We were using a workaround branch to support log-rotation for kokoro-automation. Now, we will use logrotate package to support log-rotation for kokoro-automation.
Current change requires only for dino model.  I'll create a separate PR for tf-automation.
2. Also, changing the kokoro-job time to 7 days instead of 16 days.
1. Manual - Tested on the fresh machine, it's working fine.
2. Integration - NA
3. Unit - NA
=> Kokoro automation - Log rotation using logrotate

tools/mount_gcsfuse/main.go
Followed by this [issue](https://github.com/GoogleCloudPlatform/gcsfuse/issues/1014) 
Pass the value if explicitly define in flag, or pass it as  it is
1. Manual - tested manually on VM
2. UnitTest - N/A
3. IntegrationTest - N/A
=> Fixing: mount_gcsfuse not respecting bool values when passed to bool flags e.g. enable_storage_client_library

docs/installing.md
check here for [view](https://github.com/GoogleCloudPlatform/gcsfuse/blob/caa85e2fb7d67ae4d23937c65f8d0e8d7bf25d66/docs/installing.md)
N/A
=> Updating installtion doc

internal/fs/fs.go
Currently, we get many log-entries (if --debug_fs is enabled) containing GetXattr() while accessing any iNode. To avoid such entries, we need to return correct error response to the kernel. 
According to the linux-manual:
```
ENODATA
The named attribute does not exist, or the process has no
access to this attribute; see [xattr(7)](https://man7.org/linux/man-pages/man7/xattr.7.html).
In POSIX.1-2001 (XSI STREAMS option), this error was
described as "No message is available on the STREAM head
read queue".
ENOSYS Function not implemented (POSIX.1-2001).
```
Currently, we were returning error as `ENODATA`, which says attribute doesn't exist and kernel requests to get the data in the further call again and again. Instead when we return error as `ENOSYS` which says function not implemented, and …
=> Returning correct system error for un-implemented method

perfmetrics/scripts/load_tests/python/load_generator/load_generator.py, perfmetrics/scripts/load_tests/python/load_test.py
- Due to wrong order of process_id and thread_id. We make the read call to the wrong file, which doesn't produce the load to the right file.
- Changing the sleep time default value to zero second.
NA
1. Manual - checked manually.
=> Fixing load-script related to process_id and thread_id

docs/mounting.md, flags.go
`--debug_http` flag doesn't work for storage-client-library, updating the description. It is supported only for jacobsa/gcloud client.
https://github.com/GoogleCloudPlatform/gcsfuse/issues/1049
1. Manual - NA
=> Updating the description for --debug_http flag

internal/logger/logger.go
GCSFuse doesn't writer time-stamp information while logging via os.Stdout/err writer. Added a wrapper over these writer to write all these information.
Command executed:
`gcsfuse --debug_fuse --debug_fs --foreground <bucket_name> <mount_dir>`
Before:
```text
Creating a new server...
Set up root directory for bucket princer-working-dirs
Mounting file system "princer-working-dirs"...
Error while mounting gcsfuse: mountWithConn: Mount: stat /usr/local/google/home/princer/Documents/code/gcsfuse/mnt: no such file or directory
mountWithArgs: mountWithConn: Mount: stat /usr/local/google/home/princer/Documents/code/gcsfuse/mnt: no such file or directory
```
After:
```text
I0411 15:33:59.567735 Opening GCS connection...
I0411 15:33:59.567950 Creating a mount at …
```
=> Creating a text/json writer wrapping over standard output logging writer

docs/mounting.md
This will be pull request template
[Doc Update] Fixed gcsfuse --only-dir flag usage example in mounting.md.
1. Manual - Manually tested mounting the bucket with the --only-dir flag.
=> [Doc Update] Fixed gcsfuse --only-dir flag usage example.

internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go
Fix bug in list object method due to which some files are not listed if number of files in a directory are more than 5000 and contains one or more nested directory.
- The listing of objects (includes both files and directories as directories are also object in GCS) happens one by one using the next function of [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/storage/bucket_handle.go#L263) iterator. 
- The next function returns object, next page token and other attributes. E.g. if the listing is happening for 1st page, then the next function returns page token of 2nd page. 
Before fix: 
- This [for](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/storage/bucket_handle.go#L254) loop runs until the number of files [are not …
=> List obj fix

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/ls_metrics/config.json, perfmetrics/scripts/populate_metrics.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/run_load_test_and_fetch_metrics.sh, perfmetrics/scripts/vm_metrics/vm_metrics.py
Update bucket names in CI tests to point in new GCP project
1. Manual - Will run the tests once other setup is migrated.
2. Unit tests - N/A
3. Integration tests - N/A
=> Update bucket names in CI tests to point in new GCP project

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
Small change to use the latest version CI test scripts (e.g. build.sh, run_load_test_and_fetch_metrics.sh) in master branch during periodic tests.
Before this change: The [build script](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh) checkout to yesterday's last commit and then run the complete tests while staying on that commit.
After this change: The [build script](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh) will checkout to yesterday's last commit, build gcsfuse, run integration tests, checkout back to master's last commit and run the complete tests using the gcsfuse built before checking out to latest commit.
This change should allow testing …
=> Checkout back to master branch in periodic tests to use latest CI test scripts

docs/installing.md, tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
Due to the recent changes of removing the vendoring file in git, `go get github.com/GoogleCloudPlatform/gcsfuse` started building and installing by fetching the latest dependencies.
Go fetch module dependency on the basis of this environment variable `GO111MODULE=on`
1. `ON` - Always tries to find go.mod file in the current directory and any parent directory and fetches the dependency according to the `go.mod` file.
2. `OFF` - In this mode go fetch the latest code as a module dependency.
3. `AUTO`- So, if `go.mod` file exist in current or parent directory this is treated as `on` other wise `off`.
Note: `go get` command doesn't build or install module in module aware mode (`GO111MODULE=on`), otherwise we need to explicitly add `-d` flag to bypass building and installation of the module …
=> Fixing the build failure using go get command

tools/build_gcsfuse/main.go
While building the gcsfuse using [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/package_gcsfuse_docker/Dockerfile) Dockerfile.
First we get the gcsfuse go module using `go get -d github.com/googlecloudplatform/gcsfuse` command, it fetches the data in the `$GO_PATH/src/github.com/googlecloudplatform/gcsfuse` directory. After that, build_gcsfuse package is installed using `go install github.com/googlecloudplatform/gcsfuse/tools/build_gcsfuse` command. And in the end, we execute `build_gcsfuse <src_dir> <output_dir> <version>` to build the gcsfuse binaries.
In the last step, internally it runs the `go build -o <binary_output_dir> github.com/googlecloudplatform/gcsfuse`, which eventually tries to get the latest dependency of gcsfuse and build it and leads to the …
=> Adding the execution directory in the go build command

go.mod, go.sum
Upgrading the fuse go module to accommodate [this](https://github.com/jacobsa/fuse/pull/142) change.
**Mount using the below command on cloud top machine:**
` gcsfuse --foreground --debug_fuse --debug_fuse_errors <bucket_name> <mount_dir>`
**Before this change:**
```
{"name":"root","levelname":"ERROR","severity":"ERROR","message":"fuse: *fuseops.GetXattrOp error: function not implemented\n","timestampSeconds":1683638463,"timestampNanos":315054543}
```
**After this change:**
We don't get the error log when we mount with the above mentioned command.
1. Manual - Manually verified.
=> Upgrading the fuse go module to suppress error logs for GetXAttrs call

go.mod, go.sum
Update protobuf version as suggested in dependabot alert: https://github.com/GoogleCloudPlatform/gcsfuse/pull/1105/files
1. Manual - N/A
Results of perf tests (No perf regression):
Branch | File Size  |   Read BW    |  Write BW  | RandRead BW | RandWrite BW |
+--------+------------+--------------+------------+-------------+--------------+
| Master |  0.25MiB   | 398.16MiB/s  | 2.44MiB/s  |  30.4MiB/s  |  2.83MiB/s   |
|   PR   |  0.25MiB   |  396.0MiB/s  | 3.29MiB/s  |  28.74MiB/s |  2.77MiB/s   |
|        |            |              |            |             |              |
|        |            |              |            |             |              |
| Master | 48.828MiB  | 4496.73MiB/s | 79.3MiB/s  | 836.74MiB/s | …
=> Update protobuf version as suggested in dependabot alert

internal/storage/storage_handle_test.go, main.go, main_test.go
Reverts GoogleCloudPlatform/gcsfuse#1072
=> Revert "Add "(GPN: gcsfuse-<client-identifier>)" to useragent for partner data tracking."

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, tools/package_gcsfuse_docker/Dockerfile
Use the same steps to build gcsfuse in periodic test as used while releasing. This can help us catch issues like beforehand: https://github.com/GoogleCloudPlatform/gcsfuse/pull/1094
1. Manual - (a) Tried building gcsfuse from release tag and with both release tag and branch/commit using package_gcsfuse_docker/Dockerfile. (b)  Tried running continuous_tests/gcp_ubuntu/build.sh. 
2. Unit tests - N/A
3. Integration tests - N/A
=> Use the same steps to build gcsfuse in periodic test as used while releasing

.github/workflows/ci.yml
This will be pull request template
1. Manual: NA
2. Unit tests: NA
3. Integration tests: NA
=> Added timeout to golangci-lint as it is fails with timeout error

tools/integration_tests/util/setup/setup.go
This will be pull request template
Before if mounting output is throwing more then one line it was throwing an error.
but if I pass --key-file as parameter, in the first line it is fetching absolute path of key file and then throw success message.
but because of [this condition](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/integration_tests/util/setup/setup.go#L160) it was failing before.
Remove the condition to fix the failure
1. Manual
- All the integration tests are working fine for both the flags testBucket and mountedDirectoy.
- Tested for both foreground and background 
- No permission from key file to mount the bucket (mounting is failing) 
- Without key file and gcloud credentials
- Panic  (mounting is failing) 
- Crash during mounting
- Normal error while …
=> Removing condition in setup mounting 

internal/storage/storage_handle_test.go, main.go, main_test.go
Added GPN:gcsfuse-<client-identifier> to user agent.
Removed redundant client identifier(appname or metadata image type env variable) from user agent if it has been appended to GPN.
Possible Scenarios and changes:
1. When both GCSFUSE_METADATA_IMAGE_TYPE  environment variable and app-name flag are set
- `GCSFUSE_METADATA_IMAGE_TYPE=DLC` `app-name=myapp`
- Old UserAgent = `gcsfuse/0.42.3 (Go version go1.19.5) myapp DLC,gzip(gfe)`
- New UserAgent =`gcsfuse/0.42.3 (Go version go1.19.5) myapp (GPN:gcsfuse-DLC),gzip(gfe)`
2.  When both GCSFUSE_METADATA_IMAGE_TYPE  environment variable and app-name flag are unset
- `GCSFUSE_METADATA_IMAGE_TYPE=""` `app-name=""`
- Old UserAgent = `gcsfuse/0.42.3 (Go version go1.19.5),gzip(gfe)`
- New UserAgent =`gcsfuse/0.42.3 (Go version go1.19.5) …
=> Add "(GPN: gcsfuse-<client-identifier>)" to useragent

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
Kokoro will copy all files created during the test execution as artifacts unless they are deleted. Its copying all the files created by FIO as well. Hence doing umount to avoid copying the bucket contents as artifacts.
NA
1. Manual - Tested the presubmit flow via kokoro. For continuous tests, manually tested the umount step on vm after mounting the gcsfuse 
=> [execute-perf-test] Fixing kokoro tests which are failing with disk space error.

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
Unmount is being done before deleting the old logs. fixing it by moving the umount command to post all clean up.
NA
1. Manual - NA
=> fixing kokoro script

go.mod
Retracting v1.0.0 before new release as mentioned [here](https://go.dev/blog/go116-module-changes#module-retraction)
https://pkg.go.dev/github.com/googlecloudplatform/gcsfuse?tab=versions
1. Manual - NA
=> retracting v1.0.0

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/continuous.cfg, perfmetrics/scripts/run_load_test_and_fetch_metrics.sh
Today in CI script we manually copy the logs to gcs bucket. These logs doesn't get uploaded when there is a failure in script. Kokoro supports uploading artifacts to gcs bucket for both success and failure scenarios. Making changes to use the support provided.
NA
1. Manual - Test manually by copying continuous integration script into presubmit script
=> Copying gcsfuse logs and fio output to gcs bucket via Kokoro

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
Kokoro perf test was failing due to space issue. Fix it by running integration tests after fio tests.
We are going with this fix till the disk issue is not resolved in Kokoro.
NA
1. Manual - Tests were passing on kokoro.
=> Fixing kokoro perf test issue

perfmetrics/scripts/fetch_metrics.py
Printing the start and end time of all the fio jobs during the daily kokoro test. This will help to ensure the total run time of fio job is constant. If that is the case, then we have to figure out for the shift, for which we can reach to open-centsos team.
NA
1. Manual - NA
=> Adding logs to print all the fio job timing

tools/integration_tests/operations/delete_dir_test.go, tools/integration_tests/operations/operations_test.go
1. Test delete empty explicit directory
2. Test delete non-empty explicit directory
Note: Test delete non-empty implicit directory test will add in implicit dir package.
3. Integration tests - Run all the tests for testbucket and mountedDirectory flags.(status:SUCCESS)
=> Delete Directory integration tests

.github/workflows/stale.yml
Added github action to close issues with "pending customer action" label after 30 days of inactivity. Ref: https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues
NA
1. Manual - NA
=> Stale Github Action Integration

perfmetrics/scripts/run_load_test_and_fetch_metrics.sh
Logging the overall start and end time of fio jobs. This execution time will be source of truth and help in knowing that the calculated start and end time of the every job is correct or not.
NA
1. Manual - checked the echo command manually it print the time as epoch time.
=> Printing overall fio execution start and end time

internal/fs/fs.go, internal/fs/implicit_dirs_with_cache_test.go, internal/fs/inode/base_dir.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go
While running `rm -r` command on an implicit directory, we were getting the following error: 
`rm: cannot remove 'implicitSubDirectory/': Input/output error`
While running `mv` command on an implicit directory, we were getting the following error:
`mv: cannot stat 'implicitDirectory/': No such file or directory`
Cause: for implicit directory, the 0 byte directory backing object did not exist on gcsfuse but we were still making a deleteObject request in DeleteChildDir() method. 
NA
1. Manual - Manually tested recursive delete and rename flows.
Details:
- Recursive delete:
Mount Command: go run ./ --implicit-dirs --debug_fuse --debug_gcs --foreground ashmeenbkt /tmp/testnew/
```
ashmeen@ashmeen:/tmp/testnew$ tree
.
├── explicitDir
├── implicitDirectory1
│   ├── file1InImplicitDir1
│   ├── …
```
=> Fixed false error for implicit dir in rename and remove directory flow

README.md
Update the README.md to point to new docs links on cloud.google.com. Make general writing improvements. Note that I wrote most cloud.google.com links as hard links because I think it'd be beneficial for users to see that the link goes to the cloud.google.com site.
NA
1. Manual - NA
=> Update README.md to point to new docs links on cloud.google.com

tools/build_gcsfuse/main.go
while running integration tests with go version 1.21.x, we were seeing the following error: 
```
invalid value "$HOME/gcsfuse" for flag -C: -C flag must be first flag on command line
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
```
Fix: made -C the first flag on command line. These changes are compatible with go version 1.20.x and newer.
NA
1. Manual - NA
=> fix integration test

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/build.sh, perfmetrics/scripts/ls_metrics/listing_benchmark.py, perfmetrics/scripts/ls_metrics/run_ls_benchmark.sh
Fixing some issues related to timeout and problem in uploading metrics to BigQuery during KOKORO build. Added new KOKORO_JOB_TYPE, SUB_JOB and reduced sample size to 30 for listing tests
NA
1. Manual - Ran the build scripts from "periodic_experiments" folder using command "./build.sh" after commenting out the call to "run_load_test_and_fetch_metrics.sh" and setting EXPERIMENT_NUMBER to "1" and KOKORO_JOB_TYPE to "SUB_JOB". Observed the time taken for listing experiments to run, it was 18 mins and 34 seconds, which was under acceptable range.
=> Fixing some issues encountered during KOKORO build for periodic experiments

perfmetrics/scripts/bigquery/experiments_gcsfuse_bq_test.py, perfmetrics/scripts/ls_metrics/listing_benchmark.py
Created bigquery_test.py and added 11 unit tests for the various methods in ExperimentsGCSFuseBQ module in bigquery.py
NA
1. Manual - Tested code changes with the existing codebase and verified that the expected behavior is maintained
2. Unit tests - Added unit tests.
=> Unit tests for ExperimentsGCSFuseBQ module in bigquery.py

perfmetrics/scripts/ls_metrics/listing_benchmark.py
Fixing some issues encountered during KOKORO build for periodic experiments related to conflicting arguments. Removed the duplicated and conflicting arguments.
NA
1. Manual - Ran the build scripts from "periodic_experiments" folder using command "./build.sh" after commenting out the call to "run_load_test_and_fetch_metrics.sh" (only ran the list tests) and ensured that no arguments were conflicting with each other and all arguments were being parsed correctly.
=> Fixing some issues encountered during KOKORO build for periodic experiments 

perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/resnet_runner.py
**Changing the number of epochs:**
**Pytorch** - from 100 to 80 - since initial number took more than 7 days. Expectation is to run the test for 7 days, hence reducing the number of epochs.
**TF** - 675 - from 1000 to 675 - since initial number took more than 7 days. Expectation is to run the test for 7 days, hence reducing the number of epochs.
NA
1. Manual - NA
=> Changing the number of epoch based on previous run

tools/package_gcsfuse_docker/Dockerfile
Issue: Error "cpio: Digest mismatch" while installing gcsfuse on RHEL 8 in FIPS mode
```
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
1:gcsfuse-0.42.5-1                 ################################# [100%]
error: unpacking of archive failed on file /sbin/mount.gcsfuse;64a7afd5: cpio: Digest mismatch
error: gcsfuse-0.42.5-1.x86_64: install failed
```
Fix:
By default, per-file verification happens with MD5 digest, but in RHEL 8 (FIPS enabled) verification happens with sha256. Hence, this PR contains changes to build the rpm file with sha256 digest. This is also recommended.
Ref -  https://bugzilla.redhat.com/show_bug.cgi?id=1659053
NA
1. Manual - …
=> Adding rpm digest while creating rpm package

tools/integration_tests/util/operations/dir_operations.go
Removing defer as not working properly in for loop.
NA
Tested on centos-7 (Throwing error previously, working fine now)
Tested on Ubuntu
11. Unit tests - NA
12. Integration tests - Run all the tests for testbucket and mountedDirectory flags.(status:SUCCESS)
=> Fixing open file issue

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/README.md, perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Added a new experiment configuration with "listexperiments" branch.
NA
1. Manual - Ran the build scripts from "periodic_experiments" folder using command "./build.sh" after commenting out the call to "run_load_test_and_fetch_metrics.sh" (only ran the list tests) after setting EXPERIMENT_NUMBER to "4" and ensured that the test were running as expected on newly added configuration and the disabled configuration was ignored.
=> Added a new experiments configuration in GCSFuse periodic experiments configuration file. 

tools/integration_tests/operations/operations_test.go, tools/integration_tests/readonly/readonly_test.go
Testing viewer permission with key file and GOOGLE_APPLICATION_CREDENTIALS env variable.
NA
11. Unit tests - NA
12. Integration tests - Run all the tests for testbucket and mountedDirectory flags.(status:SUCCESS)
=> Integration tests for  key-file flag with viewer permission tests

.github/ISSUE_TEMPLATE/gcsfuse-bug-report.md, perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/resnet_runner.py, tools/integration_tests/operations/operations_test.go, tools/integration_tests/util/creds_tests/creds.go, tools/integration_tests/util/creds_tests/testdata/create_key_file.sh, tools/integration_tests/util/creds_tests/testdata/create_service_account.sh, tools/integration_tests/util/creds_tests/testdata/provide_permission.sh, tools/integration_tests/util/creds_tests/testdata/revoke_permission_and_delete_service_account_and_creds.sh, tools/integration_tests/util/operations/dir_operations.go, tools/package_gcsfuse_docker/Dockerfile
=> Merging master branch into sept_release branch

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Added time to the end_date of "SeptRelease" config to fix failing KOKORO build.
NA
1. Manual - NA
=> Fixed end_date in SeptRelease config

DEBIAN/changelog, DEBIAN/control, DEBIAN/copyright, DEBIAN/gcsfuse-docs.docs, tools/package_gcsfuse_docker/Dockerfile
Included copyright file in deb package.
https://github.com/GoogleCloudPlatform/gcsfuse/issues/290
1. Manual - Copyright file present in /usr/share/doc/gcsfuse post installation
```
ashmeen_google_com@ashmeen-bookworm:/usr/share/doc/gcsfuse$ ls
changelog.gz  copyright  gcsfuse-docs.docs
```
Added license flag to rpm package
```
ashmeen@ashmeen:~/gcsfuse/release/v1.0.2/packages$ rpm -qid gcsfuse-1.0.2-1.x86_64.rpm
Name        : gcsfuse
Version     : 1.0.2
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : default
Size        : 22491743
License     : Apache-2.0
Signature   : (none)
Source RPM  : gcsfuse-1.0.2-1.src.rpm
Build Date  : Mon 17 Jul 2023 06:27:21 AM UTC
Build Host  : 47c73e7d027e
Relocations : / 
Packager    : GCSFuse Team <gcs-fuse-dev@google.com> …
```
=> Add copyright file

tools/integration_tests/list_large_dir/list_large_dir_test.go, tools/integration_tests/operations/operations_test.go, tools/integration_tests/readonly/readonly_test.go, tools/integration_tests/rename_dir_limit/rename_dir_limit_test.go, tools/integration_tests/util/creds_tests/creds.go, tools/integration_tests/util/operations/dir_operations.go, tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go, tools/integration_tests/util/setup/setup.go
mount.gcsfuse was searching gcsfuse executables in the mentioned [places](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/mount_gcsfuse/find.go#L59). As gcsfuse was not installed in the machine where we are doing perf tests, it was failing.
Solution: Copied executables in /usr/local/bin dir 
It can run only with sudo permission so added function to copy with sudo permission.
NA
11. Unit tests - NA
12. Integration tests - Run all the tests for testbucket and mountedDirectory flags.(status:SUCCESS)
=> Kokoro perf test fix - Integration tests

tools/cd_scripts/e2e_test.sh
minor changes to the test script as follows:
- yum check-update command's exit code will be 100  when  there  are  updates available and is not necessary for yum updates.
- Logs are not captured incase a failure with non zero exit code occurs while running e2e tests.
NA
1. Manual - NA
=> Minor update to CD pipeline test script

tools/integration_tests/operations/operations_test.go, tools/integration_tests/util/creds_tests/creds.go, tools/integration_tests/util/creds_tests/testdata/create_key_file.sh, tools/integration_tests/util/creds_tests/testdata/create_service_account.sh, tools/integration_tests/util/creds_tests/testdata/revoke_permission_and_creds.sh
As we are hardcoded [service account name](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/integration_tests/util/creds_tests/creds.go#L31), when two VMs belongs to the same projects tries to run the tests at a time it is failing due to service account creation and deletion inconsistency. 
Made changes to create a service account and ignore the error if "already exist." 
The flow is.
1. Create service account will create service account name creds-test-gcsfuse in the project. If the service account already exist it will use existing one only.
2. create_key_file script will create credentials in that service account for testing.
3. revoke_and_delete_creds will revoke permission and delete the crede which we have created in create_key_file script.
here we are not deleting …
=> Creds test error fixing Integration tests

tools/cd_scripts/install_test.sh
To install from artifact registry, we need to write "deb ar+https://us-apt.pkg.dev/projects/gcs-fuse-prod gcsfuse-$(lsb_release -cs) main" to `/etc/apt/sources.list.d/artifact-registry.list` file.
`gcsfuse-` was missing in this command.
NA
1. Manual - Tested the changes manually by running on a VM
=> minor change to test script

internal/config/mount_config.go, internal/config/yaml_parser.go, internal/config/yaml_parser_test.go, internal/fs/fs.go, internal/fs/fs_test.go, internal/fs/inode/base_dir.go, internal/fs/inode/core.go, internal/fs/inode/core_test.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go, internal/fs/inode/file.go, internal/fs/inode/file_test.go, internal/fs/inode/symlink.go, internal/fs/inode/symlink_test.go, internal/fs/wrappers/error_mapping.go
NA
1. Manual - Tested manually by enabling and disabling the flag. 
2. Unit tests - Added where ever applicable. We cannot add unit tests for fs.go since fs.go tests do real mounting using fake gcs bucket. For any file operation, multiple operations will be invoked by kernel like lookUpInode, CreateFile, writeFile etc. Without modifying all these operations we will not be able to write unit tests. Hence unit tests will be added in a seperate cl when all operations are modified in fs.go
3. Integration tests - Existing tests are running fine. New tests will be added after all operations are modified.
=> Modified CreateFile operation to create localFiles based on config flag

tools/integration_tests/util/mounting/dynamic_mounting/testdata/create_bucket.sh, tools/integration_tests/util/mounting/dynamic_mounting/testdata/delete_bucket.sh
gcloud storage is not working due to older version of gcloud on kokoro machine. Changing it to gcloud alpha storage until we test with latest ubuntu image working or not.
NA
1. Manual - Tested all the integration tests are working on kokoro machine and GCE VM.
=> Kokoro perf test fix - gcloud storage command not working

.gitignore, go.mod, go.sum
Updates dependency to latest jacobsa/gcloud version. This is to account for https://github.com/jacobsa/gcloud/pull/34 .
NA
1. Manual - Tested by mounting a bucket, running ls command in different folders and checking file/object sizes etc.
=> Update gcloud version

tools/integration_tests/gzip/gzip_test.go, tools/integration_tests/gzip/helpers/helpers.go, tools/integration_tests/gzip/read_gzip_test.go, tools/integration_tests/run_tests_mounted_directory.sh, tools/integration_tests/util/operations/file_operations.go
This adds read-flow integration tests for the gzip read-compressed changes added in previous PR https://github.com/GoogleCloudPlatform/gcsfuse/pull/1255 .
Tests added (2*5 = 10 tests)
* Two types of operations each
* List, Stat and full-file read
* On five types of objects each
* Object with text content, uploaded with gzip compression with content-encoding: gzip, and cache-control: no-transform
* Object with text content, uploaded with gzip compression with content-encoding: gzip, and cache-control: ''
* Object with gzip content, uploaded with content-encoding: ''
* Object with gzip content, uploaded with gzip compression (i.e. doubly compressed) with content-encoding: gzip, and cache-control: no-transform
* Object with gzip content, uploaded with gzip compression (i.e. doubly …
=> gzip integration tests

tools/integration_tests/gzip/gzip_test.go, tools/integration_tests/gzip/write_gzip_test.go, tools/integration_tests/run_tests_mounted_directory.sh, tools/integration_tests/util/operations/file_operations.go
It adds write-flow integration tests (on top of the read-flow tests added in https://github.com/GoogleCloudPlatform/gcsfuse/pull/1256) for GCSfuse-mounted objects with content-encoding gzip. 
These tests replace an existing gzip object in a mounted bucket, then verify the size of the re-uploaded GCS object.
Tests added (1*5 = 5 tests)
* One type of operation
* Overwrite
* On five types of objects each
* Object with text content, uploaded with gzip compression with content-encoding: gzip, and cache-control: no-transform
* Object with text content, uploaded with gzip compression with content-encoding: gzip, and cache-control: ''
* Object with gzip content, uploaded with content-encoding: ''
* Object with gzip content, uploaded with gzip compression (i.e. doubly compressed) with …
=> gzip write-flow integration tests

tools/integration_tests/util/operations/file_operations.go
Replaces `gcloud` or `gcloud alpha` with `gsutil` in all gcs related utilities in file_operations utils in integration_tests. This is to avoid failures related to compatibility in kokoro VMs which support an old version of gcloud cli.
NA
1. Manual - Tested through gzip integration tests manually.
3. Integration tests - Tested through integration tests on VM.
=> Replace gcloud with gsutil in file-op utils

flags.go, flags_test.go
Removing printf statement to errorf
NA
1. Manual - basic operations locally.
2. Unit tests - automation
=> Fixing review comments: replacing printf error log to returning error

flags.go
Minor change in `--experimental-enable-json-read` api.
NA
1. Manual - locally.
2. Unit tests - automation
=> Updating gcsufse --help for `--experimental-enable-json-read` flag

internal/config/mount_config.go, internal/fs/fs.go, internal/fs/inode/file.go, internal/fs/inode/file_test.go, internal/gcsx/append_object_creator.go, internal/gcsx/append_object_creator_test.go, internal/gcsx/integration_test.go, internal/gcsx/syncer.go, internal/gcsx/syncer_test.go
Modified SyncFile, ForgetInode operations to handle local Files.
NA
1. Manual - Done manual testing and verified that file is getting uploaded to GCS correctly. Also verified forgetInode by manually throwing an error in writeFile flow. 
2. Unit tests - Added wherever applicable. Fs.go unit tests will be added after lookupinode operation is updated.
3. Integration tests -Yet to run the existing tests. New tests will be added in later PRs.
=> Modified Sync, forgetInode  operations to handle localFiles

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
1. If anyone wants to run only integration tests - attach  execute-integration-test label.
2. If anyone wants to run only perf tests - attach execute-perf-tes label.
3. If anyone wants to run both the tests - attach  execute-perf-tes and execute-integration-test  labels.
For integration test
Create bucket with gcsfuse-integration-test-xxxxx name.
Perform tests.
Delete bucket after testing.
NA
1. Manual - Tested on kokoro VM.
6. Integration tests - NA
=> Adding changes to run integration and perf tests with label

internal/config/mount_config.go, internal/fs/fs.go, internal/fs/fs_test.go, internal/fs/local_file_test.go
Modified lookUpInode operation to check localFileInodes first before calling GCS. Added unit tests for fs.go
NA
1. Manual - Tested manually by mounting gcsfuse and checking if lookUpInode is returning correct inodeId. 
2. Unit tests - Added unit tests for fs.go
3. Integration tests - Yet to run
=> Modified lookUpInode operation to check localFileInodes

internal/fs/dir_handle.go, internal/fs/fs.go, internal/fs/handle/dir_handle.go, internal/fs/handle/dir_handle_test.go, internal/fs/inode/base_dir.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go, internal/fs/local_file_test.go
Added support to list local files present in a directory.
NA
1. Manual - 
* ls command on mounted directory with local files
* ls command on explicit dir with local files
* ls command on implicit dir with local files
* ls -R command
here 
`l1, l2, l3, l4, l5` and `l6` are local files.
`c` and `d` are explicit directories
`foo` is implicit directory
error `ls: cannot access 'l*': No such file or directory` is because changes are required in lookupInode command.
```
ashmeen@ashmeen:~/Documents/mnt$ ls -R
.:
ls: cannot access 'l1': No such file or directory
ls: cannot access 'l2': No such file or directory
c  d  foo  l1  l2
./c:
ls: cannot access './c/l3': No such file or directory
l3
./d:
ls: cannot access './d/l4': No such file or directory
ls: cannot access './d/l5': No such file or …
```
=> Support local files for ReadDir operations

internal/canned/canned.go, internal/fs/all_buckets_test.go, internal/fs/caching_test.go, internal/fs/fs_test.go, internal/fs/handle/dir_handle_test.go, internal/fs/inode/base_dir_test.go, internal/fs/inode/core_test.go, internal/fs/inode/dir_test.go, internal/fs/inode/file_test.go, internal/gcloud/gcs/gcscaching/integration_test.go, internal/gcloud/gcs/gcsfake/bucket.go, internal/gcloud/gcs/gcsfake/bucket_test.go, internal/gcsx/content_type_bucket_test.go, internal/gcsx/integration_test.go, internal/gcsx/prefix_bucket_test.go, internal/gcsx/syncer_test.go
Copy [gcsfake](https://github.com/jacobsa/gcloud/tree/master/gcs/gcsfake) dependency
Didn't copy [conn.go](https://github.com/jacobsa/gcloud/blob/master/gcs/gcsfake/conn.go) [conn_test.go](https://github.com/jacobsa/gcloud/blob/master/gcs/gcsfake/conn_test.go) as we deprecated storage-client-library flag. 
[doc.go](https://github.com/jacobsa/gcloud/blob/master/gcs/gcsfake/doc.go) not have any implementation
Fixed lint issue
remove dependency on [io/ioutil](https://github.com/jacobsa/gcloud/blob/master/gcs/gcsfake/bucket.go#L25)
NA
1. Manual - Sanity check done(Read, Write, Delete, Create operations)
3. Integration tests - Integration tests are passing
=> Removing jacobsa gcsfake dependency

.github/workflows/ci.yml, Dockerfile, go.mod, perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, tools/containerize_gcsfuse_docker/Dockerfile
Upgrade to go version 1.21 as it fixes security vulnerabilities in the older version.
https://github.com/GoogleCloudPlatform/gcsfuse/issues/1288
1. Manual - basic sanity checks with go run command
3. Integration tests 
- ran integration tests on KOKORO.
- ran integration tests on deb and rpm package via louhi on all OS types.
=> Upgrade to go version 1.21

internal/fs/fs.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go, internal/fs/inode/file.go, internal/fs/inode/file_test.go, internal/fs/local_file_test.go
Changes to support unlink and remove directory operation on local files. 
These changes are in sync with non-local file system behaviour, i.e., 
- When FlushFile call is made on an unlinked file, 
- the file is considered clobbered.
- we don't return any error in this case.
- we don't write the file to GCS.
- ref: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/fs/inode/file.go#L168C35-L168C35
- When WriteFile call is made on an unlinked file, 
- the write operation fails while writing. 
- throws IO error while opening a reader.
- ref: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/fs/inode/file.go#L217
<br> <br>
Changes for local files:
* Unlink will remove the local file entry from localFileInodes map.
* RmDir will check for entries in …
=> Unlink and RmDir changes to support local files

perfmetrics/scripts/ml_tests/setup.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, tools/cd_scripts/e2e_test.sh, tools/package_gcsfuse_docker/Dockerfile
Missed upgrading go version in a few files in PR https://github.com/GoogleCloudPlatform/gcsfuse/pull/1317 
https://github.com/GoogleCloudPlatform/gcsfuse/issues/1288
1. Manual - NA
3. Integration tests - Ran on louhi (passed) and kokoro (Kokoro failed on the flaky test - [link](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/e20d1387-5b91-4e23-a3a7-6d6fb58d04e5/summary) )
4. Perf test results: https://screenshot.googleplex.com/72Hty4qck98wVWa.png
=> Upgrade go1.21

perfmetrics/scripts/run_e2e_tests.sh
Ensure that the bucket is deleted even when integration tests fail. Currently, the program exits before deletion step due to which there are many dangling buckets in gcs-fuse-test-ml. We will do one time clean up of those buckets.
NA
1. Manual - NA
3. Integration tests - Ran with Kokoro presubmit tests. The tests are failing because of flakiness and not because of these changes. Also, you can see in the logs that the bucket is deleted in this case.
=> Delete bucket pr tests

tools/integration_tests/operations/file_and_dir_attributes_test.go, tools/integration_tests/operations/operations_test.go, tools/integration_tests/util/setup/setup.go, tools/integration_tests/util/setup/yaml-config.go
- Added local files tests to operation_test.go .
- Fixed flaky test:
Attributes tests were flaky as the kernel clock was slightly out of sync of time.Now() 
ref bug: https://github.com/golang/go/issues/33510
ref logs: 
time in SetInodeAttributes() call `11:15:03.322725758` is behind CreateFile() call time `11:15:03.326389`.
```
D0901 11:15:03.326389 fuse_debug: Op 0x000007d2        connection.go:416] <- CreateFile (parent 1, name "tmpFile", PID 190957)
D0901 11:15:03.326603 fuse_debug: Op 0x000007d2        connection.go:498] -> OK (inode 51)
D0901 11:15:03.326728 fuse_debug: Op 0x000007d4        connection.go:416] <- WriteFile (inode 51, PID 190957, handle 114, offset 0, 14 bytes)
D0901 11:15:03.326830 fuse_debug: Op 0x000007d4        connection.go:498] -> OK ()
D0901 11:15:03.326899 …
```
=> Integration test for local files

tools/integration_tests/operations/operations_test.go
integration tests started failing because of empty log severity in config.yaml file. The issue happened because the PRs were submitted in parallel.
NA
1. Manual - Ran integration tests again
=> fix config_file integration test

internal/fs/fs.go, internal/fs/local_file_test.go
Throw IO error during sync or flush file calls when a local file is unlinked.
NA
1. Manual - Manually verified that IO error is thrown.
Logs:
```
D0907 13:29:04.384908 fuse_debug: Op 0x00000194        connection.go:416] <- FlushFile (inode 3, PID 1949237)
E0907 13:29:04.385009 FlushFile: input/output error, file is unlinked
D0907 13:29:04.385058 fuse_debug: Op 0x00000194        connection.go:500] -> Error: "input/output error"
E0907 13:29:04.385074 fuse: *fuseops.FlushFileOp error: input/output error
```
=> Unlinked local file should throw IO error

tools/package_gcsfuse_docker/Dockerfile
Updating building package docker file to add architecture in control file
Currently due to [Architecture](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/DEBIAN/control#L6) value all, the deb package gets uploaded on  all the cloud [repos](https://packages.cloud.google.com/apt/dists/gcsfuse-jessie/main)(amd64, arm64)
NA
1. Manual - Tested locally by building docker image and uploading it on artifact registary.
=> Update architecture in DEBIAN control file while building docker

internal/fs/fs.go, internal/fs/local_file_test.go
Sync after unlink for local file is made similar to multi-writer fix flow. Throwing error is not letting user to close the file handle. Hence reverting it as part of multi-write fix revert.
Reverts: https://github.com/GoogleCloudPlatform/gcsfuse/pull/1358
Manual revert is done since automatic revert is not possible.
NA
1. Manual - NA
=> Reverting the unlink changes for local files as part of multi-writer fix revert

internal/gcsx/bucket_manager.go, internal/storage/debug_bucket.go
As we are enabling log-levels, removed debug logger from debug_bucket.go and logged gcs logs as trace logs instead.
NA
1. Manual - NA
=> use default logger instead of separate logger for debug_gcs logs [slog PR-3]

internal/fs/wrappers/error_mapping.go
As we are enabling log-levels, removed error logger from error_mapping.go and used appropriate default logger methods instead.
NA
1. Manual - NA
=> use default logger instead of separate logger in error_mapping.go [slog PR-4]

main.go, mount.go
As we are enabling log-levels, removed mountStatus info logger and logged via default logger methods instead.
NA
1. Manual - NA
=> use default logger instead of separate logger for mount logs [slog PR-5]

internal/fs/wrappers/monitoring.go
As we are enabling log-levels, removed error logger from monitoring.go and logged via default logger methods instead.
NA
1. Manual - NA
=> use default logger instead of separate logger for monitoring logs [slog PR-6]

internal/locker/locker.go
As we are enabling log-levels, removed debug_mutex logger from locker.go and logged via default logger methods instead.
NA
1. Manual - NA
=> use default logger instead of separate debug_mutex logger [slog PR-7]

internal/monitor/bucket.go, internal/monitor/exporter.go
As we are enabling log-levels, removed loggers from monitor/exporter.go and monitor/bucket.go and logged via default logger methods instead.
NA
1. Manual - NA
=> use default logger instead of separate logger for exporter logs [slog PR-8]

internal/storage/debug_bucket.go
The logger is no longer required (not used). The lint issue crept in because of parallel changes by me and @Tulsishah.  
NA
1. Manual - NA
=> fix lint issue on sept_release branch

internal/fs/inode/file.go, internal/fs/inode/file_test.go, internal/fs/local_file_test.go
Any modification to the file will result in a setInodeAttributes call to GCSFuse to update mtime. But when a file is created and synced without writing any content, then mtime is not set. Fixing it by setting mtime on file when it is created.
NA
1. Manual - Tested manually by mounting.
=> [execute-integration-tests]Fixing mtime for empty local files synced to GCS

perfmetrics/scripts/run_e2e_tests.sh
On kokoro continuous test we used n2-standard-16 and t2a-standard-16 machines. On these machines operation package is taking around 30 minutes to run all the tests, so I increase the timeout from 24m to 40m.
As discussed @vadlakondaswetha I'll investigate about why it is taking long time and merge this for now. 
NA
1. Manual - Tested on local VM
=> Increasing timeout in e2e tests

internal/config/mount_config.go, internal/config/yaml_parser_test.go, internal/logger/logger.go
Earlier we were assigning default value to log-format as JSON (also the default value of flag) in the config file. 
The config file value takes precedence when both flag and config are set. Due to this the log-format flag stopped working as we were overriding with config value always. 
Fix: do not assign default value. If nothing is set, override with flag. Later on when we deprecate log-format flag, the format value will be empty. In this case, the default behaviour will remain JSON as when format is not text, we return JSON handler.
NA
1. Manual - 
When log-format flag is used without config
```
ashmeen@ashmeen:~/gcsfuse$ go run ./ --foreground --log-format=text ashmeen-bucket-1 ~/Documents/mnt
time="14/09/2023 09:54:53.155826" severity=INFO msg="Start gcsfuse/unknown (Go version …
```
=> fix log-format flag behaviour

tools/integration_tests/explicit_dir/explicit_dir_test.go, tools/integration_tests/implicit_dir/implicit_dir_test.go, tools/integration_tests/implicit_dir/local_file_test.go, tools/integration_tests/util/client/gcs_helper.go, tools/integration_tests/util/client/storage_client.go, tools/integration_tests/util/operations/dir_operations.go, tools/integration_tests/util/operations/file_operations.go, tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go, tools/integration_tests/util/setup/setup.go
Add tests to verify that file is not created on GCS until local files are synced to run with implicit_dir flag.
1. Manual - NA
3. Integration tests - 
Ran implicit_dir and explicit_dir tests locally on a VM with 
- test-bucket flag
- The following commands:
```
gcsfuse --implicit-dirs $TEST_BUCKET_NAME $MOUNT_DIR
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/implicit_dir/...  -p 1 --integrationTest -v --mountedDirectory=$MOUNT_DIR --testbucket=$TEST_BUCKET_NAME
sudo umount $MOUNT_DIR
mount.gcsfuse $TEST_BUCKET_NAME $MOUNT_DIR -o implicit_dirs
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/implicit_dir/...  -p 1 --integrationTest -v --mountedDirectory=$MOUNT_DIR --testbucket=$TEST_BUCKET_NAME
sudo umount $MOUNT_DIR
gcsfuse --only-dir testDir …
```
=> [ready for review] local file tests with implicit dir flag

tools/integration_tests/local_file/stat_file_test.go, tools/integration_tests/local_file/sym_link_test.go, tools/integration_tests/util/client/gcs_helper.go, tools/integration_tests/util/operations/file_operations.go
NA
1. Manual 
- Manually ran on GCP VM using the following commands:
```
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/local_file/...  -p 1 --integrationTest -v --testbucket=$TEST_BUCKET_NAME
``` 
```
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/local_file/...  -p 1 --integrationTest -v --testbucket=$TEST_BUCKET_NAME --testInstalledPackage
``` 
- Ran the following commands for mounted directory tests
```
gcsfuse --implicit-dirs=true --rename-dir-limit=3 $TEST_BUCKET_NAME $MOUNT_DIR
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/local_file/... -p 1 --integrationTest -v --mountedDirectory=$MOUNT_DIR --testbucket=$TEST_BUCKET_NAME
sudo umount $MOUNT_DIR
gcsfuse --implicit-dirs=false --rename-dir-limit=3 $TEST_BUCKET_NAME $MOUNT_DIR …
```
=> Integration tests to verify symlink and stat operations on local file

tools/integration_tests/local_file/read_dir_test.go, tools/integration_tests/local_file/unlinked_file_test.go, tools/integration_tests/util/client/gcs_helper.go, tools/integration_tests/util/operations/file_operations.go
NA
1. Manual - 
- Ran the following commands for test bucket tests
```
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/local_file/...  -p 1 --integrationTest -v --testbucket=$TEST_BUCKET_NAME
``` 
```
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/local_file/...  -p 1 --integrationTest -v --testbucket=$TEST_BUCKET_NAME --testInstalledPackage
``` 
- Ran the following commands for mounted directory tests
```
gcsfuse --implicit-dirs=true --rename-dir-limit=3 $TEST_BUCKET_NAME $MOUNT_DIR
GODEBUG=asyncpreemptoff=1 go test ./tools/integration_tests/local_file/... -p 1 --integrationTest -v --mountedDirectory=$MOUNT_DIR --testbucket=$TEST_BUCKET_NAME
sudo umount $MOUNT_DIR
gcsfuse --implicit-dirs=false --rename-dir-limit=3 $TEST_BUCKET_NAME $MOUNT_DIR …
```
=> Read directory and unlink local file integration test

tools/cd_scripts/e2e_test.sh
louhi pipeline is unable to find [requirements.txt](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/cd_scripts/requirements.txt) file, as we are running script as startup script and we don;t have  [requirements.txt](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/tools/cd_scripts/requirements.txt) in VM.
NA
1. Manual - tested on rhel-9,rhel-9-arm64,cenos-9,ubuntu20,centos-7
1. Created e2e_test.sh locally.   
2.  Created VM instance with this command
```
gcloud compute instances create release-test-debian-12     --machine-type=MACHINE-TYPE --image-family=IMAGE_FAMILY     --image-project=IMAGE_PROJECT  --zone=ZONE     --scopes=https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/devstorage.read_write …
```
=> Fix for requirements for e2e tests

tools/integration_tests/gzip/read_gzip_test.go, tools/integration_tests/util/operations/dir_operations.go, tools/integration_tests/util/operations/file_operations.go, tools/integration_tests/write_large_files/write_large_files_test.go
This rationalizes the memory requirement
of file-op utility DiffFiles. This utility
earlier used to the read the complete files
in memory, but now only a chunk is read and
compared at a time.
It also changes the name (to AreFilesIdentical) and the return-type of the utility to boolean (true=identical, false=otherwise) .
NA
1. Manual - NA
3. Integration tests - No new tests. Existing tests passed.
=> Fix DiffFiles utility function

internal/auth/auth.go, internal/auth/proxy.go, internal/contentcache/contentcache.go, internal/fs/fs.go, internal/fs/inode/file_test.go, internal/fs/inode/name.go, internal/fs/inode/type_cache.go, internal/gcsx/append_object_creator_test.go, internal/gcsx/integration_test.go
This fixes all the [lint errors](https://github.com/GoogleCloudPlatform/gcsfuse/actions/runs/6310787426/job/17164364560?pr=1400) blocking the rebase of release to master branch (https://github.com/GoogleCloudPlatform/gcsfuse/pull/1400)
NA
1. Manual - Did manual testing locally for following operations: list, stat, read, write, delete-in-mount-directory, copy-in-mount-directory, delete-from-gcs, copy-in-gcs .
2. Unit tests - Ran locally and all passed.
3. Integration tests - Will run as part of presubmit using the presubmit integration-tests label.
=> Fix lint errors blocking rebase of release to master branch

Dockerfile, perfmetrics/scripts/ml_tests/pytorch/dino/setup_container.sh, perfmetrics/scripts/ml_tests/setup.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/run_e2e_tests.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
Upgrading the go version from 1.21.0 to 1.21.1
https://github.com/GoogleCloudPlatform/gcsfuse/issues/1398
1. Manual - NA
3. Integration tests - Automation (passed integration test)
=> Upgrading go version from 1.21.0 to 1.21.1

docs/semantics.md
Updating semantics docs - removing 0.txt file reference to explain --implicit-dir flag.
NA
1. Manual - NA
=> Updating semantics docs - remove 0.txt file reference

internal/logger/logger.go, tools/integration_tests/util/setup/setup.go
It prints stack-trace whenever logger.Fatalf(...) is called in gcsfuse runtime or LogAndExit is called in the integration tests.
NA
1. **Manual** - For testing, an intentional panic needs to be generated in the gcsfuse code, or a LogAndExit call in integration tests. These were not easy, so, I have tested this by manually inserting these calls in the code (code changes parked in https://github.com/GoogleCloudPlatform/gcsfuse/pull/1379 ).
Log differences
1. **Panic during gcsfuse runtime**: For testing this, a panic was intentionally inserted during mount whenever a non-empty `--temp-dir` argument was passed (code changes for testing in https://github.com/GoogleCloudPlatform/gcsfuse/pull/1379).
A. **Before/Without this change**
```
$ gcsfuse --temp-dir=abc --log-file=$log $bucket $mntdir ; …
```
=> Print stack-trace on crash

flags.go, internal/config/testdata/invalid_unexpectedfield_config.yaml, internal/config/yaml_parser.go, internal/config/yaml_parser_test.go
Throw an error if user passes wrong fields in the config file. e.g. an extra field or typo in the existing field. Used Decoder instead of Unmarshal due to https://github.com/go-yaml/yaml/issues/602#issuecomment-623485602
NA
1. Manual - NA
2. Unit tests - Added unit test for invalid file.
=> Throw error in case of unexpected fields

go.mod, go.sum
Upgrading the fuse module: only contains change in this [PR](https://github.com/jacobsa/fuse/pull/151).
NA
1. Manual - Basic sanity (ls, cat, touch, rm)
=> Upgraded the fuse library

internal/gcsx/content_type_bucket.go, internal/gcsx/prefix_bucket.go, internal/monitor/bucket.go, internal/ratelimit/throttled_bucket.go, internal/storage/bucket_handle.go, internal/storage/caching/fast_stat_bucket.go, internal/storage/debug_bucket.go, internal/storage/fake/bucket.go, internal/storage/gcs/bucket.go, internal/storage/mock_bucket.go
Adds 
1. ChunkUploader interface
ChunkUploader interface represents asynchronous object
uploaders which upload a chunk of an object's data in a
call using GCS' resumable upload API.
On closing, they return a GCS object (gcs.Object)
and and error object for error-handling.
2. CreateChunkUploader in Bucket interface
CreateChunkUploader creates a new object-chunk-uploader (which implements
the ChunkUploader interface) according to the supplied CreateObjectRequest.
This is used to uploaded content incrementally.
On closing this uploader, a gcs.Object is returned.
This is an alternative to CreateObject which is
a one-shot object content-uploader and creator, and is meant
to be invoked on file sync/flush operation.
The CreateChunkUploader is instead called
when you want to asynchronously upload …
=> [Async object upload 1] Add CreateChunkUploader in Bucket interface

tools/integration_tests/run_tests_mounted_directory.sh
added commands in `run_tests_mounted_directory.sh` to run tests with "create-empty-file" config set to true.
NA
1. Manual - Manually ran the commands on GCE VM.
=> update run_tests_mounted_directory.sh with create-empty-file tests

internal/config/mount_config.go, internal/config/testdata/invalid_filecachettl_config.yaml, internal/config/testdata/valid_config.yaml, internal/config/yaml_parser.go, internal/config/yaml_parser_test.go
Removinfg ttl from file cache as it is not required.
NA
1. Manual - NA
=> Correct cache config

.github/workflows/ci.yml
Adding race detector test specially for ./internal/cache/... directory.
NA
1. Manual - (a) Remove locked in the lru_cache.go in insert method. (b) Run the test with `-race` flag - Found below error.
```
testing.(*T).Run.func1()
/usr/lib/google-golang/src/testing/testing.go:1648 +0x44
==================
[       OK ] CacheTest.TestRaceCondition
[----------] Finished with tests from CacheTest
testing.go:1465: race detected during execution of test
--- FAIL: TestCache (0.00s)
=== NAME  
testing.go:1465: race detected during execution of test
FAIL
coverage: 91.1% of statements
FAIL    github.com/googlecloudplatform/gcsfuse/internal/cache/lru       0.060s
FAIL
```
If we revert changes (a), then test gets succeeded.
=> Adding race detector test for cache directory

internal/cache/lru/lru.go, internal/cache/lru/lru_test.go
Changing the normal mutex with the customise locker which supports debugging and invariant check.
NA
1. Manual - NA
=> Using locker with invariant check in LRU cache

internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go
Adding helper functions for adding and notifying subscriber in download job and a function to fail while downloading. Also setup fake GCS object and bucket in job_test.go. I
NA
1. Manual - NA
2. Unit tests - Added unit tests for newly added functions
=> Adding logic to add and notify subscriber

internal/cache/data/file_info.go, internal/cache/data/file_info_test.go, internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go, internal/cache/util/util.go, internal/cache/util/util_test.go
Changes involve:
1. Added create file util to create file in the file cache at the time of downloading.
2. Helper to update file info cache at the time of downloading.
3. Realized from the design that we don't need to put specific uid and gid for files in cache. So removed that from file spec. Haven't deleted file spec in case we need to add more parameters in future.
4. Ignored check in fileinfokey for bucket creation time till we support bucket creation time via metadata call.
NA
1. Manual - Ran unit tests.
5. Unit tests - Added unit tests wherever applicable.
6. Integration tests - NA
=> Add create file util , update fileinfocache, remove ownership, bucket creation time

internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go, internal/cache/util/util.go
Adding downloadObjectAsync method to download object into a file in cache sequentially. Their can only be one go routine running this method at a time for a download job object. 
This method can be cancelled by job.Cancel method. I will add job.Cancel and job.Download in the next PR along with test cases for job.Download and job.Cancel.
NA
1. Manual - NA
2. Unit tests - Added unit tests.
=> Read cache job 4 - Adding download async job & test cases

perfmetrics/scripts/presubmit/run_load_test_on_presubmit.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
Perf tests were failing because we were using job_start key while fetching the metrics but still using the old fio version which did not support "job_start" key. 
In this PR:
- moved installing requirements before switching to master.
- building fio from source to support job_start key.
NA
Ran perf tests
1. Manual - NA
=> Fix perf test

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/ls_metrics/run_ls_benchmark.sh
-  It was failing due to 300 samples 
-  Fixed log directory to kokoro logs and Removed `--stackdriver-export-interval=30s` from list tests as we are not extracting VM metrics for list tests.
NA
1. Manual - Tested locally
=> Fix kokoro tests

internal/storage/chunk_uploader.go, internal/storage/chunk_uploader_test.go, internal/storage/gcs/bucket.go
Adds a new struct chunkUploader which implements the ChunkUploader interface.
A chunkUploader is used to write content to a new GCS object asynchronously.
This is followed up in and [Async object upload 3](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1417).
NA
1. Manual - NA
2. Unit tests - All existing unit tests passed. New tests needed for chunkUploader.
=> [Async object upload 2] Add struct chunkUploader

internal/fs/inode/file.go, internal/storage/storageutil/object_attrs.go, internal/storage/storageutil/object_attrs_test.go
1. Moving private convertObjectToMinObject to storage-util.
NA
1. Manual - NA
3. Unit tests - Added unit test.
4. Integration tests - Automation
=> Moving private convertObjectToMinObject to storageutil

tools/cd_scripts/install_test.sh
Update install_test.sh with the install commands mentioned [here](https://cloud.google.com/storage/docs/gcsfuse-install#install-binaries).
NA
1. Manual - Manually ran the script on all OS types and verified that it is working as intended.
=> Update install test.sh with public documentation install commands

internal/gcsx/content_type_bucket_test.go, internal/gcsx/prefix_bucket.go, internal/gcsx/prefix_bucket_test.go, internal/monitor/bucket.go, internal/ratelimit/throttled_bucket.go, internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go, internal/storage/caching/fast_stat_bucket.go, internal/storage/caching/fast_stat_bucket_test.go, internal/storage/debug_bucket.go, internal/storage/fake/bucket.go, internal/storage/gcs/bucket.go, internal/storage/mock_bucket.go
This adds implementation of gcs.ChunkUploader interface and CreateChunkUploader for all bucket types, and their corresponding unit tests.
NA
1. Manual - NA
2. Unit tests - All unit tests passed.
3. Integration tests - Ran as presubmit
=> [Async object upload 3] Invoke ChunkUploader from bucket implementations

perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/build.sh, perfmetrics/scripts/continuous_test/ml_tests/build.sh, perfmetrics/scripts/continuous_test/ml_tests/pytorch/dino/build.sh, perfmetrics/scripts/continuous_test/ml_tests/tf/resnet/build.sh, perfmetrics/scripts/ml_tests/pytorch/dino/Dockerfile, perfmetrics/scripts/ml_tests/pytorch/dino/setup_host_and_run_model.sh, perfmetrics/scripts/ml_tests/run_image_recognition_models.py, perfmetrics/scripts/ml_tests/tf/resnet/Dockerfile, perfmetrics/scripts/ml_tests/tf/resnet/setup_host_and_run_model.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
Remove chmod calls for running scripts
As in the previous commit, we now have
exec-mode set on all script files, and thus
chmod for runningi them is not needed anymore.
This is on top of [Add exec-mode to script files](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1486) .
NA
1. Manual - NA
3. Integration tests - Ran as presubmit
=> Remove chmod calls for running scripts

internal/cache/file/cache_handle.go, internal/cache/file/cache_handle_test.go, internal/cache/file/cache_handler.go, internal/cache/file/cache_handler_test.go, internal/cache/util/util.go, internal/cache/util/util_test.go, internal/fs/fs.go, internal/fs/handle/file.go, internal/gcsx/random_reader.go, internal/gcsx/random_reader_test.go
1. Random reader change to support reading from cache.
2. Changes in FileHandle and fs.go to propagate CacheHandler and downloadForRandom
3. Semantic changes for Destroy method, now it returns an error.
4. Correction in CacheHandler.go, now we will not destroy the cacheHandle if the job is NOT_STARTED.
NA
1. Manual - NA
5. Unit tests - Automation
6. Integration tests - (will run the automatic integration test in the last)
=> Random reader change to support reading from cache

internal/config/mount_config.go, internal/config/testdata/invalid_log_rotate_config_1.yaml, internal/config/testdata/invalid_log_rotate_config_2.yaml, internal/config/testdata/valid_config.yaml, internal/config/yaml_parser.go, internal/config/yaml_parser_test.go, internal/logger/logger.go, internal/logger/logger_test.go, main.go
Added the following configs for log rotation.
1. max-file-size-mb: specifies the maximum size in megabytes that a log file
can reach before it is rotated. The default value is 512 megabytes.
2. file-count: determines the maximum number of log files to retain after they
have been rotated. The default value is 10.
3. compress: indicates whether the rotated log files should be compressed
using gzip. The default value is False.
NA
1. Manual - NA
=> add configs for log rotation

perfmetrics/scripts/fio/install_fio.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/run_load_test_and_fetch_metrics.sh
Currently the commands for installing fio
is duplicated at two different places. This change merges them and puts it into a common script at
perfmetrics/scripts/fio/install_fio.sh and invokes it from both the places.
fio version 3.36 has been released, so we could directly installed that from the fio-3.36 package, but we need to build fio from source for the [fix in clat latency calculations](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1503) .
This is precursor to https://github.com/GoogleCloudPlatform/gcsfuse/pull/1503.
NA
1. Manual - NA
=> Collate fio installations at one place

.github/workflows/ci.yml
Increase linux-tests timeout to 15m
This is to address internal issue#311507969 .
The linux-tests in github ci have false failures because of
timeout (currently 10 m) some times, which force the developer to
rerun the test manually. Increasing the timeout duration from
10m to 15m should lower the failure caused by timeout and
should reduce developer pain.
[screenshot](https://user-images.githubusercontent.com/8597474/284286106-61d562aa-9fda-4d9c-af0f-9ab10c15813c.png)
In the above run, the overall runtime of the linux-tests presubmit run is more than 6 min. But it varies from run to run.
As mentioned [here](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1500#issuecomment-1819102111), about 4 min of runtime is supposed to be added by new cache tests, thus timeout needs to also be …
=> Increase linux-tests timeout to 15m

perfmetrics/scripts/fio/install_fio.sh
This fix is to address internal bug#309563824.
As recorded in this bug, fio by default supports
clat percentile values to be calculated accurately upto only 2^(FIO_IO_U_PLAT_GROUP_NR + 5) ns = 14 ms
(with default value of FIO_IO_U_PLAT_GROUP_NR = 29). This change increases it upto 32, to allow latencies upto 112 ms to be calculated accurately.
This is dependent on https://github.com/GoogleCloudPlatform/gcsfuse/pull/1506 . This fix is bsased on the suggestion in https://github.com/axboe/fio/issues/1668#issuecomment-1795094235 .
NA
1. Manual - NA
=> Fix clat-percentile accuracy in fio

internal/fs/buffer/inmemory_write_buffer.go, internal/fs/buffer/inmemory_write_buffer_test.go, internal/fs/buffer/write_buffer.go, internal/fs/fs.go, internal/fs/inode/file.go, internal/fs/inode/file_test.go
Write to buffer when file buffering flow is enabled. 
NA
1. Manual - NA
=> Write to buffer for minimal file buffering flow

tools/cd_scripts/install_test.sh
One of the customer asked for providing a way of installation that doesn't require apt-key because that's deprecated from Ubuntu21+ and Debian 11+. This PR changes the release pipeline tests to use installation steps with apt-key command for Ubuntu21+ and Debian11+. 
NA
1. Manual - Tested with our release pipeline.
=> Update installation steps for not using apt-key

internal/cache/file/cache_handle.go, internal/cache/file/cache_handle_test.go
Handling io.ErrUnexpectedEOF error while reading via CacheHandle. This is required as kernel always sends the buffer of fixed size. When the objectSize is less the fixed buffer size, in that case we get io.ErrUnexpectedEOF error. Returning success in those cases.
NA
1. Manual - NA
=> Handling io.ErrUnexpectedEOF while reading via CacheHandle

perfmetrics/scripts/ml_tests/tf/resnet/setup_host_and_run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
This PR upgrades tf-models-official to version 2.13.2 (latest stable minor version with tensorflow 2.13) and DLC conatiner image to [tf-gpu.2-13](https://pantheon.corp.google.com/gcr/images/deeplearning-platform-release/GLOBAL/tf-gpu.2-13?e=13803378&mods=local_coliseum) (latest DLC image with compatible CUDA drivers).
NA
1. Manual - Manually ran the model. It is running successfully with better steps/sec values than previous runs.
=> Upgrade tensorflow model dependencies

internal/cache/file/cache_handler.go, internal/cache/file/cache_handler_test.go, internal/cache/util/util.go, internal/fs/fs.go, internal/fs/read_cache_test.go, internal/gcsx/random_reader.go, internal/gcsx/random_reader_test.go
1. Handling error the case when someone deletes the file cache externally.
2. Adding support to invalidate cache in case some deletes the file.
Important: What happens if the cache file is deleted externally? This means that the fileInfoCache contains an entry for the cache file, but the cache file is not available locally.
(a) If the fileCacheHandle is nil, in this case it will return a data-inconsistent error.
(b) In the case of an old cacheFileHandle, if the local file is deleted externally, this will return correct data until the handle is closed. This is because Linux does not delete a file until its link count is zero. When the fileHandle is open, it contributes to the link_count and therefore the file is not deleted and serves the data correctly.
NA
1. Manual - NA
3. Unit tests - …
=> Adding checks to catch - if cache is deleted externally

internal/cache/file/cache_handler.go, internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go, internal/cache/lru/lru.go, internal/cache/lru/lru_test.go, internal/locker/rw_locker.go
- Add lookup and update without changing order in LRU cache
- Also removed one of the unit test in job_test.go as it is expected that GetCacheHandle will insert fileInfo in fileInfoCache at the time of creating cache handle and initializing job.
NA
1. Manual - NA
2. Unit tests - Added unit test.
=> Add lookup and update without changing order in LRU cache

internal/cache/metadata/stat_cache.go, internal/cache/metadata/stat_cache_test.go, internal/storage/caching/integration_test.go, internal/storage/caching/mock_gcscaching/mock_stat_cache.go
This change switches internal.cache.metadata.statCache
to use gcsfuse-internal lru.Cache from
jacobsa/*lrucache.Cache .
This is a step towards unification of metadata cache with
the readonly cache interface and design. Currently
statCache takes in capacity (count) for initialization,
but is now well-placed to switch to size (in Mbytes)
It also removes CheckInvariants() from StatCache as 
the new lru cache doesn't expose its checkInvariants 
method, so StatCache also cannot implement a CheckInvariants()
method anymore.
NA
1. Manual - Sanity checks done locally: Mounting, listing, reads, writes, copying, unmount.
2. Unit tests - Ran and passed all locally. No new tests.
3. Integration tests - existing tests tested through presubmit tests. No new tests added.
=> Switch stat cache to gcsfuse internal lru.Cache

internal/config/mount_config.go, internal/config/testdata/invalid_log_rotate_config_1.yaml, internal/config/testdata/invalid_log_rotate_config_2.yaml, internal/config/testdata/valid_config.yaml, internal/config/testdata/valid_config_with_0_backup-file-count.yaml, internal/config/yaml_parser.go, internal/config/yaml_parser_test.go, internal/logger/logger.go, internal/logger/logger_test.go, tools/integration_tests/log_rotation/log_rotation_test.go, tools/integration_tests/operations/operations_test.go, tools/integration_tests/run_tests_mounted_directory.sh
Based on the limitation in lumberjack library that doesn't allow creation of 0 backup files, we are renaming "file-count" config to "backup-file-count".
1. Manual - Manually ran on VM and docker again to verify everything is working as intended
3. Integration tests - passed
=> Rename log rotate config

internal/cache/file/cache_handler.go, internal/cache/file/cache_handler_test.go
Truncate file on invalidation before deletion so that space is not taken because of open file handles.
NA
1. Manual - NA
2. Unit tests - Added where applicable.
=> Truncate file on invalidation before deletion

internal/fs/inode/dir.go
Changing the hardcoded type cache capacity from (1 << 16) to (1 << 22)
NA
1. Manual - NA
=> Increasing the hardcoded type cache capacity to 4 million for read-cache load test

perfmetrics/scripts/ml_tests/tf/resnet/setup_host_and_run_model.sh
curl command was failing due to DRIVER_VERSION variable.
NA
1. Manual - manually tested.
=> Fix tf-resnet model failure

docs/metrics.md, internal/cache/file/downloader/job.go, internal/fs/wrappers/monitoring.go, internal/gcsx/random_reader.go, internal/monitor/reader.go, internal/monitor/tags/tags.go, internal/util/util.go
Export file cache metrics via stackdriver
NA
1. Manual - Checked the metrics are exported on console (PTAL at metrics explorer of console to confirm).
Perf tests:
=> Export file cache metrics via stackdriver

internal/config/mount_config.go, internal/config/yaml_parser_test.go
This PR changes the default value of `compress` log rotate config to true by default so that rotated logs are compressed.
NA
1. Manual - NA
=> make log compression on by default

internal/cache/file/downloader/job.go
Wait for termination of async job during cancel and invalidation. 
Details:
Termination of Go routine is co-operative and not preemptive which means that when we signal job.downloadAsync to terminate by running job.cancelFunc() then it may not be immediately terminated and run few statements in the default case of select.
When CacheHandler.cleanUpEvictedEntry is called, it executes job.Invalidate + os.remove(file_in_cache) one after the other, because of that, it may happen that job.Invalidate signals the job.downloadAsync but it takes some time to terminate and meanwhile os.remove is called. If that happens, it's possible that job.downloadAsync is writing to the file in cache at that time and hence the file in cache will appear again which is not correct.
This is more graceful handling …
=> Wait for termination of async job during Cancel and Invalidate

perfmetrics/scripts/ml_tests/pytorch/run_model.sh
Reducing the epochs as pytorch2 long haul tests are running on NVIDIA L4 machines, which lack the powerful GPU of
the NVIDIA A100. So it is taking longer time to complete the training. We will set it back to 80 when the NVIDIA A100 GPU machine will be available.
NA
1. Manual - NA
=> Reduce epoches in pytorch2.0 model

perfmetrics/scripts/read_cache/run_read_cache_fio_workload.sh, perfmetrics/scripts/read_cache/setup.sh
1. Bug: number of threads flag was not being respected.
2. Changing the number of local-ssd for the test to 4.
NA
1. Manual - NA
=> Fixing issue in the fio scripts

internal/cache/metadata/stat_cache.go, internal/cache/metadata/stat_cache_test.go, internal/fs/caching_test.go, internal/fs/fs.go, internal/fs/fs_test.go, internal/fs/inode/base_dir.go, internal/fs/inode/base_dir_test.go, internal/gcsx/bucket_manager.go, internal/gcsx/bucket_manager_test.go, internal/storage/caching/integration_test.go, internal/storage/storageutil/create_object.go
Currently during dynamic-mount case,
each mounted bucket has its own dedicated
stat-cache instance. This change combines
all of them into one. This change does the
following:
1. Creates an instance of lru.Cache (called globalStatCache) in bucketManager, which is shared among all buckets (through their corresponding statCache objects).
2. Passes globalStatCache and a bucket names for creation of individual statCache objects.
3. Corresponding unit tests.
NA
1. Manual - Sanity testing done.
2. Unit tests - Ran locally and all passed. New tests added for this change.
3. Integration tests - Ran through presubmit.
=> Unify stat cache for all buckets in dynamic-mount

go.mod, go.sum
Upgrade golang.org/x/crypto from v0.14.0 to v0.17.0 to fix CVEs
NA
1. Manual - NA
2. Unit tests - Ran as part of presubmit tests (passed)
3. Integration tests - Ran as part of presubmit tests (passed)
4. Perf tests - 
(no regression)
=> dependabot-fixes

Dockerfile, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/run_e2e_tests.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
Upgrade to go-lang version 1.21.5
NA
1. Manual - NA
2. Unit tests - Ran as part of presubmits (passed)
3. Integration tests - Ran as part of presubmits (passed)
4. Perf tests: 
(no regression)
=> upgrade to go 1.21.5

perfmetrics/scripts/read_cache/mount_gcsfuse.sh
As we run the grep command as part of mount_gcsfuse process, hence, we used to print the pid of mount_gcsfuse process.
Corrected by using more gcsfuse specific grep search to uniquely identify the currently running gcsfuse process.
NA
1. Manual - NA
=> Fixing printing gcsfuse pid bug in the script

perfmetrics/scripts/job_files/seq_rand_read_write.fio
This is for internal bug id 316284545 .
Currently in the periodic perf tests, we
fsync after each write (set through fsync=1)
in all write tests. This poses two problems.
1. It underrates our write bandwidth as most of the runtime is spent in the sync calls and
little in the actual write operation.
2. This causes frequent sync which result in frequent object generations on GCS, which is
throttled by GCS.
This change should address both these problems.
NA
1. Manual - NA
=> Lower freq of syncs in periodic-perf-tests

perfmetrics/scripts/read_cache/mount_gcsfuse.sh
Adding sleep after the unmount
Why?
Sporadic failures have been observed within the file-cache flow, particularly when the subsequent mount operation immediately follows the unmount operation. By default, the unmount process occurs lazily, during which time the cache folder is deleted. This lazy deletion creates challenges in the subsequent mount process. Specifically, it is possible that the lazy deletion will delete a file after it has been created during the next mount operation. This results in an inconsistency where the fileInfoCache contains an entry for a file that is no longer present on the system.
NA
1. Manual - NA
=> Fixing script to fix the lazy deletion issue in file-cache

perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_host_and_run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
Tensorflow model was failing with the following error:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.8, please update your driver to a newer version, or use an earlier cuda container: unknown.
```
Fix: Upgraded driver version to 520.61.05 based on documentation: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions
Also updated VM image as ubuntu-2004-focal-v20230616 was deprecated.
NA
1. Manual - …
=> Fix tf model by upgrading driver version

internal/cache/file/cache_handle.go, internal/cache/file/cache_handle_test.go, internal/cache/file/cache_handler_test.go, internal/fs/read_cache_test.go, internal/gcsx/random_reader.go, perfmetrics/scripts/job_files/presubmit_perf_test.fio, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
Change LRU in file cache on every request from kernel. Also replaced file.Seek + io.ReadFull with file.ReadAt along with a check that number of bytes read into dst buffer is equal to requested number of bytes.
NA
1. Manual - NA
2. Unit tests - Added for LRU order.
3. Integration tests - Ran existing integration tests [here](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/28180e6a-2ac8-4dfe-9ba2-dc092fbf03a9)
=> Change LRU in file cache on every request from kernel

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-master.cfg, perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-release.cfg
Kokoro is not triggering on the define branch in the config. Kokoro is set up to use the commit hash from the parent configuration's branch for all subjobs, even if those subjobs with different branches. I have asked yaqs question on kokoro team but until it gets resolved we can use this workaround.
NA
1. Manual - NA
=> Kokoro is not triggering on the define branch in the config

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh
Issue:
Kokoro tests on the release branch were failing due to Git's inability to identify the intended branch.
**Error Message**:
```
fatal: ambiguous argument 'read_cache_release': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]
```
**Cause**:
Missing remote branch information.
**Resolution**:
Resolved by explicitly specifying the remote branch using origin/$BRANCH_NAME.
NA
1. Manual - Tested on local VM and kokoro
=> Fix e2e kokoro tests

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh
Problem:
Integration tests were failing due to we are building gcsfuse from release branch and testing from master commit only.
Fix:
To execute tests for a specific branch, ensure you've checked out from that branch first.
NA
1. Manual - Tested integration tests locally on VM
=> Fix e2e tests for release branch

perfmetrics/scripts/read_cache/mount_gcsfuse.sh, perfmetrics/scripts/read_cache/run_read_cache_fio_workload.sh
Fixing 2nd epoch onwards slowness in read-cache fio test
(a) Increasing the stat-cache capacity to more than 3 millions.
(b) Only clearing the page cache not inodes, just to keep type-cache intact for further epochs. Otherwise, it will try to populate the type-cache again and in the process it will make two stat calls for each in which one of them will be served from the stat-cache and another one will be served GCS since (during list negative entry is not stored in the stat-cache).
NA
1. Manual - NA
=> Fixing 2nd epoch onwards slowness in read-cache fio test

internal/gcsx/bucket_manager.go, internal/gcsx/bucket_manager_test.go, perfmetrics/scripts/read_cache/run_read_cache_fio_workload.sh
Moving the monitor bucket in the bottom of the hierarchy, just before the actual bucket implementation which interacts with GCS.
Why?
Currently, monitoring bucket is on the top of hierarchy, above fast-stat bucket. So, we see all the request/response gcs stackdriver metrics which is served by cache (fast-stat-bucket). Ideally, we should only see the metrics which is served by gcs server. Hence, fixing this by moving the monitoring bucket bottom of hierarchy.
Impact:
We don't get false Stat call in gcs stackdriver metrics. As you can see in the below screenshot containing before and after
metrics graph for the same workload.
NA
1. Manual - Verified debug gcs logs and exported stackdriver metrics before and after.
2. Unit tests - Automation.
=> Moving monitoring bucket bottom in hierarchy

internal/storage/storageutil/client.go, internal/storage/storageutil/client_test.go
GCSFuse was not respecting `https_proxy` and `http_proxy` environment variables. This was pointed out in bug https://github.com/GoogleCloudPlatform/gcsfuse/issues/1541
Setting http.ProxyFromEnvironment in the underlying http client fixes the issue. (Ref: [Stackoverflow](https://stackoverflow.com/questions/51845690/how-to-program-go-to-use-a-proxy-when-using-a-custom-transport/51848441#51848441))
https://github.com/GoogleCloudPlatform/gcsfuse/issues/1541
1. Manual - I confirmed through manual checks that requests are successfully flowing through the proxy server, regardless of whetherGCSFuse is running in foreground or background mode.
Proxy server access logs:
```
1703535566.729  20150 127.0.0.1 TCP_TUNNEL/200 5507 CONNECT storage.googleapis.com:443
1703535566.729  20226 127.0.0.1 …
```
=> Http proxy fix

internal/fs/fs.go, internal/gcsx/random_reader.go, internal/gcsx/random_reader_test.go
Updated the file cache logs to also have file handle by storing reference to fuseops.readOp in the read operation context.
Sample log:
```
{"time":{"timestampSeconds":1704433722,"timestampNanos":1704433722741155012},"severity":"TRACE","msg":"0930ffe0-1a86 <- FileCache(<redacted>:/file-10-mb, offset: 262144, size: 262144 handle: 28)"}
```
NA
1. Manual - Manually verified the logs are updated
=> Add file handle to file cache logs

perfmetrics/scripts/job_files/read_cache_load_test.fio
change file_service_type to random so that files in epoch are picked randomly
Ran for 100mb file size - 100% and 50%. 100% see neglible drop in perf (763.4 to 764 seconds and 50% doesn't see gain in perf. We will investigate it more but this change should anyways be done)
NA
1. Manual - Ran fio script manually.
=> change file_service_type to random so files in epoch are picked randomly

internal/logger/logger_test.go, internal/logger/slog_helper.go
This PR changes GCSFuse logging keys to be compatible with fluentD based on the following references:
1. https://cloud.google.com/logging/docs/agent/logging/configuration#timestamp-processing
2. https://cloud.google.com/logging/docs/agent/logging/configuration#special-fields
Changes summary:
1. JSON log structure time changed 
`"time":{"timestampSeconds":1694164762,"timestampNanos":1694164762084862036}`
to
`"timestamp":{"seconds":1704697907,"nanos":553918512}`
2. JSON log structure message changed from  
` "msg":"<log message>"`
to
` "message":"<log message>"`
Sample log:
```
{"timestamp":{"seconds":1704703429,"nanos":670828386},"severity":"TRACE","message":"fuse_debug: Op 0x00000144        connection.go:415] <- ReleaseDirHandle (PID 0)"}
```
NA
1. Manual - Manually verified the log …
=> make logging keys fluentD compatible

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-master.cfg, perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-release.cfg
We did temporary fix to fix this issue - https://github.com/GoogleCloudPlatform/gcsfuse/pull/1561 and  https://github.com/GoogleCloudPlatform/gcsfuse/pull/1567
We got solution so, undoing the changes did earlier.
NA
1. Manual - NA
=> Remove branch name env variable in periodic e2e tests

tools/integration_tests/util/mounting/mounting.go
Log output from the failed mount command for easier debugging in case of failure in GCSFuse integration tests.
Example:
```
2024/01/09 09:04:20 /tmp/gcsfuse_readwrite_test_2044354406/bin/gcsfuse --o=ro --implicit-dirs=true --config-file=/tmp/gcsfuse_readwrite_test_2044354406/config.yaml --debug_gcs --debug_fs --debug_fuse --log-file=/tmp/gcsfuse_readwrite_test_2044354406/gcsfuse.log --log-format=text bucket_name /tmp/gcsfuse_readwrite_test_2044354406/mnt
2024/01/09 09:04:20 Error:  parsing config file failed: error parsing config file: max-file-size-mb should be atleast 1
2024/01/09 09:04:20 mountGcsfuse: cannot mount gcsfuse: exit status 1
```
NA
1. Manual - Manually verified the log message.
=> log failed mount message in e2e tests

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/README.md, perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
The  experiment perf tests are failing as it's looking for `download-file-for-random-read` flag.
This change is due to this PR-https://github.com/GoogleCloudPlatform/gcsfuse/pull/1571
NA
1. Manual - Tested locally
=> Changing flag name to cache-file-for-range-read in experiment perf tests.

internal/fs/fs.go, internal/gcsx/random_reader.go, internal/gcsx/random_reader_test.go
use constant for read operation in context instead of using "readOp" string multiple times.
NA
1. Manual - NA
=> use constant for read operation in context

tools/integration_tests/util/test_setup/test_setup.go, tools/integration_tests/util/test_setup/test_setup_test.go
Post this change, package test_setup can be imported to support setup and teardown methods in tests. Setup and teardown methods can be used for per test setup and clean up. This is required for GCSFuse ReadCache functional tests to unmount and mount GCSFuse after each test.
Refer to `tools/integration_tests/util/test_setup/test_setup_test.go` for usage.
NA
1. Manual - NA
=> [ReadCacheFunctionalTest] add support for setup and teardown methods in tests

tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser_test.go, tools/integration_tests/util/setup/setup.go, tools/integration_tests/util/test_setup/test_setup_test.go
Integration tests started failing because all the tests in integration_tests directory run with --integration_test flag which was unused in these unit tests. 
Fix: Skip the tests if integration_test flag is set.
NA
1. Manual - NA
2. Unit tests - ran as part of presubmit
3. Integration tests - ran as part of presubmit
=> skip running unit tests in util package if integration test flag is set

tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/read_only_test.go, tools/integration_tests/read_cache/small_cache_ttl_test.go, tools/integration_tests/util/client/storage_client.go
R1: Full object read 
Another client has written to make it the file to change object generation
R2: Full object read 
R3: Full object read (after stat cache expiry) 
R1 - cache miss
R2 - cache hit (but stale data)
R3 - cache miss (new data)
NA
1. Manual - NA
=> [ReadCacheFunctionalTest] Test 2: Object modified by another client after read.

tools/integration_tests/read_cache/disabled_cache_ttl_test.go, tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/read_only_test.go, tools/integration_tests/read_cache/small_cache_ttl_test.go, tools/integration_tests/util/client/gcs_helper.go, tools/integration_tests/util/client/storage_client.go, tools/integration_tests/util/operations/file_operations.go
With stat cache ttl = 0
R1: Full object read 
Another client has written to make it the file to change object generation
R2: Full object read 
R3: Full object read
R1 - cache miss
R2 - cache miss (serves updated data as cache ttl is 0)
R3 - cache hit (serves updated data)
NA
1. Manual - NA
3. Integration tests - In progress
=> [ReadCacheFunctionalTest] Test 3: Object modified by another client after read with stat cache ttl 0

tools/integration_tests/read_cache/disabled_cache_ttl_test.go, tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/local_modification_test.go, tools/integration_tests/read_cache/read_only_test.go, tools/integration_tests/read_cache/remount_test.go, tools/integration_tests/read_cache/setup_test.go, tools/integration_tests/read_cache/small_cache_ttl_test.go
R1: Read file sequentially
R2: read again
Remount GCSFuse
R3: Read same file again sequentially
R4: Read same file again sequentially
R1: Cache miss
R2: Cache Hit
Validate cache directory empty
R3: Cache miss
R4: cache hit
NA
1. Manual - NA
3. Integration tests - Ran via presubmits
=> [ReadCacheFunctionalTest] Test 19: Test that cache works as intended on remounting GCSFuse and data is cleared between remount.

tools/integration_tests/read_cache/disabled_cache_ttl_test.go, tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/local_modification_test.go, tools/integration_tests/read_cache/read_only_test.go, tools/integration_tests/read_cache/remount_test.go, tools/integration_tests/read_cache/setup_test.go, tools/integration_tests/read_cache/small_cache_ttl_test.go, tools/integration_tests/util/client/gcs_helper.go, tools/integration_tests/util/client/storage_client.go, tools/integration_tests/util/operations/file_operations.go
With flag cacheFileForRangeRead true
R1: Single file random read of size more than cache capacity
R2: read again
R1: Cache miss
R2: Cache Miss (because the file won't be cached)
With flag cacheFileForRangeRead false
R1: Single file random read of size more than cache capacity
R2: read again
R1: Cache miss
R2: Cache Miss (because the file won't be cached)
This PR also includes refactoring to make flag setup more efficient.
NA
1. Manual - NA
3. Integration tests - Ran via presubmits
=> [ReadCacheFunctionalTest] Test 11 and 12: Single file random read of size more than cache capacity

Dockerfile, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/run_e2e_tests.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
Upgrade Go version from 1.21.5 to 1.21.6
NA
1. Manual - NA
Performance tests
Integration tests [link](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/9c23d3f3-38a9-4df6-9c33-b3a40c848c59/log)
=> Upgrade Go version from 1.21.5 to 1.21.6

internal/logger/logger_test.go
log's timestamp in nanoseconds can be any value between 0 to 999999999. Updated the regex to match with 0 to 9 digit number.
NA
1. Manual - NA
=> fix flaky log test

perfmetrics/scripts/continuous_test/ml_tests/pytorch/v2/dino/build.sh, perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/pytorch/v2/dino/setup_host_and_run_container.sh
We reduced the epochs as pytorch2 long haul tests are running on NVIDIA L4 machines, which lack the powerful GPU of the NVIDIA A100. 
1. NVIDIA A100 GPU machine is available now on `asia-northeast1-a` region so changed the machine from NVIDIA L4 to NVIDIA A100.
2. Increasing epochs to 80 again.
3. Updating driver version, which is compatible with NVIDIA A100 machine.
NA
=> Updating NVIDIA A100 GPU machine for pytorch2.0

tools/integration_tests/gzip/read_gzip_test.go, tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_large_files/random_read_large_file_test.go, tools/integration_tests/util/operations/file_operations.go
gzip and random read large file tests started failing after ReadChunkFromFile method started using O_DIRECT flag. This is likely due to alignment restrictions when using O_DIRECT flag. Ref: [manpage](https://man7.org/linux/man-pages/man2/read.2.html#:~:text=EINVAL%20fd%20is%20attached%20to%20an%20object%20which%20is%20unsuitable%20for%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20reading%3B%20or%20the%20file%20was%20opened%20with%20the%20O_DIRECT%20flag%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20and%20either%20the%20address%20specified%20in%20buf%2C%20the%20value%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20specified%20in%20count%2C%20or%20the%20file%20offset%20is%20not%20suitably%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20aligned.)
This was unfortunately not caught in PR: …
=> fix tests which started failing because of 0_DIRECT flag in ReadChunkFromFile method

internal/cache/file/cache_handler.go, internal/cache/file/cache_handler_test.go, internal/gcsx/random_reader_test.go
**Before fix:**
We don't restart the async job once failed and always fallback to GCS.
**After fix:**
Invalidate the cache for the object corresponding to failed Download job to initiate the caching from scratch.
Other approach: handling at the time of failure - [PR](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1652)
NA
1. Manual - NA
2. Unit tests - Added unit test to simulate - failure, invalidate and cacheHit again.
3. Integration tests - Automation.
=> Support to restart failed async job in the next call

main.go
Remove obsolete warning for stat-cache-capacity
This is an outdated warning that was supposed for warn for use
of flag `stat-cache-capacity` and suggested to switch to
`metadata-cache:stat-cache-max-size-mb` . Now
`metadata-cache:stat-cache-max-size-mb` itself has become irrelevant,
and stat-cache-capacity is no longer meant to be deprecated soon, so
removing this warning.
NA
1. Manual - Did sanity testing. Also the following warning went away after the change.
```
{"time":"30/01/2024 07:57:46.029872","severity":"WARNING","message":"Old flag stat-cache-capacity used! Please switch to config parameter 'metadata-cache: stat-cache-max-size-mb'."}
```
3. Unit tests - Ran locally.
4. Integration tests - Not needed.
=> Remove unnecessary warning logs

internal/cache/metadata/stat_cache.go, internal/cache/metadata/stat_cache_test.go, internal/fs/caching_test.go, internal/gcsx/bucket_manager.go, internal/storage/caching/integration_test.go
This is needed to remove any unnecessary calculations at the stat-cache operations time.
NA
1. Manual - Did sanity testing
2. Unit tests - Passed locally
3. Integration tests - Ran through presubmit
=> Fix stat-cache entry-size at 1

.github/dependabot.yml
Change dependency type from "all" to "direct" in .github/dependabot.yml file for go.mod dependencies.
NA
1. Manual - NA
=> dependabot should bump only direct dependencies

tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go, tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/range_read_test.go, tools/integration_tests/read_cache/setup_test.go
TestRangeReadsWithinReadChunkSize
R1: Read a file starting at offset 0
R2: read again within range of read chunk size (8 MiB)
R1: Cache miss
R2: Cache Hit
TestRangeReadsBeyondReadChunkSizeWithWait
R1: Read a file starting at offset 0
wait for file to be cached
R2: read again at offset 38MiB
R1: Cache miss
R2: Cache Hit
TestRangeReadsBeyondReadChunkSizeWithoutWait
R1: Read a file starting at offset 0
do not wait for file to be cached
R2: read again at offset 38MiB
R1: Cache miss
R2: Cache miss (file not yet cached)
NA
1. Manual - NA
3. Integration tests - ran via kokoro
=> [ReadCacheFunctionalTest] Test 14, 15, 16: Range read tests

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
Range Reads
FlagDownloadRandom: False
R1: (Obj1), [5000,6000]
// Wait for sufficient time for file to be downloaded
R2: (Obj1), [2000,3000]
R1: Cache Miss
R2: Cache Miss 
NA
1. Manual - NA
=> [ReadCacheFunctionalTest] Test 17 range reads with cacheFileForRangeRead false

internal/gcsx/random_reader.go, internal/gcsx/random_reader_test.go
Random reads were not working as intended; they did not reuse the existing reader, even when existing reader had the data to serve the request. 
This issue occurred because we were using the Read method (instead of ReadFull). According to the [documentation](https://cs.opensource.google/go/go/+/refs/tags/go1.21.6:src/io/io.go;drc=1ff89009f198ad5bae3549dd3b992882bd97e5f8;l=60), this method does not wait for the entire data to be available, preventing the reader's start offset from being moved by the required number of bytes.
Fix: We should use io.ReadFull() instead.
Before this change:
```
time="06/02/2024 08:34:55.221154" severity=TRACE message="fuse_debug: Op 0x0000016e        connection.go:415] <- ReadFile (inode 2, PID 367041, handle 27, offset 41943040, 16384 bytes)"
time="06/02/2024 …
```
=> [Fix] Random reads won't re-use previous reader even if existing reader can serve the request

internal/cache/data/file_info.go, internal/cache/file/cache_handle_test.go, internal/cache/file/cache_handler.go, internal/cache/file/cache_handler_test.go, internal/cache/file/downloader/downloader.go, internal/cache/file/downloader/downloader_test.go, internal/cache/file/downloader/job_test.go, internal/cache/util/util.go, internal/cache/util/util_test.go, internal/fs/fs.go, internal/gcsx/random_reader_test.go
[Link](https://b.corp.google.com/issues/322301637)
[With -o allow_option] Tested by adding allow_other, users other than owner were able to view cache folder and files.
[Without -o allow_option] Tested without allow_other option, users other than owner were NOT able to cd into cache folder and was unable to see cache file name or content of cache dir.
3. Unit tests - Done
4. Integration tests - Added new card for automation
=> Latest allow other cache dir fix

internal/cache/file/cache_handle.go, internal/cache/file/cache_handle_test.go, internal/cache/file/cache_handler.go, internal/cache/file/cache_handler_test.go, internal/cache/file/downloader/downloader.go, internal/cache/file/downloader/downloader_test.go, internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go, internal/gcsx/random_reader_test.go
Optimize memory by removing async job after completion/failure
This PR includes the following changes:
Functional change:
1. The async job is removed from memory once the job is stopped (i.e. complete/failed) or invalidated in case of eviction. We are doing this to reduce the overall memory footprint of GCSFuse with read cache is enabled.
Code changes:
1. Documentation fixes and changes corresponding to code changes.
3. Unit test fixes for test files under internal/cache/. This includes not using the same function in "Arrange" part of unit test that is being tested in unit test.
4. Addition of few more unit test cases.
5. job.go: (a) Added a property called removeJobCallback to Job struct which is call back function to remove job from JobManager. (b) Call removeJobCallback function when …
=> Optimize memory by removing async job after completion/failure

tools/integration_tests/read_cache/range_read_test.go, tools/integration_tests/read_cache/setup_test.go
TestRangeReadsBeyondReadChunkSizeWithoutWait was flaky as cache hit was coming to be true. Increased the file size to 100MiB (from 50MiB) to ensure cache hit is false in this case.  
NA
1. Manual - NA
=> fix flaky TestRangeReadsBeyondReadChunkSizeWithoutWait test

flags.go
Removing experimental-local-file-cache flag, this flag value will be default false and user won't be able to pass this flag after this.
NA
1. Manual - `help` command does not show the flag and while using the flag it was returning error.
=> Removing experimental-local-file-cache flag

internal/cache/util/util.go, internal/cache/util/util_test.go, internal/fs/fs.go, internal/fs/read_cache_test.go, mount.go
Problem
1. GCSFuse supports two more permissions related flags that are file-mode and dir-mode which decides the permissions of files and directories inside the gcsfuse mount. Note if file-mode is set 777 but allow-other is not passed then other users except owner will still not be able to access the files via GCSFuse mount. So allow-other tells whether to even respect file-mode and dir-mode for users other than mounting user or not.
2. Mounting gcsfuse with --allow-other flag and setting file-mode 700 is a completely valid thing to do from user's perspective. If user mounts gcsfuse with this config then other users on machine will not be able to access files via GCSFuse mount but will be able to access cache directory directly which is wrong. 
Solution
Always set 700 and 600 permissions …
=> Fix cache dir permissions

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go, tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go, tools/integration_tests/read_cache/setup_test.go
Scenario:
With cacheFileForRangeRead config false
cache size: 50 MiB:
R1 50 MiB file (parallel)
R2 50MiB file (parallel)
Expected: 
R1 cache evicted, follow up read calls (from R1 operation) will not cache R1 50MiB file as the reads will be considered non sequential. In the end R2 file should be cached.
NA
1. Manual - NA
=> [ReadCacheFunctionalTest] Test Concurrent Reads results in non sequential read behavior if download for range read flag is false

internal/cache/file/cache_handle_test.go, internal/cache/file/cache_handler.go, internal/cache/file/cache_handler_test.go, internal/cache/file/downloader/downloader.go, internal/cache/file/downloader/downloader_test.go, internal/cache/file/downloader/job_test.go, internal/cache/util/util.go, internal/cache/util/util_test.go, internal/config/mount_config.go, internal/config/testdata/invalid_filecachesize_config.yaml, internal/config/testdata/valid_config.yaml, internal/config/yaml_parser.go, internal/config/yaml_parser_test.go, internal/fs/fs.go, internal/fs/read_cache_test.go, internal/gcsx/random_reader_test.go, main_test.go, perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json, perfmetrics/scripts/read_cache/generate_yml_config.sh, perfmetrics/scripts/read_cache/mount_gcsfuse.sh, tools/integration_tests/operations/operations_test.go, tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/setup_test.go, tools/integration_tests/read_large_files/read_large_files_test.go, tools/integration_tests/readonly/readonly_test.go, tools/integration_tests/run_tests_mounted_directory.sh
1. Rename read-cache config-file variables
1. "max-size-in-mb" -> "max-size-mb"
2. "cache-location" -> "cache-dir"
2. Did deep replacement of similar identifiers (using regex) throughout the code.
NA
1. Manual - Ran sanity tests.
2. Unit tests - Ran and passed locally. No new tests.
4. Integration tests - Ran and passed through presubmit. No new tests.
=> Rename read-cache config vars

.github/CODEOWNERS
Ashmeen should be co-owner of integration tests (and not the sole-owner).
NA
1. Manual - NA
=> Make ashmeen co-owner of integration tests

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Change max-size-in-mb to max-size-mbin file-cache in
perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json.
This is a parallel of https://github.com/GoogleCloudPlatform/gcsfuse/pull/1703 which is for read_cache_release branch.
NA
1. Manual - NA
=> Change max-size-in-mb to max-size-mb

tools/integration_tests/util/client/gcs_helper.go, tools/integration_tests/util/client/storage_client.go, tools/integration_tests/write_large_files/concurrent_write_files_test.go, tools/integration_tests/write_large_files/random_write_large_file_test.go, tools/integration_tests/write_large_files/seq_write_large_file_test.go, tools/integration_tests/write_large_files/write_large_files_test.go
We were using `gsutil` or `gcloud` command to download file from gcs which is suddenly breaking with crcmod issue on arm64 machines. Changing that approach to download with storageclient instead of `gsutil` or `gcloud`.
CreateStorageClientWithTimeOut function is getting used in read_cache functional tests, we will remove [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/read_cache_release/tools/integration_tests/read_cache/helpers_test.go#L181) function whenever we will back merge.
NA
1. Manual - Tested manually on VM
3. Integration tests - louhi and kokoro
=> Download file using storage client

flags.go, flags_test.go, internal/config/config_util.go, internal/config/config_util_test.go, internal/config/mount_config.go, internal/config/yaml_parser_test.go, internal/fs/fs.go, internal/fs/read_cache_test.go, internal/util/util.go, main.go, perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Enable or disable file cache via cache-dir and not via max-size-mb. Also, make max-size-mb default as -1. Also did some refactoring to make sure util.go don't make any other internal package imports and we also don't go into cyclic dependency.
NA
1. Manual - NA
3. Integration tests - [kokoro build logs](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/f0049d29-36df-4130-acdd-254755dfc901/summary)
=> Enable or disable file cache via cache-dir

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Add cache-dir to experiment configuration
NA
1. Manual - NA
=> Add cache-dir to experiment configuration of read cache tests

internal/cache/file/cache_handle_test.go, internal/cache/file/cache_handler_test.go, internal/cache/file/downloader/job_test.go, internal/fs/inode/file.go, internal/storage/gcs/object.go, internal/storage/storageutil/object_attrs.go, internal/storage/storageutil/object_attrs_test.go
1. This PR adds struct for ExtendedObjectAttributes which contains the missing attributes of Object which are not present in MinObject.
2. This PR also adds following converters to storageutil package:
1. ConvertObjToExtendedAttributes
2. ConvertMinObjectAndExtendedAttributesToObject
Internal bug b/325024088
1. Manual - NA
=> [PR-1] Add struct for extended object attribute

internal/fs/inode/file.go, internal/storage/gcs/request.go
This PR includes ReturnFull parameter in stat object request to determine whether ExtendedObjectAttributes should be returned from StatObject Call.
ReturnFull is only passed true during clobbered check.
NA
1. Manual - NA
=> [PR-3] Include ReturnFull in stat object request

tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/range_read_test.go
Merge [Run tests with static mounting only to reduce run time in e2e tests](https://github.com/GoogleCloudPlatform/gcsfuse/commit/01ad85a9c076a53f7ce8e89aafb3af71eb8cc096) ([1736](https://github.com/GoogleCloudPlatform/gcsfuse/commit/01ad85a9c076a53f7ce8e89aafb3af71eb8cc096)) to master.
This is cherry-picking the fix in high runtime of the e2e tests from read_cache_release branch to the master branch.
NA
1. Manual - NA
3. Integration tests - Through presubmit
=> Merge "Run tests with static mounting only to reduce run time in e2e tests" to master

internal/cache/file/cache_handle_test.go, internal/cache/file/cache_handler_test.go, internal/cache/file/downloader/job_test.go, internal/fs/inode/dir.go, internal/fs/inode/file.go, internal/fs/inode/file_test.go, internal/fs/local_modifications_test.go, internal/gcsx/integration_test.go, internal/gcsx/prefix_bucket.go, internal/gcsx/prefix_bucket_test.go, internal/monitor/bucket.go, internal/ratelimit/throttled_bucket.go, internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go, internal/storage/caching/fast_stat_bucket.go, internal/storage/caching/fast_stat_bucket_test.go, internal/storage/caching/integration_test.go, internal/storage/debug_bucket.go, internal/storage/fake/bucket.go, internal/storage/fake/testing/bucket_tests.go, internal/storage/gcs/bucket.go, internal/storage/mock_bucket.go
This PR changes StatObjet method to return MinObject and ExtendedObjectAttributes instead of complete GCS Object. This will enable us to store MinObject in stat cache.
NA
1. Manual - NA
=> [PR-2] Changes to StatObject to return min object and extended object attributes

internal/cache/metadata/stat_cache.go, internal/cache/metadata/stat_cache_test.go, internal/storage/caching/fast_stat_bucket.go, internal/storage/caching/fast_stat_bucket_test.go, internal/storage/caching/mock_gcscaching/mock_stat_cache.go, internal/util/sizeof.go, internal/util/sizeof_test.go
This PR includes changes to store minimal object in GCSFuse stat cache instead of all the attributes of object.
Insert and LookUp method of stat cache interface & all the implementations are also changed to use gcs.MinObject instead of gcs.Object.
NA
1. Manual - NA
=> [PR-4] Store min object in stat cache

internal/fs/fs.go, internal/fs/inode/base_dir.go, internal/fs/inode/base_dir_test.go, internal/fs/inode/core.go, internal/fs/inode/core_test.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go, internal/fs/inode/explicit_dir.go, internal/fs/inode/file.go, internal/fs/inode/file_test.go, internal/fs/inode/symlink.go, internal/fs/inode/symlink_test.go
Change core inode implementation to store min object instead of complete object. 
1. Manual - NA
=> [PR-5] Store min object in core inode instead of complete object

internal/fs/fs.go, internal/fs/handle/dir_handle.go, internal/fs/handle/dir_handle_test.go, internal/fs/inode/dir.go, tools/integration_tests/local_file/read_dir_test.go
Concurrently listing a directory along with file creation caused GCSFuse process to crash causing transport endpoint not connected errors. This was happening because fs.localFileInodes map was being read without acquiring a lock. Go maps are not safe for concurrent reads and writes which caused the crash.
Fix: Acquire fs lock before reading localFileInodes map
https://github.com/GoogleCloudPlatform/gcsfuse/issues/1726
https://github.com/GoogleCloudPlatform/gcsfuse/issues/1603
1. Manual - Manually verified that the issue is no longer happening by listing a directory 1000 times and creating 1000 files in a separate directory on GCSFuse mount.
3. Integration tests - Added and ran via KOKORO
5. List Benchmarks -
=> [Bug fix] Fix concurrent list directory and file creation

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go, tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go, tools/integration_tests/read_cache/disabled_cache_ttl_test.go, tools/integration_tests/read_cache/local_modification_test.go, tools/integration_tests/read_cache/range_read_test.go, tools/integration_tests/read_cache/read_only_test.go, tools/integration_tests/read_cache/setup_test.go, tools/integration_tests/read_cache/small_cache_ttl_test.go, tools/integration_tests/run_tests_mounted_directory.sh
This PR includes 
* refactoring and setup to run read cache functional tests with mounted directory flag.
* Shell script to run read cache tests on an already mounted directory.
NA
1. Manual - Manually ran the tests on a GCE VM.
=> [ReadCacheFunctionalTests] Setup to run read cache functional tests on an already mounted directory

docs/semantics.md, flags.go, internal/cache/metadata/stat_cache.go, internal/cache/metadata/stat_cache_test.go, internal/mount/flag.go, internal/mount/flag_test.go
This PR includes the following changes:
* Changed AverageSizeOfPositiveStatCacheEntry to 1400 bytes (from 2400 bytes) based on listing benchmarks done when stat cache stores gcs.MinObject instead of entire gcs.Object. 
* Accordingly DefaultStatCacheCapacity is increased to 20460 entries (default stat cache size divided by size of each entry = `32*1024*1024/1640`)
* The delta factor between computed gcs.MinObject and RSS reduced to 515.
NA
1. Manual - NA
2. Unit tests - updated
=> [PR-6] changes to account for min object size instead of object size

.github/workflows/ci.yml, Dockerfile, go.mod, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/read_cache/setup.sh, perfmetrics/scripts/run_e2e_tests.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
Upgrade to golang 1.22
NA
1. Manual - Did sanity testing.
3. Integration tests - Ran through presubmit - [passed](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/767422dc-ccd0-4c6c-a6ed-f34437a02db5)
4. Perf tests results
```
First run
---------
+--------+------------+--------------+------------+-------------+--------------+
| Branch | File Size  |   Read BW    |  Write BW  | RandRead BW | RandWrite BW |
+--------+------------+--------------+------------+-------------+--------------+
| Master |  0.25MiB   |  496.7MiB/s  | 1.21MiB/s  |  71.83MiB/s |  1.27MiB/s   |
|   PR   |  0.25MiB   |  509.3MiB/s  |  1.3MiB/s  |  71.32MiB/s |  1.08MiB/s   |
|        |            |              |            |             | …
```
=> Upgrade to golang 1.22

Dockerfile
Bumps alpine from 3.13 to 3.19.
---
updated-dependencies:
- dependency-name: alpine dependency-type: direct:production update-type: version-update:semver-minor ...
Clone of #1579  .
NA
1. Manual - NA
=> Bump alpine from 3.13 to 3.19

internal/fs/fs.go
Problem: we should not use panic statement for the user-controlled behavior. Also, we were getting generic failure while mounting.
Before the change, stdout for the mount with no permission to create cache-dir:
```
daemonize.Run: readFromProcess: Decode: EOF
```
After the change, stdout for the mount with no permission to create cache-dir:
```
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithStorageHandle: fs.NewServer: create file system: while creating NewFileSystem(): createFileCacheHandler: while creating file cache directory: error in creating directory structure /prince/gcsfuse-file-cache: mkdir /prince: permission denied
```
NA
1. Manual - checked the mount failing behavior manually.
2. Unit tests - Decided to go without unit-test for now, since we don't have …
=> Replacing panic with error message

main.go
The following changes in logging.
* Log `File system has been successfully mounted.` on stdout if mount succeeds, even if has specified log-file. This change is only for non-`--foreground` case.
* If log-file is specified, don't log mount-config and flags on stdout, to avoid duplication of log.
* Always prefix all mount-error logs with "Error while mounting gcsfuse: " for clarity.
More detailed log is as follows:
```
$ go run .  $bucket $mountpath
{"time":"28/02/2024 07:46:07.408051","severity":"INFO","message":"Start gcsfuse/unknown (Go version go1.22-20240109-RC01 cl/597041403 +dcbe772469 X:fieldtrack,boringcrypto) for app \"\" using mount point: /usr/local/google/home/gargnitin/work/cloud/storage/client/gcsfuse/test_buckets/gargnitin-fuse-test-bucket1-mount\n"}
{"time":"28/02/2024 …
```
=> Improve default logs on mounting

.github/workflows/ci.yml, Dockerfile, go.mod, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/read_cache/setup.sh, perfmetrics/scripts/run_e2e_tests.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
This reverts commit 3adecdfe5270ed28fc230ea8cb91caa0b5e9b293 (#1753). This is needed to fix the GKE build failure caused by `go get error` i.e.
```
go: go.mod file not found in current directory or any parent directory.                                                                                                                                                                                                                 
'go get' is no longer supported outside a module.                                                                                                                                                                                                                               
To build and install a command, use 'go install' with a version, …
```
=> Revert "Upgrade to golang 1.22 (#1753)"

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
* Experimental dashboard config to run v1 benchmark with gRPC_support1
NA
1. Manual - NA
=> Experimental dashboard config to run v1 benchmark with gRPC_support1

tools/integration_tests/operations/operations_test.go, tools/integration_tests/run_tests_mounted_directory.sh, tools/integration_tests/util/client/storage_client.go, tools/integration_tests/util/setup/setup.go
E2E tests started failing with mounted directory flag because we were not setting the bucket and object properly after refactoring changes https://github.com/GoogleCloudPlatform/gcsfuse/pull/1771. 
Also reverted the changes to expose onlyirMounted flag as GKE team is not using it.
NA
1. Manual - Manually ran the script on GCE VM.
=> Fix e2e tests

perfmetrics/scripts/run_e2e_tests.sh
Kokoro e2e tests are failing on arm64 machine with
```
Beginning update. This process may take several minutes.
ERROR: (gcloud.components.update) You cannot perform this action because this Google Cloud CLI installation is managed by an external package manager.
Please consider using a separate installation of the Google Cloud CLI created through the default mechanism described at: https://cloud.google.com/sdk/
```
NA
1. Manual - tested on local kokoro setup
=> fix kokoro e2e tests

.github/workflows/ci.yml, Dockerfile, go.mod, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/read_cache/setup.sh, perfmetrics/scripts/run_e2e_tests.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
* Reapply "Upgrade to golang 1.22 (#1753)" (#1766)
This reverts commit a63a46fdbecbcfa58591e76a9bf49af6239ae7f1.
* Fixes dockerfiles which failed with go 1.22, because of `go get` error, by switching to `git clone` (in the docker container).
* Upgrade to 1.22.1
NA
1. Manual - Sanity testing
3. Integration tests - [Passed](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/a557edef-b441-4b82-a37a-06757750634a).
4. Perf tests
```
+--------+------------+--------------+------------+--------------+--------------+
+--------+------------+--------------+------------+--------------+--------------+
| Master |  0.25MiB   | 536.37MiB/s  | 1.26MiB/s  | …
```
=> Upgrade to go 1.22.1 (with fix for dockerfiles)

docs/semantics.md
This updates the semantics.md for the changes
related to replacement of gcs.Object with MinObject in stat-cache and in other places.
This is a cherry-pick from [this](https://github.com/GoogleCloudPlatform/gcsfuse/pull/1752/files#diff-fb497abe2ee21cd857a4434d6fa6aa054e45cfa22e73808db344344ea8d492e9) .
NA
1. Manual - NA
=> Update semantics for MinObject in stat-cache in march_2024_release

perfmetrics/scripts/run_e2e_tests.sh
Issue :  The gcloud command exists in two locations on a Kokoro ARM64 machine: /usr/bin/gcloud and /usr/snap/gcloud.
Fix: added new path as prefix in PATH env variable.
NA
1. Manual - local kokoro setup
3. Integration tests - Kokoro
=> Fix e2e tests on arm64 machine

tools/containerize_gcsfuse_docker/Dockerfile, tools/package_gcsfuse_docker/Dockerfile
Switch `git clone --depth 1 BRANCH_NAME` to
`git clone && git checkout BRANCH_NAME` to
extend support for BRANCH_NAME to be commit-hash
apart from branch-name or tag.
This is of course slower than `git clone --depth 1`, but is compatible with commit IDs too.
NA
1. Manual - NA
=> Allow Dockerfiles to clone from commit-hash too

perfmetrics/scripts/run_e2e_tests.sh, tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/testdata/create_objects.sh
Description
create a main method for all execution steps to be orchestrated at one place
extracted bucket creation and cleanup to a method | add hns bucket creation and clean up
run operations and implicit package tests for hns bucket
adds create_hns_buckets to create bucket for hns
seggregated check for hns test failures
reafctor variable names to lower case to make it consistent and more readable ([ref](https://stackoverflow.com/questions/673055/correct-bash-and-shell-script-variable-capitalization#:~:text=If%20it%27s%20your%20variable%2C%20lowercase%20it.%20If%20you%20export%20it%2C%20uppercase%20it.))
fix echo statement for hns bucket name
refactoring move actual test calls into functions for flat and hns bu…
adds bucket for hns in allow list project
Link to the issue in case of a bug …
=> refactor run_e2e_tests script | add hns tests

tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/util/client/gcs_helper.go, tools/integration_tests/util/operations/file_operations.go
Instead of comparing content read with GCS and cached file with GCS, calculate CRC of the file and validate that it matches the CRC values on GCS.
NA
1. Manual - Manually ran mounted directory tests.
=> Add crc check to read cache functional tests

perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh
Increase the wait time to 15 minutes for VM to setup as the pytorch v2 takes more than 10 minutes and fails every 7 days when the model starts.
NA
1. Manual - NA
=> Increase the wait time to 15 minutes for VM setup in ML tests.

flags.go, internal/mount/flag.go, main.go, main_test.go
Adding one more candidate value `grpc` as part of client-protocol flag. This will enable gcsfuse to communicate with cloud-storage using grpc client.
NA
1. Manual - Checked grpc integration is working fine.
=> PR3: GRPC - Add support of `grpc` value as client-protocol flag

internal/fs/local_file_test.go, internal/fs/local_modifications_test.go
This PR adds composite (fs_test package) tests for min object changes to validate extended object attributes are properly written.
NA
1. Manual - NA
=> composite test for min object changes

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
- Changes to support gRPC flow in the experimental dashboard script (renaming the bucket name, also ensured same region of GCP vm and bucket for direct path).
- Modified the existing `gRPC disabled` dashboard config with `gRPC enabled` config.
NA
1. Manual - NA
=> Adding experimental config to benchmark grpc performance

perfmetrics/scripts/run_e2e_tests.sh
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/perfmetrics/scripts/run_e2e_tests.sh#L185
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/perfmetrics/scripts/run_e2e_tests.sh#L205
If a test fails, an error is raised/thrown, causing the program to exit that section of code and preventing execution of subsequent lines.
Fixed that by doing return instead of exit. 
NA
1. Manual - NA
=> Fix exit code issue in script

flags.go, internal/storage/storage_handle.go, internal/storage/storageutil/client.go, internal/storage/storageutil/client_test.go
`STORAGE_EMULATOR_HOST_GRPC` was not working with grpc client, as internally [go-sdk](https://github.com/googleapis/google-cloud-go/blob/67d353beefe3b607c08c891876fbd95ab89e5fe3/storage/grpc_client.go#L97) sets option.WithoutAuthentication when this environment variable is set. As we are setting the creds everytime hence it fails because of [this](https://github.com/googleapis/google-api-go-client/blob/3daccecaae7b1bcd1371a44cb2d25b2fec4f34f2/internal/settings.go#L109) check.
```
Error while mounting gcsfuse: Failed to create storage handle using createStorageHandle: go storage client creation failed: options.WithoutAuthentication is incompatible with any option that provides credentials
```
Simulating the same behaviour for custom-endpoint as for setting `STORAGE_EMULATOR_HOST_GRPC` …
=> Fixing custom-endpoint issue in grpc

perfmetrics/scripts/continuous_test/gcp_ubuntu/periodic_experiments/experiments_configuration.json
Changes
1. Extended end-dates from 2023/03/31 to very high end dates to avoid having to update the end dates frequently.
2. Switched experiments using `read_cache_release` branches to master branch.
3. Changed names of the updated tests.
NA
1. Manual - NA
=> Update periodic experiments json

tools/integration_tests/managed_folders/admin_permissions_test.go, tools/integration_tests/managed_folders/test_helper.go, tools/integration_tests/util/operations/dir_operations.go
- Added 10s sleep for policy to get propagate.
NA
1. Manual - Ran tests for 10 times to check flaky ness on arm64 machine.
=> Fix flaky e2e tests for managed folder

perfmetrics/scripts/run_e2e_tests.sh, tools/integration_tests/read_large_files/concurrent_read_files_test.go, tools/integration_tests/read_large_files/random_read_large_file_test.go, tools/integration_tests/read_large_files/read_large_files_test.go, tools/integration_tests/read_large_files/seq_read_large_file_test.go
Made read large files package independent, to make it parallel run with other packages.
NA
1. Manual - NA
=> Making read large files test package parallell

perfmetrics/scripts/run_e2e_tests.sh, tools/integration_tests/rename_dir_limit/move_dir_test.go, tools/integration_tests/rename_dir_limit/rename_dir_limit_test.go, tools/integration_tests/rename_dir_limit/rename_dir_test.go
Made rename dir limit package independent, to make it parallel run with other packages.
NA
1. Manual - NA
=> Making rename dir limit test package parallell

internal/storage/storageutil/custom_retry.go
Adding info log, in case operation is retried because of some retriable error.
Sample log:
```
time="19/04/2024 01:26:00.013023" severity=INFO message="Retrying for the error: Get \"https://storage.googleapis.com/storage/v1/b/princer-working-dirs/o?alt=json&delimiter=&endOffset=&includeFoldersAsPrefixes=false&includeTrailingDelimiter=false&matchGlob=&maxResults=1&pageToken=&prefix=&prettyPrint=false&projection=full&startOffset=&versions=false\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="19/04/2024 01:26:00.632900" severity=INFO message="Retrying for the error: Get \"https://storage.googleapis.com/storage/v1/b/princer-working-dirs/o?alt=json&delimiter=&endOffset=&includeFoldersAsPrefixes=false&includeTrailingDelimiter=false&matchGlob=&maxResults=1&pag …
```
=> Adding info log for operation retry

perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, tools/integration_tests/explicit_dir/explicit_dir_test.go, tools/integration_tests/gzip/gzip_test.go, tools/integration_tests/implicit_dir/implicit_dir_test.go, tools/integration_tests/list_large_dir/list_large_dir_test.go, tools/integration_tests/local_file/local_file_test.go, tools/integration_tests/operations/operations_test.go, tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go, tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go, tools/integration_tests/read_cache/disabled_cache_ttl_test.go, tools/integration_tests/read_cache/local_modification_test.go, tools/integration_tests/read_cache/range_read_test.go, tools/integration_tests/read_cache/read_only_test.go, tools/integration_tests/read_cache/remount_test.go, tools/integration_tests/read_cache/setup_test.go, tools/integration_tests/read_cache/small_cache_ttl_test.go, tools/integration_tests/readonly/readonly_test.go, tools/integration_tests/run_e2e_tests.sh, tools/integration_tests/run_tests_mounted_directory.sh, tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go, tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go, tools/integration_tests/util/mounting/static_mounting/static_mounting.go, tools/integration_tests/util/setup/setup.go
- Enabling e2e test for gRPC changes.
- Added support of -short flag while running the integration test, this will skip few tests inside test package. 
- Enabling only important tests (operations) for gRPC as part presubmit test. But exhaustive test will be run as part of e2e test.
Currently time taken by pre-submit test - 34m.
NA
1. Manual - NA
=> Enabling gRPC related integration test

tools/integration_tests/read_cache/range_read_test.go, tools/integration_tests/run_tests_mounted_directory.sh
The test case doesn't add much value and is flaky on certain ARM machines where the file get's cached almost immediately.
NA
1. Manual - NA
=> remove flaky TestRangeReadsBeyondReadChunkSizeWithoutChunkDownloaded test

tools/integration_tests/list_large_dir/list_large_dir_test.go
This change is necessary because there is a test failures due to delays in updating the stat-cache.
NA
1. Manual - NA
=> Fix flaky list large dir e2e test

tools/integration_tests/operations/operations_test.go, tools/integration_tests/run_e2e_tests.sh, tools/integration_tests/util/setup/setup.go
Repeatedly copying bin file was throwing warnings. Using PATH env variable instead to keep the test logs clean.
NA
1. Manual - NA
=> Using PATH env variable instead of copying gcsfuse package for integration tests 

tools/integration_tests/operations/file_and_dir_attributes_test.go, tools/integration_tests/util/operations/file_operations.go
This PR fixes flaky file and directory attributes tests. 
**Cause:** The tests were flaky because kernel clock can be out of sync of time.Now() Ref: https://github.com/golang/go/issues/33510
To handle this case, we were rounding off the times to nearest second for comparison but sometimes, edge condition can happen where pre-create time gets rounded up while the actual modification time gets rounded down.
**New Fix:** We will use time slop of 25 milli seconds to move pre and post create times so that file modification time lies between the range of preCreate and postCreate time.
NA
1. Manual - NA
3. Integration tests - Ran on VM and via KOKORO
=> fix flaky modification time check in integration tests

Dockerfile, go.mod, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/read_cache/setup.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/integration_tests/run_e2e_tests.sh, tools/package_gcsfuse_docker/Dockerfile
Upgrading go's minor version from 1.22.1 to 1.22.2
NA
1. Manual - NA
2. Unit tests - Presubmits
3. Integration tests - Presubmits
4. Per tests - below:
=> Upgrading go version to 1.22.2

tools/integration_tests/interrupt/git_clone_test.go
The tests were failing on CD pipeline with the following error:
```
git_clone_test.go:116: Git empty commit failed: : failed command '/bin/bash -c git commit --allow-empty -m " empty commit"': exit status 128, Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
```
Fixed by setting the user config before running the tests.
NA
1. Manual - Manually ran on debian 11 and centos 7 VM to verify the fix.
4. Integration tests - Ran on KOKORO
=> fix ignore interrupt integration tests

flags.go, flags_test.go, perfmetrics/scripts/README.md, perfmetrics/scripts/compare_fuse_types_using_fio.py, perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh, perfmetrics/scripts/ls_metrics/listing_benchmark_test.py, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
change default value of max-conns-per-host to 0 [unlimited].
b/329816962
1. Manual - NA
4. Perf tests - (2 runs)
[
](url)
=> Remove default limit on max tcp connections by setting max-conns-per-host to 0

.github/.codecov.yml, .github/workflows/codecov.yml
This change integrates codecov.io into gcsfuse which would keep track of coverage stats and fail presubmit checks if the code-coverage drops beyond a certain target. For code in master, we've set a minimum value of 60% and for patches, the threshold is 80%.
NA
1. Manual - NA
=> Implement code coverage checks

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh, tools/cd_scripts/e2e_test.sh, tools/integration_tests/implicit_dir/implicit_dir_test.go, tools/integration_tests/operations/operations_test.go
Currently, -short flag totally hijacked by gRPC.
Need to revert this PR once b/333307965 is fixed, created another bug to revert this PR b/341240872.
NA
1. Manual - NA
=> Disabling gRPC test temporarily

internal/auth/auth_test.go, internal/config/config_util_test.go, internal/config/yaml_parser_test.go
Moving auth and config packages to stretchr/testify
NA
1. Manual - NA
=> Moving auth and config packages to stretchr/testify

go.mod, go.sum, internal/config/mount_config.go, internal/config/testdata/file_system_config/invalid_disable_parallel_dirops.yaml, internal/config/testdata/file_system_config/unset_disable_parallel_dirops.yaml, internal/config/testdata/valid_config.yaml, internal/config/yaml_parser_test.go, internal/fs/fs.go, internal/fs/inode/base_dir.go, internal/fs/inode/dir.go, main_test.go, mount.go
Allow parallel lookups by 
(a) passing FUSE_PARALLEL_DIROPS option which allows parallel dirops (readdir and lookup calls) from FUSE driver. In my experiments i noticed that with this flag, readdir becomes parallel for same directory and lookup becomes parallel for files under same mount. Also, the even without this option, the lookup calls are parallel on repeat lookups of same files. GCSFuse takes locks on dir inode during readdir operations hence with this option. for user only the lookups are parallelized.
(b) take readonly lock on dir inode instead of exclusive lock while doing lookup.
NA
1. Manual - NA
2. Unit tests - Added in https://github.com/GoogleCloudPlatform/gcsfuse/pull/1906
3. Integration tests - [Run1](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpr …
=> [PR1] allow parallel lookups

.github/.codecov.yml
Currently codecov uses master as the reference which doesn't really portray the right picture since the changes in master since the feature branch was cut off can lead to unrelated code coverage changes showing up.
NA
1. Manual - NA
=> Update .codecov.yml to use the PRs base as reference

go.mod, go.sum, internal/config/mount_config.go, internal/config/testdata/file_system_config/invalid_disable_parallel_dirops.yaml, internal/config/testdata/file_system_config/unset_disable_parallel_dirops.yaml, internal/config/testdata/valid_config.yaml, internal/config/yaml_parser_test.go, internal/fs/fs.go, internal/fs/inode/base_dir.go, internal/fs/inode/dir.go, internal/fs/parallel_dirops_test.go, main_test.go, mount.go
Composite tests for Parallel dirops test.
NA
1. Manual - NA
3. Integration tests - [Run1](http://fusion2/ci/kokoro/prod%3Agcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/095b660f-5941-4778-9985-b1e9b23eaab0)
=> [PR2] Composite tests for Parallel dirops test.

cmd/root.go, go.mod, go.sum, main.go
* This is to ease the migration from urfave/cli to Cobra + Viper for configuration.
* The new config will only be triggered if ENABLE_VIPER_CONFIG env var is set to true.
NA
1. Manual - NA
=> Add a Cobra root command.

.github/.codecov.yml
The "changes" feature detects unrelated code coverage changes. It's been noisy for gcsfuse. Disabling it.
NA
1. Manual - NA
=> Disable the "changes" feature of codecov

tools/integration_tests/operations/operations_test.go
Removing these tests as these are failing in some cases in periodic e2e tests.
This is only an experimental feature right now, so its failing integration tests should not block
periodic e2e tests.
NA
1. Manual - NA
=> Remove operations e2e tests for metadata-prefetch

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, tools/integration_tests/run_e2e_tests.sh
Allow passing bucket location flag to run_e2e_tests.sh script
NA
1. Manual - NA
3. Integration tests - [NA](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/f153ebd0-0f6f-406e-922b-06d1d64191fb/log)
=> Allow passing bucket location flag to run_e2e_tests.sh script

tools/build_gcsfuse/main_test.go
=> Add a test to ensure that the version is correctly printed in the gcsfuse binary

internal/cache/file/downloader/job.go
Close the reader of async job in file cache to have the closing logs
NA
1. Manual - Checked with and without changes. With changes the closing logs appear.
3. Integration tests -[link](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/6e27566c-42a6-4de7-ad43-01c1db7877f5/log)
=> Close the reader of async job in file cache to have the closing debug logs

docs/semantics.md
Since create-empty-file is by default false, only one event and not three should be generated.
NA
1. Manual - NA
=> Fix the details of pubsub events generated due to file-creation

tools/integration_tests/readonly/readonly_test.go, tools/integration_tests/util/setup/setup.go
In scenarios where we were only mounting a directory, the test targeting that mount point failed because the "onlydir" path was not being set correctly. 
NA
1. Manual - Tested mounted directory tests
=> Fix readonly --only-dir tests for GKE environment

go.mod, go.sum, tools/config-gen/main.go
Move to use safetext/yamltemplate
This change fixes a security vulnerability associated with text/template by replacing it with safetext/yamltemplate.
b/344125887
1. Manual - NA
=> Fix security vulnerability by getting rid of text/template 

docs/semantics.md
The documentation is misleading because it fails to mention that Pantheon's "create folder" action also creates a 0-byte object, making it visible even without the implicit-dir flag.
Our documentation currently states that using the mkdir command in the filesystem is necessary, which is misleading.
Corrected the documentation to clarify it clearly.
NA
1. Manual - NA
=> Fix semantic doc for implicit dirs

cfg/config.go, cfg/decode_hook.go, cfg/decode_hook_test.go, cfg/types.go, tools/config-gen/flag_template_data_gen.go, tools/config-gen/params.yaml, tools/config-gen/parser.go, tools/config-gen/type_template_data_gen.go
We have added support to declare and decode the following types:
* LogSeverity
* ResolvedPath
* Octal
* Protocol
NA
1. Manual - NA
=> Add handling for custom types in Config object.

go.mod, go.sum, tools/config-gen/main.go
safetext/yamltemplate doesn't work for our use-case since we are generating Golang code and not YAML. So, yamltemplate reports errors during code-generation. Reverting back to text/template with a NOLINT annotation so that it's not flagged as a security risk: go/yamltemplate-gob-request.
This is in essence a revert of https://github.com/GoogleCloudPlatform/gcsfuse/pull/1975.
NA
1. Manual - NA
=> Use text/template for code-generation

cmd/legacy_main_test.go
* This will simplify changing the tests for flag addition.
* Simplify merge conflicts for cases where two different flags are being added by two developers simultaneously.
* Improve the readability of the test.
NA
1. Manual - NA
=> Making stringify tests readable.

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go, tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go, tools/integration_tests/read_cache/setup_test.go
TestRangeReadsWithCacheHit was sometimes failing with the following error:
```
2024/05/20 04:36:31 Running tests with flags: [--implicit-dirs=true --config-file=/tmp/gcsfuse_readwrite_test_2956740480/config --o=ro]
=== RUN   TestCacheFileForRangeReadTrueTest/TestRangeReadsWithCacheHit
helpers_test.go:118: Incorrect cached file size. Expected 52428800, Got: 20044413
gcs_helper.go:164: CRC32 mismatch. Expected 583443541, Got 3098506051
```
Fix: Reduced the file size to 8 MiB to ensure that complete file gets cached within time limit.
NA
1. Manual - Ran on louhi - the test did not fail in any of the runs
3. Integration tests - via KOKORO (The test did not fail in any of the KOKORO runs)
=> fix flaky TestRangeReadsWithCacheHit test by reducing the file size

Dockerfile, go.mod, perfmetrics/scripts/ml_tests/pytorch/run_model.sh, perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, perfmetrics/scripts/read_cache/setup.sh, tools/cd_scripts/e2e_test.sh, tools/containerize_gcsfuse_docker/Dockerfile, tools/integration_tests/run_e2e_tests.sh, tools/package_gcsfuse_docker/Dockerfile
Upgrading go lang version to 1.22.4
Contains fix of: https://nvd.nist.gov/vuln/detail/CVE-2024-24789
NA
1. Manual - NA
=> Upgrading go lang to 1.22.4

internal/cache/file/cache_handler_test.go, internal/cache/file/downloader/downloader.go, internal/cache/file/downloader/downloader_test.go, internal/fs/fs.go, internal/gcsx/random_reader_test.go
Instead of passing file-cache related arguments individually, using the FileCacheConfig struct to make code more readable.
b/345646639
1. Manual - NA
=> Use struct to bundle function parameters

internal/cache/file/downloader/downloader_test.go, internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go, internal/cache/util/testdata/validfile.txt, internal/cache/util/util.go, internal/cache/util/util_test.go, internal/fs/local_modifications_test.go, internal/gcsx/random_reader_test.go, internal/storage/gcs/object.go, internal/storage/storageutil/object_attrs.go, internal/storage/storageutil/object_attrs_test.go
CRC check will be done after the entire file is downloaded into cache based on the enableCRCCheck flag.
NA
3. Integration tests - No new integration tests
=> Added code changes to add crc check for sequential download behind flag

internal/cache/file/cache_handle_test.go
=> updates cache handler test to use strechr/testify to make each test runnable from IDE

go.mod, go.sum
The following direct dependencies were upgraded:
* cloud.google.com/go/storage v1.41.0 -> v1.42.0
* github.com/fsouza/fake-gcs-server v1.49.1 -> v1.49.2
* github.com/jacobsa/fuse v0.0.0-20240522090807-a2f23eec702d -> v0.0.0-20240607092844-7285af0d05b0
1. Manual - NA
=> Update direct dependencies.

cfg/config.go, tools/config-gen/config.tpl, tools/config-gen/params.yaml, tools/config-gen/type_template_data_gen.go
* All all currently used params to params.yaml.
* Generate int flags with type as int64 as opposed to platform-dependent int.
NA
1. Manual - NA
=> Add all config-params to params.yaml

tools/config-gen/params.yaml
This will guide devs on how to add new params.
I've purposely excluded hide-shorthand and shorthand features because we are not sure whether or how they will be supported.
NA
1. Manual - NA
=> Add documentation to params.yaml

tools/integration_tests/operations/operations_test.go, tools/integration_tests/run_e2e_tests.sh
1. Increase the timeout for the storage client, as operations tests often run for more than 15 minutes.
2. The HNS function process was running in the foreground, so we were unable to obtain a process ID and therefore couldn't get the correct exit code.
NA
1. Manual - NA
4. Integration tests - Automated
=> fix e2e test for hns bucket

internal/cache/file/downloader/downloader_test.go, internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go, internal/cache/util/util.go, internal/cache/util/util_test.go
Making compute crc method context cancellable, so it can be cancelled as part of job cancellation
NA
=> Making compute crc method context cancellable

go.mod
The "go" line in go.mod specifies the minimum Go version that's required by the current module. While building, go automatically picks up the installed go version if it's same or more recent than the specified go version in go.mod. Since GCSFuse is compatible with go v1.22, we can declare the same in go.mod and let Go decide the right toolchain to build.
b/346695794
1. Manual - NA
=> Use 1.22 as the min Go version

internal/storage/storageutil/object_attrs.go, internal/storage/storageutil/object_attrs_test.go
Set crc32 when converting minobject to object
NA
=> Set crc32 when converting minobject to object

docs/metrics.md, internal/cache/file/downloader/downloader_test.go, internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go, internal/cache/file/downloader/parallel_downloads_job.go, internal/cache/file/downloader/parallel_downloads_job_test.go, internal/util/util.go
Add parallel downloads job
Note: I will add more unit/composite tests in the next PR. Also, I will enable the configs to run e2e tests with parallel downloads in a separate PR.
NA
1. Manual - NA
=> Add parallel downloads job

main.go, main_test.go
Golang flags don't distinguish between single-hyphen and double-hyphen flags. POSIX compliant flags that are supported by pflag and Cobra however require flags to be prefixed with double hyphens. So, augment the flags in os.Args by converting the single-hyphen flags to double-hyphen ones so that they can be consumed by Cobra and Viper.
NA
1. Manual - NA
=> Convert Golang compliant flags to POSIX compliant

internal/cache/file/cache_handle.go, internal/cache/file/cache_handle_test.go, internal/cache/file/downloader/job.go, internal/cache/file/downloader/job_test.go
Make Wait for Download false for all read scenarios when parallel downloads is true
b/345645002
1. Manual - NA
=> Make Wait for Download false for all read scenarios when parallel downloads is true

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/tpc_build.sh
Kokoro TPC build is failing with 
```
ERROR: (gcloud) Invalid choice: 'storage'.
This command is available in one or more alternate release tracks.  Try:
gcloud alpha storage
```
NA
1. Manual - NA
=> Kokoro tpc build fix

perfmetrics/scripts/ml_tests/pytorch/v2/dino/Dockerfile
The issue is same as https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863 and lowering the setuptool version fixes the problem. Not sure of the reason why this failure started coming now. Perhaps, the DLC team updated the tool version in their DLC image that we are using. I don't think it's worth investigating the issue more and it's fine to go ahead with the fix in this PR.
NA
1. Manual - NA
=> Fix Pytorch v2 model failure

cmd/root.go
Construct the config object which is derived from the commandline
args, config file and the defaults.
NA
1. Manual - NA
=> Unmarshal the config object

internal/config/testdata/file_cache_config/invalid_zero_max_download_parallelism.yaml, internal/config/yaml_parser.go, internal/config/yaml_parser_test.go
Reject 0 max-download-parallelism when parallel downloads enabled
NA
1. Manual - NA
=> Add max-download-parallelism validation

cfg/config.go, tools/config-gen/config.tpl, tools/config-gen/flag_template_data_gen.go, tools/config-gen/type_template_data_gen.go
Add "squash" to config structure tags to make decoding easier from legacy flagStorage & mountConfig.
This is a temporary change to make transition easier to new CLI and config flags and will be reverted post transition.
Reason to revert this in future - This change doesn't allow having leaf config with conflicting names.
Reference: https://pkg.go.dev/github.com/mitchellh/mapstructure#hdr-Embedded_Structs_and_Squashing
Open issue on mapstructure library which is blocking the change: https://github.com/mitchellh/mapstructure/issues/356
NA
1. Manual - Manually verified that viper configs and cobra flags are still working as intended
=> [Config CLI Parity] add squash to config structure tags to make decoding easier

cmd/root.go
Config object should be populated with only CLI flags in cases where config file is not provided.
Also resolves the config file path before usage.
NA
1. Manual - Tested manually and printed the config object to confirm it is working as intended
=> [Config-CLI Parity][Fix] Populate config object when config file is not provided

internal/gcsx/prefix_bucket.go, internal/gcsx/prefix_bucket_test.go, internal/monitor/bucket.go, internal/ratelimit/throttled_bucket.go, internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go, internal/storage/caching/fast_stat_bucket.go, internal/storage/control_client_wrapper.go, internal/storage/debug_bucket.go, internal/storage/fake/bucket.go, internal/storage/gcs/bucket.go, internal/storage/mock_bucket.go, internal/storage/mock_control_client.go
integrates with get folder method of control client for all buckets (except fast stat bucket - next PR).
it is not called from anywhere, hence no change in existing functionality.
NA
=> adds get folder method in bucket.go

tools/config-gen/parser.go
=> Raise error if params.yaml contains invalid fields

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/tpc_build.sh, tools/integration_tests/run_e2e_tests.sh
- The command `sudo mv google-cloud-sdk /usr/local` was causing issues(`mv: cannot move 'google-cloud-sdk' to '/usr/local/google-cloud-sdk': Directory not empty`) because it was also needed in tpc_build.sh and the e2e test script. It has been replaced with the command cp -r.
- Activating default config properly after testing.
NA
=> fix gcloud install 

internal/cache/file/downloader/jm_parallel_downloads_test.go, internal/cache/file/downloader/parallel_downloads_job.go
Use atleast 1 goroutine for async job in parallel downloads.
NA
1. Manual - NA
=> Use atleast 1 goroutine for async job

.github/CODEOWNERS
=> Add @kislaykishore as owners for config

internal/cache/file/downloader/job_test.go, internal/cache/file/downloader/parallel_downloads_job_test.go, internal/fs/read_cache_test.go
Add some tests (unit, composite & e2e) tests for parallel downloads
I tried to add to existing e2e tests but those were [failing](https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/6e63e377-1c89-4ecc-b237-4c7d0a9baf9f/log), so we will address e2e tests in a separate PR.
NA
1. Manual - NA
=> Add more tests (unit, composite) tests for parallel downloads

internal/cache/file/downloader/job_test.go, internal/fs/read_cache_test.go
Remove flakiness in parallel downloads unit tests. Will add the tests back in new PR.
NA
1. Manual - Ran go test with count 10.
=> Remove flakiness in parallel downloads unit tests

cmd/root.go, cmd/root_test.go
Limit the number of arguments that the root command can receive to the range [1, 2]
NA
1. Manual - NA
2. Unit tests - Added unit tests.
=> Add constraints on number of args

internal/cache/file/downloader/jm_parallel_downloads_test.go
Shadow the tc variable so that different subtests refer to their corresponding tc.
It's have been fine had the subtests ran sequentially but in a parallel run, different tests sharing the same tc variable can lead to race.
=> Fix race in test

internal/config/config_util.go, internal/config/config_util_test.go, internal/config/mount_config.go, internal/config/yaml_parser_test.go
Use default MaxDownloadParallelism based on number of CPU cores. Also set a minimum value of 16 in case the cores of CPU is less (2 or 4).
Using default 2 * number of cores as with the testing so far with a workload, this value looks good.
And couple of more things to tell upfront :
1. This is based on CPU cores count of machine, so on GKE this will translate to machine's CPU cores and not on the CPU limit on pod. We are fine here because pod limit <= machine CPU cores. So, we are just assigning higher value to max parallel downloads there.
2. It's possible to mount multiple GCSFuse mounts on single GCE VM/GKE node. In that case, one GCSFuse default is not affected by the other.
NA
1. Manual - NA
=> Use default MaxDownloadParallelism based on number of CPU cores

cfg/config.go, cmd/root_test.go, tools/config-gen/config.tpl, tools/config-gen/params.yaml
=> Set default max-parallel-downloads in new config

cmd/flags.go, cmd/flags_test.go, cmd/legacy_main.go, cmd/legacy_main_test.go, cmd/legacy_param_mapper_test.go
This PR is part of migration to new cobra/viper configs for CLI config parity.  
Replaced usage of `key-file` flag stored in `flagstorage.KeyFile` to `newConfig.GcsAuth.KeyFile`. 
NA
1. Manual - Manually verified that key-file flag is working.
=> [CLI Config Parity] migrate key-file flag usage to new config

internal/cache/file/cache_handler.go, internal/cache/file/downloader/job.go, internal/cache/util/util.go, internal/cache/util/util_test.go
Use truncate and remove function while eviction from job during CRC check.
NA
1. Manual - NA
3. Integration tests - added integration test tag.
=> Use truncate and remove function while eviction from job during CRC check

cmd/flags.go, cmd/flags_test.go, cmd/legacy_main.go, cmd/legacy_param_mapper_test.go, internal/config/config_util.go, internal/config/config_util_test.go, internal/logger/logger.go, internal/logger/logger_test.go, tools/integration_tests/log_rotation/log_rotation_test.go
This PR is part of migration to new cobra/viper configs for CLI config parity.
Replaced usage of `log-file` flag stored in `flagstorage.LogFile` and `mountConfig.LogConfig.FilePath` to `newConfig.Logging.FilePath`.
Note: Post merging this PR, log-file flag will start taking precedence when both flag and config is set.
NA
1. Manual - Manually verified that the new flag is working
=> [CLI Config Parity] migrate log-file legacy flag/config to new config 

tools/integration_tests/util/setup/setup.go
I've implemented a check for HierarchicalNamespace.Enabled to incorporate the HNS flag in end-to-end tests. Older buckets lack this attribute, potentially leading to nil pointer exceptions. To mitigate this, I've added a fix to verify the presence of HierarchicalNamespace.
Alternatively, the GKE team could create a new bucket where the `HierarchicalNamespace` attribute already defined.
NA
1. Manual - NA
3. Integration tests - Automated and Ran mounted directory script
=> Fix test in GKE environment

cfg/config.go, cmd/root.go, cmd/root_test.go, tools/config-gen/config.tpl
Using a global viper instance could cause problems since the same viper is shared across the entire application and libraries. This can lead to races. So, use instance level viper.
NA
1. Manual - NA
2. Unit tests - Existing tests should suffice.
=> Use a viper instance for deserialization

cmd/root.go
The root-command instances returned by NewRootCommand() share the package-level variables. The package-level variables are never garbage-collected. So, they increase memory footprint. It also makes the code flow more understandable since it's not very clear currently that initConfig modifies the package variables which the rootCommand uses later on.
NA
1. Manual - NA
=> Remove references to package-level variables in root.go

internal/fs/parallel_dirops_test.go
Assert does not stop execution of test. We should use require when it's necessary to stop execution.
NA
1. Manual - NA
=> use require in tests wherever necessary

cfg/config.go, cfg/decode_hook.go, cfg/decode_hook_test.go, cmd/legacy_param_mapper_test.go, tools/config-gen/type_template_data_gen.go
Code-gen URL params as pointer types. This is in line with the URL params in the legacy config.
NA
1. Manual - NA
=> Code-gen URL params as pointer

cfg/types.go, cmd/flags.go, cmd/legacy_main.go, cmd/legacy_main_test.go, cmd/mount.go, internal/mount/flag.go, internal/storage/storage_handle.go, internal/storage/storage_handle_test.go, internal/storage/storageutil/client.go, internal/storage/storageutil/test_util.go
Migrate the following flags to the new config:
* app-name
* foreground
* rename-dir-limit
* billing-project
* limit-bytes-per-sec
* limit-ops-per-sec
* stackdriver-export-interval
* experimental-opentelemetry-collector-address
* experimental-enable-json-read
* temp-dir
* enable-nonexistent-type-cache
* file-mode
* dir-mode
* uid
* gid
NA
1. Manual - Tested manually to see that the flags are correctly being reflected.
2. Unit tests - Existing unit-tests in legacy_param_mapper.go should already cover it.
=> Migrate a few flags to the new config

internal/fs/fs_test.go, internal/fs/kernel_list_cache_inifinite_ttl_test.go, internal/fs/kernel_list_cache_test.go, internal/fs/kernel_list_cache_zero_ttl_test.go
- Added basic composite test to make sure kernel-list-cache is working fine.
- I'll add more tests in another PR - like creation or deletion of file inside a directory invalidates the cache.
NA
1. Manual - NA
=> Kernel List Cache: Composite Test

cfg/config.go, tools/config-gen/params.yaml
Change the default for experimental-grpc-conn-pool-size in the new config to 1.
NA
1. Manual - NA
2. Unit tests - Will be added in a follow-up PR
=> Fix default for experimental-grpc-conn-pool-size

internal/gcsx/prefix_bucket.go, internal/gcsx/prefix_bucket_test.go, internal/storage/fake/bucket.go
- Fake bucket implementation for rename folder
- Fix Get folder fake bucket implementation(It was not returning error if folder does not exist)
- Created rename folder test in prefix_bucket_test.
- Fix some TODOs. GetFolder API instead of statObject in prefix_bucket_tests.
NA
1. Manual - NA
=> Implement rename folder 3

cfg/config.go, cmd/flags.go, cmd/flags_test.go, cmd/legacy_main_test.go, cmd/legacy_param_mapper.go, cmd/legacy_param_mapper_test.go, internal/config/config_util.go, internal/config/config_util_test.go, internal/config/mount_config.go, internal/config/testdata/valid_config.yaml, internal/config/yaml_parser_test.go, tools/config-gen/params.yaml
- A new flag, max-retry-attempts, has been added to prevent infinite retry loops for retryable errors. 
-  The default value is set to 6, aligning with the behavior of the previous max-retry-duration flag, which allowed retries for approximately one minute.
NA
1. Manual - NA
=> Introducing max retry attempts flag

Makefile
The "clean-gen" target deletes the auto-generated code i.e. "config.go". It's a dependency of "clean" and "clean-all" targets so that the generated code gets cleaned up too.
NA
1. Manual - Yes - tested the the generated code was getting deleted.
=> Clean generated code as part of "clean" target

main.go, main_test.go
urfave/cli uses the golang flags library which treats the "-flagName" and "--flagName" as equivalent, however Cobra, which uses the pFlags (POSIX flag standard), treats single-hyphen-prefixed flags as shorthands while doubly-hyphen-prefixed as flags. In order to be backward compatible, we prefix the flags that have been specified with a single hyphen with another hyphen. This however causes problems for certain shorthand flags such as "-v" and "-h" which have special meaning to Cobra. Prefixing them with another hyphen causes errors since to Cobra, Cobra only knows about "v" and "h" shorthands not flags.
As part of this PR we address the following:
* Don't modify "-h" to "--h"
* Convert "--h" and "--v" to "-h" and "-v" respectively.
NA
3. Integration …
=> Don't change "-h" shorthand to "--h"

internal/storage/caching/fast_stat_bucket.go, internal/storage/caching/fast_stat_bucket_test.go, internal/storage/mock_bucket.go
- This PR adds implementation for get folder in fast stat bucket.
- Next PR will contain force fetch from gcs.
- Prioritised next work for hns over adding support testify for fast stat cache bucket tests as it contains mock implementation and test method renaming which would take more time and out of scope for this PR.
NA
1. Manual - NA
=> Stat cache bucket changes

tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go, tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go, tools/integration_tests/read_cache/disabled_cache_ttl_test.go, tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/read_cache/local_modification_test.go, tools/integration_tests/read_cache/range_read_test.go, tools/integration_tests/read_cache/read_only_test.go, tools/integration_tests/read_cache/remount_test.go, tools/integration_tests/read_cache/setup_test.go, tools/integration_tests/read_cache/small_cache_ttl_test.go, tools/integration_tests/util/client/gcs_helper.go
This PR adds parallel download configuration to existing read cache e2e tests.
Changes involved:
- Parallel download config added to the existing tests.
- It is possible that cache file is not fully downloaded after the read is served, so retry for 5 seconds until the file is cached before matching CRC with GCS.
- Some miscellaneous changes to return error / use stretchr testify to make the test more debuggable.
- Reduce file size for tools/integration_tests/read_cache/range_read_test.go file so that the test executes faster. Parallel download tests are not added for this file as it is not predictable that the file will be cached for a chunk in this case. 
NA
1. Manual - Ran multiple times manually to confirm that the test is not flaky.
3. Integration tests - Ran via …
=>  Add parallel download configuration to existing read cache e2e tests

tools/integration_tests/kernel-list-cache/disabled_kernel_list_cache_test.go, tools/integration_tests/kernel-list-cache/finite_kernel_list_cache_test.go, tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go, tools/integration_tests/kernel-list-cache/setup_test.go, tools/integration_tests/run_e2e_tests.sh, tools/integration_tests/util/setup/setup.go
Add setup for kernel list cache E2E tests
NA
1. Manual - NA
=> Add setup for kernel list cache E2E tests

tools/integration_tests/util/mounting/only_dir_mounting/only_dir_mounting.go
Return success code for scenario when only-dir-mounted directory does not pre-exist in bucket.
NA
1. Manual - NA
=> fix only dir mounting test's success code

tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go, tools/integration_tests/list_large_dir/list_large_dir_test.go, tools/integration_tests/run_e2e_tests.sh, tools/integration_tests/run_tests_mounted_directory.sh, tools/integration_tests/util/setup/setup.go
1. Added the `--kernel-list-cache-ttl-secs=-1` flag to the "list_large_directory" end-to-end tests.
2. Since we are running the list operation twice, created a separate validator function for each test.
NA
1. Manual 
Manually checked the list time for all the tests. Second list is much faster than first.
```
=== RUN   TestListDirectoryWithTwelveThousandFiles
2024/07/11 08:31:04 First List Time:  612.80212ms   Second List Time: 49.783908ms
--- PASS: TestListDirectoryWithTwelveThousandFiles (71.26s)
=== RUN   TestListDirectoryWithTwelveThousandFilesAndHundredExplicitDir
2024/07/11 08:32:28 First List Time: 687.169932ms   Second List Time: 51.786384ms
--- PASS: TestListDirectoryWithTwelveThousandFilesAndHundredExplicitDir (84.28s)
=== RUN …
```
=> Kernel cache list tests in list large directory e2e tests

tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
Functional test for kernel-cache-ttl=-1
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from Kernel cache.
NA
1. Manual - NA
=> Functional test infinite kernel cache ttl - 1

tools/integration_tests/kernel-list-cache/disabled_kernel_list_cache_test.go, tools/integration_tests/kernel-list-cache/finite_kernel_list_cache_test.go
- Functional test for kernel-cache-ttl=0 
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from GCSFuse filesystem.
NA
1. Manual - NA
=> Functional test for kernel-cache-ttl=0

tools/integration_tests/kernel-list-cache/finite_kernel_list_cache_test.go, tools/integration_tests/kernel-list-cache/setup_test.go
Functional test with  kernel cache ttl 5s
1. Within TTL it will be cache hit and server from kernel cache.
2. Above TTL , response will be serve from GCSFuse.
NA
1. Manual - NA
4. Integration tests - Automated
=> Functional test with finite kernel cache ttl

tools/integration_tests/kernel-list-cache/finite_kernel_list_cache_test.go, tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
1. addition of new file.
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from GCSFuse filesystem
2. deletion of new file.
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from GCSFuse filesystem
3. file rename.
(a) First ReadDir() will be served from GCSFuse filesystem.
(b) Second ReadDir() will also be served from GCSFuse filesystem
NA
1. Manual - NA
6. Integration tests - Automated
=> Functional test infinite  kernel cache ttl - 2

tools/integration_tests/concurrent_operations/concurrent_listing_test.go, tools/integration_tests/concurrent_operations/setup_test.go, tools/integration_tests/kernel-list-cache/setup_test.go, tools/integration_tests/run_e2e_tests.sh
**Test case added**
(a) Added test for parellel OpenDir and LookUp concurrently.
(b) Added test for parallel ReadDir and LookUp concurrently.
(c) Added test for parallel ReadDir by 10 go routines.
(d) Added test for concurrent ReadDir and delete/create/rename on file underneath.
(e) Added test for concurrent ReadDir and delete/create/rename folder underneath.
(f) Added test for concurrent ReadDir and FileEdit underneath.
(g) Added a kitchen task to run multiple operations concurrently.
**Parallelize the test within test-suite**
Test time got  reduced from 300s to 170s (on n2-std-96 vm). Ref: https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently
NA
1. Manual - Tested on n2-std-96 vm.
=> Adding e2e test for kernel-list-cache concurrency test 

internal/fs/fs.go, internal/fs/handle/dir_handle_test.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go, internal/fs/inode/explicit_dir.go
- This PR adds a parameter for HNS enable check in dir inode and its creation method.
- This is first PR for changes needed for implicit-dirs check in HNS, more changes will be in subsequent PRs.
NA
1. Manual - NA
=> adds hns check in dir.go

tools/integration_tests/operations/operations_test.go, tools/integration_tests/run_tests_mounted_directory.sh
Add kernel list cache tests to operations package
NA
1. Manual - NA
=> Add kernel list cache tests to operations package

go.mod
This fixes the CodeQL warning about incorrect Go Toolchain version.
NA
1. Manual - NA
=> Change Go version to match 1.N.P syntax.

tools/integration_tests/run_tests_mounted_directory.sh
Adding sample tests to run kernel-list-cache and concurrent_operations package. This will be used by GKE team to test for CSI driver.
NA
1. Manual - Done.
=> Adding example to run kernel_list_cache and concurrent_operations test

tools/integration_tests/concurrent_operations/concurrent_listing_test.go
Pre-creating file to avoid input/output error while concurrent listing and creation.
NA
1. Manual - NA
=> Concurrent test: pre-create file to avoid input/output error

tools/integration_tests/read_cache/helpers_test.go, tools/integration_tests/util/client/gcs_helper.go
Problem: Read Cache test scenario where we modify file via GCSFuse was flaky with parallel downloads. It is happening because we are retrying on file size before calculating CRC but in this case file size is same (because we are over-writing the same file). 
Fix: Added retry on CRC check of the cached file to ensure it passes.
NA
1. Manual - NA
3. Integration tests - KOKORO
=> fix flakiness in read cache parallel download test

tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go
On some n2-standard-16 machines, kernel list cache is taking ~130 ms thus making this test flaky. Made the logic relative to first list time to remove flakiness.
NA
1. Manual - NA
=> fix flakiness in list large directory tests

internal/gcsx/prefix_bucket.go, internal/monitor/bucket.go, internal/ratelimit/throttled_bucket.go, internal/storage/bucket_handle.go, internal/storage/bucket_handle_test.go, internal/storage/caching/fast_stat_bucket.go, internal/storage/control_client_wrapper.go, internal/storage/debug_bucket.go, internal/storage/fake/bucket.go, internal/storage/gcs/bucket.go, internal/storage/mock_bucket.go, internal/storage/mock_control_client.go
- The signature of the RenameFolder function has been modified.
- We previously returned control.RenameFolderOperation, but to keep the control client integration within the bucket handle, we now return gcs.Folder.
- Unit testing a successful rename is not possible because the control client's rename folder operation returns a control.RenameFolderOperation response containing private data that we cannot access externally so we can not mock it in our unit tests.
- We've added a wait call directly within the bucket handle to block until the long-running operation completes successfully.(Previously we thought to add this call from where we call RenameFolder API)
NA
1. Manual - NA
=> Change rename folder signature 

internal/fs/inode/base_dir.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go, internal/storage/fake/bucket.go
- RenameFolder function in DirInode interface. We will call this function further from fs.go whenever renameDir call will make for HNS. Currently this function is not being called from anywhere.
- Unit test
NA
1. Manual - NA
=> Implement rename folder function in dir Inode interface

internal/fs/fs.go, internal/fs/local_modifications_test.go, internal/perf/memory.go, internal/storage/gcs/object.go
Google is [shutting down](https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/) `goo.gl` short link redirects (after [previously announcing](https://developers.googleblog.com/en/transitioning-google-url-shortener-to-firebase-dynamic-links/) that they'll continue to work).
Google also previously announced that you could export your links from "the `goo.gl` console", but I can't find that anywhere (the site is now just a redirect to their stupid blog post), so I had to do this by hand. There may be some errors.
=> Migrate goo.gl links to TinyURL.

internal/storage/caching/fast_stat_bucket.go, internal/storage/caching/fast_stat_bucket_test.go
- Fast stat bucket integration with create folder
- Insert the folder into cache after successfully created.
- Added unit tests.
- Haven't integrated stretcher testify as it will add more changes in this PR.
NA
1. Manual - NA
=> Create folder implementation - 3

perfmetrics/scripts/load_tests/python/requirements.txt, perfmetrics/scripts/requirements.txt
Dependabot PRs
https://github.com/GoogleCloudPlatform/gcsfuse/pull/2091
https://github.com/GoogleCloudPlatform/gcsfuse/pull/2110
NA
1. Manual - NA
4. Perf tests - Automated
=> Python dependencies

tools/gem_dependency/Gemfile.lock
Dependabot dependency
https://github.com/GoogleCloudPlatform/gcsfuse/pull/2205/commits/0cb462f80ec56855a6d7e57eeb4e4f5b3b9dc341
NA
1. Manual - Package building successfully
4. Perf tests - ![B8dees2utG5HZvL](https://github.com/user-attachments/assets/7f87fe13-7ba5-4132-9113-0e69ec8c684b)
=> Upgrade gem lock dependency

perfmetrics/scripts/hns_rename_folders_metrics/config.json, perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files.py, perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py
This script will be used to create test data in gcs bucket for hns rename folder tests.Currently, it contains the consistency checks for configuration file which contains the details of the desired folder structure.
NA
1. Manual - Manually tested scenarios with all combinations of the required keys  missing under the folders/nested-folders section
2. Unit tests - [Unit tests](https://github.com/GoogleCloudPlatform/gcsfuse/commit/105840cbad268c2514b801c060e70f329ab48cd7#diff-9680f5049ff6a200fb5b6dfe223da1835f434911e749171d19bf7841fa36dec0) for checking consistency covering scenarios where keys are missing, mismatch in the number of folders specified and the folder structure provided, valid config file is passed ,etc . 
=> Adding function to check the consistency of config file

tools/integration_tests/concurrent_operations/setup_test.go
Add kernel cache ttl=0 in e2e tests
NA
1. Manual - NA
3. Integration tests - Autoamated
=> Add kernel-cache-ttl=0 in e2e tests

cmd/legacy_main.go, cmd/root.go, cmd/root_test.go, main.go
Pass the bucket and mountpoint into the mount fn
* Refactor the populateArgs function to take a slice of args as input instead of the cliContext.
* Invoke populateArgs in the root command so that the new config gets access to the bucket and mountpoint and can invoke the mount function with the config, bucket and mountpoint.
NA
1. Manual - NA
2. Unit tests - Added the unit tests.
=> Pass the bucket and mountpoint into the mount fn

perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh, perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/tpc_build.sh, perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh, tools/integration_tests/operations/operations_test.go, tools/integration_tests/run_e2e_tests.sh, tools/integration_tests/util/setup/setup.go
This change 
* increases e2e test runs by 10 minutes for scenarios which run the experimental-feature test.
* Removes e2e test corresponding to https://github.com/GoogleCloudPlatform/gcsfuse/blob/deb9ba8e40ba4fb3ea82844a70a54132d2cdcb28/tools/integration_tests/operations/operations_test.go#L184 from presubmit tests run (though still kept in the periodic e2e test runs).
This addresses internal bug id 353629055.
NA
1. Manual - In presubmit integration tests, it prints the following logs
```
Setting the flag to skip few un-important integration tests.
This is a presubmit-run, which skips some tests.
Setting the integration test timeout to: 40m
```
4. Integration tests - presubmit runs
=> disable experimental test run for presubmit test

perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files.py, perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py
Added helper function and its unit tests for listing directories which will be further used as a check to create directory structure if it does not exist already.
NA
1. Manual - Tested that recursive listing does not happen.
2. Unit tests - Unit tests for [successful execution](https://github.com/GoogleCloudPlatform/gcsfuse/blob/5a29bdf591af09b3e3f847b6bdcd91df6f181148/perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py#L135) and [thrown exception](https://github.com/GoogleCloudPlatform/gcsfuse/blob/5a29bdf591af09b3e3f847b6bdcd91df6f181148/perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py#L121) 
=> Adding helper function for rename folder test

internal/fs/fs.go, internal/fs/inode/base_dir.go, internal/fs/inode/dir.go, internal/fs/inode/dir_test.go, internal/fs/kernel_list_cache_inifinite_ttl_test.go, tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
Scenario:
1. Read directory (listing) with kernel list cache enabled
2. List response is cached in kernel.
3. Create a file on the same GCS bucket inside the same directory outside of the GCSFuse mount via another tool like pantheon, gsutil.
4. call os.RemoveAll on the same directory in GCS Fuse.
5. Kernel will use the list cache response to list & delete the files and the newly created file (outside GCSFuse mount) won't be deleted.
6. os.RemoveAll will fail with directory not empty error when trying to delete the parent directory.
Fix: 
1. As part of the RmDir call, we will invalidate the cache by setting the previous directory listing timestamp to 0. 
2. This will make the open dir call to invalidate the cache so os.RemoveAll will start working.
Note: even after this fix, rm -r from …
=> [bug fix] Kernel list cache remove directory operation fails when files are created on GCS 

internal/fs/fs.go, internal/fs/inode/explicit_dir.go
Pass correct enable-hns flag value while creating directory inode
NA
1. Manual - NA
=> Pass correct enable-hns flag value while creating directory inode

internal/cache/metadata/stat_cache.go, internal/storage/caching/fast_stat_bucket.go, internal/storage/caching/fast_stat_bucket_test.go
- Minor refactoring to simplify if condition for lookup folder.
- Inserts folder in stat cache if get folder was  successful.
- Negative stat cache scenario will be added in next PR, as some discussion is going on for it.
NA
1. Manual - NA
=> Minor changes for stat cache for HNS

perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files.py, perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py
Added the check_if_dir_structure_exists function in order to prevent recreation of existing test data in the bucket for rename folder tests.
NA
1. Manual - checked scenarios when number of directories is same but name differs on both top and second level folders .
2. Unit tests - wrote unit tests for [existing directory](https://github.com/GoogleCloudPlatform/gcsfuse/blob/ccb4bccca45e47803a1ecb590e0d9a0ce5d6898d/perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py#L148) and [directory not existing](https://github.com/GoogleCloudPlatform/gcsfuse/blob/ccb4bccca45e47803a1ecb590e0d9a0ce5d6898d/perfmetrics/scripts/hns_rename_folders_metrics/generate_folders_and_files_test.py#L188) scenarios 
=> Added function to check if the directory structure in config file already exists in bucket

internal/fs/inode/dir_test.go, internal/fs/inode/hns_dir_test.go, internal/storage/testify_mock_bucket.go
- Moved rename dir tests to hns dir test as they are part of hns scenarios and needed to use mock bucket instead of fake bucket which can mock atomic rename behaviour without adding complex logic in fake bucket.
NA
1. Manual - NA
=> Rename folder unit tests with mock bucket in dir handle

internal/fs/inode/hns_dir_test.go
Moved delete tests to hns dir test as they are part of hns scenarios and needed to use mock bucket instead of fake bucket which can mock atomic rename behaviour without adding complex logic in fake bucket.
NA
1. Manual - NA
=> Unit tests for delete child dir
